### ISSUE TITLE
Ladders added by the mod are not added to Vanilla's "climbable" block tag.

### ISSUE THREAD

**Issue by nitrodynamite18** [MehVahdJukaar/WoodGood#103]
As the title says, the mod adds the ladders successfully but does not add the to the minecraft:climbable block tag. Here's a screenshot of the F3 debug screen using the Witch Hazel ladder.

![2022-12-06_00 22 09](https://user-images.githubusercontent.com/69542632/205823937-18807a90-694e-4310-8332-9fa3e5ff68b9.png)

**Comment by LolJohn11** [comment]
Same issue here, can't climb the ladders created by EveryCompat mod.

**Comment by Xelbayria** [comment]
Is this issue resolved? if yes, then please close this issue.

otherwise, please fill out the missing info:
- Which Mods Every Compat has an issue with: ???? ( can be multiple mods, one with wood_types and the other with ladders) 
- Minecraft Version: 1.19.2
- Loader (Forge or Fabric): **Forge**
