### ISSUE TITLE
Latest 1.18.2 file broken with Macaw's Windows still

### ISSUE THREAD

**Issue by brisingraerowing** [MehVahdJukaar/WoodGood#108]
As a side note, the file version is 1.5.12, while the last version was 1.5.13. Is that the right file?

[Error from game output log](https://gist.github.com/brisingraerowing/6d3741fda59a0479f2fee400a15437f5)

**Comment by Stupidplays** [comment]
Same too
[crash-2022-12-09_17.09.28-fml.txt](https://github.com/MehVahdJukaar/WoodGood/files/10193610/crash-2022-12-09_17.09.28-fml.txt)

**Comment by isaaclepes** [comment]
Same here
![image](https://user-images.githubusercontent.com/54421422/212558705-1201c58c-2690-4ec8-ba2f-a0138255a3ae.png)

**Comment by brisingraerowing** [comment]
@isaaclepes You're out of date then, as the latest version works.

**Comment by Xelbayria** [comment]
Please close this issue if it's already solved. it's not a good idea to leave this issue open.
