### ISSUE TITLE
Stuck at "joining world" on latest version (1.19.2-2.2.1 & 1.19.2-2.2.0)

### ISSUE THREAD

**Issue by Mathio95** [MehVahdJukaar/WoodGood#109]
MC: 1.19.2
Forge: 43.1.57
Wood good mod versions: 1.19.2-2.2.1 & 1.19.2-2.2.0

Whenever i want to join my world after updating this mod its stays stuck on "joining world"
Really can't figure out what's causing it

Maybe a incompatible mod? 

Please help!  

[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/10197796/latest.log)
[debug.log](https://github.com/MehVahdJukaar/WoodGood/files/10197797/debug.log)

**Comment by MehVahdJukaar** [comment]
I don't see anything related to this. Infact I don't see anything at all. Seems that the game was just doing normal loading stuff while that happened. No crash or error. Maybe try adding more ram

**Comment by Mathio95** [comment]
That did kinda work, 

Buut it only works when i add 10gb of ram :/ 
could there be a memory issue with the latest version?

**Comment by MehVahdJukaar** [comment]
No but everycompat can add many many blocks which need resources to get registered. Don't install too many furniture mods or mods that ad wood and it won't be an issue

**Comment by Mathio95** [comment]
Been able to get trough the loading screen after latest update(2.2.1), but now a different issue arrises.
If i walk 10 blocks (even in new world) my game freezes up and then without crass log just closes. 

Been testing a lot, deleted all my furniture mods added them 1 by one.
but when i add macaw furniture (even if its only macaw furniture without anything else) with the latest everycomp updates (2.2.0 and 2.2.1), this happens. 

If i roll back 2 versions (2.1.6) then the problem is gone.
I even tested it by adding simply every comp you have until version 2.1.6 and no problems what so ever. 
When i update to latest (2.2.0 and 2.2.1) it freezes

**Comment by MehVahdJukaar** [comment]
You sure your log doesn't say anything? Game always logs stuff so send that over

**Comment by Xelbayria** [comment]
Is this issue resolved? if yes, then please close this issue.

**Comment by Xelbayria** [comment]
Closing this
