### ISSUE TITLE
Farmer's delight stripping recipes

### ISSUE THREAD

**Issue by akochi** [MehVahdJukaar/WoodGood#11]
Hi,

It would be good if the mod could also allow custom wood to be striped using Farmer's Delight's cutting board and axe.

Thanks in advance!

**Comment by Xelbayria** [comment]
@akochi 
hey, I'm a new collaborator here. I am checking. Is this issue resolved? If yes, then please close this

**Comment by akochi** [comment]
It still is applicable.

I just tested with the following configuration:
Minecraft 1.20.1
Forge 47.2.0
Moonlight Library 1.20-2.8.60
Farmer's Delight 1.20.1-1.2.3
Every Compat 1.20-2.6.16
Ecologics 2.2.0 (To provide a non-native wood)

Putting Oak Log on a Cutting board and using an axe yields striped oak log and Tree Bark.
Putting Walnut Log on a Cutting board and using an axe tells "This doesn't seem cuttable".

Thanks for looking into it!

**Comment by Xelbayria** [comment]
Alright, I'll investigate.

**Comment by Xelbayria** [comment]
Sorry for the long wait. I looked at this. The best way to add these foreign logs from other mods to the cutting board is to create a new recipe for it via **CraftTweaker** or **KubeJS**, you could use Minecraft's data pack, too. 

the recipe for the cutting board is in `data\farmersdelight\cutting\...`

<strike> there is nothing I can do to fix this on **Every Compat** side. </strike>

EDIT: 
ignore the above. I got an idea and gave it a try. It worked. It will be in the next version.

**Comment by Xelbayria** [comment]
I'll add this feature to 1.19.2, too. 

This feature will be in **v2.6.35**.  Sorry for the long wait.
