### ISSUE TITLE
1.19.2 Item doesn't have name

### ISSUE THREAD

**Issue by gousisme** [MehVahdJukaar/WoodGood#114]
All the item name looks like this, I'm using the latest version
![image](https://user-images.githubusercontent.com/77152530/207598246-2142fd3d-7c09-4c67-812a-b2b30db21499.png)

**Comment by MehVahdJukaar** [comment]
Shoot ;-;

**Comment by gousisme** [comment]
Oh btw immersive weathering has the same problem too, only non-vanilla stuff

**Comment by MehVahdJukaar** [comment]
Update moonlight
