### ISSUE TITLE
Chests from the mod lack multiple parity features

### ISSUE THREAD

**Issue by nitrodynamite18** [MehVahdJukaar/WoodGood#119]
Quark wooden chests have multiple features that Every Compat's chests lack. For one, EC's chests are not added to the forge:chests/wooden block tag by default, which severely limits their use in crafting recipes. The trapped chests aren't added to that tag or the forge:chests/trapped tag either. Also, none of the chests are added to their respective "revertable" chest tag meaning they can't even be turned back to Vanilla.

EC's chests are also not added as fuel sources like Quark's.

**Comment by MehVahdJukaar** [comment]
Fixed
