### ISSUE TITLE
Possible issue with Roughly Enough Items

### ISSUE THREAD

**Issue by BookerCatch** [MehVahdJukaar/WoodGood#122]
Game crashes upon opening the inventory screen. Please see attached log.

[crash-2023-01-03_16.55.05-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/10340060/crash-2023-01-03_16.55.05-client.txt)

**Comment by MehVahdJukaar** [comment]
Uninstall every compat. You don't need it

**Comment by BookerCatch** [comment]
I just enabled one of the mods it adds block compatibility--Farmers Delight--and it no longer crashes. Apparently some funky thing is happening with REI if none of the mods every compat supports isn't loaded. Thanks.

**Comment by MehVahdJukaar** [comment]
Crash happens when the mod has registered no items meaning you don't need it
