### ISSUE TITLE
[1.18.2] Need Config Ability To Disable Wood Based Items Added By Other Mods

### ISSUE THREAD

**Issue by caniplzjustlogin4godsakesthistakesforev** [MehVahdJukaar/WoodGood#124]
everycompat-registry.toml allows for various wood and leave types to be turned off and on, It would be extremely helpful for both pack debugging and fixing for the items that Every Compat generates derivatives of to be added to this registry as well, so they're the addition of wood derivatives of those items can be turned off.

**Comment by MehVahdJukaar** [comment]
This has already been added on latest versions

**Comment by MehVahdJukaar** [comment]
Also I'd a mod is modular and has built-in recipe conditions these will be inherited. Same thing if a pack maker adds an always true condition to those mod recipes then every company will pick that up as it just copies the mod recipes. In fact recipe itself could be made empty with a datapack
