### ISSUE TITLE
1.19.3 - ``Forge 44.1.0`` Failed to start due to ``Incorrect Java Lang Invocation`` with mod ``everycomp-1.19.2-2.0.9.jar``

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MehVahdJukaar/WoodGood#125]
Crashlog 
https://gist.github.com/P3rf3ctXZer0/bd823aac3a0052eaf0c8fa8a7ce102de

Full Log
https://gist.github.com/P3rf3ctXZer0/0eecff4cc49fcc03d9d09d86e5bc7b0d

Also why is curse even pointing to this mod? Its clearly made for 1.19.2
![sfZ1hmR 1](https://user-images.githubusercontent.com/10351221/211005510-e129b2d5-54eb-4697-9773-b8cbff97f823.png)

**Comment by MehVahdJukaar** [comment]
Fixed

**Comment by P3rf3ctXZer0** [comment]
I will test now. Yay its no longe on 1.19.3 ... peace :D
