### ISSUE TITLE
Macaw's/BYG Tikki Torch Items missing textures

### ISSUE THREAD

**Issue by DaRealSparky** [MehVahdJukaar/WoodGood#126]
The Biomes You'll Go Tiki Torches from Macaw's Lights do not have textures in item form. When looking at the log, it seams to be looking in a folder that doesn't exist in the mod file.

This is on Minecraft 1.18.2, Mod Version 1.5.15.

**Comment by Attack8** [comment]
I'm having the same issue.

**Comment by Xelbayria** [comment]
Is this issue resolved in the latest version? If yes, then please close this issue, thanks

**Comment by Xelbayria** [comment]
I've run a quick test on this. there are no problems with the latest version. closing this.
