### ISSUE TITLE
[Suggestion] Enable TwilightForest and/or Farmer's Delight in Fabric

### ISSUE THREAD

**Issue by kingkuys2123** [MehVahdJukaar/WoodGood#128]
The TwilightForest and Farmer's Delight Compat for EveryComp are not available in fabric

**Comment by ghost** [comment]
I assume there's a reason for disabling these on Fabric, but a fix would be much appreciated if possible. Would love to use banisters and cabinets!

**Comment by Xelbayria** [comment]
Can you create a separate issue for both mods using the "Module Enhancement"?

**Comment by kingkuys2123** [comment]
okay suree, and will be closing this

**Comment by Xelbayria** [comment]
> I assume there's a reason for disabling these on Fabric, but a fix would be much appreciated if possible. Would love to use banisters and cabinets!

It was disabled like you said. I'll update it if there is any problems and re-add it to EC later on. 

Btw, **Farmer's Delight** is supported in both FORGE & FABRIC. that's all. thanks for separating these suggestions into issues.
