### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by Alpha-Flyte** [MehVahdJukaar/WoodGood#13]
As the title says, the came crashes on startup
Here's my crashlog:
[crash-2022-06-16_20.37.56-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/8918950/crash-2022-06-16_20.37.56-client.txt)

Mods: Plenty of different mods, doubt they're related from what it seems in the crashlog, I do have SeleneLib installed for Every Compat, Smarter Farmers, and Supplementaries

Version: Minecraft 1.18.2, Forge 40.1.14, SeleneLib 1.17.7, Every Compat 1.5.6 (These two mods seem to be the ones core to the issue)

**Comment by MehVahdJukaar** [comment]
hm weird I'll look into it

**Comment by Alpha-Flyte** [comment]
Ok, so...
Used Every Compat 1.5.7 w/ SeleneLib 1.17.7, made it to MC loading screen after which MC told me SeleneLib was out of date
After upgrading to SeleneLib 1.17.9, game crashes w/ this log:
[crash-2022-06-22_16.20.47-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/8955862/crash-2022-06-22_16.20.47-client.txt)

**Comment by MehVahdJukaar** [comment]
Can you list me all the mods that add wood types that you have? It's one of them that has some blockstate dependant properties in its planks

**Comment by Alpha-Flyte** [comment]
The mods I have that add wood/wood related items/mechanics are:
Biomes O Plenty
Compat O Plenty
Bonsai Trees
Corail Woodcutter
Ecologics
Every Compat
Immersive Weathering
Macaw's Fences, Macaw's Fences Biomes O Plenty, Macaw's Furniture, Macaw's Windows
Quark

That should be it.

**Comment by Alpha-Flyte** [comment]
Ok so, I've updated several mods in my modlist, and added like one or two more? The same error seems to be occurring as far as I can tell.
Interestingly, a mod that should be unrelated (Apathy Mod) is calling an error in the modlist portion of the error log. None of the other mods call error.
However, I based many of my mod choices on Vazkii's Bliss modpack, which also includes the Apathy Mod among many others, including Supplementaries, Every Compat, and Moonlight Lib (formerly Selene Lib), and Bliss should be stable (at least I would assume they don't have my crash on startup issue).
