### ISSUE TITLE
[Suggestion] Please consider adding the chests to the forge chest tag

### ISSUE THREAD

**Issue by sciguyryan** [MehVahdJukaar/WoodGood#130]
Hi.

Thanks for making this fantastic mod. Would it be possible for you to consider adding the chests to the forge chests tag, so that they can more easily be used in recipes added via datapack or kubejs?

Thanks.

**Comment by MehVahdJukaar** [comment]
fixed

**Comment by tgstyle** [comment]
Has this been released yet or is it broken? I have plenty of chests that do not have the tag - Redwood, Cherry, Green Cactus, etc.

Using 1.9.2-2.4.7

**Comment by MehVahdJukaar** [comment]
Chests from which mod? I think I only got quark ones and last time I checked they were tagged

**Comment by tgstyle** [comment]
Biomes-O-Plenty is the one.
