### ISSUE TITLE
[Bug] Create - sequence recipes with wooden cogwheels

### ISSUE THREAD

**Issue by FlynnLies** [MehVahdJukaar/WoodGood#131]
Sequence recipies do not work using the added wooden cogwheels at least in 1.18.2

While this is not game breaking since you can still craft them into the regular cogwheels it took me quite a bit of time to figure out that this was the problem.

**Comment by Xelbayria** [comment]
is this issue solved? If yes, then please close this

**Comment by Xelbayria** [comment]
Closing this blc of no replying
