### ISSUE TITLE
Can't join server even through mod versions are the same

### ISSUE THREAD

**Issue by Nariod14** [MehVahdJukaar/WoodGood#132]
I can't join my server as apparently the mod version i have on the server and locally are different when they're both the latest, 2.2.3. After looking at the logs it seems quark is to blame for this as the bamboo torches don't seem to have a map in everycompat. Here are my logs: https://mclo.gs/s8CYFXL hope they help! as of now most of my farms are made using items from this mod, so removing it might actually mess up all my fences, so I'm a little afraid to do so. I'll try downgrading quark a bit to resolve this and keep this updated, but I wanted to make the issue known!

 

Please do let me know if I need to provide anything else!

**Comment by Xelbayria** [comment]
check this out for some detail: #71 

try update `moonlight lib` to the latest version according to **Issue\#71**

if this issue is resolved, then please close this, thanks!

**Comment by Nariod14** [comment]
my god i forgot to close this. thats on me. Yeah not having this anymore.
