### ISSUE TITLE
[Bug] EveryCompat fences can't connect with each other

### ISSUE THREAD

**Issue by LolJohn11** [MehVahdJukaar/WoodGood#134]
The modded fence variants generated by this mod don't seem to connect with each other, even though they appear to be able to connect with nearby blocks just fine. See the demonstration in the video attached below.
This seems to be caused by EveryCompat fence blocks (same issue as with [ladders](https://github.com/MehVahdJukaar/WoodGood/issues/103#issue-1478248244), currently) not having any block tags assigned to them.

https://user-images.githubusercontent.com/49366383/214618652-a280ba9c-f80c-4222-b1fe-8989040b09f4.mp4

**Comment by EnbyChu** [comment]
I have also noticed this happening, which is interesting because i believe in a previous version the fences did connect properly. I could be misremembering, however.

**Comment by MehVahdJukaar** [comment]
should be fixed now
