### ISSUE TITLE
Issues with Twilight Forest and Furnish causes crashing

### ISSUE THREAD

**Issue by xvmorphvx** [MehVahdJukaar/WoodGood#137]
Twilight Forest wood types fail to make chests but cam load every other block type. And Furnish causes Minecraft to crash upon startup saying that Every Compat failed to load correctly. Crash report and latest log are attached.
[crash-2023-02-04_11.44.59-fml.txt](https://github.com/MehVahdJukaar/WoodGood/files/10609114/crash-2023-02-04_11.44.59-fml.txt)
[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/10609118/latest.log)

**Comment by MehVahdJukaar** [comment]
should be fixed
