### ISSUE TITLE
1.18.2 - Startup Crash 

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MehVahdJukaar/WoodGood#139]
So I have no idea if this should be reported.
https://gist.github.com/P3rf3ctXZer0/92ed31b741bc52e9faecaa0fd7bea9dc

**Comment by Xelbayria** [comment]
it looks like this is related to Alex's mobs.

if this happens again, then please add the crash-report file or latest.log here. You can attach them here. I'll check if it's related to Every Compat or not.
