### ISSUE TITLE
Chests, bookshelves, ladders aren't craftable when quark and woodworks are both enabled

### ISSUE THREAD

**Issue by 0Navis0** [MehVahdJukaar/WoodGood#140]
Quark disables by default its own integration for chests, bookshelves, and ladders, in favor of WoodWorks ones, when both are present. It causes chests, bookshelves, and ladders from Every Compat to not be more craftable.

**Comment by MehVahdJukaar** [comment]
thats intended. EC follows what quark does. if its stuff gets hidded so will every compat one. if you want to use quark wood stuff just disable its recipe anti overlap
