### ISSUE TITLE
[1.19.2] Most added items broken?

### ISSUE THREAD

**Issue by VaelophisNyx** [MehVahdJukaar/WoodGood#145]
So it seems the vast bulk of items this adds for BYG, Bewitchment, etc, all turn into weird thing when placed.
Doors become stacked waterlogged slabs, fences, carpets, etc, at random

can't pin it down, no errors in the log at all

**Comment by MehVahdJukaar** [comment]
It sounds like a client server mod desync on your own end

**Comment by VaelophisNyx** [comment]
thing is this affects every other client as well

**Comment by VaelophisNyx** [comment]
additionally if a block update is issued to affected blocks (not doors though?) it causes them to be fixed

**Comment by VaelophisNyx** [comment]
https://user-images.githubusercontent.com/1534478/225416646-b3b2ea7d-e828-4dd7-913a-3f37507ee03c.mp4

this is contagious as well, spreading to nearby blocks, even of not-matching block states

**Comment by VaelophisNyx** [comment]
lastly, this only effects Every Compat, no other mod's blocks are causing this

**Comment by MehVahdJukaar** [comment]
You on a server right?

**Comment by MehVahdJukaar** [comment]
If not might be some weird conflict with some rendering mod. Also what loader?

**Comment by VaelophisNyx** [comment]
Yes this is a server; but also the mod set is about 99% identical, just some client side mods that are different
Renderer is Sodium + Indium
Loader is Fabric 14.17

**Comment by MehVahdJukaar** [comment]
If it's only on a server it's definitely a server client desync. Check if all the mods versions are the same

**Comment by VaelophisNyx** [comment]
they are-
I'm the server operator
that said tests show singleplayer is fine, so I am entirely unsure what the cause is, as the mod set is identical aside from client side mods

**Comment by MehVahdJukaar** [comment]
If that's the case must be some weird mod incompatibility. Maybe something has messd up the blockstate map. Idk what would would or could do that

**Comment by VaelophisNyx** [comment]
I'm trying just dumping every mod, client and server side, into the server to test that

**Comment by VaelophisNyx** [comment]
yep, even with a 100% identical mod set, Every Compat doors/roofs on the server break as per the video posted earlier. they technically "function" but the fake blocks have their proper hitboxes overlapping them too preventing their use

**Comment by VaelophisNyx** [comment]
https://pastebin.com/9pVNmdWG here's a list of all mods on the server

**Comment by MehVahdJukaar** [comment]
Is it just those roofs and doors?

**Comment by VaelophisNyx** [comment]
seems so? I tried out tables, bridges. supports, etc, and none of those were misbehaving at all

**Comment by MehVahdJukaar** [comment]
try new version
