### ISSUE TITLE
[1.19.2] Crashing on startup with Furnish V22

### ISSUE THREAD

**Issue by NovaViper** [MehVahdJukaar/WoodGood#146]
Hey I noticed the game crashes when I load up specifically v22 of the Furnish mod. I get this error in the screenshot below. This issue goes away as soon as I go the previous version of the mod, v21-1.19. Will there be a hotfix update to address this issue?
![image](https://user-images.githubusercontent.com/7191115/228368237-5df98e66-255a-4d53-8562-704e133257f4.png)
Full Logs: https://mclo.gs/dlLcJCc

**Comment by iobiarg** [comment]
same here
