### ISSUE TITLE
Twigs Table Model Error

### ISSUE THREAD

**Issue by ghost** [MehVahdJukaar/WoodGood#153]
Minecraft `1.19.2`
Fabric `0.14.19`
Fabric API `0.76.0`
Every Compat `2.3.1`
Ecologics `2.1.11`
Frame API `0.26.1`
Moonlight Lib `2.2.29`
Twigs `2.0.0-beta-9`
Latest log: https://gist.github.com/Puffadillo/1f2dd21c29e81127ca5bac8cb2030f33

The latest version of Every Compat has missing textures for all Twigs tables. The model is probably broken in some way.
![tables](https://user-images.githubusercontent.com/108554062/230736991-088fbf77-819a-49d5-a37e-361fc5fda850.png)
This issue was not present on Every Compat version 2.2.2. Tested on a fresh instance with only the mods posted above.

**Comment by MehVahdJukaar** [comment]
This still an issue?

**Comment by Xelbayria** [comment]
@Puffadillo is this issue resolved in the latest version? If yes, then please close this issue, thanks!

**Comment by Xelbayria** [comment]
I've run a test using the latest version of these mods via the list. 

there are no issues.
