### ISSUE TITLE
Storage Drawers Compat (1.18.2)

### ISSUE THREAD

**Issue by Farcr** [MehVahdJukaar/WoodGood#156]
Despite the curseforge page saying there is compat with Storage Drawers - that does not seem to be the case. Was it added in 1.19, or is it broken?

**Comment by Xelbayria** [comment]
It is working in 1.19.2 but not 1.18.2. I've tested it.  Please check with the latest version of Everycompat & Moonlight along Storage Drawers

if it's fixed, then please close this issue, thanks! 


## DETAIL:

**Storage Drawers** is not supported in 1.18.2. It is supported in 1.19.2 and newer versions.
