### ISSUE TITLE
Dramatic Doors ClassNotFoundException

### ISSUE THREAD

**Issue by karltroid51** [MehVahdJukaar/WoodGood#159]
Every Compat failed to load correctly when running with Dramatic Doors, when it would previously run just fine. I'll attach the crash log here.

[crash-2023-04-22_06.16.38-fml.txt](https://github.com/MehVahdJukaar/WoodGood/files/11299582/crash-2023-04-22_06.16.38-fml.txt)

**Comment by Royal-Jelly** [comment]
I get the same issue when using the latest version of Dramatic doors

**Comment by Numerosityy** [comment]
Have had this issue as well.
