### ISSUE TITLE
[Feature Request/Bug Fix] Update Architect's Palette Board support

### ISSUE THREAD

**Issue by jsburger** [MehVahdJukaar/WoodGood#160]
As of AP 1.3, Boards have been rewritten and are causing crashes with EveryCompat for 1.18. I looked into it and I'm not sure how to fix it myself, so I will list details to help with the update.

- The crash is seemingly caused by changing OAK_BOARDS from a RegistryObject to a new custom class I use for registering things like slabs and other variants. This class implements Supplier<Block> so I'm not sure why its crashing. You can call OAK_BOARDS.getObject() to get the normal registry object.
- Board models are now completely mundane, barring the item model, which uses the original parent model and is used to add the odd texture to the block atlas.
- The BoardBlock class is no longer used, instead, all Boards and their variants use standard Block classes, and the visual function is added via dynamic model baking. I added a static function which should register these [here](https://github.com/jsburger/Architects-Palette/blob/1.19.2/src/main/java/architectspalette/core/event/ModelBakeEventHandler.java#L53). I tried to make it as generic as possible, since I'm not sure how your process works. The baseBoard parameter is the board block that the variants are made of.
- Boards now have Slabs, Stairs, Walls, and Vertical Slabs when Quark is present. These all need to be passed through the model registering function but are otherwise mundane variants.

Sorry for the inconvenience and not fixing it myself.

**Comment by MehVahdJukaar** [comment]
should be working now
