### ISSUE TITLE
The Storage Drawers module doesn't work in 1.18.2

### ISSUE THREAD

**Issue by hyygybs** [MehVahdJukaar/WoodGood#163]
Storage Drawers version: 10.2.1
Selene version: 1.17.9
Every Compat version: 1.5.15

otherwise, could you please add support to Functional Storage?

**Comment by Xelbayria** [comment]
**Storage Drawers** is not supported in 1.18.2 but are supported in 1.19.2 or newer version. In future, **Functional Storage** will be added. no eta.

**Comment by Xelbayria** [comment]
Funcitional Storage are now supported from 1.19.2 onward.

There is a good news: Storage Drawers is now working properly in 1.18.2 (I've run tests on my side)
