### ISSUE TITLE
Server crashes with Create mod installed

### ISSUE THREAD

**Issue by hadrizi** [MehVahdJukaar/WoodGood#165]
If you install Wood Good(`everycomp-1.19.2-2.3.4-fabric`) and Create(`create-fabric-0.5.0.i-1003+1.19.2`) on the Fabric server, it crashes on startup

for more info and logs you can check the [issue I created in Create repostory](https://github.com/Fabricators-of-Create/Create/issues/907)

**Comment by TorchTheDragon** [comment]
Having same issue with Wood Good version 2.4.0 for fabric

**Comment by TorchTheDragon** [comment]
I tested, fixed in 2.4.6 version
