### ISSUE TITLE
Macaw's Furniture and Roofs is installed. No varients from this mod exist for them.

### ISSUE THREAD

**Issue by MagmaSlime123** [MehVahdJukaar/WoodGood#169]

**Comment by MehVahdJukaar** [comment]
It's not among the supported mods

**Comment by MagmaSlime123** [comment]
Your description mentions furniture and roofs under Macaw's stuff.

![image](https://user-images.githubusercontent.com/51277766/236887345-480dcbaa-99f0-4b10-8969-97c43ddb852d.png)
