### ISSUE TITLE
Forbidden Arcanus Chest & Pyromancer Post

### ISSUE THREAD

**Issue by BookerCatch** [MehVahdJukaar/WoodGood#17]
https://gist.github.com/BookerCatch/225ffd4acb4c9b0d14a173282de29de2
Let me know if you need the full log

Pyromancer's log texture has an unorthodox file name of "pyrowoodlogside.png" which may or may not be creating the issue.

Forbidden Arcanus' mystery wood's texture is indeed longer than usual due to its animated nature; however, the mod works fine for other mysterwood components, like bookshelves, windows, etc.

**Comment by MehVahdJukaar** [comment]
hm I have to come up with as system to hardcode all those weird wood names. Thing is texture detection cant be automated and just relies on naming convention so it fails with those weirdly named ones

**Comment by Xelbayria** [comment]
Is this issue solved? If yes, then please close this

**Comment by Xelbayria** [comment]
Closing this blc of no replying

& this should be fixed via Moonlight lib since it has the system to deal with hardcoded WoodTypes' name
