### ISSUE TITLE
Loading error on launch after last update

### ISSUE THREAD

**Issue by ObsyTek** [MehVahdJukaar/WoodGood#170]
I made a modpack that worked well until today. Updating my mods I installed "everycomp-1.19.2-2.4.4.jar" and when I launched the game I got the error text : `Every Compat (everycomp) has failed to load correctly java.lang.reflect.InvocationTargetException: null`

- Minecraft 1.19.2
- Forge 43.2.7
- Client side
- Every Compat 1.19.2-2.4.4
- Error on launch

[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/11446453/latest.log)
[crash-2023-05-10_23.30.22-fml.txt](https://github.com/MehVahdJukaar/WoodGood/files/11446454/crash-2023-05-10_23.30.22-fml.txt)

**Comment by ASchneider-GitHub** [comment]
Figured it was worth noting, but I'm having the same issue with both `1.19.2-2.4.4` and `1.19.2-2.3.3.jar`
[crash-2023-05-10_21.30.43-fml.txt](https://github.com/MehVahdJukaar/WoodGood/files/11448111/crash-2023-05-10_21.30.43-fml.txt)

**Comment by ASchneider-GitHub** [comment]
Looks like it's because they rewrote the Twigs mod recently and it broke compatibility here. Downgrade Twigs to `twigs-forge-2.0.1+1.19.2` and it will launch correctly.

**Comment by TrueDevron** [comment]
Same issue with fabric, but it's to be expected as the entire mod has been rewritten

**Comment by MehVahdJukaar** [comment]
fixed
