### ISSUE TITLE
[suggestion/request] Regions unexplored compatibility?

### ISSUE THREAD

**Issue by Darkmega18** [MehVahdJukaar/WoodGood#175]
Would you be able to do the wood varieties from Regions unexplored and have it create chests etc for the other mods you list for compatibility?

**Comment by MehVahdJukaar** [comment]
Have you tried it? Does it not work already?

**Comment by Darkmega18** [comment]
nope. I wouldn't be here if it did... >_>' so does that mean it's been added but theres something wrong with my modpack...?

I've got quark installed, so I'd figure a chest for quark like advertised on the main page would get fabricated for woods that don't already have their own... like the maple and pine wood from regions unexplored specifically which don't have such.

isn't that how it's meant to work? any woods with missing parts for the various other listed compatible mods this mod supports get objects of those types dynamically created?

as an aside I'm stuck behind a create update cause of a few lingering addon mods. so if it was added most recently or requires most recent quark (which I'm also stuck behind due to other GUI issues with it's recent update) then that could be the issue. but otherwise, no, it's wasn't working.

**Comment by MehVahdJukaar** [comment]
I don't know,  just open the game and check if they are there. If not I'll have a look. I'm asking because it's not the first time I had to boot up the game to see if something was working when it actually was fine

**Comment by Darkmega18** [comment]
so check if they're in JEI but for some reason not getting recipes basically? alright, one sec...

**Comment by Darkmega18** [comment]
![image](https://github.com/MehVahdJukaar/WoodGood/assets/8104689/501eeae7-5891-46ca-b5af-1eb2e76bc50f)
it's there. but no recipe attached apparently. my bad. upon checking other things, the cabinet etc all work. just that outlier of the chest not picking up.

**Comment by MehVahdJukaar** [comment]
Are quark chests craftable? Like blossom chest

**Comment by Darkmega18** [comment]
> Are quark chests craftable? Like blossom chest

ah crap. I checked it. and it seems the chests have turned themselves off due to woodwork existing. Well, that tops my frick. I'm sorry for bothering you. I went and disabled the anti-overlap, which should make that work.
