### ISSUE TITLE
[Mod Compatibility] BetterNether Chairs and Stools with Better End

### ISSUE THREAD

**Issue by Atirtra** [MehVahdJukaar/WoodGood#177]
BetterNether chairs and stools are not supported by the mod currently. You can only craft them using Vanilla and BetterNether wood types.

BetterNether and BetterEnd have become the popular go-to dimension mods for Fabric so crafting compatibility with other mods for the chairs and stools would be greatly appreciated. I'm not sure if this would have to be done on their side so I'm sorry in advance if that's the case.

**Comment by MehVahdJukaar** [comment]
Last time I checked those mods had a sort of dynamic system where they register blocks kind of like I do so wouldn't make sense for me to add them when their system can do the same

**Comment by Atirtra** [comment]
That's a shame because they don't even seem to have compatibilty with each other in that regard, so compatibility with any mod is basically none right now. Not gonna bother you though if they have a system that's not easily overwriteable/is complicated to make work in parallel. I'll just go ask them then. Thanks for the quick reply.

**Comment by MehVahdJukaar** [comment]
I wouldn't be able to add it even if I wanted to unfortunately. The mod intact barely works with those 2 mods as many of their wood blocks aren't even registered when everycomoat adds is on contrary of mods other normal mods. This means that texture detection is off so EC just assumes where those could be. This is for finding planks blocks flbut for furniture I would need the base oak instance to be there which it isn't at that time. Personally I don't know why they did all that as dynamic registration only make sense when your blocks are actually dynamic, meaning their number and types can vary depending on what mods you have which isn't the case there. Instead they might be using that to have config dependant registration which is a pretty questionable practice, very discouraged on forge, same reason EC doesn't have it and it's registered blocks are always only based on the installed mods

**Comment by Atirtra** [comment]
Oh, I'd also ask about this Variant Block series for wood types. Is there a similar reason why none of it's mods work at all with EC? Thanks
https://www.curseforge.com/minecraft/mc-mods/variant-bookshelves-fabric

**Comment by MehVahdJukaar** [comment]
Well EC just adds blocks to some mods it supports. That isn't among them

**Comment by Atirtra** [comment]
Oh ok, I misunderstood it saying "It's magic" on curseforge, I somewhy thought it was half-automatic? :D If you could in the future add compatibility for them, it would be awesome, no rushes needed. I'll now close this issue.

**Comment by MehVahdJukaar** [comment]
Well the woos part is automatic. The block definitions are not

**Comment by MehVahdJukaar** [comment]
Tho adding these with my system is quite easy. I've got some people what went crazy with those making pull requests for ec
