### ISSUE TITLE
Crash with Create 5.1b

### ISSUE THREAD

**Issue by PapaDimitri** [MehVahdJukaar/WoodGood#187]
So I was trying to startup modpack but i was welcomed with crash :/

java.lang.Exception: Mod Loading has failed

Crash report:
[crash-2023-06-09_12.07.51-fml.txt](https://github.com/MehVahdJukaar/WoodGood/files/11705197/crash-2023-06-09_12.07.51-fml.txt)

**Comment by MehVahdJukaar** [comment]
Update dramatic doors

**Comment by PapaDimitri** [comment]
It works thank you so much!
Sry for issuing I literally just read crash log again and I saw dramatic doors -_-

**Comment by MehVahdJukaar** [comment]
Sure glad it worked!
