### ISSUE TITLE
Some posts make fungal wood noises

### ISSUE THREAD

**Issue by saltyseadoggo** [MehVahdJukaar/WoodGood#189]
As per the title, I noticed that some posts added by this mod make fungal wood noises when placed/broken/stepped on instead of regular wood noises. They are as follows:

- Twilight Forest twilight oak, canopy, darkwood, mangrove, transwood, minewood, sortingwood & timewood
- Nether's Exoticism jabuticaba
- Stripped versions of all of these

As I do not have other mods that lack posts in my save, I do not know if their posts make the wrong noises too. Given that all of the Every Compat posts in my save make the wrong noises, however, it's possible that this affects all Every Compat posts.

**Comment by MehVahdJukaar** [comment]
Posts from which mod?

**Comment by saltyseadoggo** [comment]
Quark. My apologies, I didn't know there were other post adding mods

**Comment by MehVahdJukaar** [comment]
Hm and those wood planks all make normal wood noise? I think posts are set to copy that

**Comment by saltyseadoggo** [comment]
Indeed, the planks all make regular wood noises.

**Comment by MehVahdJukaar** [comment]
tracked it down to the way quark post handles sound type (not inheriting but rather if the woodtype is flamable or not) and those mods not marking those types as flammable. if it makes that sound it means the fence made of that woodtype is not flammable which is likely a bug for most of those

**Comment by MehVahdJukaar** [comment]
anyways ive added a workaround so should be fixed
