### ISSUE TITLE
Error in log with Croptopia [1.18.2 Forge]

### ISSUE THREAD

**Issue by TobyVanBuynder** [MehVahdJukaar/WoodGood#19]
On loading a Forge server on 40.1.51, it consistently shows this error:
`[Worker-Main-21/ERROR] [minecraft/RecipeManager]: Parsing error loading recipe everycomp:q/croptopia/cinnamon_hedge
com.google.gson.JsonSyntaxExceptionItem array cannot be empty, at least one item must be defined`

Console log dump: https://pastebin.com/SKqYKjYr
Used mods: https://pastebin.com/dCxyx2mJ
The modpack (if needed) can be downloaded here to test: https://www.curseforge.com/minecraft/modpacks/you-want-some-flizz

**Comment by Xelbayria** [comment]
is this issue solved? If yes, then please close this

**Comment by Xelbayria** [comment]
closed this due to no replying
