### ISSUE TITLE
1.18.2 Crash with Create 0.5.1.b

### ISSUE THREAD

**Issue by JDtheHutt** [MehVahdJukaar/WoodGood#191]
I saw #187 but I've tried this with purely the minimal mods needed for Create and Every Compat, with everything up to date and this continues to occur.  It seems unhappy with the new connected textures included in 0.5.1.  On my larger mod build I had another mod that did something like that too, hence I created a new instance to test just the base mods.  Please let me know if I am doing something wrong here.  Thank you.

[crash-2023-06-14_09.49.26-fml.txt](https://github.com/MehVahdJukaar/WoodGood/files/11743713/crash-2023-06-14_09.49.26-fml.txt)

**Comment by MehVahdJukaar** [comment]
You are 3 every compat versions behind

**Comment by JDtheHutt** [comment]
Not according to your page on Modrinth :D  Thanks, will get from Curseforge as I see it is on .18 there.

**Comment by Xelbayria** [comment]
If the latest version resolves your issue, then please close this issue.
