### ISSUE TITLE
Crash on launch with Builder's Delight

### ISSUE THREAD

**Issue by Khaeops** [MehVahdJukaar/WoodGood#194]
Game crashes on load, pointing to what appears to be difficulties with generating loot tables for Builder's Delight.
[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/11779155/latest.log)

**Comment by MehVahdJukaar** [comment]
check moonlight is updated

**Comment by Xelbayria** [comment]
@Khaeops 
Please close the issue if the issue is resolved. It's not a good idea to leave it open.

**Comment by Khaeops** [comment]
My bad I forgot about this, it seems to be working with at least 1.19.2 - 2.4.9, so I'll mark this as closed.
