### ISSUE TITLE
Architect's Pallette Boards not varying even-odd as intended

### ISSUE THREAD

**Issue by annastropha** [MehVahdJukaar/WoodGood#200]
Here's an image of Morado (From Atmospheric, boards by this mod) and Spruce (from AP itself):
![image](https://github.com/MehVahdJukaar/WoodGood/assets/111990369/011ab44f-7228-44d0-a695-a42312336916)
Morado has odd_x and odd_z blockstates, but they do nothing, while spruce doesn't.

I see that #160 has a comment that it should be working a while ago, but that change is not reflected in the code - BoardBlock is used [here](https://github.com/MehVahdJukaar/WoodGood/blob/multi-loader/forge/src/main/java/net/mehvahdjukaar/every_compat/modules/forge/architect_palette/ArchitectsPaletteModule.java#L68) and the mentioned function for registering dynamic models (`registerBoardModel`) is unused as far as I can tell.

**Comment by jsburger** [comment]
Today I fixed this on AP's side for the Forge version of the mod (as seen [here](https://github.com/jsburger/Architects-Palette/commit/20073d4d6215e08d4a5c4b01b2e70bc87f26e91c)). The update should be out relatively soon.
