### ISSUE TITLE
Possible 1.20.x version?

### ISSUE THREAD

**Issue by Gamemassa** [MehVahdJukaar/WoodGood#203]
Hi, I noticed that the latest version of EveryComp does not work with MC 1.20.x and I was just curious if there is a 1.20.x version of EveryComp being worked on. No rush, either, btw. I just wanted to make sure you're aware of this incompatibilitty.

**Comment by MehVahdJukaar** [comment]
Most of the dependencies are not for 1.20
Also it's obvious that I'm aware. It's a different version and like all mods it needs updating to work xD

**Comment by Gamemassa** [comment]
Gotcha. Thanks for the quick response, and apologies for the silly question.

**Comment by Gamemassa** [comment]
@MehVahdJukaar Out of curiosity, I'm assuming one of the reasons EveryCompat for 1.20.x isn't out yet is because you need BYG for 1.20.x first in order to get object/texture references, right? (Among other mods as well, I'd imagine)

**Comment by MehVahdJukaar** [comment]
No, mod has no ties whatsoever to any mod that adds wood. Reason is the 1.19 verison has some issues and also many of the mods this mod ads support for aren't uodated

**Comment by MehVahdJukaar** [comment]
So be patient

**Comment by Gamemassa** [comment]
> No, mod has no ties whatsoever to any mod that adds wood. Reason is the 1.19 verison has some issues and also many of the mods this mod ads support for aren't uodated

Yeah, that's what I meant. And no, I'm not in a rush at all. I was just asking questions for fun.
