### ISSUE TITLE
Added every compat and i cant craft certain blocks

### ISSUE THREAD

**Issue by SassyKatREEEEE** [MehVahdJukaar/WoodGood#204]
So i have Oh the biomes you'll go with every compat and i cant seem to make any of the wood variants whether it's ebony planks or witch hazel planks.
I try to press R in jei and it just gives nothing but uncrafting
![image_2023-07-05_070034835](https://github.com/MehVahdJukaar/WoodGood/assets/138556785/ef455c1a-1918-40a7-9814-9dcec6d39cf5)

**Comment by Xelbayria** [comment]
please fill in the following:
Minecraft Version:
Loader: (Forge or Fabric)
EveryCompat (EC) Version:
Which Mods does EC have an issue with:

**Comment by Xelbayria** [comment]
Haven't heard from you for a while. Can you reply to the above?
