### ISSUE TITLE
Mod Incompatibilty breaking Forge:planks crafting recipes

### ISSUE THREAD

**Issue by DraTrav** [MehVahdJukaar/WoodGood#206]
If all of the mods are installed, removing any one of them fixes it but all combines breaks it.
-chipped
-kubejs
-hexeri
-every Comp

recipes that use forge:planks break preventing even the crafting table from being craftable.

Minecraft: 1.19.2
Forge: 43.2.14
Every Compact: 2.4.12 (Does not happen in 2.4.11

[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/12022453/latest.log)

![image](https://github.com/MehVahdJukaar/WoodGood/assets/42803478/1e47302d-a7e9-47f2-8d1b-3a81cc897aa3)

**Comment by MehVahdJukaar** [comment]
Log says this 
Not all defined tags for registry ResourceKey[minecraft:root / minecraft:item] are present in data pack: hexerei:mahogany_planks, 
	hexerei:willow_planks, 
	hexerei:witch_hazel_planks

**Comment by DraTrav** [comment]
I am aware of that, however this workes just fine in 2.4.11. something that got changed in 2.4.12 broke it. and interestingly removing any one of the 4 mods fixes the issue

**Comment by MehVahdJukaar** [comment]
Are chipped blocks available using hexereinwoodtypes?

**Comment by MehVahdJukaar** [comment]
Must be some weird tag loading stuff, maybe circular tag dependencies or something, maybe something with kubejs doing stuff early I'm not sure. EC just adds entries to those 3 tags which if those blocks are there are definitely getting generated. Maybe kubejs prevents them from loading. Try reloading datapack

**Comment by DraTrav** [comment]
Reloading the data pack does fix it! however it has to be reloaded everytime the world loads.

**Comment by MehVahdJukaar** [comment]
I have no idea how this could be fixed but I suspect it's something with kubejs being fundamentally incompatible as both alter tags supposedly in same stage which would possibly cause such edge cases

**Comment by DraTrav** [comment]
actually, it worked after a reload and reloading the world. so it just has to be reloaded once. is there a way to set a priority?

**Comment by MehVahdJukaar** [comment]
Only thing that comes to mind is adding a datapack which adds those tags manually. No idk how that mod works

**Comment by DraTrav** [comment]
I mean within yours. I'm unsure if it would help but I believe you can add a priority to a mixin as a second parameter.  for example in your LootTableHackMixin.java I think you can call it as @Mixin(BlockBehaviour.class,  priority = 0).

**Comment by MehVahdJukaar** [comment]
Mixins have nothing to do here

**Comment by DraTrav** [comment]
ah, sorry, I am not too familiar with java in general.

**Comment by Xelbayria** [comment]
@DraTrav 
are you able to solve the issue? I know KubeJS & CraftTweaker have the ability to set priority on the script when launching Minecraft. I am not sure if Datapack is capable of this as I am not familiar with Datapack.

**Comment by DraTrav** [comment]
I was not, I ultimatly removed the mod due to high ram usage, but a fix would be with kubejs and have a delay after 30 seconds to run /reload

**Comment by Xelbayria** [comment]
I supposed you removed Every Compat because of High ram usage?
