### ISSUE TITLE
[Fabric Mod Compat Suggestions]

### ISSUE THREAD

**Issue by kingkuys2123** [MehVahdJukaar/WoodGood#209]
## Mod Support
- [`Backpacked (Fabric)`](https://legacy.curseforge.com/minecraft/mc-mods/backpacked-fabric):
     - **Wooden Backpack Shelves**
- [`The Graveyard`](https://legacy.curseforge.com/minecraft/mc-mods/the-graveyard-fabric):
     - **Wooden Coffins**
- [`Bewitchment`](https://legacy.curseforge.com/minecraft/mc-mods/bewitchment): 
     - **Poppet Shelves**
- [`Create: Steam n' Rails`](https://legacy.curseforge.com/minecraft/mc-mods/create-steam-n-rails/files/4630216):
     - **Wooden Train Tracks**
     - **Incomplete Wooden Tracks**
- [`RedBits`](https://legacy.curseforge.com/minecraft/mc-mods/red-bits):
     - **Large Wooden Buttons**
- [`Twilight Forest (Fabric)`](https://legacy.curseforge.com/minecraft/mc-mods/the-twilight-forest):
     - **Wooden Banisters**
     - **Hollow Logs**
- [`Wooden Hoppers`](https://legacy.curseforge.com/minecraft/mc-mods/wooden-hoppers):
     - **Wooden Hoppers**
- [`Table Top Craft`](https://legacy.curseforge.com/minecraft/mc-mods/table-top-craft-fabric):
     - **Chesses & Connect Fours**
- [`Mighty Mail`](https://legacy.curseforge.com/minecraft/mc-mods/mighty-mail-fabric):
     - **Mail Boxes**
- [`Valhelsia Furniture`](https://legacy.curseforge.com/minecraft/mc-mods/valhelsia-furniture)
     - **Tables**
     - **Desks**
     - **Desk Drawers**
     - **Chairs**
     - **Stools**

## Planks Support

- [`Bewitchment`](https://legacy.curseforge.com/minecraft/mc-mods/bewitchment)
   - Dragon's Blood Planks
   - Juniper Planks
   - Elder Planks
   - Cypress Planks

**Comment by Xelbayria** [comment]
A list of mods has already been mentioned:
- Bewitchment

Can you create a separate issue for each mod except **Bewitchment**? Use `Suggest Mod` and fill out the information.

**Comment by Xelbayria** [comment]
I haven't heard from you for a while. Please do ☝️, thanks!

**Comment by kingkuys2123** [comment]
sorry, I will create sepperate issues with `Suggest Mod` and will be closing this issue :)

**Comment by Xelbayria** [comment]
Oh One more thing.. check the link "EC Backlog". it already have
- **Valhelsia Furniture**
- **Mighty Mail**
- **Create: Steam N' Rails** (can be found on the further right side with details for why it's abandoned), just click on the card) 
- **The Graveyard** I think it's already supported, I'll check 

check other cards that may be already suggested on your lists. and no need to apologize. I am just organizing things, that's all. Thanks, for the replying!

**Comment by Xelbayria** [comment]
**The Graveyard** is already supported for FORGE, but not FABRIC. I'll add this to FABRIC
