### ISSUE TITLE
Allow woods with special functions to impart their functions on furniture and such added by this mod

### ISSUE THREAD

**Issue by Sunconure11** [MehVahdJukaar/WoodGood#22]
A good example of a mod with such functions would be say, Bewitchment's dragon blood wood, with the sigil functionality.

**Comment by MehVahdJukaar** [comment]
That isn't easily doable or not even doable at all. I guess it however depends on what these "functions" would be. Stuff like material color and sound type and such are already copied over

**Comment by Xelbayria** [comment]
is this issue solved? If yes, then please close this

**Comment by Xelbayria** [comment]
will be closing this blc of no replying.
