### ISSUE TITLE
Another Furniture Chairs

### ISSUE THREAD

**Issue by SafeOfArsenal** [MehVahdJukaar/WoodGood#222]
In Another Furniture Mod the chairs should have different designs on the back however in every compat all the chairs are the same

**Comment by SafeOfArsenal** [comment]
I just noticed same goes for the shutter item  (also i would like to point out the designs for the chairs back are for the doors and the shutters are for the trapdoors)

**Comment by MehVahdJukaar** [comment]
EC generates assets for infinite wood types. Unfortunately it is not AI powered and can't create unique custom textures for those
