### ISSUE TITLE
Crash on startup with Woodster

### ISSUE THREAD

**Issue by WaterOre** [MehVahdJukaar/WoodGood#224]
[Woodster](https://modrinth.com/mod/woodster) adds wood variants for chiseled bookshelves, which do not appear to be supported by EveryCompat. When launching the game, it crashed with the message `java.lang.NoSuchFieldError: OAK_CHISELED_BOOKSHELF`

[crash-2023-08-20_18.06.05-fml.txt](https://github.com/MehVahdJukaar/WoodGood/files/12389372/crash-2023-08-20_18.06.05-fml.txt)

**Comment by MehVahdJukaar** [comment]
Fixed

**Comment by Xelbayria** [comment]
If this problem is resolved, then please close this issue, thanks!
