### ISSUE TITLE
Allow datapack/config definition of custom wood types

### ISSUE THREAD

**Issue by Irbynx** [MehVahdJukaar/WoodGood#23]
I'm currently working on a modpack that creates (via kubejs) a few blocks I would like to register as wood types so that they would be usable in various configurations (mostly furniture). Would it be possible to include functionality to register those as wood types somehow, either through datapacks, configs, scripts or some other way?

**Comment by MehVahdJukaar** [comment]
That is not possible. Datapacks are loaded per world while block registration happens on startup and only once. For that to work Mojang would have to make block registration use the datapsack registry system allowing server owners to define custom blocks

**Comment by MehVahdJukaar** [comment]
If you want to add a wood type just add a plant block and a log block that use conventional names and materials. The system will pick them up

**Comment by Irbynx** [comment]
> If you want to add a wood type just add a plant block and a log block that use conventional names and materials. The system will pick them up

Thanks, this works quite well, even if a bit hacky (due to proper blocks not being 'planks' and 'logs'), but nothing that can't be dealt with.

**Comment by Irbynx** [comment]
There is a minor problem with the generation however - Posts from Valhelsia Structures and Signs/Sign Posts from Supplementaries fail to generate and create missing texutres instead. What assets are needed for them to generate properly?

**Comment by MehVahdJukaar** [comment]
oh hm well those use the log texture. Thing is there isnt a way to detect what texture is which so I have to make some assumption like that the side one contains _side and the top one contains _top. If you follow vanilla naming convention everything will work fine

**Comment by Xelbayria** [comment]
If this issue is not solved, then you can re-open this. I'll assume this is solved.
