### ISSUE TITLE
recpies issues

### ISSUE THREAD

**Issue by ZEROX7** [MehVahdJukaar/WoodGood#242]
![image](https://github.com/MehVahdJukaar/WoodGood/assets/12628051/392f7646-aacd-412a-833c-612939ef4440)
no receipes for
bca cubboard
bca small cupboard
bca support bracket
![image](https://github.com/MehVahdJukaar/WoodGood/assets/12628051/89cb5419-bc6d-4dfc-ad9f-ab0bce03d7d9)
no recipes for
stripped park bench
![image](https://github.com/MehVahdJukaar/WoodGood/assets/12628051/37161f11-2b63-4874-b76f-3c0f5eb98f59)
![image](https://github.com/MehVahdJukaar/WoodGood/assets/12628051/04a66f94-61ca-49b0-bc89-c8d8188380a2)
![image](https://github.com/MehVahdJukaar/WoodGood/assets/12628051/2caf0cae-d4f3-4bdb-9baf-1c24a10ef6da)
![image](https://github.com/MehVahdJukaar/WoodGood/assets/12628051/ecb4f04c-9d14-4c9a-91ac-a607a1fe2db9)
this is just the umbra variant but it happens on the others from bop aswell

**Comment by Xelbayria** [comment]
I'll need the version of minecraft

**Comment by ZEROX7** [comment]
its 1.20.1

**Comment by Xelbayria** [comment]
thanks for replying. I'll check and confirm if that's an issue. if it is, then I'll do some investigation to find out what's wrong.

**Comment by Xelbayria** [comment]
@ZEROX7 
I assume you're using the latest version, EveryCompat v2.6.7 & Moonlight v2.8.42.

I'm working on the BCA module. It's kind of "uncompleted". 

EDIT: 
Alright, BCA module is finished. It will be included in the next version of Every Compat.
