### ISSUE TITLE
Massive amounts of spurious missing texture warnings + a handful of real ones

### ISSUE THREAD

**Issue by Traehgniw** [MehVahdJukaar/WoodGood#243]
On 1.20.1 Minecraft, 1.20-2.6.5 Forge Every Compat, more than half my log is filled with Every Compat missing texture warnings.

It's erroring on every item and block Every Compat adds, in every direction directional blocks have. The textures are not missing, except for a few Hollow Log item textures; all the block textures are present.

It's a massive amount of log bloat. This log has over 26,000 lines.

**Comment by MehVahdJukaar** [comment]
you sure you got latest moonlight version? i did add some 1 liner logging insetead of those classic stacktrace dump for those. EC 1.20 is still being worked on so some mods need to have their module checked as some textures might have been moved in the original mod. What mod has the missing textures it says in the log?

**Comment by Traehgniw** [comment]
Moonlight Library is up to date

Everything gets missing texture warnings, but the actual missing textures are: Hollow Jabutica Log Item, Hollow Mulberry Log Item, Hollow Olive Log Item, Hollow Palm Log Item, Hollow Geoxyle Log Item, and Hollow Eucalyptus Log Item.

The block forms of those all have their textures.

Olives are from Pizzacraft, Jabu is from Nether's Exoticism, Geoxyle is from Trails and Tales Plus, Mulberry and Eucalyptus are from Forest X Reborn, and Palm is from Let's Do Beachparty. 

Nothing else from those mods have missing textures. It is ONLY the item forms of the hollow logs that specifically Every Compat adds.

**Comment by winnetrie83** [comment]
I have the same problem with the missing texture spam in the log and also real missing textures.
For me the missing textures are for Twilight forest.
Versions:
- everycomp-1.20-2.6.5
- moonlight-1.20-2.8.13-forge
- forge - 47.1.44

**Comment by winnetrie83** [comment]
The latest update for everycompat and moonlight solved most of the texture issues for me.
However there are still missing textures. As far as i can tell all missing textures are for the "hollow" logs 
Edit: The missing texture is also only for the item not the the block

**Comment by MehVahdJukaar** [comment]
Issues are mostly coming from weird wood types that have unusual names for their stripped variants. Those need to manually be added by me with their id and all as the dynamic system can't detect them, or just ones that simply don't have a stripped log for some reason

**Comment by Xelbayria** [comment]
have the latest version fix this issue. I've seen a similar issue like this before.

**Comment by Xelbayria** [comment]
<strike> Can anyone tell me which mods that **EveryCompat** has a problem with regarding the missing textures for Hollow logs which I believe is from **Quark**?

If there is no replying for a while, then I'll be closing this. </strike>

nvm. i found my answer.

**Comment by Xelbayria** [comment]
I ran a test with the latest version of **Every Compat** & **Moonlight** with the mods that have the missing textures. all are accounted for. 

will be closing this.
