### ISSUE TITLE
1.19.2: Chipped compat texture sets and tags don't include the original plank types in their own tag.

### ISSUE THREAD

**Issue by Darkmega18** [MehVahdJukaar/WoodGood#246]
Basically what it says in the tin. I'm noticing that for chipped, there are wood good textures for every type of wood, which is amazing. but then I can't use them anyway, cause anything not vanilla has a similar issue.

![image](https://github.com/MehVahdJukaar/WoodGood/assets/8104689/a1d923c7-e8fe-4ee7-97f9-dbe1ed23f93b)
![image](https://github.com/MehVahdJukaar/WoodGood/assets/8104689/27b4ec63-546d-40e0-9c5b-663257df28e0)
![image](https://github.com/MehVahdJukaar/WoodGood/assets/8104689/ba62306a-f45f-4b93-bf66-28e43f5ebc1d)

As an aside. it'd be amazing if you could eventually extend this to dynamically make the log textures also in a similar way. :D

**Comment by Xelbayria** [comment]
how did you get the extra information of a block & item with tags when you hover over them? 

<strike>
Also, Can you include the version of 
- Chipped
- EveryCompat
- Moonlight
</strike>

---

EDIT: 
nvm. I investigated the problem and found 2 problems. I've told MehVahdJukaar about 2 problems. they are being fixed.

**Comment by Darkmega18** [comment]
got em.

**Comment by Xelbayria** [comment]
OK, I've fixed the 2 problems. The v2.5.7 has been uploaded to CF, <strike>so it will take a while to be approved. </strike> 
You can check it out to ensure all is good. 

if all is good, then you can close this issue if you feel satisfied with the fixes.

**Comment by Darkmega18** [comment]
Roger-roger. will take a look when I can.

**Comment by sh0tybumbati** [comment]
can we get this fix on modrith as well? we're still on 2.5.5 over there
(oh and fabric as well i mean)
and this might be related, but oak plank versions of things can make any variant, BUT when you select one, it makes a random variant??
![image](https://github.com/MehVahdJukaar/WoodGood/assets/39677663/0683613c-0cfa-4c0c-87e7-a235e59cb60f)

**Comment by Xelbayria** [comment]
> Can we get this fix on modrith as well? we're still on 2.5.5 over there (oh and fabric as well i mean) and this might be related, but oak plank versions of things can make any variant, BUT when you select one, it makes a random variant?? 

I'll speak to MehVahdJukaar about the Modrinth and <strike>I'll upload V2.5.7-Fabric to CF. </strike>

EDIT:
it's uploaded to CF. Regarding Modrinth. it will take a while.

**Comment by Xelbayria** [comment]
> Roger-roger. will take a look when I can.

If you are satisfied with issues gone, then please close this issue, thanks!

**Comment by Darkmega18** [comment]
Ah, yeah, it's been working for a while. so it's all good.
