### ISSUE TITLE
[📦]: Handcrafted

### ISSUE THREAD

**Issue by szunakabeats** [MehVahdJukaar/WoodGood#254]
Handcrafted is such a lovely furniture mod. It would be awesome to use other wood types with it ! <3

https://modrinth.com/mod/handcrafted

**Comment by Xelbayria** [comment]
I'll be adding this to EC since 3+ people wish for this. It will take some time.

**Comment by szunakabeats** [comment]
Happy to hear that ! whats the progress ? :)

**Comment by Tollainmear** [comment]
Seeing the support plan update for this mod makes me very happy, thank you! I appreciate your work, I've been waiting for EC to be compatible with this mod for a month now! Hahaha.

**Comment by Xelbayria** [comment]
yea Sorry about that, I am going to focus on **Handcrafted** and try to get it finished this week.

**Comment by szunakabeats** [comment]
no stress :)

**Comment by Tollainmear** [comment]
Hello, I was wondering if there has been any development progress on compatibility with the HandCrafted mod for version 1.20.1?

**Comment by Xelbayria** [comment]
It will be ported to 1.20.1 when the 1.19.2 is finished. I am trying to get it finished this week or so.

**Comment by etherealgears** [comment]
Just curious if there's been any progress made on this for 1.20.1?

**Comment by szunakabeats** [comment]
is this still going to happen ?

**Comment by Xelbayria** [comment]
still happening. it's difficult to work on. it's 50% done.

**Comment by szunakabeats** [comment]
hey just wanted 2 ask how the progress is going :)

**Comment by Xelbayria** [comment]
😩 quite slow. and a pain in the bum. No worries, i'm still working on it and need to do research.

**Comment by Coach-mdl** [comment]
Just posting so I can stay up to date on the thread. I looked in the code for for Handcrafted thinking I could add compat through KubeJS. For my own sake, I'm not going to try.

**Comment by Xelbayria** [comment]
@Coach-mdl Smart move to not try. Trust me, it's a headache to add it in EveryComp.

**Comment by Coach-mdl** [comment]
Could

**Comment by Coach-mdl** [comment]
@Xelbayria Could be worth see if the mod dev has any ideas if you're struggling. Then you can both struggle.

**Comment by Xelbayria** [comment]
ha. MehVahdJukaar said it's a pain in the bum. I feel the same, it is.

**Comment by Xelbayria** [comment]
## UPDATE: 
The progress: 
I have 3 more blocks left to do: _counter_, _cupboard_, _drawers_. 
This may take some time. I am not sure how to support them yet.

**Comment by szunakabeats** [comment]
atleast it goes forward haha ! thx for the hard work :)

**Comment by Xelbayria** [comment]
## UPDATE: 

version 1.20.1 is almost finished and will be in **v2.6.62**
version 1.19.2 is still not finished because of these 3 blocks. I haven't found a good way to support them yet. 

## UPDATE 2: 

**version 1.20.1** is finished. and I've uploaded the mod to Curseforge (CF) & Modrinth.  CF will take a while to approve the mod.

**Comment by Xelbayria** [comment]
## FINAL UPDATE: 
- 1.19.2 is finished.  it will be in **v2.5.23**

**Comment by szunakabeats** [comment]
HUUUUUUGE S/o to the whole team here! This is really really awesome 🤩 thanks a lot !

**Comment by Xelbayria** [comment]
np! 

FYI, handcrafted for 1.19.2 is kind of "unfinished". I noticed the item _board_ has no recipe. the best way to fix this is to use CraftTweaker or KubeJS to create your own preferred recipe for the boards (both vanilla & everycomp).

**Comment by szunakabeats** [comment]
Alright thx for the info. I’m using 1.20.1 anyways haha 🤓

**Comment by Coach-mdl** [comment]
Dream come true. Can't wait to have my TFC themed Fancy beds.

**Comment by Xelbayria** [comment]
haha. Handcrafted 1.20.1 is already out on the latest version of EveryComp. Never imagine that you would use it with TFC. 

have fun!

**Comment by szunakabeats** [comment]
do you guys have a donation page or something ? :)

**Comment by Xelbayria** [comment]
well, there is no donation page or something. AFAIK.

**Comment by MehVahdJukaar** [comment]
@Xelbayria you are free to add your donation link if you feel like

**Comment by Xelbayria** [comment]
Actually, I'm not familiar with how donation works. I have no idea how to add my donation link. it's my first time
