### ISSUE TITLE
[🐞]: Missing recipe for Quark

### ISSUE THREAD

**Issue by Pantz71** [MehVahdJukaar/WoodGood#255]
I tried to put Quark planks into the sawmill of Woodworks Mod but none of them show up. The boards, ladders, etc... of Woodworks still have in Quark's wood variations
![2023-09-05_21 04 30](https://github.com/MehVahdJukaar/WoodGood/assets/144138711/ce03204d-8c56-4cd1-a6af-2187f6deb5f0)
![2023-09-05_21 05 28](https://github.com/MehVahdJukaar/WoodGood/assets/144138711/98bfbd4f-d973-495d-93a1-bf78b7526a15)
![2023-09-05_21 05 46](https://github.com/MehVahdJukaar/WoodGood/assets/144138711/5221c2b6-58ef-49a1-a50d-15422126e2e4)

**Comment by Xelbayria** [comment]
Woodworks & Quark are missing recipes via Every Compat, correct? I'll assume it's 1.20.1.

**Comment by Xelbayria** [comment]
I haven't heard from you for a while. Is my assumption above correct and  

please fill in the following:
Minecraft Version:
Loader: (Forge or Fabric)
EveryCompat (EC) Version:
Which Mods does EC have an issue with:
- Woodworks
- Quark

**Comment by Xelbayria** [comment]
Reason for closing: No replying for a week. 

if you want to re-open, please provide the information using my previous post as a reference

**Comment by Pantz71** [comment]
srry for not reply. I too busy so can't active for a few months?
anyway
MC ver: 1.19.2
Mod loader: Forge 43.3.7
EC ver: everycomp-1.19.2-2.5.15.jar
Mods does EC have an issue with:

- Woodworks
- Quark
- Deeper and Darker
- Biomes O' Plenty????
I think every mods that not made by Abnormal Team didn't have sawmill recipes....i guess...

**Comment by Xelbayria** [comment]
Thanks for getting back to me. I'll run some tests with the above.

**Comment by Pantz71** [comment]
tysm!

**Comment by Xelbayria** [comment]
I ran test on this. There are no problem on my side. You should use the latest version of EveryComp and Moonlight Lib. 

I've check the recipes with Logs and Planks from **Deeper & Darker** and **Biomes O' Plenty**. Even the blocks generated from **EveryComp** are included in **Woodwork**'s Sawmill. 

Closing this. 

Let me know if some recipes are missing in sawmill.
