### ISSUE TITLE
Potentially poor dedicated server syncing?

### ISSUE THREAD

**Issue by Darkmega18** [MehVahdJukaar/WoodGood#256]
everycomp-1.19.2-2.5.7.jar
forge-1.19.2-43.2.21
Other mods: yes. many.

While playing on my server with a friend I was making some chests out of wood from environmental which had cross compatibility with quark chests. However when I placed them down she got mildly concerned and said we probably shouldn't use the chests.

I asked why and she sent me a picture from ingame in her perspective:
![image](https://github.com/MehVahdJukaar/WoodGood/assets/8104689/575bdee3-2f68-4dac-92db-f0d3152120c8)

I had already placed all 6 chests i had, only only some of them were rendering properly until they were interacted with. Later on, I dug another two infront of the chests on the right and when I placed them they didn't render at all for her until I interacted with them. There seems to be some weird syncing going on server side potentially, can it be looked at why or what can be causing it?

I have a handful of different fixer patches and optimization mods including packet fixer mod, rubidium and modern fix if any of those could be instrumental. I can also just send a copy of the pack we were testing that you could test it against to also see the mods in play too.

**Comment by MehVahdJukaar** [comment]
Mod doesn't touch synching. What matters here is if the blocks and their blockstates registered on client match exactly the ones on client which they should as logic is the same provided all mods are same versions

**Comment by Darkmega18** [comment]
only mods removed are some client sided ones which don't crash on load... :<

**Comment by MehVahdJukaar** [comment]
Are you sure all the mods are on the same exact version?

**Comment by Darkmega18** [comment]
yeah, otherwise it'd kick me out, right? I literally built the server out of the mods in the actual curseforge profile.

**Comment by MehVahdJukaar** [comment]
No that isn't the case. Only if registries differ, if blockstate map differs however this could happen. There's s config in the mod that allows performing some additional checks on the blockstate map so turn it on and check the logs but first do check all the mods are same version

**Comment by Darkmega18** [comment]
alright, will do. 
wait, is it the debug packet thing? or whos configs?

**Comment by Xelbayria** [comment]
is this issue resolved? if yes, then please close this issue.

**Comment by Darkmega18** [comment]
Unsure. it didn't come up again, but we didn't exactly test for it either.

**Comment by Xelbayria** [comment]
@Darkmega18 
Alright. I'll wait for MehVahdJukaar to answer my question. Someday, this needs to be tested so we can close this issue. 

meanwhile, we wait for answers. You should try the latest version of EveryCompat v2.5.10 and Moonlight Lib, too
to see if the issue still persists

**Comment by Darkmega18** [comment]
Once I'm done with some reworks and other things that're stopping me getting back to playing on server we'll see about testing the various wood stuff and chests and see if anything weird happens again then.
but I didn't know what the config vahd wanted me to turn on, since there wasn't an option that was exactly what he said in any of the files. :<

**Comment by Xelbayria** [comment]
> Once I'm done with some reworks and other things that're stopping me getting back to playing on server we'll see about testing the various wood stuff and chests and see if anything weird happens again then. but I didn't know what the config vahd wanted me to turn on, since there wasn't an option that was exactly what he said in any of the files. :<

what you said

> wait, is it the debug packet thing? or whos configs?

yes. via `everycomp-common.toml`. Set it to `true`, then check the log or you can share it here. That's what Vahd said. 

Ensure both your server and client are using the same version for mods and also the Forge version, too.

**Comment by Xelbayria** [comment]
Has the latest version resolved this problem?

**Comment by Darkmega18** [comment]
Wouldn't know unfortunately. haven't played in a long time. howabout if I come across it ever again in the eventuality I might play again on another version of MC, I'll let you know?
