### ISSUE TITLE
1.19.2-Crashing on Server Start when ``Handcrafted`` is present

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [MehVahdJukaar/WoodGood#266]
https://gist.github.com/P3rf3ctXZer0/226ebfaf85c2c4beaabe5978d3c6d638
Does not crash in SP
![Overwolf_jGO6ThtYvQ 1](https://github.com/MehVahdJukaar/WoodGood/assets/10351221/6ff73766-fbc3-4aec-93cf-b37855d06de7)

**Comment by Xelbayria** [comment]
@MehVahdJukaar 

🤦   that's why I disabled the module because it's not ready. Let me know if you want me to take care of this and push a quick fix with mod to CF

**Comment by Xelbayria** [comment]
@P3rf3ctXZer0 
downgrade to the previous version (v2.5.7) for now.

**Comment by MehVahdJukaar** [comment]
Didn't realize it was on

**Comment by P3rf3ctXZer0** [comment]
> @P3rf3ctXZer0 downgrade to the previous version (v2.5.7) for now.

Did it immediately when I crashed. I am a vetran pack maker. Thanks for the headsup though :)

**Comment by Xelbayria** [comment]
@P3rf3ctXZer0 
I've uploaded v2.5.10 with the disabled `Handcrafted Module`, you can use the latest version. you shouldn't have any problem. 
Once you confirm all is good, then please close this issue. Thanks!

**Comment by P3rf3ctXZer0** [comment]
It fixed it.
