### ISSUE TITLE
crashed on startup from 2.5.9 to 2.5.10

### ISSUE THREAD

**Issue by liangmoe** [MehVahdJukaar/WoodGood#268]
[crash-2023-10-06_10.45.26-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/12826473/crash-2023-10-06_10.45.26-client.txt)
[2023-10-06-5.log.gz](https://github.com/MehVahdJukaar/WoodGood/files/12826475/2023-10-06-5.log.gz)

**Comment by Xelbayria** [comment]
hmm let me investigate that right away

edit: ok i found the cause, i'll apply the fix right away.

**Comment by Xelbayria** [comment]
I've uploaded the hotfixes to the current file. please delete your file and re-download the new one with hotfixes. 
if it's fixed, then please close this issue, 

this way, i got your confirmation that it's fixed. thanks.

**Comment by liangmoe** [comment]
it fixed, thanks🙏🙏
