### ISSUE TITLE
[1.18.2] Macaw's Lamps 1.0.4 breaks things

### ISSUE THREAD

**Issue by brisingraerowing** [MehVahdJukaar/WoodGood#27]
[Crash Log](https://gist.github.com/brisingraerowing/1e2ac05946e743b0523a60e121e29652)

**Comment by MehVahdJukaar** [comment]
You likely need an older version of the mod

**Comment by brisingraerowing** [comment]
1.5.10 is still broken. [Crash Log](https://gist.github.com/brisingraerowing/eb662a21b9ce6025cbcd52bc177e02ed)
