### ISSUE TITLE
Whistlecane Hollowed Log (Quark + Gardens of the Dead)

### ISSUE THREAD

**Issue by SafeOfArsenal** [MehVahdJukaar/WoodGood#273]
![cat](https://github.com/MehVahdJukaar/WoodGood/assets/66153781/ee335534-33d8-487a-b202-e9c6a3762b44)

**Comment by Xelbayria** [comment]
Is this 1.20.1 issue? and can you please filling the following info: 

- Minecraft Version:
- Moonlight Version:
- Every Compat Version: 
- Which mods Every Compat have issues with: 
    - Quark \<version>
    - Gardens of the Dead \<version>
- loader: (forge or fabric)

**Comment by Xelbayria** [comment]
Will be closing this since no response for more than a week now.

**Comment by Xelbayria** [comment]
This is fixed in the newer version.
