### ISSUE TITLE
some holllow logs have broken textures

### ISSUE THREAD

**Issue by gitguette** [MehVahdJukaar/WoodGood#274]
they look fine when placed, but in the inventory and when held, it has the black and purple broken texture.

**Comment by Xelbayria** [comment]
please fill in the following information: 
EveryCompat (EC) Version: 
Which loaders: Forge OR Fabric
Minecraft Version: 
Mods EC have an issue with (which mod does hollow logs come from): 

Ensure you are using the latest version of EC which is relevant to the issue you reported.

**Comment by gitguette** [comment]
EC version 1.20-2.6.7
Forge 1.20.1 version 47.1.3
Hollow logs come from twilight forest

**Comment by GizmoTheMoonPig** [comment]
this has been fixed in d538b6f, which hasnt released quite yet
