### ISSUE TITLE
Twisted Wood :(

### ISSUE THREAD

**Issue by Derpgamer22** [MehVahdJukaar/WoodGood#277]
I cannot make twisted wood boards from woodworks with the twisted wood from architects palette.

**Comment by Xelbayria** [comment]
please fill in the following: 
Minecraft Version:
Loader: (Forge or Fabric)
EveryCompat (EC) Version: 
Which Mods does EC have an issue with:

**Comment by Xelbayria** [comment]
@Derpgamer22 
Haven't heard from you for a while. Does the issue still occur?

**Comment by Derpgamer22** [comment]
i am alive.. i forgot this was even here lol.. yes this is STILL happening

this is using 1.19.2 
forge
newest every compat
the mod it is having trouble with is architect's palette
abnormals woodworks


im pretty sure it is due to that mod having it's own boards :p

**Comment by Xelbayria** [comment]
Alright, i'll see if i can fix it. & Which mods are the wood variants from?

**Comment by Xelbayria** [comment]
Good news, it's fixed and will be in **v2.5.23**
