### ISSUE TITLE
[📦]: Cobblemon

### ISSUE THREAD

**Issue by Burgersim** [MehVahdJukaar/WoodGood#282]
### Curseforge

https://www.curseforge.com/minecraft/mc-mods/cobblemon

### FABRIC Version Availability

- [ ] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [ ] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

## Item:
- Apricoco Wood

### Optional Details

Hope this request was made in the right way ^^*

Basically there is Apricoco Wood in Cobblemon and it would be great if that was also added to the other mods (like Macaw's Stuff) if it is present. So you could craft Apricoco Doors, Cabinets and whatever ^^

**Comment by MehVahdJukaar** [comment]
Can you write out the id of both those wood type planks and log block? Also what sound do they make when you put it under anoteblock

**Comment by Burgersim** [comment]
It's
`cobblemon:apricorn_log -> Bass`
`cobblemon:apricorn_wood -> Bass`
`cobblemon:stripped_apricorn_log -> Bass`
`cobblemon:stripped_apricorn_wood -> Bass`
`cobblemon:apricorn_planks -> Harp`
`cobblemon:apricorn_stairs -> Harp`
`cobblemon:apricorn_slab -> Harp`
`cobblemon:apricorn_fence -> Harp`
`cobblemon:apricorn_fence_gate -> Harp`
`cobblemon:apricorn_door -> Harp`
`cobblemon:apricorn_trapdoor -> Harp`
`cobblemon:apricorn_button`
`cobblemon:apricorn_pressure_plate`
`cobblemon:apricorn_leaves -> Harp`

Hope that helps :3

**Comment by Xelbayria** [comment]
> Can you write out the id of both those wood type planks and log block? Also what sound do they make when you put it under anoteblock

do you want me to include that information? the ID of these blocks in the TEMPLATE?

**Comment by Xelbayria** [comment]
@Burgersim 
I've checked with Macaw's Bridge and there is no problem with Woods from Cobblemon

![cobblemon](https://github.com/MehVahdJukaar/WoodGood/assets/12866666/f40056e8-3fc7-4e65-80a4-761b724704d9)

So what do you want from Every Compat to support Cobblemon?

**Comment by Burgersim** [comment]
> @Burgersim I've checked with Macaw's Bridge and there is no problem with Woods from Cobblemon
> 
> ![cobblemon](https://user-images.githubusercontent.com/12866666/275346684-f40056e8-3fc7-4e65-80a4-761b724704d9.png)
> 
> So what do you want from Every Compat to support Cobblemon?

I have a lot of Macaws mods installed, but there is no support for Apricorn Wood. Which Version did you check on? I'm using the 1.20.1

**Comment by Xelbayria** [comment]
Oh, it was 1.19.2. Hmm, i'll need to check 1.20.1, too.

**Comment by Xelbayria** [comment]
Alright, it wasn't working in 1.20.1. Will investigate this.

**Comment by Xelbayria** [comment]
@Burgersim  Ok found the cause. It's not Every Comapt's issue. it's on Cobblemon's issue. this `cobblemon:apricorn_planks -> Harp`. It doesn't work 1.20.1.  I also checked 1.19.2, and the plank's sound is "Bass", This is why EC was able to combine planks from Cobblemon with Macaw's stuff. 

There is nothing we can do about this on our side.

**Comment by Burgersim** [comment]
What do the Planks and logs need to be to actually get recognized by this mod?

**Comment by MehVahdJukaar** [comment]
Name that follows convention, log planks with wood properties (aka bass noteblock sound/wood material )
