### ISSUE TITLE
[📦]: Beautify!

### ISSUE THREAD

**Issue by breadguyyy** [MehVahdJukaar/WoodGood#285]
### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/beautify-decorate

### Curseforge-Fabric (Optional)

https://www.curseforge.com/minecraft/mc-mods/beautify-refabricated)

### FABRIC Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

beautify

### Types

**Block:**
- blinds
- lattice
- picture frames (edited by Xelbayria)

**Comment by steve-the-player** [comment]
Also picture frames

**Comment by Xelbayria** [comment]
FYI, you can edit your original post. u see the 3 dots on the right of your comment. that's where you can click it to select the option to edit

**Comment by breadguyyy** [comment]
thats not me lol

**Comment by Suel-ki** [comment]
Already have [fabric](https://www.curseforge.com/minecraft/mc-mods/beautify-refabricated), support 1.18.2~1.21

**Comment by Xelbayria** [comment]
ADDED TO 
- v2.6.75 (1.20.1)
- v2.5.27 (1.19.2)
- v1.6.17 (1.18.2)
