### ISSUE TITLE
[🐞]: Twilight Forest hollow log item textures missing

### ISSUE THREAD

**Issue by breadguyyy** [MehVahdJukaar/WoodGood#287]
### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycompat-1.20-2.6.7

### Moonlight Lib Version

moonlight-1.20-2.8.50-forge

### Issue with mods

Twilight Forest (version 4.3.1860)

### Issue Detail

hollow log item texture missing, blocks place fine

### Optional Attachment

![image](https://github.com/MehVahdJukaar/WoodGood/assets/21149431/bf27bae0-b9f5-49bd-bfee-cbb3dc179a6c)

**Comment by Xelbayria** [comment]
> hollow log item texture missing, blocks place fine

the item is missing the texture, but when you placed these blocks, they have textures, correct?

**Comment by breadguyyy** [comment]
Yep, no issues in-world, only bugged in inventory

**Comment by breadguyyy** [comment]
I should have sent a log, sorry, I'll grab one tomorrow if you need it. Off the top of my head though, in terms of possible rendering breaking mods I am using embeddium, canary, starlight, and most of the other popular performance mods I can't think of all the names right now lol

**Comment by MehVahdJukaar** [comment]
Wasn't this fixed by a pr by tf Devs?

**Comment by breadguyyy** [comment]
oh yeah 2 weeks ago it looks like

**Comment by MehVahdJukaar** [comment]
should be fixed
