### ISSUE TITLE
[❔]: A possible generated resource problem

### ISSUE THREAD

**Issue by An-thracene** [MehVahdJukaar/WoodGood#290]
### Question

How does EC generate textures?

### Optional: Details

![2023-10-23_13 36 37](https://github.com/MehVahdJukaar/WoodGood/assets/96624949/0e154f99-099f-4c9c-876f-08a120b9bc5f)
The textures of cypress cabinet and rainbow eucalyptus cabinet look weird

**Comment by Daisiaa** [comment]
I have a similar question about some of the assets generated for terrestria and decorative blocks. Some look fine, but others don't look right. (redwood looks fine, rainbow eucalyptus and cypress look odd.)

![2023-10-27_16 21 11](https://github.com/MehVahdJukaar/WoodGood/assets/149205700/96b0fd88-f843-4c5c-93f6-c299e97fa3a7)
![2023-10-27_16 21 05](https://github.com/MehVahdJukaar/WoodGood/assets/149205700/02f0b8d5-1549-451a-aa7f-3ce6fa1f7873)

**Comment by Xelbayria** [comment]
What version is this related to?

**Comment by Daisiaa** [comment]
> What version is this related to?

I am on minecraft version 1.20.1, not sure about OP. I'm using the newest versions of all mods involved. 
(Fabric API, Terrestria, Decorative Blocks, Every Compat, Moonlight library.)

**Comment by An-thracene** [comment]
> What version is this related to?

the same with @Daisiaa 
but it can be confirmed that the problem also appears in 1.19.2.

**Comment by Xelbayria** [comment]
alright, I'll look at 1.19.2. I am currently working on 1.19.2 

@Daisiaa  which blocks? and which wood-type if it's just one wood? 

---

### Details: 

- Loaders: Fabric
- Mods: 
    - Terrestria (Wood type) 
    - Decorative Blocks (Furniture & Blocks)

**Comment by Daisiaa** [comment]
@Xelbayria 
**All decorative blocks** seem to have the issue. (Beams, palisades, supports, seats.) **And most wood types from terrestria**. The only wood type that seems correct is the Sakura wood, which is furthest to the right in this screenshot. 

Some look almost normal, but one or two of the variations may look odd. Like with the Hemlock and the Redwood the support and palisade look normal, but the seat and beam look slightly off. However most of the others seem to have the problem with all variants.

![decorativeblocks-terrestria](https://github.com/MehVahdJukaar/WoodGood/assets/149205700/e392c084-7382-4c8b-b1e0-268e1bb45593)

**Comment by Xelbayria** [comment]
Your question: 
> How does EC generate textures?

The system in Every Compat (EC) used 2 textures to combine them to get the texture; 
- Wood Type: Hemlock texture
- Beam Texture

You get Hemlock Beam block & texture. The system is not perfect.
