### ISSUE TITLE
[🐞]: EveryCompat startup crash with current 1.20.1 version of AnotherFurniture  forge 1.20.1 47.2.0 (and 2.1)

### ISSUE THREAD

**Issue by TheWitherlord** [MehVahdJukaar/WoodGood#291]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

EveryCompat 1.20-2.6.8

### Moonlight Lib Version

MoonlightLib 1.20-2.8.51

### Issue with mods

Versions of Mods:
EveryCompat 1.20-2.6.8
MoonlightLib 1.20-2.8.51
Another_Furniture-forge-1.20.1-3.0.0

The PlanterBox from AnotherFurniture isn't registering for EveryCompat.

https://gist.github.com/TheWitherlord/bdeae59a35527108fa5ab31c753d580a

### Issue Detail

The PlanterBox from AnotherFurniture isn't registering for EveryCompat.

This also happens with a few other mods like "The New Shutters" and some cases "Dramatic Doors".

AnotherFurniture just ported to 1.20.1 today

### To Produce

Download all the mods and their libraries

 Load the latest version of forge for 1.20.1

The game crashes

### Optional Attachment

https://gist.github.com/TheWitherlord/bdeae59a35527108fa5ab31c753d580a

**Comment by vinnyg0621** [comment]
thanks for reporting this, i'm having the same problem.

**Comment by Xelbayria** [comment]
Alright, I'm investigating this. I was going to upload a new version of 1.20.1. I'll add the fixes for this issue in the new version, too

EDIT: 
Alright, I've applied the fixes. 

EDIT 2: 
I could use your help to find the code responsible for adding items to Mod's tab. I cannot find it. 

All `.setTab()` in **AnotherFurniture Module** is disabled for now. This means **EveryComp**'s blocks via Another Furniture won't be added to the mod's tab.

**Comment by mateus3c** [comment]
im also having the same issue :c

**Comment by Xelbayria** [comment]
@mateus3c 
> im also having the same issue :c

no worries. I am going to upload the fixes in the next version along with other fixes like chipped's texturing. 

right now I'm trying to find out a way to fix the loot_table for Flower_box 😦 

the rest are working properly.

**Comment by TheWitherlord** [comment]
Not sure there is much you can do, but the load time for the mod after that new version is insane.

It gets stuck on the Mojang loading screen and never completes the task.

https://gist.github.com/TheWitherlord/cd691e33e3aa05220c4856c718a3d783

**Comment by Xelbayria** [comment]
this should be related to this issue. That's because the module for Another Furniture is outdated. There are some small changes to **Another Furniture**'s code. Other people's case is that Minecraft crashed and your is stuck in a loop.

No worries. 


**Everyone**, I am finished with this.
