### ISSUE TITLE
[🐞]: Chairs, Flower Box and Shutter from Another Furniture 3.0 do not work on 1.20.1 Fabric

### ISSUE THREAD

**Issue by MrGreenTea** [MehVahdJukaar/WoodGood#292]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Fabric

### EveryCompat Version

v1.20-2.6.9

### Moonlight Lib Version

v1.20-2.8.51

### Issue with mods

Another Furniture - v1.20.1 - 3.0.0

### Issue Detail

Three blocks/items from the new Another Furniture update 3.0 don't work correctly:

- Flower Box
- Shutter
- Chair

![image](https://github.com/MehVahdJukaar/WoodGood/assets/9407731/d14c517e-acda-45e4-80d5-934f45cccf86)

**Comment by MrGreenTea** [comment]
The wood in this detail are from promenade, but I also had this with Better End woods before removing it.

**Comment by Xelbayria** [comment]
Already been mentioned in another bug #291. 
I already fixed this. 
I'm working on fixing one last problem. and the next version of EC will be uploaded to CF

**Comment by MrGreenTea** [comment]
@Xelbayria I see, I saw that and thought it's something different as I don't experience any crash and the linked issue mentions Forge while I am on fabric. I'll close this then :)

**Comment by Xelbayria** [comment]
Alright. I am aware that Fabric has the same issue as Forge.   The fixes in Forge will also be applied to Fabric. You could comment, "You have the same issue with fabric"  on the existing issue.

All good.
