### ISSUE TITLE
[🐞]: HABITAT MOD & EC CAUSE CRASH

### ISSUE THREAD

**Issue by Camawama** [MehVahdJukaar/WoodGood#298]
### Before Continuing:

- [x] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycompat-1.20-2.6.12

### Moonlight Lib Version

moonlight-1.20-2.8.42

### Issue with mods

Habitat mod by SnappyDragon64
Version: 1.2.5

### Issue Detail

When I have both of these mods enabled on my modpack, I get a crash while starting.

### OPTIONAL: Latest.log | Crash-report Attachment

LATEST LOG: 
[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/13171969/latest.log)

CRASH REPORT:
[crash-2023-10-25_19.53.35-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/13171971/crash-2023-10-25_19.53.35-client.txt)

**Comment by Camawama** [comment]
https://github.com/SnappyDragon64/Habitat/issues/33

**Comment by Xelbayria** [comment]
is the wood types from **Habitat** mod? I've check the list of supported mod on EveryCompat's side. There is no habitat module. 
The "fairy ring woodset", it seems to be a set of foreign wood.

**Comment by Xelbayria** [comment]
@Camawama 

ok i noticed your **Moonlight** is `moonlight-1.20-2.8.42`. the latest is **51**, please update it and try again. 

EDIT:
i removed "marked" - `Always check you are using the latest version of the mods and its dependencies` in your first post, apparently you didn't check.

**Comment by Camawama** [comment]
I noticed shortly after that I was running the outdated moonlight. I'll give it a test real quick

**Comment by Camawama** [comment]
Yep, same problem on latest updates:

[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/13172382/latest.log)
[crash-2023-10-25_21.31.58-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/13172384/crash-2023-10-25_21.31.58-client.txt)

**Comment by Xelbayria** [comment]
hmm. I ran test on my sides using:
- Every Compat Latest Version
- Moonlight Latest Version
- Habitat Latest version

I had no issue. Something else is causing the crash. 

EDIT: 
I recommend you to do this: `If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit` so we can find the culprit

u just need to disable the one that adds wood types (no need to disable **Habitat** & **Every Compat** and other mods). I think another mod added the same type of wood as **Habitat** does

**Comment by Xelbayria** [comment]
@Camawama Hold on. Can you send me your `everycomp-common.toml` I want to take a look.

**Comment by Camawama** [comment]
Hmm, GitHub isn't letting me paste a TOML file here. I uploaded it to PasteBin

https://pastebin.com/tj6u3L1C

**Comment by Xelbayria** [comment]
> Hmm, GitHub isn't letting me paste a TOML file here. I uploaded it to PasteBin
> 
> https://pastebin.com/tj6u3L1C

Did you have the all of mods enabled when you made a copy of the `TOML file`?

**Comment by Camawama** [comment]
I'm going to test again but delete the everycomp-common file. There is a chance that it was carried over from the 1.18.2 version of my modpack.

**Comment by Xelbayria** [comment]
> It was carried over from the 1.18.2 version of my modpack.

Ah, the difference between 1.18.2 and 1.20.1 is huge in terms of code. Keep me posted.

**Comment by Camawama** [comment]
Alright so I just recently switched from Forge 47.2.1 to 47.1.3 so if anything looks different from last night, that may be why. Unfortunately, after deleting the TOML file, I am still getting the crash. I do have quite a few mods in my pack...running through all 260 might be a long process...I am considering just forgetting about Habitat even though I really liked some of it's content. Every Compat is more important to me.

LOGS: 
[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/13183829/latest.log)

CRASH REPORT: 
[crash-2023-10-26_19.31.41-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/13183828/crash-2023-10-26_19.31.41-client.txt)

EVERYCOMP-COMMON.TOML: https://pastebin.com/uiTEk9B7

**Comment by Xelbayria** [comment]
I think I may have found the cause. 

go to `everycomp-common.toml` and use "Find..." to search `cabinet`.  Pick one of two to be set to "false". and try again. 

There are 2 of them which look like this ` cabinet = true `

---
## EDIT:
I'll be running a test with a few mods that I think may be culprit to the issue above. 

---

## EDIT 2:
Finally, I found it. The cause.  "cabinet" come from **Farmer's Delight** & **MrCrayFish's Furniture**.  Both have the same ID name for cabinet.

the solution above is the best way to fix the problem.   You can set ` cabinet = true ` to `false` in either one of two: **Farmer's Delight** OR **MrCrayFish's Furniture (CFM)**

**Comment by Xelbayria** [comment]
@Camawama 
Alright, this issue is solved! You can play with **Habitat**. You only need to configure the setting in the TOML file to ensure the crash doesn't happen. Have fun! 

---
EDIT: 
Oh, right, I forgot to mention this. If you removed **habitat**, then it won't solve the problem. The same error will show up in the latest.log or crash-report. The block won't be from **habitat**. It would be from one of the mods that give foreign woods.

**Comment by Camawama** [comment]
I am getting very strange results. 

Tried disabling cabinet from MrCrayfish with Habitat Installed: CRASH
Tried disabling cabinet from Farmer's Delight with Habitat Installed: CRASH
Tried disabling cabinet from both MCF and Farmer's Delight with Habitat Installed: CRASH
Tried uninstalling HABITAT with an unmodified TOML: LOADED FINE

**Comment by Xelbayria** [comment]
weird.... :\ 

I also get crash with mods: **Habitat**, **Farmer's Delight**, **MrCrayfish's Furniture**. Let me modify the TOML file and see if I get the same crash. 

---
EDIT: 

Ok. We know which mods are the culprits.. but I thought the solution would fix the issue, apparently, it's not. that's making it more mystery

**Comment by Camawama** [comment]
This is why modding is so great. It is constantly making our brains work overtime 😂

**Comment by Xelbayria** [comment]
hahaha, yeah. 

if I removed **Farmer's Delight**, leaving only **MrCrayFish's Furniture (CFM)** & **Habitat**, i had no issue. (tested this)

if I removed **CFM**, only only **Farmer's Delight** & **Habitat**, I'm sure I won't have any issues (haven't tested this) 

that suggested the issue is the TOML file for **Every Compat** because the boolean for furniture is not working properly???

@MehVahdJukaar ☝️ <strike>  the `cabinet` in the TOML file should have disabled the EveryCompat from registering the same type of furniture with "cabinet" in the ID via ONE module?  </strike> NVM 👇

**Comment by Xelbayria** [comment]
This is clearly a conflict between 3 mods: 
- CFM (MrCrayfish's Furniture) has one furniture with ID: \<type>_cabinet
- Farmer's Delight has one furniture with ID: \<type>_cabinet
- habitat has foreign woods.
- Every Compat

ran another test using **Biomes O' Plenty** without **Habitat**. The result is no issues

EDIT: I ran another test without **Every Compat**, no issue with **CFM**, **Farmer's Delight** & **Habitat**

**Comment by Xelbayria** [comment]
does the latest version fixed this issue? I ran a test on my side and i had no crash with all 3 mods including **EveryComp**.

**Comment by Camawama** [comment]
I have had all three mods for a bit and haven't noticed any crashing. I can't remember if I changed config to fix it though.

**Comment by Xelbayria** [comment]
if you happened to remember, then please share. I am really curious on what's the cause of the crash. Have fun playing!

**Comment by Camawama** [comment]
My apologies, it had been a little while and I forgot 😅 

If I experience any problems, I'll make sure to come back. Thank you!
