### ISSUE TITLE
[🐞]: blockstate spam and missing textures in log from mulitiple mods  all with wierd wood types

### ISSUE THREAD

**Issue by marchiggs** [MehVahdJukaar/WoodGood#299]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2

### Loader

Fabric

### EveryCompat Version

everycomp-1.19.2-2.5.11-fabric

### Moonlight Lib Version

moonlight-1.19.2-2.2.45-fabric

### Issue with mods

Oh_The_Biomes_You'll_Go-fabric-1.19.2-2.0.1.4
minecells-1.5.3
paradise-lost-2.1.0-beta+1.19.2
better-end-2.1.6
better-nether-7.1.4
bewitchment-1.19-7
twilightforest-fabric-1.19.2-4.2.357
eden-ring-0.6.4
promenade-2.7.1
ecologics-fabric-1.19.2-2.1.11
charm-fabric-1.19.2-4.4.4
deeperdarker-fabric-1.19.2-1.2.1
architects-palette-fabric-3.0.0
cinderscapes-3.0.6
biomemakeover-FABRIC-1.19.2-1.6.4

planterbox,shutter ,table, chair, shelf drawer bench beam palisade support seat beehive bredgepier bridge

### Issue Detail

large amount of missing textures from various mods all with wierd wood type 

plus a massive blockstate spam from same 

also have modernfix-fabric-5.8.1+mc1.19.2 installed 

### OPTIONAL: Latest.log | Crash-report Attachment

[https://1drv.ms/u/s!AtoaO-i3gJuVqrwfk9OJr0zyb4KlCg?e=azv9PI](url)

latest log on one drive as too large to upload here.

**Comment by Xelbayria** [comment]
the link is not working. you can copy all of the logs from `latest.log` to a [website](https://text.is/). If you are familiar with Pastebin. that's what it is. 

once you get the working link. you can update the broken link above.

**Comment by marchiggs** [comment]
sure no problem  actually problem file is too large to paste 

https://1drv.ms/u/s!AtoaO-i3gJuVqrwfk9OJr0zyb4KlCg?e=9DBfBN

let me know if this works

**Comment by Xelbayria** [comment]
Got it. & wow. 189MB of the file.

**Comment by Xelbayria** [comment]
Ok. I took a look at the file and that's not right. I noticed that you did not do `Always check you are using the latest version of the mods and its dependencies`

because the version of Moonlight is now `2.2.46` & your current Moonlight is `2.2.45`. Try updating it and check if the same log shows up again in the `latest.log`

**Comment by Xelbayria** [comment]
I apologize for the inconvenience, I could use your help to investigate. So with the mods you listed above, 
1) you can disable them all except **Everycompat** & **Moonlight**. 
2) Try running Minecraft with the rest of the enabled mods 
3) check the `latest.log`

If no more errors regarding textures show up in the `latest.log`, then you can enable one or two of these disabled mods, until you see the errors in `latest.log`

There are too many factors to pin what's the problem. From the `latest.log`, I see there are other mods like **Macaw's fence** or others. They are missing textures that shouldn't happened. In normal cases, these blocks shouldn't be missing textures but something is causing the problem.

**Comment by marchiggs** [comment]
ok will do

**Comment by marchiggs** [comment]
https://1drv.ms/u/s!AtoaO-i3gJuVqrwg4E7rm1NWb-kbCA?e=L6R99y

with above moda and vinery ,meadow ,wounderous wilds also disabled

**Comment by marchiggs** [comment]
https://1drv.ms/u/s!AtoaO-i3gJuVqrwhFfMBOouti-0sCA?e=FcGma1

with just  architects-palette-fabric-3.0.0 added back in

**Comment by marchiggs** [comment]
im not a modder at all but i did try and work it out and it seemed to me to be something to do with dynamic textures???

**Comment by Xelbayria** [comment]
> https://1drv.ms/u/s!AtoaO-i3gJuVqrwg4E7rm1NWb-kbCA?e=L6R99y
> 
> with above moda and vinery ,meadow ,wounderous wilds also disabled

Ok, I've checked the `latest.log`, and there are still some errors regarding texture. Same with `architects-palette` enabled. 

Have you disabled 4 of these mods to check if there are any errors showing up in the log? 

EDIT: 
Is your modpack an official modpack or have you made your own modpack?

**Comment by marchiggs** [comment]
its medival minecraft

**Comment by marchiggs** [comment]
ok i think ive disabled everything that had a missing texture 

https://1drv.ms/u/s!AtoaO-i3gJuVqrwi1435ggCc3gMC3w?e=B6ahqG

**Comment by marchiggs** [comment]
and again with just architects-palette reenabled 

https://1drv.ms/u/s!AtoaO-i3gJuVqrwjvo7nTdmty8HzrA?e=GtOE4Z

**Comment by Xelbayria** [comment]
With disabled everything, The errors still show up in the latest.log. That goes for the **architects palette**, too. 

> its medival Minecraft

so it's an official modpack?

**Comment by marchiggs** [comment]
yes official

**Comment by Xelbayria** [comment]
Can I get the link, I can't find it.

**Comment by marchiggs** [comment]
https://www.curseforge.com/minecraft/modpacks/medieval-mc-fabric-mmc1/files/4722751

**Comment by Xelbayria** [comment]
Thanks, Do your friends have a similar issue with the modpack with similar errors in the `latest.log`?

**Comment by marchiggs** [comment]
playing single player

**Comment by Xelbayria** [comment]
alright, i'll run a test on the modpack.  to see if I get a similar problem.

**Comment by marchiggs** [comment]
i had updated a few mods but ive put the old ones back and still getting it

**Comment by Xelbayria** [comment]
> i had updated a few mods but ive put the old ones back and still getting it

Ok, I ran the modpack on my side. I had no issue. I recommend the following steps: 
1) back up your saved world.  if you don't know where it is. it's in `.minecraft/saves/<yourworld-name>` 
2) uninstall your modpack
3) Do a clean installation of the modpack. 

The devs of the modpack wouldn't release a broken modpack, They would ensure it's working without any problem. This is why I wanted to know if it's an official modpack or just self-made modpack. 

let me know if the clean installation of the modpack fixes the problem.

**Comment by marchiggs** [comment]
im actually going on holiday so i will  have to leave this till i get back  but i will let you know thanks for the help

**Comment by Xelbayria** [comment]
Alright, too bad, this GitHub doesn't have a feature where you can use `!remind` like from Reddit to remind you on the day you get back from holiday. enjoy your holiday!

**Comment by X-XLebyshek** [comment]
I have the same issue but on forge, it really increases the load time. Do you have any solutions?

**Comment by Xelbayria** [comment]
> I have the same issue but on forge, it really increases the load time. Do you have any solutions?

have you tried the clean installation of the mod pack?

**Comment by X-XLebyshek** [comment]
It's my own modpack

**Comment by Xelbayria** [comment]
Checking up on this issue. do u still have the problem or did you somehow get it all solved?

**Comment by X-XLebyshek** [comment]
I... deleted the mod after I had another issue with it, it didn't load and said something like java.lang.NoSuchFieldError: SPRUCE_BARREL_TRAPDOOR. I looked into the crash-report, it has something to do with every_compat.modules.forge.mcaw.MacawTrapdoorsModule

**Comment by Xelbayria** [comment]
oh,you need to update **Macaw's Trapdoor** to the latest version because it added a new trapdoor.  the older version of **Macaw's Trapdoor** is no longer supported by **Every Compat**

**Comment by Xelbayria** [comment]
@marchiggs 
Just checking to see if you made some progress on solving the problem.

**Comment by marchiggs** [comment]
hi the last update seems to have fixed it , there doesnt seem to be any  serious issues now  a couple of things that cant find textures but no biggie as they are not things im likely to need

**Comment by Xelbayria** [comment]
that's good. With that, i can close this issue. have fun!
