### ISSUE TITLE
[1.19 | Forge] Missing chest textures & glass is not see-through on doors

### ISSUE THREAD

**Issue by Illios42** [MehVahdJukaar/WoodGood#30]
I am using
- Macaw's doors (v1.0.6) & trapdoors (v.1.0.6)
- Biomes O' Plenty (v.17.0.0.143)
- Ecologics (v.2.1.6)
- Quark (v.366)
and the recommended build for forge 1.19, alongside some other unrelated mods. The mods work fine for the most part, but for some reason none of the compat doors/trapdoors from macaws have see-through glass elements. Furthermore, all chests and trapped chests appear to have missing textures. See below:
![2022-08-03_14 21 55](https://user-images.githubusercontent.com/101580687/182606947-4dc9607c-57b4-4e89-8055-1fa9390b2b2a.png)
![2022-08-03_14 22 24](https://user-images.githubusercontent.com/101580687/182607023-2b00b74c-a2a0-48ee-b8c6-09deff673d79.png)
![2022-08-03_14 22 30](https://user-images.githubusercontent.com/101580687/182607112-ecf32674-808a-4fbb-b1ba-a6138841f6ba.png)

**Comment by MehVahdJukaar** [comment]
Chest are fixed. I forgot the other one

**Comment by Illios42** [comment]
Actually, I retested with some of the newer Macaw versions that had changelog for "fixing solid rendered door/trapdoor textures" (which never happened for me in the base mod tho) and now it seems to be fixed in every compat too. I'd still check nontheless ofc but it might have been something from their side. And yes, saw the chest fix so thanks!
