### ISSUE TITLE
[❔]: 1.20-2.6.12 Fabric not on modrinth?

### ISSUE THREAD

**Issue by aninusmuffin** [MehVahdJukaar/WoodGood#306]
### Question

Every Compat 1.20-2.6.12 Forge is on modrinth, but not the fabric one. Is there any reason for this?

### Optional: Details

Curseforge has both versions.

This would be useful because in 1.20-2.6.9 the Another Furniture module has missing textures

**Comment by Xelbayria** [comment]
ah, I forgot about Modrinth. I'll upload them to Modrinth. I'll let you know when it's done.

**Comment by Xelbayria** [comment]
v2.6.13 is uploaded to Modrinth. Have fun!
