### ISSUE TITLE
[Fabric] Crash with Macaw's Lights

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [MehVahdJukaar/WoodGood#32]
**MC** 1.19.2
**Every Compat** 2.0.3
**Moonlight Lib** 2.0.15
**Macaw's Lights** 1.0.4

Same issue as https://github.com/MehVahdJukaar/WoodGood/issues/28 and https://github.com/MehVahdJukaar/WoodGood/issues/27, but on Fabric.

Logs: https://gist.github.com/Footage2-Amply-Pounce/68b1e29f39fb3f2d7766d7ca3a1e1bd9

**Comment by Gamemassa** [comment]
Oh, this is happening in Fabric too?

**Comment by MehVahdJukaar** [comment]
And I thought I fixed this

**Comment by MehVahdJukaar** [comment]
Foxed
