### ISSUE TITLE
[❔]: Item tags for new variants

### ISSUE THREAD

**Issue by MrGreenTea** [MehVahdJukaar/WoodGood#321]
### Question

Can Every Compat automatically add item tags for new variants?

### Optional: Details

Mods like another furniture and handcrafted have tags for the different types of furniture like `#handcrafted:wooden_benches`.

Sadly variants added by Every Compat do not get these built-in tags. Would it be possible to add that?

**Comment by MehVahdJukaar** [comment]
yes. If they are missing some please provide a list of all the missing tag per type so we can add more efficently

**Comment by MrGreenTea** [comment]
These are the ones I noticed are missing:
```
"#item:another_furniture:benches",
"#item:another_furniture:chairs",
"#item:another_furniture:curtains",
"#item:another_furniture:drawers",
"#item:another_furniture:flower_boxes",
"#item:another_furniture:lamps",
"#item:another_furniture:shelves",
"#item:another_furniture:shutters",
"#item:another_furniture:sofas",
"#item:another_furniture:stools",
"#item:another_furniture:tables",
"#item:another_furniture:tall_stools",
"#item:handcrafted:benches",
"#item:handcrafted:counter_materials",
"#item:handcrafted:metal_benches",
"#item:handcrafted:wooden_benches",
"#item:farmersdelight:cabinets",
```

**Comment by MehVahdJukaar** [comment]
thanks will add

**Comment by Xelbayria** [comment]
I've investigated this in both 1.19.2 and 1.20.1. The loader is Forge They are added to variant blocks without any problem. 
Is there anything I missed?

**Comment by Xelbayria** [comment]
is the issue resolved?

**Comment by Xelbayria** [comment]
Since there has been no replying for a while. I'll assume this is resolved. 
if it's not, then it can be reopened.
