### ISSUE TITLE
[🐞][1.19.2]: Crash on Load with newest version of EveryCompat

### ISSUE THREAD

**Issue by Reshy** [MehVahdJukaar/WoodGood#322]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2

### Loader

Forge

### EveryCompat Version

2.5.12

### Moonlight Lib Version

2.3.3

### Issue with mods

Unknown, the culprit mods aren't clear.  I'm still testing for the culprit, but the crash only happens on the most recent version, not the one from October 21th.

### Issue Detail

Unknown what's causing the crash, but it only occurs on the most recent version.

### OPTIONAL: Latest.log | Crash-report Attachment

Log:  https://pastebin.com/z2kFARbu
Crash:  https://pastebin.com/jBP0jZXk

**Comment by Xelbayria** [comment]
dang it. I know what's the problem. I'll fix this in next version.

**Comment by Xelbayria** [comment]
Uploaded to CF with the new version: 2.5.13. Let me know if the fix solved your problem. 

EDIT: 
It will take a while for the new version to be approved and become visible

**Comment by Xelbayria** [comment]
Have the v2.5.13 fixed the problem?
