### ISSUE TITLE
[🐞]: Parquets (Hearth & Home) don't have a preferred tool

### ISSUE THREAD

**Issue by Numerosityy** [MehVahdJukaar/WoodGood#325]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Fabric

### EveryCompat Version

1.20-2.6.15

### Moonlight Lib Version

1.20-2.8.56

### Issue with mods

Hearth & Home - any version (Fabric, at least)

### Issue Detail

Hearth and Home's Parquet Blocks take unusually long to break with an axe (I tested with a few different variants of the blocks, I believe it's consistent with every variant). This should not be the case.

I'm guessing the correct tool has not been defined for the block. It takes the same amount of time to break each block regardless of the tool being used.

The issue might exist with Sanded Wood as well, although I haven't tested it as thoroughly. Would look into it.

**Comment by Xelbayria** [comment]
Interesting. 

The Stone Axe has a shorter time than the Wooden Axe to break a block. Gold Axs have a shorter time than the Stone Axe. We know how it works, right? 
Is it the vanilla axe you are using for testing? Or it doesn't matter which axe is from any mods or vanilla?

**Comment by Numerosityy** [comment]
I don't believe it matters which kind of axe you're using. The reason I noticed the bug is it took way longer to break an Every Compat Parquet than a Hearth & Home Parquet with an axe. Also, it took the same time to break regardless of tool.

**Comment by Xelbayria** [comment]
alright, I'll check the code. 

EDIT:
OK, it looks like I need to investigate this.

**Comment by Numerosityy** [comment]
Also, the blocks don't spread fire

**Comment by Xelbayria** [comment]
I checked Forge and they are fine. but I didn't realize the Fabric side needs to be checked, too. it turned out they don't have the tag, `<tag:blocks:minecraft:mineable/axe>`

that's the cause. It's an easy fix.
