### ISSUE TITLE
[📦]: Decorative Blocks Fork

### ISSUE THREAD

**Issue by ambientNexus** [MehVahdJukaar/WoodGood#331]
### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/decorative-blocks-fork

### FABRIC Version Availability

- [ ] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [ ] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

decorative_blocks

### Types

All blocks contained within Decorative Blocks are included within the fork.

### Optional Details

As Decorative Blocks appears to no longer be receiving updates, this fork was made to fix bugs with the mod for the 1.19.2 version as well as port it upwards to 1.20.1.

**Comment by Xelbayria** [comment]
alright, I'll add this for 1.19.2 & 1.20.1

**Comment by ambientNexus** [comment]
Nevermind, Decorative Blocks was officially updated to 1.20, that fork is effectively irrelevant now.

**Comment by Xelbayria** [comment]
good to know! 👍 I was planning to work on that later this month.
