### ISSUE TITLE
[🐞]: Crashup on start; related to BetterEnd?

### ISSUE THREAD

**Issue by temyy** [MehVahdJukaar/WoodGood#335]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Fabric

### EveryCompat Version

everycomp-1.20-2.6.16-fabric

### Moonlight Lib Version

moonlight-1.20-2.8.60-fabric

### Issue with mods

better-end-4.0.10 (?)

crash error states "java.lang.IllegalArgumentException: value already present: Block{betterend:mossy_glowshroom_chair}"

### Issue Detail

game crashes while starting, crash log points to it being a duplicate value of a mossy glowshroom chair. everycomp has been tested with just betterend and theres no issue with them, and binary searching this amount of mods is my last resort :,D

i did see an issue where someone was experiencing a similar thing with betternether, and ive attached everycomp-common.json to the log files section

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/13325784/latest.log)
[crash-2023-11-11_16.30.01-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/13325785/crash-2023-11-11_16.30.01-client.txt)
[everycomp-common.json](https://github.com/MehVahdJukaar/WoodGood/files/13325789/everycomp-common.json)

### OPTIONAL: To Produce

1. load up around 350+ mods
2. boot the game
3. somethings broken (to no ones surprise)

**Comment by Xelbayria** [comment]
Take a look at #298. The error log is very similar. 

Go to the last post. It has a summary of the cause and no current solutions.

**Comment by temyy** [comment]
so i guess the solution is to just binary search :p unfortunate but ill get to that tmrw and ill report my findings, cheers

**Comment by Xelbayria** [comment]
> so i guess the solution is to just binary search :p unfortunate but ill get to that tmrw and ill report my findings, cheers

the fastest way to find out which mods is to look at `everycomp-common.toml`. The file has a list of wood-types and furniture-types

you can find which 2 mods have similar names for one wood-types or furniture-types. That should save you some time. This is the third issue. I used the method above. it doesn't take very long for me to figure out which 2 mods.

**Comment by temyy** [comment]
hi, got back to this and i think i found the incompatibilities

this only happens with either [Furnish](https://www.curseforge.com/minecraft/mc-mods/furnish) or [Another Furniture](https://www.curseforge.com/minecraft/mc-mods/another-furniture) run together with [BetterEnd](https://www.curseforge.com/minecraft/mc-mods/betterend) while Every Compat is enabled. running AF and Furnish together with Every Compat works, running BE alone with Every Compat works and running all 3 without Every Compat works

no idea why but id imagine its trying to make a duplicate of the BetterEnd chairs based on the errorlog? might be a similar issue than #327 considering both mods are from the same developer. hope this helps :)

**Comment by Xelbayria** [comment]
Yea. that's great information to have. However, it's hard to pinpoint the cause of the problem. Tbh, I have no clue where to look.

**Comment by MehVahdJukaar** [comment]
does this still happen with latest moonlight and EC version

**Comment by temyy** [comment]
it works!! im not sure what u did but thank u very much haha :)

**Comment by Xelbayria** [comment]
@MehVahdJukaar what was the cause of this problem?
