### ISSUE TITLE
[🐞]: Whistlecane (Gardens of the Dead) textures incorrectly mapped

### ISSUE THREAD

**Issue by ambientNexus** [MehVahdJukaar/WoodGood#337]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycompat-1.20-2.6.16

### Moonlight Lib Version

moonlight-1.20-2.8.60-forge

### Issue with mods

[Gardens of the Dead <v4.0.1>](https://www.curseforge.com/minecraft/mc-mods/gardens-of-the-dead)

### Issue Detail

Whistlecane acts the same way as Bamboo does, where it is crafted into a block of the material which acts as the log, which is then crafted into the planks.
![image](https://github.com/MehVahdJukaar/WoodGood/assets/53546918/258a9b76-00d6-44a7-83e6-0e9e232f0689)
However, Every Compat treats the whistlecane itself as the log and the block as the planks, causing texture errors due to incorrectly mapped textures.
![image](https://github.com/MehVahdJukaar/WoodGood/assets/53546918/77fdb8f8-38d3-4c45-9541-d8be4a5fcb69)
![2023-11-11_14 22 46](https://github.com/MehVahdJukaar/WoodGood/assets/53546918/23ce19d7-3fa0-4f54-835d-29aa0a18de91)

Having a handler for bamboo-like materials would solve this issue, and would allow for better compat for other mods down the line.

### OPTIONAL: To Produce

1) Start instance with Gardens of the Dead and Every Compat (and other supported furniture mod)
2) Grab a whistlecane furniture item from the creative menu
3) Model will be broken due to improper texture assignment

**Comment by Xelbayria** [comment]
This is why I suggested talking to the dev about the incorrect format of ID for _whistlepane_. it is explained in other issues. 

it seems that my solution will be put on hold until he fixes the ID. and the filename of these textures.

EDIT: 
to clarify the problem,  go to the `gardens_of_the_dead:textures/block/` and look for `whistlecane` files for textures. Take a good look at a good look at their filenames. that is the problem

**Comment by Xelbayria** [comment]
ok let me know if Dev made some changes to his mod, **Gardens of the dead**. I've applied the temporary fix to this for now.
