### ISSUE TITLE
Client Startup Crash

### ISSUE THREAD

**Issue by Blunder-G** [MehVahdJukaar/WoodGood#34]
Idk why it is crashing, yesterday was okey, but now it's broken
Here is the Crash Report:
[crash-2022-08-15_15.50.46-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/9337321/crash-2022-08-15_15.50.46-client.txt)

**Comment by brisingraerowing** [comment]
Some mod is accessing the Block Registry during mod construction. I'm betting Selene is doing so, though why it just broke is a mystery. Did you update any mods before the crash? And if you did, what were they?

**Comment by Blunder-G** [comment]
Solved, my config files was corrapted and i don't know why

**Comment by brisingraerowing** [comment]
I've noticed config corruption before for several mods. Might be a Forge issue, though random errors like this corruption are usually a pain to debug, because random.

**Comment by MehVahdJukaar** [comment]
Yes it's a known issue. Not from forge but from the config library they use
