### ISSUE TITLE
[🐞]: Quark Variant Chest anti-overlap prevents crafting Every Compat BYG chests

### ISSUE THREAD

**Issue by Magiwarriorx** [MehVahdJukaar/WoodGood#345]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2

### Loader

Forge

### EveryCompat Version

everycomp-1.19.2-2.5.13

### Moonlight Lib Version

moonlight-1.19.2-2.3.5-forge

### Issue with mods

- Oh The Biomes You'll Go 2.0.1.6
- Quark 3.4-418
- Woodworks 2.2.2

### Issue Detail

Quark anti-overlap disables Quark variant chests when Woodworks is detected, thus disabling Every Compat chest crafting. This behavior is sensible for vanilla woods; however, this means other modded woods not covered by Woodworks can only be used to make vanilla chests, even if Every Compat supports that wood, creating a gap in most wood sets vs Woodwork-ified vanilla sets.

Tested with BYG but theoretically applicable to all non-Abnormals woods.

(#140 references this, but seemingly only in the context of vanilla woods.)

![bmc1](https://github.com/MehVahdJukaar/WoodGood/assets/76668941/08116c8b-081d-47a4-b9ca-3c1b042660f6)
![bmc2](https://github.com/MehVahdJukaar/WoodGood/assets/76668941/89612362-2121-44ac-a315-42c73a8dcc5b)

**Comment by MehVahdJukaar** [comment]
This is intended behavior and not a bug. All EC blocks follow their original mod counterpart

**Comment by Magiwarriorx** [comment]
I understand now; I thought Every Compat supported Woodworks/supplied variant chests when Woodworks alone was loaded.

In that case, "enhancement" would have been the better tag. Every Compat already adds ladders and leaf piles when Woodworks is loaded, but for some reason does not supply chests.
