### ISSUE TITLE
[❔]: Abnormals delight and Wood good

### ISSUE THREAD

**Issue by QwertyQwerty228** [MehVahdJukaar/WoodGood#346]
### Question

If I download Abnormals delight and Wood good, it crashes ?

### Optional: Details

Abnormals Delight adds Drawers (from Farmers Delight) for own mods such Autumnity, Environmetal
Wood Good also adds Drawers (from Farmers Delight) for  Autumnity, Environmetal (and other mods too)

If I download Abnormals delight and Wood good, it crashes ?

**Comment by MehVahdJukaar** [comment]
send latest.log

**Comment by QwertyQwerty228** [comment]
I haven't played this mod. I'm just curious🧐🧐🧐

**Comment by Xelbayria** [comment]
He's right, you need to send `latest.log` so we can find out what's going on and be able to answer your question.

**Comment by QwertyQwerty228** [comment]
Ok

**Comment by QwertyQwerty228** [comment]
Good luck to you and this project

**Comment by QwertyQwerty228** [comment]
Log:
[latest.zip](https://github.com/MehVahdJukaar/WoodGood/files/13391481/latest.zip)

**Comment by QwertyQwerty228** [comment]
> Log: [latest.zip](https://github.com/MehVahdJukaar/WoodGood/files/13391481/latest.zip)

Extract this archive

**Comment by QwertyQwerty228** [comment]
I didn't see anything other than a strange bug.

**Comment by QwertyQwerty228** [comment]
I allocated 2gb ram

**Comment by QwertyQwerty228** [comment]
> I didn't see anything other than a strange bug.

Sorry, it's not Wood Good

**Comment by Xelbayria** [comment]
Ok. so if you are adding multiple mods & resource packs, I recommend at least 4GB minimum.  

if it's modpack, it has to be at least 6GB minimum (depends on which modpack you want to play). 

Some modpack have details for how much allocation of RAM minimum required

**Comment by QwertyQwerty228** [comment]
Ok Thanks
