### ISSUE TITLE
[🗃]: Cobblemon wood types missing in 1.20.1 (previous MC Version was supported. 1.19.2)

### ISSUE THREAD

**Issue by uhed01** [MehVahdJukaar/WoodGood#352]
### Version

v1.4

### Curseforge

https://www.curseforge.com/minecraft/mc-mods/cobblemon

### Details

All of the Apricorn related block types; Planks, slabs, logs, stripped logs

**Comment by Xelbayria** [comment]
Can you check to see if Apricorn has the "Bass" sound? It's a way for EveryCompat to detect wood types and add them. 

If the wood type does not have the "bass" sound, then it won't be included. I've seen this in other issues. The only solution for the dev of the mod is to correct the sound of the wood type.

**Comment by Xelbayria** [comment]
have you checked?

**Comment by BlueIsADude** [comment]
I have checked just now. All Apricorn blocks have the bass sound EXCEPT for the Apricorn planks. Those make the basic harp sound.

**Comment by BlueIsADude** [comment]
Update: The cobblemon devs have fixed this, but it'll be part of their next major update. it might be a while until then.

**Comment by Xelbayria** [comment]
👍 that's great.
