### ISSUE TITLE
[📦]: Stylish Stiles

### ISSUE THREAD

**Issue by vburnin8tor** [MehVahdJukaar/WoodGood#353]
### Curseforge (Normal)

https://modrinth.com/mod/stylish-stiles/

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [ ] 1.19.2
- [X] 1.20.1

### MODID

stylish-stiles

### Types

**Block:**
- ex: Stile
- ex: wood_type Stile

**Comment by Xelbayria** [comment]
oh, nice! It looks simple. I could add this to 1.18.2 and 1.20.1.

**Comment by Xelbayria** [comment]
## TASK 

- [x] 1.18.2-Forge
- [ ] 1.20.1-Forge
- [ ] 1.20.1-Fabric

**Comment by pantsguyapp** [comment]
where is the 1.20.1 and above??

**Comment by Xelbayria** [comment]
Stylish Stiles are supported in 1.18.2 and 1.20.1. 

EDIT: 
I just checked. I forgot to add it. it'll be in **v2.6.75**

**Comment by pantsguyapp** [comment]
For Forge or Fabric? I am asking for the Forge version.

**Comment by Xelbayria** [comment]
It's supported in both FABRIC and FORGE. Don't worry about it. I really thought I added it.

**Comment by pantsguyapp** [comment]
Its just that the list on the cf page doesmt have the mod included in the forge section, could you please update the list on release of the update.

**Comment by Xelbayria** [comment]
The cf page is correct. but a bit outdated for other modules that were recently added. 

Stylish Stiles have FABRIC & FORGE if you take a look at modrinth page. FYI, I'm the one who added a support for Stylish Stiles. Ran FORGE and FABRIC with the said mod. 

1.18.2 only have FORGE
1.20.1 have FORGE & FABRIC.
