### ISSUE TITLE
[🐞]: Every Bee hive from this mod isn't operational

### ISSUE THREAD

**Issue by Unshoshable** [MehVahdJukaar/WoodGood#354]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2

### Loader

Fabric

### EveryCompat Version

1.19.2-2.5.14

### Moonlight Lib Version

1.19.2-2.3.5

### Issue with mods

Any of the corresponding type

### Issue Detail

Bee hives this mod creates are always being ignored by bees. No matter how hard player is to try, bees will never get into one of them. However, in identical situation, they will choose bee hives from other mods / default minecraft.

### OPTIONAL: Latest.log | Crash-report Attachment

Doesn't cause a crash

### OPTIONAL: To Produce

For example:
1. Install every compat
2. Install Friends & Foes (adds new bee hives)
3. Install Terrestria (adds new wood types)
4. Place a bee hive, created by every compat
5. Bug occurs

**Comment by Xelbayria** [comment]
I'll look into it. 

EDIT:
I think I know what's the cause.

**Comment by Xelbayria** [comment]
Update: 

The fix is applied to 1.20.1-Fabric (similar issue). However the fix is not working in 1.19.2, it will take a while.

**Comment by Xelbayria** [comment]
Update 2: 

Fixed.
