### ISSUE TITLE
[❔]: Cannot make planks using logs with mods

### ISSUE THREAD

**Issue by seeingjacquelyn** [MehVahdJukaar/WoodGood#357]
### Question

I am having problems with creating planks using logs

### Optional: Details

For context, I have Builders  Crafts and Additions, Biomes O' Plenty, and Enlightened installed. Builders Additions adds a panel recipe that takes 3 planks in the crafting grid in a vertical line to create the panel which is essentially a vertical slab. My issue is that the recipe for the mod planks from both Biomes O' Plenty and Enlightened are requiring me to use panels to create them instead of logs. Which means that crafting planks is impossible because I need planks to craft the panel. And there is no option to switch recipes, and when I try to create planks with the logs there is no planks created. Any help would be appreciated, thank you in advance!

Forge: 47.2.1
MC version: 1.20.1
Every Compat version: 2.6.18
Biomes O' Plenty version: 18.0.0.598
Enlightened version: 5.0.14
Builders Crafts and Additions version: 20230928a

**Comment by Xelbayria** [comment]
I'll take a look at this.

**Comment by Xelbayria** [comment]
the way recipes work is like this: 

1. Log -> Planks -> Panels (Vertical Slab) 
2. 2 Panels -> Planks

All are done using **Crafting Table**. The planks from **Enlightend** are from Stem (not a log) 

Is there more to this?

**Comment by Xelbayria** [comment]
No reply going on for more than a month. I'll be closing this.

**Comment by zeven1707** [comment]
Same problem here, same version. How come the popular mod Biomes O' Plenty is not listed as a supported mod for this? Frustrating issue this, yesterday it worked fine with creating planks out of Biomes O' Plenty logs, but today I can't.
The only relevant log message on my server was this:
`Tried to load unrecognized recipe: everycomp:bca/biomesoplenty/fir_vertical_slab removed now.`

**Comment by MehVahdJukaar** [comment]
Because only relevant mods are the one that add furniture blocks . Bop does not. What you are having is an issue likely from another mod

**Comment by Xelbayria** [comment]
☝️ hmm. another thing to keep in mind.   The reason why **BOP** is not on the list as a supported is due to EveryCompat's ability to detect woods from mods like **BOP**, **The Twilight Forest**. which is unnecessary for us to list them. Too many to list.
