### ISSUE TITLE
Issue with reborn core.

### ISSUE THREAD

**Issue by Vixeliz** [MehVahdJukaar/WoodGood#36]
Hello again! Might remember me from moonlight lib. I have found a new apparent issue. When using every compat and tech reborn(plus a good amount of other mods) there is an issue where if everycompat is present any players joining a server on lan(might also happen on dedicated servers) will get kicked due to a string taking too long. This is happening with RebornCore recipe system? Ill link to that issue for relevant info. Im not sure whether this is every compat or reborn cores fault hence the two issues. 

https://github.com/TechReborn/TechReborn/issues/3024

**Comment by MehVahdJukaar** [comment]
From what i can understand it could be something with their recipe system. I have no clue where such a long string would come from but to debug this it's probably easier for them to do as it happens in their code if it is indeed something with their recipe system

**Comment by MehVahdJukaar** [comment]
Yeah I usually leave all unresolved issues open

**Comment by Xelbayria** [comment]
@Vixeliz If you wish to close this issue or leave it open. Up to you. It would be good to share the info you've learned so far.

**Comment by Xelbayria** [comment]
any updates on this?
