### ISSUE TITLE
[📦]: Create: Steam and Rails

### ISSUE THREAD

**Issue by CamKablam** [MehVahdJukaar/WoodGood#363]
### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails

### FABRIC Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

railways

### Types

**Block:**
- Train Tracks in All Wood Types
- Small and Wide Tracks in All Wood Types

### Optional Details

Compatibility for Twilight Forest, Hexcasting, BYG, Blue Skies and BOP appears to already be implemented, at least in the latest 1.19.2 version in the recipes folder

**Comment by Xelbayria** [comment]
This is abandoned. Please see [Kanban Board](https://github.com/users/MehVahdJukaar/projects/1#)

Scroll to the further right: "Abandoned". You'll see 4 abandoned mods. Click the title and it will reveal some details including why. 

EDIT: 
One more thing. You or Someone can create textures for **Create: Steam N' Rails** (C:SR) with Twilight Forest. It's not that hard. I've done it for **TerraFirmaCraft**. If you want more details, then you can go to **C:SR**'s discord

**Comment by CamKablam** [comment]
sorry

**Comment by Xelbayria** [comment]
> sorry

No worries. it's common for a duplicated issue or a duplicated request to show. No need to apologize.
