### ISSUE TITLE
[📦]: VillagersPlus

### ISSUE THREAD

**Issue by steve-the-player** [MehVahdJukaar/WoodGood#367]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/villagersplus-forge

### Curseforge-Fabric (Optional)

https://www.curseforge.com/minecraft/mc-mods/villagersplus-fabric

### FABRIC Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

villagersplus

### Types

**Block:**
- Flower tub (aka horticulturist table/workstation), vanilla wood variants

**Item:**
- Flower tub, vanilla wood variants

**Comment by Xelbayria** [comment]
ADDED: 
- v2.6.71 (1.20.1)
- v2.5.29 (1.19.2)
- v1.6.17 (1.18.2)
