### ISSUE TITLE
[📦]: Liroth Revamped

### ISSUE THREAD

**Issue by steve-the-player** [MehVahdJukaar/WoodGood#369]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/liroth-revamped-forge

### Curseforge-Fabric (Optional)

https://www.curseforge.com/minecraft/mc-mods/liroth-revamped-fabric

### FABRIC Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

liroth

### Types

**Block:**
Lots of new wood types and vanilla-craftable wooden variants (eg doors, trapdoors, planks, etc). Also includes crafting tables and chests. New wood types: 
- Damnation 
- Petrified Damnation 
- Japz 
- Koolaw 
- Liroth 
- Spiced 
- Tallpier

**Item:**
- just the corresponding items for each block type, and also boats/chest boats

### Optional Details

Petrified Damnation wood behaves like both wood and stone, able to be crafted into both bricks and walls, but also fences and trapdoors.

**Comment by Xelbayria** [comment]
I've checked out the mod and it has no unique furniture/block. Just vanilla blocks (Door, trapdoor, so on).

Let me know if Every Compat can't detect the woodTypes from the mod. it should have "bass" sound. Some Devs forgot to add "bass" sound to woodType when they updated their mod to 1.20.1
