### ISSUE TITLE
Missing texture for Twigs table and Architects Palette boards

### ISSUE THREAD

**Issue by Rodas011** [MehVahdJukaar/WoodGood#37]
Well, first BetterEnd textures are entirely missing, but as I have read in older issues I understood it is because of BetterEnd.

But, as you can see in the image Twigs table and Architects Palette boards don't work at all (sometimes they work for 3 or 4 types of woods randomly but in this case, they didn't work at all). Railings work just fine and even replace missing textures for BetterEnd with default oak texture, which is incredibly nice!

Ironically, Supplementaries manage to make all the woods work (except for BetterEnd of course).

Apart from fixing tables and boards, it will be nice if you could make that every missing texture uses default oak as in railings, just in case of errors like this or BetterEnd's, it will look way better that way.

Also is there a way to disable specific wood "attempts" from Supplementary with a config file as it is in Every Compat? Or entirely disabling that function from Supplementaries and making signs work with Every Compat. As magenta squares from failed "attempts" are not that pleasing to the eyes.

![image](https://user-images.githubusercontent.com/68823524/186324900-1f0b3386-a2d7-493e-8d44-94a86228149d.png)

[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/9412621/latest.log)

Forgot to mention I also test the newer version of Every Compat (everycomp-1.19.2-2.0.4-fabric.jar), as in the error I'm using "everycomp-1.19.1-2.0.3-FABRIC.jar", but the error is still the same.

Thank you for reading.

**Comment by Xelbayria** [comment]
is this issue solved? If yes, then please close this

**Comment by Xelbayria** [comment]
I haven't heard from you for a while. will be closing this.
