### ISSUE TITLE
[🗃]: Farmer's Delight - Cutting Board

### ISSUE THREAD

**Issue by steve-the-player** [MehVahdJukaar/WoodGood#371]
### Version

0.0.0

### Curseforge

https://www.curseforge.com/minecraft/mc-mods/farmers-delight

### Details

Farmer's Delight cutting boards are all the same default texture, no matter what wood variant they're crafted from. It looks closest to spruce planks.

**Comment by Xelbayria** [comment]
it looks like this is an issue. I need to check **Farmers Delight**, I have a good idea of what's going on.  Which Minecraft Version? 

EDIT: 
nvm. I checked and the _cutting board_ is just a "wooden cutting board".  You can think of it as a _universal_ cutting board.  if **Farmer's Delight** had 9 _Cutting Boards_ of different Wood Types, then it would be included in **Every Compat (EC)**. 

"universal" blocks/items are meant to be crafted with any wood type. This is why it wasn't included in **EC**

**Comment by MehVahdJukaar** [comment]
Yes FD has no cutting board variants
