### ISSUE TITLE
[🐞]: Cannot open the game due to this mod (1.18.2)

### ISSUE THREAD

**Issue by Stupidplays** [MehVahdJukaar/WoodGood#373]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.18.2

### Loader

Forge

### EveryCompat Version

everycomp-1.18.2-1.6.6.jar

### Moonlight Lib Version

selene-1.18.2-1.17.14.jar

### Issue with mods

Cannot open the game due to this mod

### Issue Detail

When I open the game it said:
Every Compat (everycomp) encountered an error during the common setup event phase java lang NoSuchMethodError com.mcwwindows.kikoz.objects Blinds: method void <init>()' not found

Probably conflicted with macaw windows.

### OPTIONAL: Latest.log | Crash-report Attachment

[crash-2023-12-21_14.04.40-fml.txt](https://github.com/MehVahdJukaar/WoodGood/files/13736875/crash-2023-12-21_14.04.40-fml.txt)

**Comment by Xelbayria** [comment]
You need to downgrade Macaw's windows to the previous version. I already fixed this in the next version.

**Comment by Xelbayria** [comment]
Ok next version has been uploaded to CurseForge / Modrinth.  it will take a while for the file to get approved on Curseforge.
