### ISSUE TITLE
[🐞]: Quark compat chests are invisible in inventory and have no textures

### ISSUE THREAD

**Issue by dabomb6405** [MehVahdJukaar/WoodGood#377]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

2.6.19

### Moonlight Lib Version

2.8.72

### Issue with mods

Quark
Any mod that adds new woods

### Issue Detail

In the inventory, all Quark chests created by Every Compat are invisible, and when placed in the world they have no texture.

**Comment by Xelbayria** [comment]
if you are using beta version of Quark. We are aware of this. The Module of Quark will be updated to support Quark's new version in the future.

**Comment by MehVahdJukaar** [comment]
fixed
