### ISSUE TITLE
[🐞]: Quark compat blocks have no recipes

### ISSUE THREAD

**Issue by dabomb6405** [MehVahdJukaar/WoodGood#378]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

2.6.19

### Moonlight Lib Version

2.8.72

### Issue with mods

Quark

### Issue Detail

None of the new quark compat blocks created by the mod have any crafting recipes.

**Comment by Xelbayria** [comment]
Which Quark version?  If you are using the beta version of Quark. We are aware of this. There will be an update to the Module to support Quark's new version in the future.

**Comment by Xelbayria** [comment]
Quark is out of Beta and the recipes are working as it is. closing this now
