### ISSUE TITLE
1.19.2 Forge - No compat blocks are generated.

### ISSUE THREAD

**Issue by cech12** [MehVahdJukaar/WoodGood#38]
Today I have tested your mod and I cannot recognize generated compat blocks.

Environment:
- Minecraft 1.19.2
- Forge: 43.1.2
- Launcher: MultiMC

Mods:
- everycomp-1.19.2-2.0.4.jar
- FarmersDelight-1.19-1.1.2.jar
- ecologics-forge-1.19.2-2.1.9.jar
- jei-1.19.2-forge-11.2.0.256.jar

I expected to see a cabinet (Farmers Delight) of the coconut wood type (Ecologics) generated by this mod (Every Compat). But it does not show up in JEI. 
Additionally, I tested Quark-3.2-358.jar and expected a post of the same wood type. But it wasn't generated either.

I hope you can help me. :)

**Comment by MehVahdJukaar** [comment]
Hm so the creative tab of the mod is emoty? Can to send me your logs?

**Comment by cech12** [comment]
Here is the log: https://paste.ee/p/pK8YL
I started the game with the described mods (I sent you a wrong version of Quark: Quark-3.3-369).

And if I search for cabinets, I don't get a coconut version of it.
![grafik](https://user-images.githubusercontent.com/16005054/186929666-ede19211-e00a-4042-9f95-de3d1456e57d.png)

The same of the Quark posts:
![grafik](https://user-images.githubusercontent.com/16005054/186931531-74effaf2-b1a2-4516-945a-4d9d15136cba.png)

**Comment by MehVahdJukaar** [comment]
That is very weird, everycompat does not even log anything in the log. Can you see it's creative tab?

**Comment by cech12** [comment]
There is no creative tab of Every Compat

**Comment by MehVahdJukaar** [comment]
Then something is definitely wrong because eveeycompat always has one even if it has no items. Try to download again or see of it shows up in mod menu

**Comment by cech12** [comment]
Really weird. I tested it in CurseForge launcher with the same mods (newly downloaded) and it works like a charm. Then I copied the mod jars to MultiMC and then it works also there. Maybe something with the downloaded jar was not right.

Thanks for your time!
