### ISSUE TITLE
[🗃]: Better Rats Support 1.20.1

### ISSUE THREAD

**Issue by mxnmnm** [MehVahdJukaar/WoodGood#380]
### Version

8.1.2

### Curseforge

https://www.curseforge.com/minecraft/mc-mods/rats

### Details

This is more of a quality of life enhancement rather than a missing texture. The main issue is that pirat logs/planks are transparent but items from this mod are not transparent. I think it would be a really nice touch to add transparency and help things to feel more cohesive/consistent. Not sure if doing some specific things like this is an option or not but figured I'd suggest it.

**Comment by Xelbayria** [comment]
<strike>Please use "**Suggest a mod**", not Mod Enhancement, I am sure **Every Compat** doesn't have support for that mod. There are a few missing information I need to know. Please fill in the following: 

---

#### Version & Loader:
- [ ] 1.18.2-Forge
- [ ] 1.18.2-Fabric
- [ ] 1.19.2-Forge
- [ ] 1.19.2-Fabric
- [ ] 1.20.1-Forge
- [ ] 1.20.1-Fabric
---
#### id of Items / Block: 
Block: 
- tables? 
- chairs? 

Item (Can be used for crafting and must be wooden type just like blocks):
- ????
</strike>
---

EDIT: 
Your Details are not enough. I have a somewhat guess of what you are talking about. Can you clarify the details?

**Comment by mxnmnm** [comment]
Forge 1.20.1 and basically everything that isn't glass (with pirat window panes being the exception) isn't transparent. Funnily enough pirat glass had the proper transparency. Here's a comparison with the sides having proper transparency (aka the base blocks) and the center being the blocks that aren't functioning as they should.
![2024-01-03_03 40 19](https://github.com/MehVahdJukaar/WoodGood/assets/8508976/a877ebc0-a57a-4084-bc54-8b57b0e2e2d0)

**Comment by Xelbayria** [comment]
Can I get a list of mods, so I can take a look:
- Rats
- ?? 

*pirat logs/planks* are from **Rats mod**, correct

**Comment by mxnmnm** [comment]
yes the planks/logs are from rats (you need to have ratlantis enabled in the configs). I can give a modlist later but at the very least Ik the issue happens with rats and chipped alone. Hopefully fixing it for one mod can fix the others. Considering how accurate most of the glass blocks worked, giving all of the things made from this material that kind of transparency should be good.

**Comment by Xelbayria** [comment]
Have the latest version resolved this issue? 

EDIT:
I've gained enough experiences in programming. so I have a good idea of what you are talking about. You must meant the glass & glass_pane blocks generated by EveryCompat doesn't have the transparent part for the "glass" part. IIRC, it should be black. 

I've seen the problem once before and fixed it in the past.

**Comment by mxnmnm** [comment]
This is still an issue. What I'm saying is that ALL blocks made with pirat logs/planks should be transparent to match the behavior in from the mod. It would likely need to be a special exception made for these logs/planks

**Comment by mxnmnm** [comment]
A good example would be to compare the hollow pirat logs when you have quark/the twilight forest vs the normal logs

**Comment by Xelbayria** [comment]
alright, I'll investigate with
- EveryCompat + Moonlight Lib
- Better Rats
- Quark

Thanks for replying with info

**Comment by mxnmnm** [comment]
Just to make sure you're testing with the rats mod and making sure ratlantis is enabled in the configs

**Comment by Xelbayria** [comment]
hmm. Rats is quite interesting mod. That's the first time i've seen a half-transparent log/planks

EDIT: 
I can't think of a way to have EveryCompat's generated blocks to have the same level of transparent like _pirat_. 

I'll speak to MehVahdJukaar regarding ☝🏻 

I have an idea, going to run a test.

**Comment by Xelbayria** [comment]
My idea don't work. Well that somewhat confirmed my guess. 

EveryCompat should be using RGB of Texture to re-paint the texture of furniture blocks from other mods. (EDIT): Oh right, the texture of furniture blocks doesn't have ALPHA and most Wood mods like Biomes O' Plenty don't use ALPHA either.

the texture of _pirat_ have RGBA (Red, Green, Blue, Alpha). so you set it to say 50% Alpha, so it would be half-transparent. EveryCompat wasn't set up to use RGBA. Regarding this, i am waiting to hear from MehVahdJukaar.

**Comment by Xelbayria** [comment]
Good news: 
My idea that don't work was the correct approach but it only applied to one block. so I had no idea how to apply it to all of blocks from EveryCompat. 

I've spoke to MehVahdJukaar and there is a way to get it done. 

---

## Enhanced in v2.6.89
