### ISSUE TITLE
[📦]: Compatibility with Good Ending

### ISSUE THREAD

**Issue by BradClc** [MehVahdJukaar/WoodGood#388]
### Before Continuing:

- [x] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/good-ending

### FABRIC Version Availability

- [ ] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [ ] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

goodending

### Types

**Block:**
wood_type:
cypress 
muddy_oak

leave_type in config has already done

**Comment by MehVahdJukaar** [comment]
If wood types (planks logs and such) are not detected its 90% their faults. Usually when mods are not updated properly from 1.19 to 1.20 and they dont change values as they should. I'm talking about setting the wood noteblock sound to Bass like all woods have. Test that, i bet its wrong

**Comment by BradClc** [comment]
Yes, you are right. The two types of wood noteblock sound to harp.
