### ISSUE TITLE
[❔]: Resource packs

### ISSUE THREAD

**Issue by steve-the-player** [MehVahdJukaar/WoodGood#389]
### Question

n/a

### Optional: Details

When using a resource pack, for example a version of the [Faithful series](https://www.curseforge.com/minecraft/texture-packs/faithful-64x), (which has been updated to include modded items and wood of course), does EC make all the generated textures also match the pack?

**Comment by MehVahdJukaar** [comment]
yes, try and see

**Comment by Xelbayria** [comment]
Seeing the question have been answered. I'll be closing this.
