### ISSUE TITLE
Permission to redistibute as part of a non-CurseForge modpack

### ISSUE THREAD

**Issue by copygirl** [MehVahdJukaar/WoodGood#39]
I've been working on a private modpack for friends for a while now. Since I now feel like it's polished enough, and I've been sharing gameplay of the pack, I was wanting to release it publicly on [Modrinth](modrinth.com/) for others to enjoy as well. Unfortunately, Every Compat (and its library mod Selene / Moonlight Lib) neither has a permissive license, nor does the CurseForge page mention a modpack policy, so I'm here to ask for explicit permission to redistribute these mods as part of my modpack. Credit would be given in the form of an extensive mod list that links to each mod's project page.

It would be nice if other modpack authors were given blanket permission to do the same.

Thank you for your work! :green_heart:

**Comment by MehVahdJukaar** [comment]
well i totally forgot to reply apologies. sure but mod is mon mortinth too now
