### ISSUE TITLE
[📦]: Round Trees (resourcepack and companion fabric mod)

### ISSUE THREAD

**Issue by steve-the-player** [MehVahdJukaar/WoodGood#391]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/texture-packs/round-trees-mc-vanilla-1-8-1-13

### Curseforge-Fabric (Optional)

https://github.com/TeamMidnightDust/RoundTrees/releases/tag/v1.0.0

### FABRIC Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20.1

### MODID

roundtrees

### Types

Resource pack: 
- Logs (visual change)

Mod: 
- Logs (hitbox change)
- Signs (visual+hitbox change)

### Optional Details

Resource pack works with Forge, Fabric, and vanilla-ish (needs something like optifine for custom models), but mod is Fabric-only. Wasn't sure how to tag this one.

**Comment by Xelbayria** [comment]
that's fine, with your details explaining why it's like that. Alright. so I see it's a resource pack. From what I understand about **Every Compat** is that it doesn't work with any resource pack, it uses them for combination (furniture mod + wood type mod). 

EDIT: 
& the mod doesn't have any blocks. it's just a visual enhancement stuff. Like I said above. **Every Compat** doesn't deal with visual stuff. just added blocks where the furniture mod doesn't have an addon for other wood-type mods.

**Comment by Xelbayria** [comment]
Closing this blc of no replying.
