### ISSUE TITLE
[🐞]: Macaw Trapdoors renamed Blossom Trapdoors to Waffle Trapdoors

### ISSUE THREAD

**Issue by Guinaro** [MehVahdJukaar/WoodGood#393]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20.2.6.23

### Moonlight Lib Version

moonlight-1.20-2.8.82

### Issue with mods

Macaw Trapdoors 1.1.2 mc1.20.1-forge

### Issue Detail

Change 
From:
"block_type.mcwtrpdoors.blossom_trapdoor": "%s Blossom Trapdoor" 
To:
"block_type.mcwtrpdoors.blossom_trapdoor": "%s Waffle Trapdoor"

in language file to be consistent with Macaw Trapdoors.

**Comment by Xelbayria** [comment]
Alright, that will be Module Enhancement.

**Comment by MehVahdJukaar** [comment]
added
