### ISSUE TITLE
[🗃]: Quark (1.20 Beta Release) Chest are Broken

### ISSUE THREAD

**Issue by OminousDiscovery** [MehVahdJukaar/WoodGood#399]
### Version

Quark 4.0 Beta 428

### Curseforge

only is on the discord

### Details

The chest are like there but like not there. There icons are invisible and the placement of the block is broken.

**Comment by Xelbayria** [comment]
**MehVahdJukaar** is aware of this the whole time. he's part of the Quark Team. he'll fix it when it's time to.
