### ISSUE TITLE
[📦]: Mighty Mail Compat (Forge & Fabric versions, 1.19.2-1.20.1)

### ISSUE THREAD

**Issue by Liamgrayskull** [MehVahdJukaar/WoodGood#401]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/mighty-mail

### Curseforge-Fabric (Optional)

https://www.curseforge.com/minecraft/mc-mods/mighty-mail-fabric

### FABRIC Version Availability

- [ ] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [ ] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

mighty_mail

### Types

**Block:**
- ex: mail_box (variant for all vanilla wood types)
- post box (not wood related)

**Item:**
Respective items for all vanilla wood types

### Optional Details

Mighty Mail has vanilla mail box variants of all woods which behave in the same way- although they have data associated with them when placed, being named to provide a tag that the post box sends items and notes to recipients. All mail boxes have a 9 slot inventory once named.

**Comment by Xelbayria** [comment]
Added to 
1.20.1: v2.6.42
1.19.2: v2.5.26
