### ISSUE TITLE
[📦]: Create: Extended Cogs (additional info)

### ISSUE THREAD

**Issue by steve-the-player** [MehVahdJukaar/WoodGood#402]
_Originally posted by @nitrodynamite18 in https://github.com/MehVahdJukaar/WoodGood/issues/77#issuecomment-1356976319_
I can't easily add more info in a comment anywhere, so I'm putting it here. 

Mod is now also available for fabric https://modrinth.com/mod/extended-cogwheels 
Item/blocks added: cogs of various sizes in all wood variants. 

Both versions now support up to 1.20.x

**Comment by Xelbayria** [comment]
That's because I changed the way things work. You should have seen a few lists: 
- Suggest a Mod
- Module Enhancement 👈 you would want to use this if there are additional or new updates to mods. 
- Question
- Report Bug

Alright, I'll add that to the kanban.

**Comment by Xelbayria** [comment]
Related to: #426 

The reason for "not-planned" is mentioned in the issue\#426
