### ISSUE TITLE
[🗃]: [1.20.1]Quark's ladder does not be displayed correctly

### ISSUE THREAD

**Issue by BradClc** [MehVahdJukaar/WoodGood#403]
### Version

Quark-4.0-beta-430.3234

### Curseforge

available on discord only

### Details

![2024-01-18_21 55 23](https://github.com/MehVahdJukaar/WoodGood/assets/88281511/8a4082c3-0e25-4ecc-a1cd-e8ce4d2a8ddd)
The ladders on the left are added by everycompat from many different mods, and they should not have the bottom layer of texture

**Comment by soleilan** [comment]
still an issue with non-beta Quark 1.20.1 release

**Comment by Xelbayria** [comment]
Can you turn off the Shader (if you have one enabled) and check if these blocks are normal, no problem with texturing. I'll need more details. which mods have the problem with texturing added by **Every Compat** and what is the name of the wood type

**Comment by soleilan** [comment]
I'm not using any shaders personally and I have the problem. It's affecting any ladder with the mod tag of Quark. I have ladder = true under [general.entries.wood_type.quark] and all of them aren't transparent textures. So any ladders for any wood types based on the quark ladder entry.

![image](https://github.com/MehVahdJukaar/WoodGood/assets/111906440/74db7379-f696-43b6-9745-b3e4cc9d9381)

Wood types are from top to bottom: 

- Canopy from Twilight Forest
- Archwood from Ars Novueau
- Jacaranda from Biomes 'o Plenty
- Walnut from Ecologics

Here's a log from a fresh instance where I just added some mods to test this. The same issue occurs in another 1.20.1 modpack I'm playing so I don't believe its related to any specific mod interaction.
https://mclo.gs/4iHgvts

**Comment by Xelbayria** [comment]
😩  not that problem again. I have seen that issue before. I somehow managed to fix it. I'll try and see if I can fix it in 1.20.1, too.

**Comment by Xelbayria** [comment]
Fixed. I know what's the problem. and the exact same issue above in 1.18.2 where I somehow managed to fix (it actually fixed itself). I thought it was fine but it wasn't. The ladder is a "cutout" type for rendering. Looks like I'll have to apply the same code to 1.18.2 and 1.19.2. Thanks for reporting this. 

anyway, the fix will be in the next versions. I gotta fix other problems for 1.20.1, too

**Comment by MythicHH** [comment]
I have this problem as well
