### ISSUE TITLE
[🐞]: Accidental required dependency breaking the game

### ISSUE THREAD

**Issue by 50xes** [MehVahdJukaar/WoodGood#409]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

2.6.27

### Moonlight Lib Version

latest

### Issue with mods

sawmill

### Issue Detail

![required dependency](https://github.com/MehVahdJukaar/WoodGood/assets/79957706/4e44f60c-e0d3-4062-b79b-9a2ede5cf204)

### OPTIONAL: To Produce

run server. play server. open creative menu. crash cause mod that isn't supposed to be there is in there.

**Comment by MehVahdJukaar** [comment]
yeah its supposed to be optional. Still why is it crashing? send laetst.log

**Comment by 50xes** [comment]
> yeah its supposed to be optional. Still why is it crashing? send laetst.log

The problem is its listed as required and pops up in my mods folder every time I update on Curse. It shouldn't be listed as required if its optional. Also there's no log because the game doesn't start when it's in the mods folder. The pack I run has a lot of mods and it's possible there's a mod conflict if nobody else is having the same issue. This is the mod list I run:
- Additional Additions
- Additional Banners
- Additional Lanterns
- Additional Structures
- Aereoblender
- AI Improvements
- Alex's Mobs
- Angel Ring
- Appleskin
- Applied Cooking
- Ae2
- Aether
 - Deep Aether
 - Aether: Redeux
- Aquaculture 2
- Aquatic Torches
- Armourer's Workshop
- Ars Nouveau
 - Ars Creo
 - Ars Elemental
- Ars Ocultas
- Attribute Fix
- Better Archeology
- Better Dogs x Doggy Talents Next
- Better Villages
- Biomes o' Plenty
- Bone Torch
- Botania
- Botany Pots
- Bountiful
- Canary
- Callable Horses
- Camera Mod
- Chimes
- Chipped
- Chisel And Bits
- Chunky
- Clumps
- Cluttered
- Connectivity
- Construction Wand
- Cooking For Blockheads
- Comforts
- Compressium
- Colorful Hearts
- Corail Woodcutter
- Crafttweaker
- Crash Utils
- Create
- Create Crafts & Additions
- Create Bells And Whistles
- Create Confectionary
- Create Deco
- Create Enchantment Industry
- Create Interiors
- Create Jetpack
- Create Slice And Dice
- Create Steam And Rails
- Create Stuff And Additions
- Create Misc & Things
- Cull Leaves
- Customizable Elytra
- Dank Storage
- DefaultSettings
- Diet
- Doggy Talents Next
- Domum Ornamentum
- Doubledoors
- Dungeons And Taverns
- Elytra Slot
- Embeddium
- Embers Rekindled
- Entity Culling
- Excessive Building
- Fairy Lights
- Fantasy's Dice
- Fantasys Furniture
- Farmers Delight
 - Chefs Delight
 - Coffee Delight
 - Corn Delight
 - End's Delight
 - Festive Delight
 - Miners Delight +
 - Nether Delight
 - Oceans Delight
 - Pineapple Delight
- Fast Furnace
- Fast Leaf Decay
- Fast Workbench
- FerriteCore
- Floral Enchantment
- Flower Patch
- Forbidden Arcanus
- Friendly Fire
- Friends & Foes
 - Mooblooms Addon
- Ftb Chunks
-Ftb Essentials
- Ftb Quests
- Ftb Ranks
- Ftb Xmod Compat
- Ftb Ultimate
- Ftb Teams
- Functional Armor Trim
- Functional Storage
- Fusion (Connected Textures)
- Gateways To Eternity
- Galosphere
- Gems And Jewels
- Handcrafted
- Hearth & Home
- Hopo Better Underwater Ruins
- Inventory Pets
- Iron Chests
- Irons Spells N Spellbooks
- JEI
- Jade
- Joy of Painting
- Kubejs
- Laser Io
- Let Me Despawn
- Let's Do Bakery
- Let's Do Beachparty
- Let's Do Candlelight
- Let's Do Herbalbrews
- Let's Do Meadow
- Let's Do Nether Vinery
- Let's Do Vinery
- Lootr
- Lucky's Cozy Home
- Macaws Bridges
- Macaws Bridges Bop
- Macaws Doors
- Macaws Fences And Walls
- Macaws Fences Bop
- Macaws Furniture
- Macaws Furniture Bop
- Macaws Lights And Lamps
- Macaws Paintings
- Macaws Paths And Pavings
- Macaws Trapdoors
- Macaws Windows
- Mcaws Holidays
- MCA Reborn
- Mekanism
 - Mekanism Generators
 - Mekanism Tools
 - Mekanism Additions
 - Mekanism Ad Astra Ores
- Mob Grinding Utils
- Mob Lassos
- Model Gap Fix
- Modern Fix
- Modular Routers
- More Mob Variants
- MrCrayfish's Furniture Mod
- Mystic's Biomes
- Mythic Mounts
- Nature Compass
- Natures Aura
- Neruina
- Nether Portal Fix
- Night Light
- Night Vision Enchantment
- Observable
- Occultism 
- Oculus
- Overweight Farming
- Pehkui
- Pipez
- Player Shops
- Powah!
- Polymorph
- Productive Bees
- Pylons
- Realistic Horse Genetics
- Rechiselled Create
- Recipe Essentials
- Refined Cooking
- Refined Storage
 - Refined Storage Addons
- Relics
- Rftools Base
 - Rftools Builder
 - Rftools Utility
 - Rftools Power
 - Rftools Storage
- Right Click Harvest
- Searchables
- Shoppy
- Smarter Farmers
- Sophisticated Backpacks
- Spark
- Spelunkery
- Starbuncle Mania
- Starlight
- Structory
- Supplementaries 
- Tarot Crads
- Tectonic
- Terralith
- Tetra
- Thermal Foundation
 - Thermal Expansion
 - Thermal Innovation
 - Thermal Dynamics
 - Thermal Cultivation
 - Thermal Integration
- Theurgy
- Trash Cans
- Twigs
- Underground Jungle
- Underground Villages
- Visuallity: Reforged
- Waystones
- When Dungeons Arise
- Worldedit
- Xnet
 - Xnet Gases
- Yungs Bridges
- Yungs Better End Island
- Yungs Better Ocean Monuments
- Yungs Better Mineshafts

**Comment by Xelbayria** [comment]
Try v2.6.28 and see if you still get the crash. it has fixes for **Macaw's Fences & walls** (just fix the hedge's textures) & **Macaw's Paths & pavings** <- this one caused the crash due to changes in the code. 

EDIT:
went through your mod list: 
this: 
- Macaws Fences Bop
- Macaws Furniture Bop

you don't need them because **Every Compat** supported both of these macaw's. It is unnecessary to add the 2 same types of blocks from 2 different mods.

**Comment by 50xes** [comment]
It works now, thank you
