### ISSUE TITLE
Is Sawmill marked as RequiredDependency on Forge builds intended?

### ISSUE THREAD

**Issue by zlainsama** [MehVahdJukaar/WoodGood#417]
Starting from everycomp-1.20-2.6.27.jar on CurseForge, you have mod Sawmill marked as RequiredDependency, causing launchers to download that automatically.
I noticed this in last version, but it persisted to everycomp-1.20-2.6.28.jar, so I opened this issue just to let you know.
If its intended, please just close and ignore this.

**Comment by Xelbayria** [comment]
it's not required. it's just optional. the only thing **Every Compat** needs is the **Moonlight lib**, weird. Thanks for reporting this.

**Comment by Xelbayria** [comment]
I've spoken to MehVahdJukaar and it was an accident. so i'll fix it. Again, thanks!
