### ISSUE TITLE
[📦]: Backpacked

### ISSUE THREAD

**Issue by kingkuys2123** [MehVahdJukaar/WoodGood#418]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/backpacked

### Curseforge-Fabric (Optional)

https://legacy.curseforge.com/minecraft/mc-mods/backpacked-fabric

### FABRIC Version Availability

- [ ] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [ ] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

backpacked

### Types

**Block:**
- Wooden Backpack Shelves

**Comment by Xelbayria** [comment]
1.20.1: Added since 1.19.2 but was moved to COMMON blc FABRIC & FORGE are supported. 
1.19.2: FABRIC added to v2.5.28

**Comment by kingkuys2123** [comment]
Thanks :)
