### ISSUE TITLE
[📦]: Redbits

### ISSUE THREAD

**Issue by kingkuys2123** [MehVahdJukaar/WoodGood#419]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://legacy.curseforge.com/minecraft/mc-mods/red-bits

### FABRIC Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20.1

### MODID

redbits

### Types

**Block:**
- Large Wooden Buttons

### Optional Details

None

**Comment by Xelbayria** [comment]
Added to 2.6.75 (1.20.1-FABRIC)

**Comment by kingkuys2123** [comment]
Thanks :)

**Comment by Xelbayria** [comment]
Added to 2.5.27 (1.19.2-FABRIC)

**Comment by kingkuys2123** [comment]
Thanks :)
