### ISSUE TITLE
[📦]: Twilight Forest

### ISSUE THREAD

**Issue by kingkuys2123** [MehVahdJukaar/WoodGood#420]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://legacy.curseforge.com/minecraft/mc-mods/the-twilight-forest

### Curseforge-Fabric (Optional)

https://legacy.curseforge.com/minecraft/mc-mods/the-twilight-forest

### FABRIC Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

twilightforest

### Types

**Block:**
- Wooden Banisters
- Hollow Logs

### Optional Details

None

**Comment by Xelbayria** [comment]
Already supported in **EC** for both Fabric & Forge (I checked)

EDIT:
oh, i see it wasn't enabled for FABRIC. Will be fixed in the next version.
