### ISSUE TITLE
[📦]: Wooden Hoppers

### ISSUE THREAD

**Issue by kingkuys2123** [MehVahdJukaar/WoodGood#421]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/wooden-hoppers

### Curseforge-Fabric (Optional)

N/A

### FABRIC Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20.1

### MODID

woodenhoppers

### Types

**Block:**
- Wooden Hoppers

### Optional Details

None

**Comment by Xelbayria** [comment]
1.20.1: Added to v2.6.76

1.19.2: Added to v2.5.28

**Comment by kingkuys2123** [comment]
Thanks :)
