### ISSUE TITLE
[📦]: Table Top Craft

### ISSUE THREAD

**Issue by kingkuys2123** [MehVahdJukaar/WoodGood#422]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/table-top-craft (x > 1M)

### Curseforge-Fabric (Optional)

https://curseforge.com/minecraft/mc-mods/table-top-craft-fabric (x > 10,000)

### FABRIC Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

table_top_craft

### Types

**Block:**
- Chess
- Connect Fours

### Optional Details

None

**Comment by Xelbayria** [comment]
- Added to v2.6.81 (1.20.1). 
- Added to v2.5.29 (1.19.2).
- Added to v1.6.17 (1.18.2).

**Comment by kingkuys2123** [comment]
Thank youuuu :)

**Comment by Xelbayria** [comment]
You should thank the Dev of Table Top Craft, he added them to 1.18.2 to 1.20.1. 

👉🏻  @andrew0030
