### ISSUE TITLE
[📦]: Villagers Plus

### ISSUE THREAD

**Issue by OminousDiscovery** [MehVahdJukaar/WoodGood#424]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/villagersplus-forge

### Curseforge-Fabric (Optional)

https://www.curseforge.com/minecraft/mc-mods/villagersplus-fabric

### FABRIC Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

tbh idk what this asking for. sorry :(

### Types

**Block:**
Flower tub with all wood variant

**Item:**
- <item-name with wood_type>

### Optional Details

you can put flowers in the flower tub

**Comment by OminousDiscovery** [comment]
sorry i put this again I didn't see it before on the backlog but then I checked a second time and it was there

**Comment by Xelbayria** [comment]
oh ok. i can add "duplication" here. no worries

**Comment by Xelbayria** [comment]
Similar Suggested Mod: #367
