### ISSUE TITLE
[🐞]: Twilight Forest : Hollow Logs Un-obtainable

### ISSUE THREAD

**Issue by CarJem** [MehVahdJukaar/WoodGood#428]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycompat-1.20-2.6.29

### Moonlight Lib Version

moonlight-1.20-2.6.29

### Issue with mods

Twilight Forest - Version 4.3.2145

### Issue Detail

Hollow Logs are generated with EveryCompat but there are no recipes to obtain them legitimately

**Comment by Xelbayria** [comment]
Isn't `Hollow Logs` from **Quark**??

EDIT:
nvm. I see **TwilightForest** has _horizontal hollow logs_.  I know what's the problem. easy fix.

**Comment by Xelbayria** [comment]
fixed in [commit](https://github.com/MehVahdJukaar/WoodGood/commit/96ddaf58439164b74149ee206b241cf2364d0545)
