### ISSUE TITLE
[🐞]: 1.20.1 Crashes when opening Creative Inventory

### ISSUE THREAD

**Issue by toErIpNid** [MehVahdJukaar/WoodGood#431]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

2.6.29

### Moonlight Lib Version

2.9.8

### Issue with mods

The mod itself.

### Issue Detail

When trying to open the creative menu, the game crashes.

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/14219157/latest.log)
[crash-2024-02-09_02.03.28-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/14219165/crash-2024-02-09_02.03.28-client.txt)

### OPTIONAL: To Produce

[Shadow Of The Dragon Test 1.20.3.zip](https://github.com/MehVahdJukaar/WoodGood/files/14219201/Shadow.Of.The.Dragon.Test.1.20.3.zip)

**Comment by Xelbayria** [comment]
the modpack run fine without **Every Compat** when you open creative menu, correct? 

EDIT: 
i looked at the crash-report. It looks like one of module via **Every Compat** is outdated. has to do with `CreativeTabMode`.
hard to say which module is outdated. I'll need you to do this: 

 > If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit

**Comment by toErIpNid** [comment]
After some testing I found out it was Quark doing osmething weird. Either Quark or Oddities. I'll make a report there too.

**Comment by Xelbayria** [comment]
> After some testing I found out it was Quark doing osmething weird. Either Quark or Oddities. I'll make a report there too.

that's a good idea. and that's weird. **Quark Module** (via **EC**) is already updated for **Quark** of 1.20.1. so it must be **Oddities**

**Comment by gardenappl** [comment]
I have this issue as well, but I don't enable Oddities.

**Comment by gardenappl** [comment]
Also, as a side effect of creative tabs being broken, it seems like JEI is also broken.

I can confirm that disabling the quark module in the hazardous config file fixes everything.

**Comment by Xelbayria** [comment]
Ok, you need to make sure **Quark** is up to date (it's out of beta). Same for **Zeta** (Quark's dependent library).

**Comment by Xelbayria** [comment]
any news regarding this?

**Comment by sdjge** [comment]
I have tested newest Quark, the creative inventory are still not work(but without crashes)

**Comment by sdjge** [comment]
![image](https://github.com/MehVahdJukaar/WoodGood/assets/32814572/558a0da3-daf9-4dfd-b7f0-06b87d258aee)

**Comment by EgbertMedia** [comment]
Wood Good/Every Compat crashes EMI when there is one of the items on the EMI page if the Chipped mod is installed. It seems related to the same crash that people have above with Quark

**Comment by MehVahdJukaar** [comment]
send log

**Comment by EgbertMedia** [comment]
I made a separate issue for it #437

**Comment by DelviousCrafts** [comment]
I have run into this issue as well. It seems to be a combination of quark, every compat, ferrite core, and something. I have narrowed it down to the 108 mods that were shared between my own pack, and OP's pack based on the list provided in the log. I will let you know when I find the offending mod combination.

**Comment by Xelbayria** [comment]
try to update all of your mods and see if it fixed the issue.

**Comment by Delvious** [comment]
All of the mods I work with are the latest versions that are available on curseforge. Had to go to work. Will get appropriate mod versions and list when I have narrowed down the full combo.

**Comment by PengyTheGamer** [comment]
im not sure if this helps, but i seem to get this issue when having jaopca installed alongside every compat and quark
(did some tests and im not sure if this happens when only the 3 mods are installed however, but disabling jaopca seems to fix this?)

**Comment by MehVahdJukaar** [comment]
Send latest.log. also that's not enough mods for EC to work. Uninstall eveyrcompat you don't need it with just those 3 mods

**Comment by PengyTheGamer** [comment]
i was just saying that it could be some sort of incompatibility between jaopca and every compat since it seemed like it didn't crash if jaopca (or every compat/quark) was disabled.
(im not actually just playing with quark, jaopca and every compat though)
but here's the latest.log and mods list for me

[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/14448673/latest.log)
mods list:
[image](https://github.com/MehVahdJukaar/WoodGood/assets/51223619/2e606760-b8eb-4340-bbdc-456c5cfb76e6)

**Comment by DelviousCrafts** [comment]
Sorry it took so long to respond. I finally found the offending mod combination. It took this long because the offending mod was updated and the update corrected the issue. So I've been going in circles to figure out why it's working now, but it wasn't a few days ago.

The mods listed prior plus the decorative blocks version 4.1.2 combination were bugged and causing this crash, however, version 4.1.3 seems to be working fine now. Now I have the fun task of finding out why that version is causing issues with loading my entire pack in general, but that's a report for that mod, not this one.

**Comment by DelviousCrafts** [comment]
I take it back, I found the offending mod combination in our shared mods. I am still having this issue in my own pack. Further investigation is now underway

**Comment by DelviousCrafts** [comment]
Well, whatever you changed in the latest version (2.6.36) seemed to fix the issue. I was having the issue this morning and was still in the process of working on finding the exact combination of mods, and now with the latest update, am no longer having the issue.

**Comment by MehVahdJukaar** [comment]
Only way the mod can crash on creative tab is if it registered 0 blocks = you don't need the mod
New modules were added in last update
