### ISSUE TITLE
[🐞]: Incorrect Localization For Architects Palette Board Subtypes

### ISSUE THREAD

**Issue by ChloeDawn** [MehVahdJukaar/WoodGood#433]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

1.20-2.6.29

### Moonlight Lib Version

forge_1.20-2.9.10

### Issue with mods

- Architect's Palette 1.20.1 v1.3.6.1

### Issue Detail

The following localizations should be using the singular Board instead of Boards to match [Architect's Palette's naming convention](https://github.com/jsburger/Architects-Palette/blob/3a8869436192a34ae5162f875664531ea704de1a/src/generated/resources/assets/architects_palette/lang/auto_generated.json#L125-L128).
https://github.com/MehVahdJukaar/WoodGood/blob/4e2bda49e3dbfc137fc862d63ec9d32312c329d4/common/src/main/resources/assets/everycomp/lang/en_us.json#L242-L244

**Comment by Xelbayria** [comment]
fixed. and will be in next version.
