### ISSUE TITLE
[🐞]: EMI crashes when Chipped is also installed

### ISSUE THREAD

**Issue by EgbertMedia** [MehVahdJukaar/WoodGood#437]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

Every Compat 1.20-2.6.33

### Moonlight Lib Version

Moonlight Library 1.20-2.9.17

### Issue with mods

Athena 3.1.1
Chipped 3.0.4
EMI 1.1.1+1.20.1 forge
Every Compat
Moonlight Lib
Resourceful Lib

### Issue Detail

Game crashes when on an EMI page where Every Compat items are present, only when Chipped is also present

### Crash log
https://mclo.gs/OWpFFit

### OPTIONAL: To Produce

1) Open inventory
2) Switch between EMI pages
3) Crash

**Comment by MehVahdJukaar** [comment]
Uninstall every compat. You don't need it

**Comment by EgbertMedia** [comment]
This was the minimal amount of mods I could reproduce the crash with.
I added Every Compat to my modpack because I was planning to add biome mods after debugging this issue, but I can now confirm that installing Biomes 'O Plenty does fix the crash so it does seem like it only crashes when there is no mod present that adds new wood types.

**Comment by MaxenceDC** [comment]
This also affects Fabric (& Quilt) (same bug, division by 0)

**Comment by MaxenceDC** [comment]
I'm no longer having the issue after updating.

**Comment by Xelbayria** [comment]
Maxen, which mod had the update that is no longer caused the problem??? I don't think it's **EveryCompat** that caused this but one of the mods that caused this.

**Comment by MehVahdJukaar** [comment]
To clarify, if you install every compact alone it will happen
.eveyrcompat is not meant to be used alone
