### ISSUE TITLE
Hedges Missing Images

### ISSUE THREAD

**Issue by saphsara** [MehVahdJukaar/WoodGood#438]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Fabric

### EveryCompat Version

everycomp-1.20-2.6.33-fabric.jar

### Moonlight Lib Version

moonlight-1.20-2.9.17-fabric.jar

### Issue with mods

macaw Walls v1.1.1 (edited by xelbayria)

### Issue Detail

Headges images arent displaying,
 I am using mod pack Saphsgamingworld fabric on curse, i am running a server and just notice it as of today. when i went to make a hedge. 

### OPTIONAL: Latest.log | Crash-report Attachment

![Hedges](https://github.com/MehVahdJukaar/WoodGood/assets/33788318/6cec10e0-346e-442f-930e-be52a78fd365)
![Hedges2](https://github.com/MehVahdJukaar/WoodGood/assets/33788318/ac39502e-859e-4237-b931-baae49e773d3)

**Comment by Xelbayria** [comment]
and which mod is the wood variants from?

**Comment by saphsara** [comment]
> and which mod is the wood variants from?

I looked at the recipes they are from chipped mod.

**Comment by saphsara** [comment]
![Uploading chipped.png…]()

**Comment by saphsara** [comment]
![chipped](https://github.com/MehVahdJukaar/WoodGood/assets/33788318/77b43b0a-1189-4491-9941-2dd8912f4acd)

**Comment by Xelbayria** [comment]
**chipped**? 👀 I didn't expect that mod to have wood variants. thanks, I'll take a look at this problem. 

If more mods have wood variants. then please add them to the list

**Comment by saphsara** [comment]
the only other mod that i use is botania that has wood that every compact doesnt support yet . but i just put a  suggestion that it be added. thank you for looking into this. i love your mod and keep up the great work.

**Comment by Xelbayria** [comment]
I found the problem. will be applying the fix. I'm glad that the mod is useful! ^_^ 
I'll check botania, too.

**Comment by Xelbayria** [comment]
The next version, v2.6.34 will be available on Curseforge & Modrinth when it's approved

**Comment by saphsara** [comment]
Thank you ! this is great! i will check it out as soon as i can . keep up the great job and thank you for being on top of stuff.

**Comment by saphsara** [comment]
I did the update you put out for this and got an error . it is the only mod i updated . moonlight and every compact. 
![updated mod error](https://github.com/MehVahdJukaar/WoodGood/assets/33788318/b0de0ec0-3457-457f-b99d-004dca72cb1c)

**Comment by Xelbayria** [comment]
looks like the problem is in Data Pack, not **Every Compat**
