### ISSUE TITLE
[🗃]: Botania

### ISSUE THREAD

**Issue by saphsara** [MehVahdJukaar/WoodGood#439]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/botania

### Curseforge-Fabric (Optional)

https://www.curseforge.com/minecraft/mc-mods/botania-fabric

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20.1

### MODID

<strike>no clue what this is</strike> botania (edited by xelbayria)

### Types

Livingwood and dreamwood

**Comment by Xelbayria** [comment]
If you have JEI, then you can use it to look at the full ID of a block from Botania,   it will look like this: `modID:oak_leaves` 

Hit F3+H to have an advanced tooltip to show you the full ID.

**Comment by Xelbayria** [comment]
i know what's the problem. the reason why **Every Compat (EC)** couldn't detect the 2 woods from Botania is that they don't have the sound "bass". you need to let the dev know about this. There is nothing I can do on the **EC** side.

EDIT: 
on another note, you should let Dev know that he should do the same with FORGE side.

**Comment by dhouck** [comment]
Why do you look for note block sound instead of the `#minecraft:planks`, which Botania does tag?

**Comment by Xelbayria** [comment]
@MehVahdJukaar  that's your question to answer ☝️

**Comment by MehVahdJukaar** [comment]
Because tags are loaded when a world is loaded. Blocks are registered way way before that . Up until you open a world tags don't exist as they depend on the world. Blocks do not

**Comment by dhouck** [comment]
Ah, makes sense.  Obvious in retrospect, too, you can’t have the tags until the things-to-be-tagged exist.

**Comment by dhouck** [comment]
The Botania issue has been closed so should be fixed in the next version of that mod, so hopefully this will work then.
