### ISSUE TITLE
Missing Azalea ladders/chests from Ecologics & Quark

### ISSUE THREAD

**Issue by brnbrd** [MehVahdJukaar/WoodGood#44]
These separate wood types (same name) provided by Ecologics & Quark each do not have a ladder or chest (is it because textures are not auto generated?)

**Comment by Xelbayria** [comment]
is this issue solved? If yes, then please close this

If not, then please fill out: 
- Minecraft Version
- Loader: (Forge or Fabric)

**Details:** 
- Which mod have issue with EveryCompat: 
    - Ecologics
    - Quark

**Comment by Xelbayria** [comment]
closing this due to no replying.
