### ISSUE TITLE
[🐞]: There are some missing textures on some logs of born in chaos and endless biomes

### ISSUE THREAD

**Issue by JuanPacoPedrodelaMar** [MehVahdJukaar/WoodGood#443]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [ ] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

2.6.34

### Moonlight Lib Version

2.10.3

### Issue with mods

Born in chaos 1.2
Endless biomes 1.4.2s

### Issue Detail

They have missing texture on the top of them. The items are Hollow Scorched Log, Hollow twisted log and Hollow Penumbra Log. I even tried deleting all the mods except quark, this one, born in chaos, endless biomes and their dependencies, I created a new world and the issue persists, so it is not a compatibility problem with others.
![Captura de pantalla (4)](https://github.com/MehVahdJukaar/WoodGood/assets/127499569/4bdb182d-7fdc-4047-8f22-47403f172c6d)
![Captura de pantalla (5)](https://github.com/MehVahdJukaar/WoodGood/assets/127499569/78802423-6082-4fb7-b4fb-4208d173a123)

**Comment by JuanPacoPedrodelaMar** [comment]
I just noticed there was another issue for born in chaos, but I did not understood how he solved it. sorry but I am not really into doing resource packs.

**Comment by Xelbayria** [comment]
for **Born In Chaos**, it's very simple. You just need to make a copy of the texture and rename it to the correct name so the texture will show up on the block. more details are in: #133 

I fixed other problems in 1.19.2 and I'll be applying this to 1.20.1, too.  FYI, The fix in 1.19.2 won't work with **Born in Chaos** because the name for the wood variant or Stem variant is not consistent and it's a mess. the fix above is very simple and can fix the texture problem with other mods mentioned in another issue. 

the Dev of **Born in Chaos** should have fix it long time ago.

**Comment by JuanPacoPedrodelaMar** [comment]
But from where can i get the texture for the top to put it inside the resource pack?

**Comment by Xelbayria** [comment]
> But from where can i get the texture for the top to put it inside the resource pack?

simply go in **Born in Chaos**'s asset and find the texture that are used for scorched_log_top (it's not an english word). u'll see what i mean by " it's a mess " 

just copy and paste it into your custom resource pack. rename it to "scorched_log_top". that's it.  The structure of the Resource pack is already shown in another issue.

**Comment by JuanPacoPedrodelaMar** [comment]
Oh, i see what you meant lol. I will try to do it thank you

**Comment by JuanPacoPedrodelaMar** [comment]
![imagen_2024-02-22_234059655](https://github.com/MehVahdJukaar/WoodGood/assets/127499569/11b68704-98a8-410c-b842-dd3907382f3e)
Well, it worked but is it supposed to see like that? it has just the texture of the center of the log

**Comment by Xelbayria** [comment]
> Well, it worked but is it supposed to see like that? it has just the texture of the center of the log

🤔  that shouldn't be the case... the side should be using "log_side" while the top/bottom use "log_top". my advice is to check the image texture and to determine whether it's top or side. again, that's why it's a mess. 

> it has just the texture of the center of the log

That's the `log_top`

**Comment by JuanPacoPedrodelaMar** [comment]
I found the texture, how should i name the side? I named it as "scorched_log_side" but it didn´t work

**Comment by Xelbayria** [comment]
you don't need to worry about the `log_side`, you just need to get the `log_top` and rename it `scorched_log_top.png`

EveryCompat got it right for `log_side`, and only `log_top` is wrong. just need a small correction.

**Comment by JuanPacoPedrodelaMar** [comment]
sorry to annoy you again, but i did what you said and the texture issue persists, i can´t see the log side just the top. Idk if i did something wrong with the resource pack but i don´t think so. Anyway, here it is if you want to see it. 
[fixed-born-in-born.zip](https://github.com/MehVahdJukaar/WoodGood/files/14391233/fixed-born-in-born.zip)

**Comment by JuanPacoPedrodelaMar** [comment]
the image that is called briverno is just the side of the log, but it does not do anything by itself, it has the same texture and name as the original mod.

**Comment by Xelbayria** [comment]
Ok i fixed it. I know why. it's a bit different from 1.19.2. Here's the resource pack: 
[fixed-born-in-born.zip](https://github.com/MehVahdJukaar/WoodGood/files/14392024/fixed-born-in-born.zip)

EDIT:
I've applied the fix from 1.19.2 to 1.20.1 and it's all fixed. It would be nice if the Dev of **Born in Chaos** fix the filename. 
the problem is much worse than 1.19.2. ☹️

**Comment by Xelbayria** [comment]
i've left a comment on **Born in Chaos**'s comment. hopefully the Dev will see my message and just need to rename these files related to 2 Stem/wood type. so the resourcepack solution won't be needed.  I do not know when it will be fixed. time will tell.

**Comment by JuanPacoPedrodelaMar** [comment]
Let´s hope he will solve it. Thank you very much anyway, it was kind of you to help me :)
