### ISSUE TITLE
[🐞]: Kicked from server

### ISSUE THREAD

**Issue by mxnmnm** [MehVahdJukaar/WoodGood#445]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [x] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [ ] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.34

### Moonlight Lib Version

moonlight-1.20-2.10.4-forge

### Issue with mods

I'm not sure but very likely quark (4.0-436 and zeta 1.0-13) is involved, I'd rather not go through my many mods unless I absolutely have to (hoping the log will be enough), but if the log isn't enough info let me know so I can find the specific mods.

### Issue Detail

When you try to join a server you will probably get kicked the first time you enter but then you can log back in afterwards

### OPTIONAL: Latest.log | Crash-report Attachment

https://gist.github.com/mxnmnm/2e89416ee62082f76f0a9ebebac29141

**Comment by MehVahdJukaar** [comment]
Do you have connector? Try without

**Comment by mxnmnm** [comment]
https://gist.github.com/mxnmnm/5076d7cc738fe852ee7b4fdd654bc802

same issue

**Comment by unilock** [comment]
Happens here too, but also *every* time I try to join a singleplayer world.

[debug.log.zip](https://github.com/MehVahdJukaar/WoodGood/files/14449777/debug.log.zip) (too big for GitHub Gist)

**Comment by MehVahdJukaar** [comment]
debug.log isnt useful. I need latest.log

**Comment by unilock** [comment]
latest.log: https://gist.github.com/unilock/bea5f9888d4a281450f2b6a0e9babd9b

**Comment by Xelbayria** [comment]
are u able to connect to the server?  According to the latest.log. It has an issue with connecting to server via `Cannot contact authentication server`. 

the best way to resolve this is to relaunch Minecraft and connect the server. it usually resolves this. there is a mod that should resolve this without relaunching Minecraft. I can't remember the name.

**Comment by mxnmnm** [comment]
I haven't run into this issue in a while so it was probably fixed in this mod or another at some point, I'll leave it open in case it is still happening for other people on newer versions

**Comment by Xelbayria** [comment]
Seeing there have been no report of this issue. Will be closing this.
