### ISSUE TITLE
[📦]: Cluttered

### ISSUE THREAD

**Issue by SeventhNinjaShadow** [MehVahdJukaar/WoodGood#450]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/cluttered

### FABRIC Version Availability

- [ ] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

cluttered

### Types

**Wood Types:**
- pink
- flowering pink
- yellow
- flowering yellow
- green
- glow
- purple
- flowering purple
- blue mushroom

**Block:**
- modded wood variants of vanilla wood blocks (including logs, wood, and stripped log blocks)
- bookshelves
- town planter (can grow crops and have flowers and saplings placed on it)

Purple bookshelves come with extra variants:
- jar
- black cat
- cobweb
- calico cat
- vase

### Optional Details

Town planters only have modded wood versions and no vanilla ones in the mod

It may be worth noting that the town planter gets replaced with a dirt block when saplings grow up in it

The blue mushroom wood set is based on the furniture set from Terraria. You may want to take a look at either Terraria's furniture or Cluttered's blue mushroom trapdoor

**Comment by Xelbayria** [comment]
I've a look at the mod and it cannot be supported because it doesn't have the vanilla WoodType. it must have an "OAK" like `oak_table`, then I could add the mod to **Every Compat**. There is nothing I can do about this.
