### ISSUE TITLE
[🐞]: Missing Textures

### ISSUE THREAD

**Issue by mxnmnm** [MehVahdJukaar/WoodGood#451]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.35

### Moonlight Lib Version

moonlight-1.20-2.10.10-forge

### Issue with mods

Quark-4.0-436
Zeta-1.0-13
twilightforest-1.20.1-4.3.2145-universal

### Issue Detail

Hedges and leaf carpets that use thorn leaves and beanstalk leaves do not have a texture.

### OPTIONAL: Latest.log | Crash-report Attachment

![2024-03-02_03 52 33](https://github.com/MehVahdJukaar/WoodGood/assets/8508976/fe0bf41c-6d84-4d19-b990-d9e179590d47)

**Comment by Xelbayria** [comment]
Does the latest version (v2.6.42) solve this problem? 

EDIT: 
I ran tests and the problem is fixed.
