### ISSUE TITLE
[🐞]: Furnish/ EC crates voids items when breaking it

### ISSUE THREAD

**Issue by Urekacraft** [MehVahdJukaar/WoodGood#454]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.35

### Moonlight Lib Version

moonlight-1.20-2.11.1-forge

### Issue with mods

furnish-26-forge
TerraFirmaCraft-Forge-1.20.1-3.1.9
(ArborFirmaCraft)afc-1.0.7-1.20.1 

### Issue Detail

Furnish have crates that act like shulker boxes, it should retain its content when broken. 
AFC/TFC furnish EC crates voids items inside when broken in survival (only empty crate dropped), tried to break with correct tool (axe), same problem exists. However, it works as intended in creative, crates with contents drop just like shulker boxes.

**Comment by Xelbayria** [comment]
let me check this on my side. 

EDIT: try with the latest **Moonlight Lib** v2.11.2 

EDIT 2: can confirm the bug.
