### ISSUE TITLE
[📦]: Totemic

### ISSUE THREAD

**Issue by NickIsCool45** [MehVahdJukaar/WoodGood#457]
# REASON: 

**Totemic is capable of adding woodTypes from other wood mods. Take a look at `~/.minecraft/config/totemic-common.toml`. It will explain everything.** 

### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/totemic

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

totemic

### Types

**Block:**
- Totem Base
- Totem Pole

### Optional Details

Totem Poles have multiple variants(Same item id however) and apply effects to the player. They are also import to the mod's magic system.

**Comment by NickIsCool45** [comment]
note that they have an woodType registry system that just requires the mapColors of a normal and stripped log, and a tag that contains the log variants(log, stripped log, wood, stripped wood)

**Comment by Xelbayria** [comment]
It's abandoned. It's not necessary to add it to Every Compat. You can add woodTypes from other wood mods. 
Go to `~/.minecraft/config/totemic-common.toml`, it will explain everything.

**Comment by NickIsCool45** [comment]
yep, this post was made before totemic added config support

**Comment by Xelbayria** [comment]
I see. Thanks for the suggestion, tho.
