### ISSUE TITLE
[🐞]: Block tags are missing for Macaw's Trapdoors

### ISSUE THREAD

**Issue by cyyynthia** [MehVahdJukaar/WoodGood#458]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.35

### Moonlight Lib Version

moonlight-1.20-2.11.4-forge

### Issue with mods

Macaw's Trapdoors, version 1.1.2-mc1.20.1forge

### Issue Detail

Trapdoors introduced by Macaw's mod have a tag per style. Variants added by Every Compat don't have this tag. All styles are affected.

Note: the waffle trapdoor doesn't have a tag to begin with. I've reported this to the mod author, but in the meantime I guess there are no tags Every Compat needs to add for this specific one.

**Comment by Xelbayria** [comment]
i'll look in this. 

EDIT: 
you are correct, it missed one tag. I fixed this. It will be in next version.
