### ISSUE TITLE
[Feature] Immersive Engineering support

### ISSUE THREAD

**Issue by brnbrd** [MehVahdJukaar/WoodGood#46]
Right now Every Compat does not recognize "Treated Wood Planks" as a wood type (because it does not have a log). It would be nice to get the plank variant items that do not involve logs to generate.

**Comment by MehVahdJukaar** [comment]
Does that wood already add all its relevant vanilla blocks?

**Comment by Xelbayria** [comment]
is this issue solved? If yes, then please close this

**Comment by Xelbayria** [comment]
Closing this because of no replying
