### ISSUE TITLE
[🐞]: Furnish Bookshelf Chest Error

### ISSUE THREAD

**Issue by WordStormRose** [MehVahdJukaar/WoodGood#462]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.36

### Moonlight Lib Version

moonlight-1.20-2.11.4-forge

### Issue with mods

Furnish - furnish-26-forge

### Issue Detail

The compat versions of Furnish's bookshelf chests don't seem to be functioning properly; the names are things like "block.everycomp.fur.quark.azalea_bookshelf_chest" rather than "Azalea Bookshelf Chest", and when they're placed they have the black-and-purple missing texture texture. As far as I know it's this way with all of the non-vanilla-wood Furnish bookshelf chests, but I've only actually seen it with Quark, Biomes O' Plenty, and Ecologics, since those are the ones in the modpack I'm putting together.

**Comment by Xelbayria** [comment]
will look in this.

EDIT: 
fixed.
