### ISSUE TITLE
The specialty Doors are broken

### ISSUE THREAD

**Issue by Kaisha1730** [MehVahdJukaar/WoodGood#463]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Fabric

### EveryCompat Version

1.20.1-.24v-fabric

### Moonlight Lib Version

Unsure in a modpack

### Issue with mods

Um wood good has an issue with the special wood doors

### Issue Detail

Well, when i or someone else on my survival server tries to break any of the doors, glass, wooden, any of the special looking doors, like over grown, or the glass door or the paper-oak door, etc ive tried like five different types. They just disappear, they break like how glass would without a silk touch tool and just breaks without dropping anything.
 I dont know if its supposed to do that but its very frustrating definitely when its a survival world and doors often get moved. Theres no issues making, placing or opening then its just breaking. 
 plus, when i hover my cross-hair over the doors it tells me that i can in fact be broken with an axe wooden and above. I know some mods dont show anything if it doesn't completely match with the item show mod or whatever its called. 
 P.S im not upset, or annoyed i just wanted to report it in case it was infact a bug. I made it work with what i got since it wasnt game ending. Thank you!

### OPTIONAL: To Produce

1) place block literally anywhere
2) break block
3) it goes caploey, doesnt drop the door we once had infront of us. Bug is here.

**Comment by Xelbayria** [comment]
I need to know which mod. is it Macaw's Door?

& please include the version of **Moonlight Lib**, a full version of **Every Compat**

**Comment by Kaisha1730** [comment]
@Xelbayria 

It is chipped and im guessing for moonlight lib as i said curse forge doesn't show the list of mods used in a modpack like better mc, if it does i dont know where. But moonlight-1.20-2.8.81-fabric.jar

**Comment by Xelbayria** [comment]
> @Xelbayria
> 
> It is chipped and im guessing for moonlight lib as i said curse forge doesn't show the list of mods used in a modpack like better mc, if it does i dont know where. But moonlight-1.20-2.8.81-fabric.jar

Wow.  that **Moonlight Lib** version is way outdated.   the latest is `1.20-2.11.9`. Please update it and check to see whether the issue persists or not. 

EDIT: 
Just checking, you are using Curseforge App from Overwolf, correct? you should be able to see the list of mods via a modpack. IIRC, simply right-click the Icon or click 3 dots at the bottom, right side of the modpack's screen. 

i haven't used Curseforge app since i went to a different app.

**Comment by Xelbayria** [comment]
I've investigated in **Chipped** module via **Every Compat**, and found it's not finished. I'll finish it so the door will be dropped
