### ISSUE TITLE
[🐞]: Architects Palette Twisted Wood doesn't work for the boards in abnormals woodworks

### ISSUE THREAD

**Issue by Derpgamer22** [MehVahdJukaar/WoodGood#464]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2

### Loader

Forge

### EveryCompat Version

2.5.19

### Moonlight Lib Version

2.3.6

### Issue with mods

Woodworks 2.2.2
Architect's Palette 1.3.5

### Issue Detail

the twisted wood from architect's palette does not work with abnormal woodworks boards... I think it may be due to possibly twisted wood having boards in architect's palette... and maybe it like is stopping it from having one for the woodworks boards... but I am not to sure

**Comment by Derpgamer22** [comment]
I would say that I could probs be fixed if maybe the block was added manually or like how blocks with custom textures in Every Compat works

not too sure though

**Comment by Xelbayria** [comment]
Don't worry about this. I already started work on this fix for the texture issue. like 2 days ago. 

EDIT: 
FYI, some mods have texture problems with EveryCompat. 1.20.1 also has this problem, too. However, it's fixed. I'm just porting the fixes from 1.20.1 to 1.19.2

<strike>
Also, you don't need to re-create the issue.. it's fine to add more information to the current issue.   you haven't answered my question. which mods are the wood variants from? 
BOP? The Twilight Forest??? or...
</strike> 
I see you already answered my question, nvm

**Comment by Derpgamer22** [comment]
omg thanks.. that is good to here.. Ill shut down the one in the discord server then :p

**Comment by Xelbayria** [comment]
ok i see it. keep this in mind. Just create one issue on GitHub. & be patient. that's all. U just need to be patient for the replying. I'm quite busy with fixing bugs and this bug. it's endless! I'll look into this problem. I'll close the other issue and keep this issue open for further discussion

EDIT: 
related to:  #277

**Comment by Derpgamer22** [comment]
oh yes i created another as that one was a while ago.. my bad :p

**Comment by Derpgamer22** [comment]
take your time.. ur fine :]

**Comment by Xelbayria** [comment]
🤦   good news. This will be fixed in the next version: **v2.5.23**. there was a typo in the code that should have check whether Woodworks and Architect's Palette is loaded.   but it was always returned false, so these blocks you reported will not be added.
