### ISSUE TITLE
[🐞]: canopy stairs twilight forest and woodworks

### ISSUE THREAD

**Issue by Aceplante** [MehVahdJukaar/WoodGood#466]
### Version

1.18.2

### Loader

Forge

### EveryCompat Version

latest

### Moonlight Lib Version

latest?

### Issue with mods

Twilight forest

### Issue Detail

Notice the lack of woodworks tab
![staaaa](https://github.com/MehVahdJukaar/WoodGood/assets/101857505/6040648d-ab3f-4336-b284-f1381702a96a)

**Comment by Aceplante** [comment]
[canopy_plank_sawing.json](https://github.com/MehVahdJukaar/WoodGood/files/14670096/canopy_plank_sawing.json)
[canopy_log_sawing.json](https://github.com/MehVahdJukaar/WoodGood/files/14670097/canopy_log_sawing.json)

added fixed files

**Comment by MehVahdJukaar** [comment]
this has nothing to do with every compat. That recipe type is NOT added by EC and neither are those stair blocks

**Comment by Xelbayria** [comment]
oh, i remember I haven't fixed my mistake in 1.18.2 for **woodworks**. I'll check

**Comment by Xelbayria** [comment]
i indeed forgot to fix the mistake in 1.18.2 via **Woodworks** module. It will be in next version.
