### ISSUE TITLE
[🐞]: Crash at start - incompatibility with Exline Bark Carpets mod

### ISSUE THREAD

**Issue by serioos** [MehVahdJukaar/WoodGood#470]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Fabric

### EveryCompat Version

everycomp-1.20-2.6.39-fabric

### Moonlight Lib Version

moonlight-1.20-2.11.9-fabric

### Issue with mods

The game crashes when I press start with this crash log. I think it's trying to generate recipes for Exline Bark Carpet mod and it's not defined? Here's the crash log:

https://pastebin.com/zd3zxywU

### Issue Detail

The game crashes when I install wood comp mod, and looking in the crash log, I think it's because of incompatibility with Exline Bark Carpet mod.

### OPTIONAL: Latest.log | Crash-report Attachment

[crash-2024-03-26_13.53.15-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/14756936/crash-2024-03-26_13.53.15-client.txt)

**Comment by Xelbayria** [comment]
Fixed.
