### ISSUE TITLE
[🐞]: builder's delight compat crash on startup

### ISSUE THREAD

**Issue by superdude808** [MehVahdJukaar/WoodGood#474]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

1.20-2.6.40

### Moonlight Lib Version

1.20-2.11.9

### Issue with mods

BuildersDelight-1.20.1-v.1.3

### Issue Detail

So Builder's removed several things in a recent update which is causing Every Compat to fail when loading because it is looking for items and code that are no longer there.

Specifically it is looking for BdFurnitureKit.class which was removed in this commit [https://github.com/Tynoxs/BuildersDelight/commit/8563fba46ec180542df688394e6a00606a7394f0](url)

now I know this update to Builder's Delight was very recent so I'm in no way expecting Every Compat to update right this second
but since this is preventing the game from running at all I thought you should know

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/14812637/latest.log)
[crash-2024-03-31_00.04.39-fml.txt](https://github.com/MehVahdJukaar/WoodGood/files/14812639/crash-2024-03-31_00.04.39-fml.txt)

**Comment by Xelbayria** [comment]
Can you provide the correct link to the commit via `BdFurnitureKit.class` being removed. I tried that link and it leads to nowhere. 

for now, you should downgrade Builder's Delight to the previous version which is working fine with Every Compat


EDIT: 
nvm. i found the commit and will update EveryComp for the newer version of Builder's Delight (FORGE)

**Comment by Xelbayria** [comment]
It's not much work to update EveryCompat for Builder's Delight (FORGE). it's finished and will be in the next version. Thanks for the report. 
I recommend you to stick with **Builders Delight (FORGE) v1.2** for now.  When will the new version of EveryCompat be out is ***unknown***.

**Comment by superdude808** [comment]
oh sorry turns out github screws with links and thinks they reference the damn issues section of the repository the comment was posted in

will just need to copy past the url in a new tab https://github.com/Tynoxs/BuildersDelight/commit/8563fba46ec180542df688394e6a00606a7394f0

wow so now posting the url works

**Comment by Xelbayria** [comment]
yea. no worries. I've tried the link before. idk why github behaved like that with the links

**Comment by xAlicatt** [comment]
Updated to 2.6.41 today and this is still happening.

**Comment by Xelbayria** [comment]
The version will be in the next version. beside that, i haven't closed this because It's work in progress

EDIT:
will be in v2.6.42
