### ISSUE TITLE
[🐞]: Most recent update breaks support for Farmer's Delight [Fabric] version

### ISSUE THREAD

**Issue by SafTheLamb** [MehVahdJukaar/WoodGood#475]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Fabric

### EveryCompat Version

1.20-2.6.40

### Moonlight Lib Version

1.20-2.11.9-Fabric

### Issue with mods

Farmer's Delight [Fabric]

### Issue Detail

Changelog lists adding support for your Farmer's Delight Refabricated, but this also breaks support for the existing fabric port of the mod, due to a version difference.

**Comment by MehVahdJukaar** [comment]
Yeah EC now has a shared common module that works with both forge and fabric version at the same time. Old addon will work with ec but won't have any integration

**Comment by Xelbayria** [comment]
you have 2 opinions: 
1) use old EC (should be **v2.6.39** to work with old **Farmer's Delight (FABRIC)** and it will work with other add-ons. You'll have to be patient for someone else to update the other add-ons. 

2) give up the addons and use the new **Farmer's Delight refabricated** with the latest EC. Again, you'll have to be patient for the add-ons

I'll be closing this.
