### ISSUE TITLE
[🐞]: Dynmap Blockscan unable to scan blocks registered by Every Compat

### ISSUE THREAD

**Issue by OrangeSniper** [MehVahdJukaar/WoodGood#476]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

1.20-2.6.41

### Moonlight Lib Version

forge_1.20-2.11.9

### Issue with mods

Dynmap Blockscan

### Issue Detail

When Dynmap Blockscan scans blocks, it does not scan blocks registered by Every Compat.

**Comment by OrangeSniper** [comment]
![2024-03-31_18 16 35](https://github.com/MehVahdJukaar/WoodGood/assets/51276538/71fed76f-da47-4e3f-8934-df434696330b)
![dynmap](https://github.com/MehVahdJukaar/WoodGood/assets/51276538/7bb9fdc9-d048-4d32-8878-93efeb930113)

**Comment by MehVahdJukaar** [comment]
nothing we can do. They would have to add some integration on their end
