### ISSUE TITLE
[🗃]: Quark Hedge Recipe Support for Botany Pots

### ISSUE THREAD

**Issue by CarJem** [MehVahdJukaar/WoodGood#479]
### Version

13.0.26

### Curseforge

https://www.curseforge.com/minecraft/mc-mods/botany-pots/files/5219190

### Details

Botany Pots 13.0.26 has added new recipes for several mods, especially the quark hedges to obtain leaves from their respective hedge variant. EveryCompat/Wood Good adds these blocks, but not the Botany Pots recipes. Be nice to have them so we can automate all the leaves from other mods that this mod supports.
![image](https://github.com/MehVahdJukaar/WoodGood/assets/18092668/3bf2040d-ca50-406f-b953-a8bd1ba17581)

**Comment by Xelbayria** [comment]
EC doesn't support Botany Pots, but it does support Quark. I'll take a look at the recipe to understand the system
