### ISSUE TITLE
[🐞]: Crash on startup with JAOPCA installed

### ISSUE THREAD

**Issue by Crackomint** [MehVahdJukaar/WoodGood#480]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.42

### Moonlight Lib Version

moonlight-1.20-2.11.9-forge

### Issue with mods

JAOPCA-1.20.1-4.4.10.15

### Issue Detail

Crashes on startup with an error: §7java.lang.UnsupportedOperationException: Base block cant be null
I apologize if the issue is with the other mod. Since I do not know which mod is the problem, I am making an issue on both mods.

### OPTIONAL: Latest.log | Crash-report Attachment

[crash-2024-04-05_16.25.05-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/14891069/crash-2024-04-05_16.25.05-client.txt)
[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/14891078/latest.log)

**Comment by Xelbayria** [comment]
what's the full name of **JAOPCA**?

**Comment by Crackomint** [comment]
Just A Ore Processing Compatibility Attempt
I apologize for using the acronym, it's found in Curseforge as JAOPCA and the full name is only used in the description.

**Comment by Xelbayria** [comment]
No worries. I am somewhat familiar with that JAOPCA, but can't remember the full name.  IIRC, it doesn't have any wood variants, right? I'll take a look at the curseforge's page

**Comment by Xelbayria** [comment]
try to disable **Quark** and see if the crash is solved. FYI, **JAOPCA** is not supported by **EveryCompat**. but **Quark** is.

EDIT:
did you modify the configuration of **Quark** so some blocks are not available via Minecraft?

**Comment by Crackomint** [comment]
Disabling Quark allows the game to load. Quark and Every Compat work fine, Every Compat and JAOPCA work fine, the combination of all three crashes. I'm sorry I didn't notice this before.

The only edits I made to Quark's config were to disable Limestone (overlaps with Create) and Monster Boxes (sort of overlaps with Apotheosis). However, re-enabling them did not stop the game from crashing.

**Comment by Xelbayria** [comment]
I can replicate a combination of 3 mods causing the crash. I've seen a combination of 4 mods that caused the crash. To the present day, it's not solved. I have no clue what caused the crash. Unfortunately, I have no idea what caused the crash above. 
that is very rare.

**Comment by Xelbayria** [comment]
a bit more information. from what I learned so far, JAOPCA supports Quark and has dynamic data generation. Where it adds the dust from other mods to the system. u get the idea. 

My best guess is the order of mods being loaded is like this: 
1) JAOPCA loaded
2) EveryComp loaded. 
3) Quark loaded

note that EveryComp should be last after Quark or other mods so it can get other blocks from these mods. that may be the cause of the crash.

**Comment by mxnmnm** [comment]
This issue didn't happen with older versions of everycomp tho so some change in 2.6.42 broke things

**Comment by Xelbayria** [comment]
I see. that's a useful info.

**Comment by mxnmnm** [comment]
It has been fixed with everycomp-1.20-2.6.45
