### ISSUE TITLE
[🐞]: MCW Bridges 3.0.0 breaks things

### ISSUE THREAD

**Issue by brisingraerowing** [MehVahdJukaar/WoodGood#484]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2

### Loader

Forge

### EveryCompat Version

2.5.19

### Moonlight Lib Version

2.3.6

### Issue with mods

Macaw's Bridges - 3.0.0

### Issue Detail

MCW Bridges 3.0.0 does a major refactoring, breaking this mod.

**Comment by f0kx** [comment]
Crashing on my side too

**Comment by Xelbayria** [comment]
don't worry about this. i am aware of this new update of Macaw's Bridge. I'm updating EveryComp to support Macaw's Bridge

for now. just downgrade Macaw's bridge to previous version. 

On another note: 
The update also applied to 1.18.2 to 1.20.1. of course. i already finished 1.20.1 and will be working on 1.19.2 and then 1.18.2

TASK
- [x] 1.20.1 - Need fixes on rope_bridges via which wood mods? UPDATED: fixed
- [x] 1.19.2
- [x] 1.18.2

**Comment by f0kx** [comment]
thank you Mr/Mrs <3

**Comment by Xelbayria** [comment]
> thank you Mr/Mrs <3

just call me Xel, and np!

**Comment by Xelbayria** [comment]
Update: 
1.19.2 is finished. and i'll try to get a few more things finished for 1.19.2 so I can upload the newer version to Curseforge.

**Comment by Xelbayria** [comment]
The 1.19.2 version is uploaded to Curseforge. Just wait for it to get approved.

**Comment by PadderFance** [comment]
The 1.20.1 Version of the update needs a fix. Blocks with the id "rope_WOODTYPE_bridge" missing its texture when placed in the world.
![2024-04-08_07 47 49](https://github.com/MehVahdJukaar/WoodGood/assets/69709733/23969ca1-b192-4153-b716-6ed5dc6a4185)

**Comment by Xelbayria** [comment]
> The 1.20.1 Version of the update needs a fix. Blocks with the id "rope_WOODTYPE_bridge" missing its texture when placed in the world. 

I need to know which wood mod is it from?

**Comment by PadderFance** [comment]
Oh excuse me. Using Biomes O' Plenty and Macaws Bridges 3.0.0

**Comment by Xelbayria** [comment]
Thanks for replying and now that's interesting. BOP 🤔 

UPDATE: 
I've checked Macaw's Bridge 3.0.0 with BOP's latest version. I had no problem. 
AND i'll need your `latest.log`, so I can take a look to see why the textures are missing.

**Comment by PadderFance** [comment]
Latest-Log: https://mclo.gs/8VTJoYQ
Activated Mods:
- MCW Bridges
- Biomes O' Plenty (with Terrablender)
- Every Compat (with Moonlight Lib)

**Comment by Xelbayria** [comment]
Thank you. I'll look in this. 

### UPDATE:
Dang. I found the problem. The fix will be in the next version. 

Now the new version of 1.20.1 is just awaiting approval.

**Comment by PadderFance** [comment]
New Version is online. I approve that this bug is fixed. Thank you
