### ISSUE TITLE
[🐞]: crash with latest update

### ISSUE THREAD

**Issue by Thunderrock424242** [MehVahdJukaar/WoodGood#485]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

1.20.1 2.6.43

### Moonlight Lib Version

2.11.9

### Issue with mods

i don't know it just crashes

### Issue Detail

when i launch my modpack it loads then says error mod loading then it crashes if I disable the mod it works fine

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/14894210/latest.log)

**Comment by MehVahdJukaar** [comment]
you are not sing latest version

**Comment by Thunderrock424242** [comment]
At the time there was no latest update yet

**Comment by Xelbayria** [comment]
I've checked the latest.log,  the version of **Moonlight lib** & **EveryComp** are latest. I am not sure why crash happened. If you could take the time to investigate to find which mods is the culprit aside **EveryComp** that could cause the crash. 

The latest.log generated crash report. please provide that crash report, it's in Crash-report folder via `~/.minecraft/crash-reports/`

**Comment by Rick-300** [comment]
Possible confirmation?
[crash.txt](https://github.com/MehVahdJukaar/WoodGood/files/14897627/crash.txt)

**Comment by Xelbayria** [comment]
@Rick-300 
it's **Macaw's Bridge**, You need to update it to v3.0.0. **EveryCompat** v2.6.44 no longer support the older version of **Macaw's Bridge** - it's because the class name has changed.

**Comment by Xelbayria** [comment]
@Thunderrock424242 
did you update the mods to the latest version and have no problem?

**Comment by Thunderrock424242** [comment]
> @Thunderrock424242 
> 
> did you update the mods to the latest version and have no problem? 

@Xelbayria i thought you said it was fixed is someone else having this issue or something

**Comment by Xelbayria** [comment]
I'm asking you because you are the one who created this issue. that "someone" - **Rick-300** should have solved the problem with my explanation. above.

**Comment by Thunderrock424242** [comment]
> I'm asking you because you are the one who created this issue. that "someone" - **Rick-300** should have solved the problem with my explanation. above. 
> 
> 

???? I created this issue @Xelbayria

**Comment by Thunderrock424242** [comment]
I think you @ the wrong person

**Comment by Xelbayria** [comment]
I'm talking about **Rick-300**'s message
> Possible confirmation?
crash.txt

Don't worry about it. Anyway, I'll assume this issue is solved. and I'm talking about the first post above as u are the OP
