### ISSUE TITLE
[🐞]: Crashes when scrolling EMI

### ISSUE THREAD

**Issue by QwertRvg** [MehVahdJukaar/WoodGood#487]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

1.20-2.6.45

### Moonlight Lib Version

1.20-2.11.9

### Issue with mods

all the mods it supports (it seems)

### Issue Detail

When having Every Compat and at least supported mod installed, the game instantly crashes when opening then inventory and scrolling through the EMI menu.

### OPTIONAL: Latest.log | Crash-report Attachment

![image](https://github.com/MehVahdJukaar/WoodGood/assets/89683173/829a2009-7a53-4922-9b31-505ff942b98c)
[crash-2024-04-08_15.22.34-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/14906011/crash-2024-04-08_15.22.34-client.txt)

### OPTIONAL: To Produce

download Every Compat
download a supported mod (i.e. Macaw's Doors, Furnish)
download EMI
open the game
open the inventory
scroll while the mouse is in the EMI menu (on the right)

**Comment by MehVahdJukaar** [comment]
Remove EC. You don't need it. It registered 0 blocks

**Comment by QwertRvg** [comment]
Oh, so it crashed because it wasn't necessary then? Should I wait till it actually creates new blocks?

**Comment by Xelbayria** [comment]
he's right. you don't need it. because you have no wood mods (Biomes O' plenty or TwilightForest). 
That's why it's registering 0 blocks (meaning no new blocks). with that, it can cause EMI to be confused and crash about why is there 0 blocks.

**Comment by QwertRvg** [comment]
thanks a lot!
