### ISSUE TITLE
[🐞]: Crafting tables recipes dupe with "More Crafting Tables for Forge!"

### ISSUE THREAD

**Issue by MikroChris** [MehVahdJukaar/WoodGood#490]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [x] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.49

### Moonlight Lib Version

moonlight-1.20-2.11.11-forge

### Issue with mods

Biomes O' Plenty and More Crafting Tables for Forge!

### Issue Detail

When installed with More Crafting Tables for Forge!, the crafting tables from the mod duplicate
Seems like it creates another recipe with another texture from the crafting tables from the mod
I have 2 crafting tables from the wood of Biomes O' plenty, but one is from the mod "More Crafting Tables for Forge!" and the other one is from "Every Compact", like shown in the image below (I have 2 crating recepies for the "Jacaranda crafting table")

![image](https://github.com/MehVahdJukaar/WoodGood/assets/136250376/843542f5-95d5-4bc1-a498-7ced1031adb8)

**Comment by MehVahdJukaar** [comment]
press f3+h, hover over that EC table and send a screenshot

**Comment by MikroChris** [comment]
![image](https://github.com/MehVahdJukaar/WoodGood/assets/136250376/45052fc5-8d75-447c-8692-27f62d210411)

**Comment by Xelbayria** [comment]
Can you check if other WoodTypes from BOP (BIomes O' Plenty) have the duplicated recipe, too? 

EDIT: 
this may be why: 

> Supports Biomes O' Plenty undefined on all versions

from the description via **More Crafting Table for Forge!**'s

**Comment by MikroChris** [comment]
Yes it is with all of the wood types

**Comment by Xelbayria** [comment]
The mod, **More Crafting Tables for Forge!** have supported a few mods including BOP.  so It's fixed.
