### ISSUE TITLE
[🐞]: Not working with Backpacked and Hearth&Home 

### ISSUE THREAD

**Issue by tamlighter** [MehVahdJukaar/WoodGood#491]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2

### Loader

Fabric

### EveryCompat Version

2.5.21

### Moonlight Lib Version

2.3.5

### Issue with mods

Integration doesn't work with Backpacked and Hearth&Home) The mod does not recognize Parquet, Shelves, Trims, etc.

### Issue Detail

-

**Comment by MehVahdJukaar** [comment]
Might be that those modules were only added in the newest version

**Comment by tamlighter** [comment]
ok, thanks for the answer)
