### ISSUE TITLE
[📦]: Framed Blocks compat

### ISSUE THREAD

**Issue by DMNerd** [MehVahdJukaar/WoodGood#492]
# REASON: 

It doesn't have wood variants. 

---

### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/framedblocks

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

framedblocks

### Types

Framed blocks allowing for other textures

### Optional Details

Adding framed versions of blocks would allow for infinite customizability and possibly les module requests allowing for efficient use of time for development

**Comment by Xelbayria** [comment]
Reason: No wood variant
