### ISSUE TITLE
[🐞]: Incompatibility with JAOPCA, Kotlin for Forge and Shutters

### ISSUE THREAD

**Issue by medsal15** [MehVahdJukaar/WoodGood#494]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

1.20-2.6.51

### Moonlight Lib Version

2.11.12

### Issue with mods

- JAOPCA (4.4.10.15)
- Kotlin for Forge (4.10.0-all)
- Shutters (2.0.0)

### Issue Detail

Using all 3 mods, with Wood Good and Moonlight, will crash the game on launch.

### OPTIONAL: Latest.log | Crash-report Attachment

[Crash report](https://mclo.gs/dHLGtPp)

**Comment by MaxWasUnavailable** [comment]
Same issue as these reports:
- https://github.com/MehVahdJukaar/WoodGood/issues/473
- https://github.com/MehVahdJukaar/WoodGood/issues/489

**Comment by Xelbayria** [comment]
Just checking, is this still unresolved? 

EDIT:
i've looked at the crash-report. IIRC **JAOPCA** doesn't have any woodTypes. You need to add wood Mods so **EveryComp** do its job. Otherwise, if you don't have any wood mods, then you don't need **EveryComp** mod.

**Comment by Xelbayria** [comment]
Haven't heard from you for a while. Is the issue resolved?

**Comment by medsal15** [comment]
Seems to be resolved
