### ISSUE TITLE
[📦]: Oreberries Replanted

### ISSUE THREAD

**Issue by DMNerd** [MehVahdJukaar/WoodGood#497]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/oreberries-replanted

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

oreberriesreplanted

### Types

**Block:**
- ex: Vat

### Optional Details

Oreberries adds vats for squeezing the oreberries

**Comment by Xelbayria** [comment]
- Added to v2.6.75 (1.20.1)
- Added to v2.5.29 (1.19.2)
- Added to v1.6.17 (1.18.2)
