### ISSUE TITLE
Cache

### ISSUE THREAD

**Issue by MehVahdJukaar** [MehVahdJukaar/WoodGood#50]
Add an option to cache the assets generated

**Comment by Xelbayria** [comment]
Is it added to Every Compat or not yet?

**Comment by MehVahdJukaar** [comment]
its not. I think i once came to the conclusion that generating assets would take less time than a bounch of i/o calls to read them from a cache in a folde. Tho i think it pulled that out of thin air becuase i dont remmeber doig any tests

**Comment by Xelbayria** [comment]
I see. should I re-open this so this can be re-visited to see if it's been added to EC?
