### ISSUE TITLE
[📦]: Vampirism Compatibility

### ISSUE THREAD

**Issue by luxidoptera** [MehVahdJukaar/WoodGood#501]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/vampirism-become-a-vampire

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

vampirism

### Types

**Block:**
- Cursed Log/Planks/Wood/Stripped Log/Stripped Wood
- Dark Spruce Log/Planks/Wood/Stripped Log/Stripped Wood
- Cursed Door/Trapdoor
- Cursed Stairs
- Cursed Pressure Plate
- Cursed Button
- Cursed Slab
- Cursed Fence
- Cursed Fence Gate
- Dark Spruce Door/Trapdoor
- Dark Spruce Stairs
- Dark Spruce Pressure Plate
- Dark Spruce Button
- Dark Spruce Slab
- Dark Spruce Fence
- Dark Spruce Fence Gate

**Item:**
- Cursed Sign/Hanging Sign
- Cursed Boat/with Chest
- Dark Spruce Sign/Hanging Sign
- Dark Spruce Boat/with Chest

**Comment by Xelbayria** [comment]
### Why is it abandoned: 

The mod has no vanilla woodset (oak_<blockType>). Furniture mod have a few unique blocks like _oak_table_, _spruce_chair_, then Every Compat could support the furniture mod.

Vampirism doesn't have any unique block. 

---

I've checked to see if Every Compat can detect the woodType from Vampirism with a randomly picked mod: Macaw's Fences & Walls

there are no problem.
