### ISSUE TITLE
[🗃]: Chipped Module is missing Regions Unexplored's Logs on the carpenter's table

### ISSUE THREAD

**Issue by Kahzel** [MehVahdJukaar/WoodGood#502]
### Version

Every Compat 1.20-2.6.53
Chipped forge-1.20.1-3.0.6
Regions Unexplored Forge-0.5.5+1.20.1

### Curseforge

https://www.curseforge.com/minecraft/mc-mods/chipped

### Details

Chipped contains the following variants for vanilla logs (using spruce as an example): Bundled, Center Cut, Damaged, Edge Cut, Firewood, Flowering, Mixed, Nailed, Overgrown, Planked, Reinforced
![image](https://github.com/MehVahdJukaar/WoodGood/assets/16464617/88858b4d-60ee-4915-9a5e-624396e0a7ed)

As well as having the following stripped log variants: Carved, Chipped, D Sign, Edged, F Sign, I Sign, K Sign, Knotted, L Sign, Layered, Lumpy, M Sign, Patient, Reinforced, Sign, Stern, Wise
![image](https://github.com/MehVahdJukaar/WoodGood/assets/16464617/50f33160-302d-4382-a4fe-8df503c3538f)

Currently, none of Regions Unexplored's wood types are supported by this.

The IDs for these types are as follows: 

chipped:<type*>_wood_log
*type is lowercased, spaces replaced with underscores. Ex: *chipped:reinforced_spruce_log* or *chipped:stern_stripped_oak_log*

This seems that only the logs are not included, since the planks are supported by EC to be used on Chipped.

**Comment by Xelbayria** [comment]
Interesting, I'll take a look

### UPDATE:

i've checked it out. it's confirmed. The fixes will be in the next version. 
Keep this in mind, the number of blocks that will be generated by EC with Chipped is going to be a huge amount.
