### ISSUE TITLE
[🐞]: Duplicated azalea cabinet

### ISSUE THREAD

**Issue by Eggmanplant** [MehVahdJukaar/WoodGood#503]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2

### Loader

Forge

### EveryCompat Version

everycomp-1.19.2-2.5.21

### Moonlight Lib Version

moonlight-1.19.2-2.3.5-forge

### Issue with mods

Caverns & Chasms (Abnormals) - caverns_and_chasms-1.19.2-1.0.2
Farmer's Delight - FarmersDelight-1.19.2-1.2.4
Abnormals Delight - abnormals_delight-1.19.2-4.1.2

### Issue Detail

The azalea cabinets are duplicated - One is original, one is added by everycompat.

**Comment by Xelbayria** [comment]
Can I get a picture of 2 cabinets with ID included (just hover over the item to show its ID) 


### UPDATE: 
I investigated on 3 mods.  **Abnormal's Delight** have supported other wood mods like **Caverns & Chasms**. But it wasn't supported by **EveryComp (EC)**,  **EC** actually supported **Farmer's Delight**

the original one should be from **Abnormal's Delight** + **Caverns & Chasms**  &  the other is from **EC** + **Caverns & Chasms** + **Farmer's Delight**

You don't have to worry about the picture with ID. This is what I want to check. to see which mod the original Cabinet is from

Can you check to see if both Cabinet have the same recipe or not?   if not, then no need to worry about it.   If yes, then I'll apply a fix for this.

**Comment by Eggmanplant** [comment]
yes, they have the same recipe

**Comment by Eggmanplant** [comment]
other abnormals cabinets aren't duplicated

**Comment by Xelbayria** [comment]
go to `~/.minecraft/config/everycomp-wood_types.toml` and disable the cabinet from Farmer's Delight (set it to false). it will get hidden in JEI or REI.

**Comment by Eggmanplant** [comment]
yes but i have more cabinets, these from architects palette, sullys mod, cobblemon, and more. that are added by every compat

**Comment by Xelbayria** [comment]
`everycomp-wood_types.toml` has list of blockTypes from furniture/block mods.. it also has a list of woodTypes/stemTypes from wood mods. You can disable one of them or more.

**Comment by MehVahdJukaar** [comment]
abn delight needs to have cavenrs_and_chastms added to the list of mods it supports in EC

**Comment by Xelbayria** [comment]
@Eggmanplant 
<strike>Can i get the ID of duplicated cabinet, I think it's from **Farmer's Delight**, not **Abnormal's Delight**.  after al. **EC** only supported **Farmer's Delight**</strike>

nvm. it's fixed.
