### ISSUE TITLE
[📦]: L_Ender's Cataclysm support for 1.20.1

### ISSUE THREAD

**Issue by CaptConrad** [MehVahdJukaar/WoodGood#504]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/lendercataclysm

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20.1

### FORGE Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20.1

### MODID

cataclysm

### Types

Wood Type:
chorus

### Optional Details

Compatibility for this mod already exists for 1.19.2 but not for 1.20.1. Please add compatibility for 1.20.1.

**Comment by Xelbayria** [comment]
Have you checked the sound of _chorus_. if it's not "bass" sound, then it's an issue on the mod's side, not EveryComp (EC).

**Comment by CaptConrad** [comment]
That appears to be the issue since chorus wood it set to "harp" and not "base". Cataclysm dev is working on fixing the issue.

**Comment by Xelbayria** [comment]
👍  alright. with the fix for L_Ender's. EveryComp will detect the wood.
