### ISSUE TITLE
[🐞]: Many items from Blooming Nature/Create have missing texture

### ISSUE THREAD

**Issue by MbtMarco** [MehVahdJukaar/WoodGood#505]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Fabric

### EveryCompat Version

1.20-2.6.54

### Moonlight Lib Version

fabric_1.20-2.11.14

### Issue with mods

<img width="1440" alt="Screenshot 2024-05-03 alle 14 43 57" src="https://github.com/MehVahdJukaar/WoodGood/assets/124934175/705c8288-fcb4-41a4-ae87-85301a95f1c1">
<img width="1440" alt="Screenshot 2024-05-03 alle 14 44 00" src="https://github.com/MehVahdJukaar/WoodGood/assets/124934175/9aedb723-ab57-437d-b3e5-eb6e8f9b3862">
<img width="1440" alt="Screenshot 2024-05-03 alle 14 44 03" src="https://github.com/MehVahdJukaar/WoodGood/assets/124934175/c4673187-0532-44c5-8b7a-62aad53d8d53">

### Issue Detail

I didnt show every bugged item because they are many, and they are all about blooming nature mod.
https://modrinth.com/mod/lets-do-bloomingnature

**Comment by IntM4rco** [comment]
Plus, as you can see, each object is marked as part of the Create mod.

**Comment by Xelbayria** [comment]
Fixed in v2.6.58

NOTE: FORGE has the same issue.
