### ISSUE TITLE
[🗃]: Variant Crafting Tables creating duplicate crafting tables

### ISSUE THREAD

**Issue by SynfulChaot** [MehVahdJukaar/WoodGood#506]
### Version

1.20.1-2.0.2

### Curseforge

https://www.curseforge.com/minecraft/mc-mods/variant-crafting-tables

### Details

When Variant Crafting Tables is installed alongside Twilight Forest (`1.20.1-4.3.2145`), VCT adds its own variants for the Twilight Forest woods.  Every Compat also does so, which it probably doesn't need to.  Would be helpful if Every Compat could detect if there are already variants of a type before creating its own (like it does with chests).

Loader: Neoforge 1.20.1-47.1.103

**Comment by Xelbayria** [comment]
Weird. EC should have detected it and not added the Crafting Table. Will investigate

## EDIT: 
Which loader are you using (FORGE|FABRIC)

**Comment by SynfulChaot** [comment]
Neoforge 1.20.1-47.1.103

**Comment by Xelbayria** [comment]
ok it's FORGE|NEOFORGE. 

Can you confirm that you do not have this: **More Crafting Table for Forge!**, This is the only mod that **EveryComp** support
It's similar to **Variant Crafting Tables**

**Comment by SynfulChaot** [comment]
I can confirm that I am using Variant Crafting Tables and have no other mod that adds variant wood crafting tables for the vanilla woods (Blue Skies adds them only for their own woods).  I know VCT support isn't listed on Modrinth, but I noticed it in the modules.

**Comment by Xelbayria** [comment]
I found **Variant Crafting Table** codes in **EveryComp**. Will apply the fix. I need to know which Wood Mods is the duplicated block from.

**Comment by SynfulChaot** [comment]
Variant Crafting Tables itself.  It has built-in support for quite a few mods now, but not all.

**Comment by Xelbayria** [comment]
I'll be using the list of supported mods via VCT's Curseforge to exclude the duplicated blocks. 

## UPDATE: 
fixed
