### ISSUE TITLE
[🐞]: Crash with Refurbished Furniture mod

### ISSUE THREAD

**Issue by Blob336** [MehVahdJukaar/WoodGood#507]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Fabric

### EveryCompat Version

1.20-2.6.55

### Moonlight Lib Version

fabric_1.20-2.11.17

### Issue with mods

MrCrayfish's Furniture Mod: Refurbished - 1.0.0-beta.4

### Issue Detail

Ceiling fans cause a crash when placed in world.  The mod with wood types does not seem to matter.

### OPTIONAL: Latest.log | Crash-report Attachment

[crash-2024-05-05_21.38.15-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/15214136/crash-2024-05-05_21.38.15-client.txt)

**Comment by Xelbayria** [comment]
Fixed by **MehVahdJukaar**
