### ISSUE TITLE
[🐞]: Error in velocity

### ISSUE THREAD

**Issue by zoe-may** [MehVahdJukaar/WoodGood#509]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.55

### Moonlight Lib Version

moonlight-1.20-2.11.17-forge

### Issue with mods

Just everycomp

### Issue Detail

I tried to use everycomp on a downstream server in velocity, but players are unable to log in to the server. The core used by the downstream server is Mohist. After my investigation, as long as the everycomp module is added, players will be prompted with "Unable to connect you to lobby, please try again later." when attempting to connect to the server.

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/MehVahdJukaar/WoodGood/files/15244708/latest.log)
[velocity-latest.log](https://github.com/MehVahdJukaar/WoodGood/files/15244712/velocity-latest.log)

**Comment by MehVahdJukaar** [comment]
Velocity is for vanilla. Any issue you have with it has to be reported to its Devs but don't think they'll do anything as it's not meant to be used with mods. Moist especially is notoriously problematic and there shouldn't be any reason for anybody to ever use a hybrid server

**Comment by zoe-may** [comment]
> 速度适用于香草。您遇到的任何问题都必须报告给其开发人员，但不要认为他们会做任何事情，因为它不适合与模组一起使用。特别是潮湿是出了名的问题，任何人都不应该有任何理由使用混合服务器

Apologies for disturbing you, but since my other mods are all working fine, I thought I'd come and ask about this issue.

**Comment by MehVahdJukaar** [comment]
you should ask for support to velocity or mohist as this isnt an EC issue. I however recomend using neither as none of them are for mods. There shouldnt be any need for them especially mohist.
