### ISSUE TITLE
[📦]: Create: Steam 'n' Rails

### ISSUE THREAD

**Issue by Popsikul** [MehVahdJukaar/WoodGood#512]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/create-steam-n-rails

### FABRIC Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

railways

### Types

**Block:**
- Tracks (wide, narrow, normal)

**Comment by Xelbayria** [comment]
Sorry, the bad news is it's not possible to add a support the said mod. You will have to ask someone via Discord (Create: Steam N' Rails) to add support for wood mod.
