### ISSUE TITLE
[📦]: Add bamboo and cherry wood as "Modded Wood"

### ISSUE THREAD

**Issue by MrRedstoneToGo** [MehVahdJukaar/WoodGood#513]
### Question

Every Combat adds all missing woodsets from mods. I would like this to apply to vanilla wood types as well, so that various cherry and bamboo wood items are also added. I have often seen that mods have been updated to 1.20.1 and the new wood types have not been taken into account

**Comment by MehVahdJukaar** [comment]
ec could easily do it but doesn't as it's something mods themselves should do. If they don't even add vanilla stuff they aren't coded properly. To force it to do this you would need to mixin I to the mod and modify the behaviour tha checks if it's a vanilla wood. I don't even remember where that is. Probably in the main class

**Comment by Xelbayria** [comment]
is your question answered?

**Comment by MrRedstoneToGo** [comment]
If I have understood correctly, there are no plans to add the feature.
