### ISSUE TITLE
[📦]: Building But Better

### ISSUE THREAD

**Issue by Tosh022402** [MehVahdJukaar/WoodGood#514]
# ALREADY SUPPORTED IN THE MOD: 

The mod now has the built-in module that is using the API of Every Compat to support any wood mods. This is already supported. 

### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/building-but-better

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20.1

### MODID

bbb

### Types

Blocks
- Trim
- Beam
- Beam Stairs
- Beam Slab
- Support
- Frame
- Pallet
- Wall
- Lantern
- Ladder
- Layer

### Optional Details

Some blocks like Supports, Frames, Pallets, Ladders, Lanterns and Layers can be edited with a Hammer to change its design (blockstates)

**Comment by Neko2n** [comment]
absolutely need this one, bbb has some of the best textures I've seen recently

**Comment by Xelbayria** [comment]
Added to v2.6.74 BUT removed since v2.6.77. 

Why: The mod already have built-in module (Using Every Compat API) to support any wood mods.
