### ISSUE TITLE
[🐞]: Crafting recepies from new chests don't exist

### ISSUE THREAD

**Issue by MikroChris** [MehVahdJukaar/WoodGood#518]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

1.20-2.6.56

### Moonlight Lib Version

1.20-2.11.31

### Issue with mods

All the aether and aether addons, goldelight, Biomes O' Plenty, deeper and darker, etc. - Crafting recipes doesn't exist
Blue skies - Repeated chests, the mod already has its own chests recipes

### Issue Detail

Crafting recipes doesn't exist, and it dupes some of the already existing, for example the blue skies ones.

**Comment by MehVahdJukaar** [comment]
we get one of these every week 💀 
EC does NOT add custom recipes per say.
If a modded block is NOT craftable it means its base mod block (in this case probably quark chests since you didnt specify where those chests are from) is also NOT craftable

**Comment by MikroChris** [comment]
So what should I do?
I'm sorry for that, but I didn't know the recipes weren't added

**Comment by Xelbayria** [comment]
Only 4 mods add chests i know are: 
- Quark
- Woodworks
- More Chest Variants
- Variant Vanilla Blcoks

which mod is it?

**Comment by MikroChris** [comment]
The mods I have that have their own chests are these:
- Blue skies
- Better end (with connector works in forge)

The mods I have wich the Every Compat chests aren't craftable are:
- Aether, deep aether, aether gravitation, ancient aether
- Goldelight
- Unusual prehistory
- Ends phantasm

I've done a new installation using only the EC mod, MCV and the mods I mentioned and didn't work either

**Comment by Xelbayria** [comment]
Can I get the `latest.log` and will investigate on this.

**Comment by Xelbayria** [comment]
🤦 I forgot to add a code to generate recipes for MCV. it is fixed

**Comment by Xelbayria** [comment]
Fixed in https://github.com/MehVahdJukaar/WoodGood/commit/9516d71ee033bd443e4921573ccbb9a0af432791
