### ISSUE TITLE
[🐞]: Missing Chest Textures for Woodworks Chests

### ISSUE THREAD

**Issue by floralstone** [MehVahdJukaar/WoodGood#519]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.56

### Moonlight Lib Version

moonlight-1.20-2.11.31-forge

### Issue with mods

- Woodworks 3.0.1
- Ecologics 2.2.0
- Create: Diesel Generators 1.2h
- Enhanced Mushrooms 5.0.0

### Issue Detail

Latest version has broken textures for Woodworks chests in various wood types.

![image](https://file.garden/ZRYdkfKULjLI5_Og/brokenchests.png)

**Comment by floralstone** [comment]
I should add this is not an issue in 1.20-2.6.55, noticed the issue after updating, and downgrading fixed the missing textures.

**Comment by Xelbayria** [comment]
I am aware of no issue in 2.6.55 and that's because there is a small change in how the system generates textures for chests and trapped_chest. it'll be fixed in the next version.

**Comment by Xelbayria** [comment]
Fixed in https://github.com/MehVahdJukaar/WoodGood/commit/416f3fa8e3eae1b80f7a240a365663fd14a01192
