### ISSUE TITLE
[1.18.2] Allow Recipes Regardless of Quark's Settings

### ISSUE THREAD

**Issue by SaltSouls** [MehVahdJukaar/WoodGood#52]
Right now if any of the quark compatibility settings are tripped, effectively turning off quarks block variants, every compat will no longer register the recipes for the other wood types it supports. It would be nice to have a config setting much like what quark has to just ignore this and allow the mod to add the recipes regardless.

**Comment by MehVahdJukaar** [comment]
This happens because the recipe that gets added are a copy of quark JSON ones which include their conditions so they work exactly as if they were from quark

**Comment by Xelbayria** [comment]
is this issue solved? and just to check, isn't this a "question" or "feature"?

**Comment by SaltSouls** [comment]
I'm not sure if this was ever changed, and given that this is apparently how it was made to work, then my post would be a feature request to make it not work like how it currently does. That is assuming it still works the way it did back when I posted this.

**Comment by Xelbayria** [comment]
Closing this. blc 1.18.2 won't get any enhancement.
