### ISSUE TITLE
[🐞]: 1.20.1 Crashed for Rendering item with JEI

### ISSUE THREAD

**Issue by PhilTheGreatLOL** [MehVahdJukaar/WoodGood#522]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.57

### Moonlight Lib Version

moonlight-1.20-2.11.31-forge

### Issue with mods

Rubidium (rubidium), Version: 0.7.1a
Better Default Biomes (betterdefaultbiomes), Version: 5.1.0-Alpha
Just Enough Item (JEI) Version: 15.3.0.4

### Issue Detail

When I open JEI for recipe but unexpected error when I scroll down and all recipe caused error icon instead of item and then crashed for Rendering item.
[crash-2024-06-04_18.36.47-client.txt](https://github.com/user-attachments/files/15550818/crash-2024-06-04_18.36.47-client.txt)

**Comment by MehVahdJukaar** [comment]
Uninstall every compat

**Comment by Xelbayria** [comment]
One more thing: Update **Moonlight Lib**, it's outdated. You also should Update **Supplementaries**, too

That's all.

**Comment by PhilTheGreatLOL** [comment]
For sure bro.

**Comment by PhilTheGreatLOL** [comment]
![2024-06-05_01 22 22](https://github.com/MehVahdJukaar/WoodGood/assets/171683440/9955f758-065e-4664-9db4-d38fa9401f01)
When I need to see recipe but All items want to craft caused Error texture

**Comment by Xelbayria** [comment]
That's new... 🤔 I need the `latest.log` to see what's going on

**Comment by PhilTheGreatLOL** [comment]
[Uploading latest.log…]()

**Comment by PhilTheGreatLOL** [comment]
[latest.log](https://github.com/user-attachments/files/15576084/latest.log)

**Comment by MehVahdJukaar** [comment]
Apologies i thought you had a different error. All i se there is actulaly one from betterdefaultbiomes

**Comment by PhilTheGreatLOL** [comment]
Shall I uninstall every compat?

**Comment by Xelbayria** [comment]
If you don't have other wood mods like **Biomes O' Plenty** or **The Twilight Forest** so on. Then yeah you can uninstall **EveryComp**. It's meant to support wood mods with furniture mods (Macaw's series or other) which don't have addon that support other wood mods. Sometimes, furniture mods have built-in support for other wood mods, too. 

UPDATE:
betterdefaultbiomes has 2 wood types, It is quite tricky to find out what's the cause

**Comment by Xelbayria** [comment]
i think i found the cause: 

the culprit mod is **croptopia** and a leave type named "cinnamon" is what caused the problem. 

will investigate this to find out what's going on. Thanks to Crash-Report that give me a clue on who is the culprit. 

---
## UPDATE

@MehVahdJukaar 
The **croptopia** doesn't generate any leave block. Idk why **EveryComp** detected these leavesType

**Comment by MehVahdJukaar** [comment]
I see. I looked it up and the only way i see that happening is if a mod were to add a leaf block without a leaf item

**Comment by Xelbayria** [comment]
So that's why. Is there a way to exclude "cinnamon" from detection in **EveryComp**?  or does it have to be done in **Moonlight Lib**??

**Comment by MehVahdJukaar** [comment]
fix should come next update

**Comment by Xelbayria** [comment]
I ran the test with the fix applied to **EveryComp**. All is good now.
