### ISSUE TITLE
[🐞]: Missing textures for Macaw's Fences and Walls

### ISSUE THREAD

**Issue by JimBob-bb** [MehVahdJukaar/WoodGood#523]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

1.20.1 2.6.57

### Moonlight Lib Version

1.20.1 2.11.31

### Issue with mods

- Autumnity 5.0.1 and Let's do Vinery 1.4.19 and Macaw's fences and walls 1.1.1
- Autumnity and Let's do Vinery have the leaf textures
- Macaw's fences and walls has the furniture item

### Issue Detail

- The furniture item, is the hedges from ''Macaw's fences and walls''.
- The missing texture's are for the ''Autumnity'' maple leaves, of all colours, and the apple leaves from ''Let's do: Vinery''.

**Comment by Xelbayria** [comment]
Alright, This will be fixed in the next version. i know what's the problem.

**Comment by Xelbayria** [comment]
Fixed in v2.6.58
