### ISSUE TITLE
[🐞]: Chest textures look kinda broken i guess

### ISSUE THREAD

**Issue by MikroChris** [MehVahdJukaar/WoodGood#524]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

1.20-2.6.57

### Moonlight Lib Version

1.20-2.11.31

### Issue with mods

Alex caves - Pewen chest
BOP - Jacaranda chest
End's phantasm - Pream chest

### Issue Detail

Textures look weird I think, this isn't happening with all of the chests, but these in particular have that issue, here are the images
![2024-06-04_10 44 19](https://github.com/MehVahdJukaar/WoodGood/assets/136250376/46f2ca27-27d3-47e7-b6ce-229d28b40cc6)
![2024-06-04_19 08 25](https://github.com/MehVahdJukaar/WoodGood/assets/136250376/0489f315-4b7f-4a44-b187-c57eb97e8012)
![2024-06-04_19 08 59](https://github.com/MehVahdJukaar/WoodGood/assets/136250376/74a6d63b-afd7-4758-a318-73357d953b0f)
eird I think, this isn't happening with all of the chests, but these in particular have that issue, here are the images

**Comment by Xelbayria** [comment]
Crap. I think I made a mistake. This will be fixed in the next version. 

EDIT: 
you forgot to say which mod is it.  MCV or VVB (Variant Vanilla Block)? 

EDIT 2: 
nvm. It was MCV and it is fixed.
