### ISSUE TITLE
[🐞]: Failed to generate recipe for mcf

### ISSUE THREAD

**Issue by zc1108aaa** [MehVahdJukaar/WoodGood#525]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Fabric

### EveryCompat Version

1.20-2.6.57-fabric

### Moonlight Lib Version

1.20-2.11.30fabric

### Issue with mods

regions_unexplored
bewitchment
wilderwild
biomemakeover
betternether
cinderscapes

### Issue Detail

Failed to generate recipe for mcf

### OPTIONAL: Latest.log | Crash-report Attachment

[latest - 副本 (2).log](https://github.com/user-attachments/files/15738482/latest.-.2.log)

### OPTIONAL: To Produce

There is a lot of tine and moonlight in the log error

**Comment by Xelbayria** [comment]
Via `Latest.log`, **MCF** is not the only one, **C** is also having a problem, too.  MCF = Macaw's Fences & Walls | C = Create 
It looks like one of the mods is screwing up the generation of Recipe. I've tested with **Diagonal Fences** & **Diagonal Windows**. They are **NOT** the culprit. a good example is in #500 
Where **Diagonal Walls** is somehow screwing up the generation of recipes. 

Can you try and isolate one mod that caused the problem?

**Comment by Xelbayria** [comment]
Haven't heard from you? Have you looked into which one of the mods caused this problem?  or do you no longer have the issue?

**Comment by Xelbayria** [comment]
closing this blc no replying to this issue.  

You can re-open this to revisit this issue so we can find out which mod is the culprit to the failed generation of recipes.
