### ISSUE TITLE
[🐞]: 1.20.1 - Dedicated server stops working after startup

### ISSUE THREAD

**Issue by ThePegNok** [MehVahdJukaar/WoodGood#526]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.59

### Moonlight Lib Version

moonlight-1.20-2.11.33-forge

### Issue with mods

woodworks-1.20.1-3.0.1

### Issue Detail

[debug-1.log](https://github.com/user-attachments/files/15751588/debug-1.log)

**Comment by Xelbayria** [comment]
I need the `latest.log` and `crash-report` if the server crashes. 
it looks like `debug.log` is similar `latest.log` so nvm. I see what's going on. Will investigate

**Comment by Xelbayria** [comment]
Fixed in **v2.6.60**
