### ISSUE TITLE
[🐞]: chipped blocks present but unobtainable for biomes o plenty, biome makeover, better archeology (NeoForge)

### ISSUE THREAD

**Issue by ArchivesOfFae** [MehVahdJukaar/WoodGood#527]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycompat-1.20-2.6.60

### Moonlight Lib Version

moonlight-1.20-2.11.33

### Issue with mods

Biomes O' Plenty 18.0.0.598
Biome Makeover 1.11.4
Better Archeology 1.1.9
Chipped 3.0.6
NeoForge 47.1.105

### Issue Detail

The chipped variants of all of these mods' wood types are present in the creative inventory and side tab from JEI-type mods, and function as expected, but the carpenter's table does not actually have valid recipes for them.

**Comment by Xelbayria** [comment]
Try logging out of the **world** and re-log back into the **world**. This way, the recipe system with _tags_ should be loaded propertly. 

This is also a similar problem with REI, too. 

---

## FYI
tbh, I am not sure why. **Chipped Module** has a lot of blocks supported.

**Comment by ArchivesOfFae** [comment]
so if this happens in multiplayer do i just have to reboot the server until it works?

**Comment by Xelbayria** [comment]
tbh, I'm not sure. you can try to log out of the server and re-log back in to see if it makes a difference. 

rebooting the server may not make a difference. The first time, A user logged into the world, the recipe was not working. The second time, A user logged into the world, the recipe is working properly. I don't have much information regarding this. 

note: Minecraft Instance was running the whole time (**NOT** re-launched).

**Comment by ArchivesOfFae** [comment]
i feel like it may also be worth noting that all of the other recipes work fine, just not the chipped variants for these mods in particular. this pack also contains regions unexplored which is working with no issue.

**Comment by Xelbayria** [comment]
I've run tests with
- **Chipped**
- **BOP**
- **Biome Makeover**
- using either JEI or REI

There are no issues. You are not the first one who reported the issue. The issue is very similar except it doesn't involve **Better Archeology**. I also checked `latest.log` and there are no issues. 

I'll check **Better Archeology** on my side. 

---

EDIT: 
on another note: I cannot figure out why the recipe system from **Chipped** is not loaded properly when a user logged in the world for first time (via CLIENT or SERVER). I don't have much information about SERVER. but CLIENT, a user will have to re-log a second time to get the recipe system working.

**Comment by ArchivesOfFae** [comment]
i rejoined my test world and the recipes loaded properly, and we did go ahead and reboot the server to see if that would do anything. it did not, the same three mods as before are still failing to cooperate with the chipped module. i also attempted to leave the server and rejoin to see if that would help, and it did not.

**Comment by Xelbayria** [comment]
> i rejoined my test world and the recipes loaded properly, and we did go ahead and reboot the server to see if that would do anything. it did not, the same three mods as before are still failing to cooperate with the chipped module. i also attempted to leave the server and rejoin to see if that would help, and it did not.

That's not good. 🤔 

---

### UPDATE: 

I ran test with 
- Better Archeology 
- Quark
- BOP (Biomes O' Plenty) 
- BMO (Biomes Makeover)

I logged into a test world. Noticed the recipe for **Quark** + **Chipped** is loaded properly. but the other wood mods aren't loaded properly. 

---

### SUGGESTION:

If your modpack has **CraftTweaker**, then you could try run `/reload` to reload all of the recipes in the server and see if that helps. I'm investigating to see if i can find any clues. 

**UPDATE:**
I found the problem. It's not the recipe system that isn't loaded properly. it's the tags system.   I just tried `/reload` and it works! 
it loaded the recipes and also the tag system. the best part is I logged into the world (FIRST TIME). 

that's your solution, use `/reload` to load the tags and recipes properly in the server

<details>
<summary> Additional Information regarding Chipped's recipe system</summary>

FYI, The recipe via **Chipped** is unique. It uses the tag as an ingredient to craft/get a block. In **EveryComp (EC)**, there is a custom code that adds the tag to the plank and also supported blocks (from **EC**). 

- `#modID:<type>_planks`
- `#modID:<type>_logs`
so on. 

I checked when I first logged into the world to see if these blocks from **EC** and also the Wood Mod to see if they have their tag included. The tags aren't included in these blocks. The recipe system was working fine but no blocks were tagged. This is the cause of why the recipe system wasn't working properly. 

</details>

**Comment by ArchivesOfFae** [comment]
that worked! thank you

**Comment by Xelbayria** [comment]
Alright, MehVahdJukaar and I discussed about this. He investigates this. The problem is fixed. 

The real problem is the `namespace:<type_>_planks` which is not "everycomp"... it was using the wood mod's namespace like `biomesoplenty` 

that leads to tags not being loaded properly after the namespace has been initialized. 

This means you don't need to use `/reload`. U can just log into the world the first time and go craft something from **Chipped**.
