### ISSUE TITLE
[🐞]: Latest version of every compat crashes on startup

### ISSUE THREAD

**Issue by BugmanBugman** [MehVahdJukaar/WoodGood#528]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.61

### Moonlight Lib Version

moonlight-1.20-2.11.35-forge

### Issue with mods

Just itself

### Issue Detail

Just starting the game up crashes the game

### OPTIONAL: Latest.log | Crash-report Attachment

https://gist.github.com/BugmanBugman/ee12548150b070d0ddd6717215586b64

**Comment by evanbones** [comment]
Same issue here

**Comment by Xelbayria** [comment]
Downgrade to **v2.6.60** for now

**Comment by Xelbayria** [comment]
you can drag the crash-report & latest.log here. it will get uploaded so i can download and take a look

**Comment by evanbones** [comment]
Somewhere between v2.6.61 and the most recent version seems to have fixed this crash

**Comment by Xelbayria** [comment]
ok closing this. if it comes back. you can re-open this and you can use https://mclo.gs/ and share the link here. Idk what's the limit of "large file" you can paste. 

or you can drag the crash-report file here.
