### ISSUE TITLE
[🐞]: "Missing Wilds" Fallen Log Compat Refers to "Stem" as "Log", Causing Texture Errors

### ISSUE THREAD

**Issue by sheshells** [MehVahdJukaar/WoodGood#529]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.18.2

### Loader

Forge

### EveryCompat Version

everycomp-1.18.2-1.6.11.jar

### Moonlight Lib Version

selene-1.18.2-1.17.14.jar

### Issue with mods

Enhanced Mushrooms v4.0.1
Missing Wilds v1.1.0
Oh The Biomes You'll Go v1.5.1

Enhanced Mushrooms v4.0.1 requires Pollen (I'm using v1.6.1, latest as of writing)
Oh The Biomes You'll Go v1.5.1 requires TerraBlender (I'm using v1.2.0.126, latest as of writing)

### Issue Detail

The mod "Missing Wilds" includes a new form of log referred to as "Fallen Logs," which are hollow and can be crawled through, and can be made out of any logs. Every Compat attempts to add Fallen Log variants to all otherwise unsupported log types (as expected).

When installed in tandem, the items:
Fallen Brown Mushroom Log
Fallen Red Mushroom Log
**Both from "Enhanced Mushrooms"**

Fallen Bulbis Log
Fallen Imparius Log
Fallen Sythian Log
**All from "Oh The Biomes You'll Go"**

are all missing textures. It is worth noting that the items they _should_ be taking their textures from are each called "stem" in their item names, not "log", and this could be why the issue is occurring:

- [x] TASK:  "enhanced_mushrooms:brown_mushroom_stem" is incorrectly being called to as "everycomp:msw/enhanced_mushrooms/fallen_brown_mushroom_log"

- [x] TASK:  "enhanced_mushrooms:red_mushroom_stem" is incorrectly being called to as "everycomp:msw/enhanced_mushrooms/fallen_red_mushroom_log"

- [x] TASK:  "byg:bulbis_stem" is incorrectly being called to as "everycomp:msw/byg/fallen_bulbis_log"

- [x] TASK:  "byg:imparius_stem" is incorrectly being called to as "everycomp:msw/byg/fallen_imparius_log"

- [x] TASK: "byg:sythian_stem" is incorrectly being called to as "everycomp:msw/byg/fallen_sythian_log"

![2024-06-14_19 27 31](https://github.com/MehVahdJukaar/WoodGood/assets/156608496/5aae9386-132a-4756-87e5-e0b0cb65fd0f)

Hope this is enough information!

**Comment by Xelbayria** [comment]
What a piece of great information. I'll investigate.

**Comment by Xelbayria** [comment]
I took a look at this issue and 2 things I can do
1) fix the naming of these blocks to have "Stem" instead of "Log"
2) fixing the textures will take some times. The model is using the wrong texture because of "log". it shouldn't be the case, it should be "stem" 


## UPDATE: 

Almost finished. There is one problem: `byg:imparius_stem` doesn't have stripped block.  I will have to add a check for stripped_block 

it's a way to say if the block doesn't have "stripped_block", then EveryComp will skip that block and move on to the other woodTypes.

**Comment by Xelbayria** [comment]
One more thing to add: `everycomp:msw/byg/fallen_bulbis_log` is just an ID, nothing more. what I can do is change its title which are displayed as "Fallen Bulbis Log" to "Fallen Bulbis Stem".

**Comment by Xelbayria** [comment]
Alright, I'll be uploading the new version to Curseforge and it will take a while for it to get approval
