### ISSUE TITLE
[❔]: Guide on how to use the API

### ISSUE THREAD

**Issue by Ryhon0** [MehVahdJukaar/WoodGood#530]
### Question

The FAQ mentions an API modders can use to generate the assets, however there is no guide or wiki explaining how to use it

**Comment by MehVahdJukaar** [comment]
It's explained in the java docs of EveryCompatAPI class

**Comment by Ryhon0** [comment]
Thanks. I still need to know how to add it to a project. It would be useful if all this information was all in one place

**Comment by MehVahdJukaar** [comment]
well you add it like any other project, you can use curse maven and add modImplementation

**Comment by Ryhon0** [comment]
To whoever is interested, this is how you add it:
```
// build.gradle
repositories {
        maven { url "https://cursemaven.com" }
}

dependencies {
        modImplementation "curse.maven:every-compat-628539:${every_compat_version}"
	modImplementation "curse.maven:selene-499980:${moonlight_version}"
}
```
`every_compat_version` and `moonlight_version` can be found by clicking on a version on the CF files page and copying the id from the url from here:
https://www.curseforge.com/minecraft/mc-mods/every-compat/files
https://www.curseforge.com/minecraft/mc-mods/selene/files

**Comment by MehVahdJukaar** [comment]
I'll add that to the readme. If you go in files there's even a button that gives you those very same lines

**Comment by Xelbayria** [comment]
I'll be closing this assuming your question is answered.
