### ISSUE TITLE
[🐞]: Trouble crafting with vanilla chest into varied drawers

### ISSUE THREAD

**Issue by Appleson3** [MehVahdJukaar/WoodGood#531]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.61

### Moonlight Lib Version

moonlight-1.20-2.11.37-forge

### Issue with mods

<strike>n/a</strike> Storage Drawers

### Issue Detail

Hey, I'm experiencing an issue with converting normal chests into varied drawers...

For an example I want to turn a normal vanilla unvaried chest into a mahogany chest but the recipe only allows for a mahogany chest, is there a way to convert vanilla chests to the "everycomp" format?

### OPTIONAL: To Produce

Try to craft a mahogany drawer either with slabs or with blocks with a vanilla chest instead of a mahogany chest and it doesn't work.
But when using vanilla varied recipes, it accepts the vanilla chest

**Comment by Xelbayria** [comment]
I need to know which mod is the _mahongany drawer_ from. My best guess is **Storage Drawers**

**Comment by Appleson3** [comment]
Sorry about that, yes it was storage drawers.

**Comment by Xelbayria** [comment]
Thanks for replying, I'll check.

**Comment by Xelbayria** [comment]
Looks like there is some missing informations. It need to be answered. 
you said "Mahogany Chest".   Isn't that from **Woodworks** or **Quark**?  They both support _chest_ & _trapped_chest_

it's normal for **Storage Drawers** to not use a variant chest as an ingredient. If you want to do this, you'll need to use CraftTweaker or KubeJS to accomplish this. 

**Quark** has a configuration where you can turn varied _chests_ into vanilla chests. but not the other way. 

I tried your reproduction step and cannot replicate it. so I had no problem.

**Comment by Xelbayria** [comment]
Haven't heard from you for a while. I'll closed this for now. You can re-open this if the issue persists.
