### ISSUE TITLE
[🐞]: Duplicate Farmer's Delight cabinets with wood types from Nature's Spirit when Nature's Delight is installed

### ISSUE THREAD

**Issue by rmnvgr** [MehVahdJukaar/WoodGood#533]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Fabric

### EveryCompat Version

everycompat-1.20-2.6.61

### Moonlight Lib Version

moonlight-fabric_1.20-2.11.41

### Issue with mods

- [Nature's Spirit](https://modrinth.com/mod/natures-spirit) 1.5.3-1.20.1 - (WOOD MOD) 
- [Nature's Delight](https://modrinth.com/mod/natures-delight) 1.2 - (ADDON) 
- [Farmer's Delight Refabricated](https://modrinth.com/mod/farmers-delight-refabricated) 1.20.1-2.1.1 - (FURNITURE MOD) 

### Issue Detail

When using Every Compat with Nature's Spirit and Nature's Delight (which adds compatibility between Nature's Spirit and Farmer's Delight Refabricated), Farmer's Delight wood cabinets already added by Nature's Delight from Nature's Spirit wood types are also added by Every Compat, leading to duplicates.

Given that Nature's Delight is developed by Nature's Spirit developer, it would make sense to disable Every Compat Farmer's Delight wood cabinets from Nature's Spirit wood types when Nature's Delight is installed.

![screenshot](https://github.com/MehVahdJukaar/WoodGood/assets/66537460/bfdbe60c-9ad9-4351-9ebd-0e87bdf658a5)

**Comment by Xelbayria** [comment]
it will be fixed in the next version.

**Comment by rmnvgr** [comment]
Nice, thank you!

**Comment by Xelbayria** [comment]
Fixed in [Commit](https://github.com/MehVahdJukaar/WoodGood/commit/55641ff3bce84ae8a8fcbde4b5ed31e70c5d7536)

will be in v2.6.62
