### ISSUE TITLE
[🗃]: Chipped missing modded stripped log variants

### ISSUE THREAD

**Issue by gugbor** [MehVahdJukaar/WoodGood#534]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

1.20-2.6.61

### Moonlight Lib Version

1.20-2.11.41

### Issue with mods

Chipped-3.0.6, Quark-4.0-458, Biomesoplenty-18.0.0.598, and Alex's Caves-1.1.4. Probably all compatible mods with stripped logs

### Issue Detail

Chipped's stripped log variants do not exist for modded stripped logs.

**Comment by Xelbayria** [comment]
if I add stripped_log, then the number of blocks being added by **EveryComp** with **Chipped** will be huge. 

EDIT:
FYI, it is not a bug. it was skipped.

**Comment by Xelbayria** [comment]
Do you still want the _stripped_log_ variants?

**Comment by gugbor** [comment]
> Do you still want the _stripped_log_ variants?

Yes. Sorry that I did not know. Since it'd be such a high number of items, maybe an addon would be more fitting?

**Comment by Xelbayria** [comment]
**EveryComp** is practically an addon for furniture mods to support wood mods like Biomes O' Plenty when furniture mods don't have any addons.

**Comment by Xelbayria** [comment]
If other people request for _stripped_log_ variants to be included in EveryComp. Consider it done but for now, it won't be included.
