### ISSUE TITLE
General Suggestion

### ISSUE THREAD

**Issue by IceCubeDragon** [MehVahdJukaar/WoodGood#536]
### Question

Idea for heavy modpacks: the ability to switch from a Blacklist to a Whitelist for what's included/generated

### Optional: Details

I'm not sure if this would be possible or not/if this is even how the logic of this mod would work, but- maybe an option where everything's turned off by default and you turn things on as needed instead of the other way around might be useful on singleplayer modpacks?

**Comment by MehVahdJukaar** [comment]
The blacklist does not do anything for resources. It simply hides those items. That is true for literally any other mod. Not doing so would result in confusing registry desync errors in servers.
The solution is to either install less furniture mods or have then not fill up a complete wood set, removing EC

**Comment by Xelbayria** [comment]
If you are planning to remove **EC**. Some of the mods supported by **EC** already have addons that can support other wood mods like **Biomes O' Plenty**.
