### ISSUE TITLE
[📦]: Integrated Dynamics

### ISSUE THREAD

**Issue by luxidoptera** [MehVahdJukaar/WoodGood#537]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/integrated-dynamics

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

integrateddynamics

### Types

**Block:**
- Menril Log
- Menril Wood
- Menril Planks
- Menril Slab
- Menril Fence
- Menril Fence Gate
- Menril Stairs

**Item:**
- Menril Door

**Comment by Xelbayria** [comment]
Just a question: Is there a problem with this mod? The blockType list i see are all normal blocks seen in Minecraft? 

The name, "Menril" is a woodType. If the problem with this mod is that Every Compat cannot detect the woodType, then it need to have "bass" sound. Check the sound of _menril_log_ and if it doesn't have the sound, then it's an issue on the mod.
