### ISSUE TITLE
[🗃]: Malum Hedge and Macaw Fences and Walls

### ISSUE THREAD

**Issue by OminousDiscovery** [MehVahdJukaar/WoodGood#539]
### Version

Malum - 1.6.1, Every Compat - 2.6.63, Macaw's Fences and Walls - 1.1.2

### Curseforge

https://www.curseforge.com/minecraft/mc-mods/malum

### Details

![2024-06-24_02 16 59](https://github.com/MehVahdJukaar/WoodGood/assets/150559423/b37adc06-6348-4e8d-a11c-718d1a8cda44)
![2024-06-24_02 15 58](https://github.com/MehVahdJukaar/WoodGood/assets/150559423/fb12adb6-1dde-4345-bce3-174c604c7343)

im to lazy to explain so take some pictures

**Comment by Xelbayria** [comment]
hahaha.  no worries. you are lucky I know what's the problem. let's see the mod is **Malum**. got it. the fix will be applied in **v2.6.64**

**Comment by Xelbayria** [comment]
**Fixed in v2.6.64**
