### ISSUE TITLE
[🗃]: Valhelsia Structures Bundled Posts

### ISSUE THREAD

**Issue by Neko2n** [MehVahdJukaar/WoodGood#541]
### Version

v1.1.2

### Curseforge

https://www.curseforge.com/minecraft/mc-mods/valhelsia-structures

### Details

Valhelsia Structures added bundled wooden posts and bundled stripped wooden posts for all vanilla wood variants. It seems to be the only block from Valhelsia Structures that isn't accounted for by Every Compat.

**Comment by MehVahdJukaar** [comment]
there is not a good way to automatically generate those textures. thats why they have not been added

**Comment by Xelbayria** [comment]
Good news:

I've finished it.  the texture part is not easy. it took some effort to tweak the textures to have the right look. 
will be in **v2.6.67**
