### ISSUE TITLE
[🗃]: Update Regions Unexplored Brimwood Texture

### ISSUE THREAD

**Issue by Neko2n** [MehVahdJukaar/WoodGood#542]
### Version

0.5.5

### Curseforge

https://www.curseforge.com/minecraft/mc-mods/regions-unexplored

### Details

Some of the items based on Regions Unexplored's Brimwood have broken textures, as they seem to be taking colors from the lava pixels instead of the wood pixels. Below are images of the problem.

![All Blocks](https://github.com/MehVahdJukaar/WoodGood/assets/43053729/a4e8b366-a5a9-4e28-a75b-198dceb6c599)
![Working Blocks & Base Brimwood Blocks](https://github.com/MehVahdJukaar/WoodGood/assets/43053729/1f35f5d8-5ce0-481c-a65b-5dde6fcdf2f6)
![Broken/Ugly Blocks](https://github.com/MehVahdJukaar/WoodGood/assets/43053729/cf2a1370-684a-4523-8cf7-d912494a3371)

**Comment by Xelbayria** [comment]
Which version of Minecraft? 

EDIT: 
I've checked the version of **Region unexplored** and 0.5.0 is not the latest version.

**Comment by Neko2n** [comment]
Yeah I made a typo, I'm using version 0.5.5 on 1.20.1.

**Comment by Xelbayria** [comment]
The generating of textures via **everycomp** from mods' blocks with its own textures are all automatic. I will not manually create textures for all of these blocks from other mods with _brimwood_ from **Region Unexplored** due to too much of work. 

I'll talk to MehVahdJukaar about this and see if there are anything we can do about the _brimwood_ texture

**Comment by Xelbayria** [comment]
I've spoke to MehVahdJukaar. We had a similar idea where we could fix that texture problem with the lava color. I'll work on this. No guarantee, tho.  it's just an experiment to see if it can be solved or not.

**Comment by Fingernailsss** [comment]
a bit random, but how did you get the unique item shelves?

EDIT: it's a mod called Supplementaries Squared

**Comment by Xelbayria** [comment]
Good news, it's working but need some tweaking. This will be finished and be in **v2.6.67**.

**Comment by Xelbayria** [comment]
I've finished this for now. The lava Overlay will be only applied to `planks`, `slab`, and `stairs` but it won't be applied to other blocks. I also fixed Chests' texture with Brimwood (of course, the lava overlay won't be applied, too).

**Comment by Neko2n** [comment]
thank you so much! I really appreciate the effort you all put into developing this mod :)
