### ISSUE TITLE
[🗃]: Create : Recipes for wood types

### ISSUE THREAD

**Issue by ghost** [MehVahdJukaar/WoodGood#543]
### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/create

### Curseforge-Fabric (Optional)

https://www.curseforge.com/minecraft/mc-mods/create-fabric

### Details

Hello, I would like to suggest the possibility of adding recipes compatible to create and possibly mods similar to it, as in how in create there exists a sawing machine that turns logs into 6 planks, I would like to see a feature where that is possible with this mod as well as in modded logs can also turn into 6 planks using the sawing machine. Though I'm aware I can use crafttweaker to add this feature myself, I feel that coding with that mod tends to ruin my enjoyment of a modpack I make so I'm just asking to basically save myself.

**Comment by Xelbayria** [comment]
This is more of "Module Enhancement" rather than "Suggesting a mod". Just so you know next time you can select the correct issue to fill out the information. 

is sawing machine a vanilla (from Minecraft) or from a mod or **create**? 

and which minecraft version?

**Comment by ghost** [comment]
The sawing machine is from create, and I'm not too sure when they first added the machine in, All I know is the machine certainly exists in 1.20 and probably existed in 1.19. Also I just checked it's called a mechanical saw so just in case to be clear that's what the mod calls it.

**Comment by Xelbayria** [comment]
gotcha. I'll look in it and I can add recipes for other blocks.

**Comment by Xelbayria** [comment]
you want the recipes for wood, planks, slab and sticks to be apply to other wood mods with create's mechanic saw, correct?

**Comment by ghost** [comment]
Yes, I would

**Comment by Xelbayria** [comment]
Thanks for the quick replying., i'll be working on this now. 

## UPDATE: 

the recipe of mechanic saw can do   Wood -> Stripped -> Planks. This is already implemented by Create.  I'm trying to find out if it can do slab or stairs

**Comment by Xelbayria** [comment]
I need to know if your wood mod is one of these: 
- architect_palette
- ars_nouveau
- biomes o plenty
- blue_skies
- botania
- byg (Oh The Biomes You'll Go)
- ecologics
- forbidden_arcanus
- hexcasting
- integrateddynamics
- quark
- silentgear
- tconstruct (Tinker's Construct)
- twilight_forest

These are the recipes supported by Create for Log -> Stripped_log -> Planks. I've spoke to some people via **Create**'s discord and they believe that the dev may be implementing the recipes for stairs, slabs. so on. there is no eta. 

I'll add the recipe via everycomp for now. if the update come with the recipes for these stairs & slabs. I can remove it or not.

**Comment by ghost** [comment]
biomes o plenty is one of the mods.

**Comment by Xelbayria** [comment]
planks -> slabs|stairs|sticks recipe is added in **v2.6.66**

**Comment by Xelbayria** [comment]
@NukolLodda 
Want to let u know, The generated recipes from above will be disabled if **sawmill** mod is installed.
