### ISSUE TITLE
[🐞]: Attempt to load client only class in server cause crash

### ISSUE THREAD

**Issue by mlus-asuka** [MehVahdJukaar/WoodGood#547]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

1.20-2.6.65

### Moonlight Lib Version

1.20-2.12.6

### Issue with mods

no bussiness with other mods

### Issue Detail

can't start server after updating every compt

### OPTIONAL: Latest.log | Crash-report Attachment

net.minecraftforge.fml.LoadingFailedException: Loading errors encountered: [
        Every Compat (everycomp) has failed to load correctly
java.lang.BootstrapMethodError: java.lang.RuntimeException: Attempted to load class net/mehvahdjukaar/every_compat/common_classes/CompatC
hestItem for invalid dist DEDICATED_SERVER
]
        at net.minecraftforge.fml.ModLoader.waitForTransition(ModLoader.java:246) ~[fmlcore-1.20.1-47.2.20.jar%23416!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$dispatchAndHandleError$20(ModLoader.java:210) ~[fmlcore-1.20.1-47.2.20.jar%23416!/:?] {}
        at java.util.Optional.ifPresent(Optional.java:178) ~[?:?] {re:mixin}
        at net.minecraftforge.fml.ModLoader.dispatchAndHandleError(ModLoader.java:210) ~[fmlcore-1.20.1-47.2.20.jar%23416!/:?] {}
        at net.minecraftforge.fml.ModLoader.lambda$gatherAndInitializeMods$13(ModLoader.java:183) ~[fmlcore-1.20.1-47.2.20.jar%23416!/:?] {}

**Comment by Xelbayria** [comment]
I thought i make sure it's only used in CLIENT, not SERVER. I'll check.

And next time, do not use copy/paste. Drag the file (`latest.log` or `crash-report` here), it will get uploaded. The dev can download it to take a look. I'll need the file to know what's going on.

**Comment by Xelbayria** [comment]
I need the `latest.log` and `crash-report`

**Comment by xhatz** [comment]
Having similar crash on server with mods:
[latest.log](https://github.com/user-attachments/files/16067021/latest.log)
[crash-2024-07-02_12.51.10-fml.txt](https://github.com/user-attachments/files/16067024/crash-2024-07-02_12.51.10-fml.txt)

**Comment by Xelbayria** [comment]
thank u! i'll take a look.

**Comment by Xelbayria** [comment]
I made a mistake & will apply the fix. I'll let u know when the **v2.6.66** is uploaded
