### ISSUE TITLE
[🐞]: Hollow Stems Incorrectly Named Hollow Log

### ISSUE THREAD

**Issue by Ghastly13** [MehVahdJukaar/WoodGood#548]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

2.6.65

### Moonlight Lib Version

2.12.6

### Issue with mods

The Aether: Redux 2.0.16c
The Outer End 1.0.9
Endless Biomes 1.5.1
Regions Unexplored 0.5.5
Optional: Voidscape 1.5.389

### Issue Detail

I noticed that when you fixed #545, that you also renamed the Hollow Logs to Hollow Stems. I have found every example of this issue in the set of mods that I use:
- [x] The Aether: Redux - Cloudcap Stem/Hollow Cloudcap Log
- [x] The Outer End - Indigo Stem/Hollow Indigo Log - Azure Stem/Hollow Azure Log
- [x] Endless Biomes - Penumbra Stem/Hollow Penumbra Log - Twisted Stem/Hollow Twisted Log
- [x] Regions Unexplored - Blue/Green/Pink/Yellow Bioshroom Stem/Hollow [Color] Bioshroom Log

I also noticed that Voidscape adds a Thunder Stem that does not recieve a Hollow Stem variant, however I believe this is an issue with Voidscape as they also use an incorrect ID naming convention for the stripped stem block, thunder_stem_stripped as opposed to stripped_thunder_stem (which causes the stripped textures to not be detected).

**Comment by Xelbayria** [comment]
> I also noticed that Voidscape adds a Thunder Stem that does not recieve a Hollow Stem variant, however I believe this is an issue with Voidscape as they also use an incorrect ID naming convention for the stripped stem block, thunder_stem_stripped as opposed to stripped_thunder_stem (which causes the stripped textures to not be detected).

that's a great info, i can fix that. 

and regarding the naming, it has to be a specific block from **furniture mod** which i can manually rename the title to "stem" from "log". I'll need to know which furniture mod. There is no way to fix that because Furniture Mod actually use the name like Quark's

hollow_\<type>_log as the ID of the block. but the best way to fix it is just to change the title of the block which is seen as "Hollow \<Type> Log".

**Comment by Xelbayria** [comment]
I need to know which furniture mod.   the only 2 mods I know has the hollow_log are: **Quark** and **The Twilight Forest**

**Comment by Ghastly13** [comment]
Sorry, I only tested Quark.

**Comment by Xelbayria** [comment]
Alright, i'll fix the naming.  considered this fixed in next version: v2.6.66

**Comment by Xelbayria** [comment]
I cannot find **Indigo Stem/Hollow Indigo Log**, **Outer End** only have _azure_stem_

nvm. it turned out i have v1.0.8 for **Outer End**, had to update it to v1.0.9 (thought i had the latest one) 

edit: again nvm. I'm sure that it doesn't have Indigo stem.
