### ISSUE TITLE
[🐞]: No Woodworks chests generated for Quark wood types

### ISSUE THREAD

**Issue by samuel-cote** [MehVahdJukaar/WoodGood#549]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [x] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycompat- 1.20-2.6.65

### Moonlight Lib Version

moonlight- 1.20-2.12.6

### Issue with mods

- Woodworks 3.0.1 (Chests)
- Quark 4.0-458 (Ashen, Azaelia, and Trumpet Wood)

### Issue Detail

Woodworks chests do not generate for wood types added by Quark. Trapped chests exist, but are unobtainable. This issue is confirmed with the listed mod versions, but has existed throughout multiple versions.

**Comment by Xelbayria** [comment]
Oh, that's because Woodworks has no foreign woods added. Otherwise, if it do, chests would be generated with **Quark** and **Woodworks**. **Quark** has some woods added, IIRC.

**Comment by Xelbayria** [comment]
If there is more to this issue, i'll need more details.

**Comment by samuel-cote** [comment]
> If there is more to this issue, i'll need more details.

The problem is that the Quark chests aren't present either. Adding Woodworks to a modpack with Quark and Every Compat prevents any standard chest made of Quark wood from being generated.

**Comment by Xelbayria** [comment]
gotcha

**Comment by Xelbayria** [comment]
interesting. this is an issue on **Quark**'s side. I can confirm no recipes for chest & trapped_chest from **Quark** without **EveryComp** or **Moonlight Lib**
I added a code for **Woodworks**' _chest_ & _trapped_chest_ to be skipped if **Quark** is installed. 

let me know if that's a no problem or you would like to have **woodworks** chest & trapped_chest included, even with **Quark** installed

**Comment by samuel-cote** [comment]
As long as there's a functional chest for each wood type, which mod takes priority doesn't matter much to me!

**Comment by Xelbayria** [comment]
alright.

**Comment by Xelbayria** [comment]
Alright, I found the culprit. it's the config from **Quark**. 

`"Ignore Anti Overlap" = true`  under **Building.variant_chests** fixed the missing recipes for _chest_ and _trapped_chest_. I think the issue is that Anti-Overlap is applied to **Quark** when **Woodworks** is installed.  it's not perfect but there are other solutions to fix this such as using **CraftTweaker** or **KubeJS**. 

 _chest_ & _trapped_chest_ from **Woodworks** with **Quark** will be skipped. that's all.
