### ISSUE TITLE
[🐞]: Missing textures for Macaw's hedge in [Let's Do] Meadow pine leaves.

### ISSUE THREAD

**Issue by Robynstar** [MehVahdJukaar/WoodGood#550]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.65.jar

### Moonlight Lib Version

moonlight-1.20-2.12.6-forge.jar

### Issue with mods

Macaw's Fences and Walls - mcw-fences-1.1.2-mc1.20.1forge.jar
[Let's Do] Meadow - letsdo-meadow-forge-1.3.17.jar

### Issue Detail

When trying to render the Macaw's hedge in the Meadow pine leaves, we get the dreaded magenta and black squares:
![2024-07-02_13 05 39](https://github.com/MehVahdJukaar/WoodGood/assets/2327643/ef98418e-1249-4a39-b723-de3ead41a48b)
Confirmed with only the three mods in question.

The Macaw's hedge works just fine in other modded leaves (e.g. Apple/Grapevine from [Let's Do] Vinery), and other modded hedges (e.g. Quark, Mr Crayfish's Furniture Mod, Builders Crafts & Additions) work just fine in the pine leaves.
Although interestingly it didn't even generate a Macaw's hedge in any of the Quark leaves (blossom/trumpet or ashen), nor a Mr Crayfish one, but did for Builders Crafts & Additions. And the Macaw's hedge generated for the Vinery Dark Cherry leaves is missing the cherries, despite them being present on the other three hedges.

**Comment by Robynstar** [comment]
The failure to generate note at the end seems similar to #525, but I do not have any of the mods mentioned in the issue. I will investigate this further and put it in its own issue when/if I work out where the issue is coming from.

**Comment by Xelbayria** [comment]
Alright, I'll await for more info about `#525`.   and the texture problem will be fixed.

**Comment by Robynstar** [comment]
Not sure it is actually that similar to #525, as most recipes _are_ generated, and there are no error messages in the log. (only a few exceptions for 'vinery:blockstates/grapevine_leaves.json' which are always there)
I have however found multiple instances of hedges missing/using incorrect textures.
Do you want them all in one issue, or in separate issues? And if separate do you want them grouped by the texture source or the hedge source?

**Comment by Xelbayria** [comment]
Yes. Please create a separate issue with the texture source (that would be helpful)  with hedge's ID from which wood mod

This issue is already closed blc it's focused on the Pine Leaves from **Meadow**. and is fixed. I'll await for your new issue. 

### EDIT: 

you can use `<type>_hedge -  woodmod:block/<type>_leaves`, i hope this is not too much of work.
