### ISSUE TITLE
[🐞]: Hedges using incorrect Vinery textures

### ISSUE THREAD

**Issue by Robynstar** [MehVahdJukaar/WoodGood#551]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.65.jar

### Moonlight Lib Version

moonlight-1.20-2.12.6-forge.jar

### Issue with mods

**Hedge sources**
Builders Crafts & Additions (Forge) - [buildersaddition-1.20.1-20230928a.jar](https://www.curseforge.com/minecraft/mc-mods/buildersaddition/files/4772826)
Macaw's Fences and Walls - [mcw-fences-1.1.2-mc1.20.1forge.jar](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls/files/5442222)
MrCrayfish's Furniture Mod - [cfm-forge-1.20.1-7.0.0-pre36.jar](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod/files/4602980)
Quark - [Quark-4.0-458.jar](https://www.curseforge.com/minecraft/mc-mods/quark/files/5418252)

**Textures**
[Let's Do] Vinery - [letsdo-vinery-forge-1.4.25.jar](https://www.curseforge.com/minecraft/mc-mods/lets-do-vinery/files/5467441)

### Issue Detail

everycomp:mcf/vinery/grapevine_hedge uses the mcwfences:oak_hedge model and should be using the vinery:block/grapevine texture, but instead looks to be using the vinery:block/apple_leaves texture
![2024-07-02_21 12 22](https://github.com/MehVahdJukaar/WoodGood/assets/2327643/78ea228f-34c2-46b7-90f1-6cbc0142a9c1)
Grapevine on the left, grapevine hedge in the middle, apple leaves on the right

everycomp:mcf/vinery/dark_cherry_hedge has the same issue - should be using the texture of vinery:block/dark_cherry_leaves but again appears to be using the apple leave texture instead
![2024-07-02_21 17 36](https://github.com/MehVahdJukaar/WoodGood/assets/2327643/6454018a-0d6b-4cf0-9918-9c66b3ce6550)
The left two hedge blocks are dark_cherry, the right two are apple. The leaves on top are apple leaves.

But the dark_cherry hedges from the other three mods seem to have picked up the fruiting texture instead:
everycomp:bca/vinery/hedge_dark_cherry (left)
everycomp:cfm/vinery/dark_cherry_hedge (middle)
everycomp:q/vinery/dark_cherry_hedge (and everycomp:q/vinery/dark_cherry_leaf_carpet) (right)
all use the vinery:block/dark_cherry_leaves_stage1 texture
![2024-07-02_21 25 46](https://github.com/MehVahdJukaar/WoodGood/assets/2327643/b2bb53b6-ef83-4356-9359-5228d8a25b03)
Which I think is incorrect because the "Dark Cherry Leaves" block (vinery:dark_cherry_leaves) is plain, as seen between the hedges in this image.
Cherry tree included in background, showing plain leaves, as well as the two fruiting textures (green blobs being vinery:block/dark_cherry_leaves_stage0)

**Comment by Xelbayria** [comment]
Oops, the problem you see are a mistake on my side. i thought Vinery only has _apple_leaves_. Apparently, it has other leaves. Beside that, it's fixed. Great finding!

**Comment by Robynstar** [comment]
On 2.6.66 I'm still seeing the dark cherry hedges for Quark, Mr Crayfish, and Builders Crafts using the fruiting texture.
As opposed to Macaw's which uses the plain leaf texture.

**Comment by Xelbayria** [comment]
hmm. I may have to add the path of these 3 leaves' texture to a class. I'll check

**Comment by Xelbayria** [comment]
Ok. i see what you are talking about. do you want to have no fruits? Just Leaves? OR do you want **MacawFences** to use the same leaves for dark_cherry just like **Quark** and the other 2 mods

**Comment by Robynstar** [comment]
As the "Dark Cherry Leaves" block (vinery:dark_cherry_leaves) is plain I believe all the hedges should match that, as the Macaw's one does. No fruit.
But ultimately it's up to you guys, just make it consistent please ^-^

**Comment by Xelbayria** [comment]
alright, got it. 

I could make it have fruits, tho. I'll make it plain. it will be in **V2.6.67**

**Comment by Robynstar** [comment]
Sorry, just wanted to check you'd got everycomp:q/vinery/dark_cherry_leaf_carpet as well.

**Comment by Xelbayria** [comment]
k, I'll make sure i got that leaves fixed, too.
