### ISSUE TITLE
[🐞]: Missing Quark texture hedges

### ISSUE THREAD

**Issue by Robynstar** [MehVahdJukaar/WoodGood#552]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.65.jar

### Moonlight Lib Version

moonlight-1.20-2.12.6-forge.jar

### Issue with mods

**Hedges missing for**
Macaw's Fences and Walls - [mcw-fences-1.1.2-mc1.20.1forge.jar](https://www.curseforge.com/minecraft/mc-mods/macaws-fences-and-walls/files/5442222)
MrCrayfish's Furniture Mod - [cfm-forge-1.20.1-7.0.0-pre36.jar](https://www.curseforge.com/minecraft/mc-mods/mrcrayfish-furniture-mod/files/4602980)

**Using textures from**
Quark - [Quark-4.0-458.jar](https://www.curseforge.com/minecraft/mc-mods/quark/files/5418252)

### Issue Detail

Every Compat is not generating hedges using the Quark trumpet/blossom or ashen/ancient textures for Macaw's Fences and Walls, or MrCrayfish's Furniture Mod.
**Hedges:**
mcwfences:oak_hedge
cfm:oak_hedge
**Textures:**
quark:block/ancient_leaves
quark:block/blue_blossom_leaves
quark:block/lavender_blossom_leaves
quark:block/orange_blossom_leaves
quark:block/red_blossom_leaves
quark:block/yellow_blossom_leaves

They are being generated for Builder's Crafts & Additions, so I know it's not a config issue.

**Comment by Xelbayria** [comment]
**Quark** have _hedge_ and it's why the hedges from **Macaw's Fences & Walls** got skipped. 

### UPDATE: 
Fixed and will be in **v2.6.66**

### EDIT: 

**MrCrayfish's Furniture Mod** on another note, is also fixed.  it also has the same name _hedge_ and it's why they got skipped, just like **Macaw's Fences & Walls**
