### ISSUE TITLE
[🗃]: Consistency issues with certain mods (Branches)

### ISSUE THREAD

**Issue by Fingernailsss** [MehVahdJukaar/WoodGood#557]
### Version

varies

### Curseforge

(https://www.curseforge.com/minecraft/mc-mods/regions-unexplored) https://www.curseforge.com/minecraft/mc-mods/nethers-exoticism, https://www.curseforge.com/minecraft/mc-mods/snifferent, and https://www.curseforge.com/minecraft/mc-mods/gardens-of-the-dead

### Details

First off, Jabuticaba (Nether's Exoticism) and Globar (Snifferent) have their own branches and therefore those should be removed like other trees with branches already have. Second, Whistlecanes (Gardens of the Dead) are WAY too small to have a branch, and should probably not have branches for the same reason bamboo doesn't.

**Comment by Xelbayria** [comment]
Ok.  I want to know which mod? 

the branch you speak of is from **Regions Unexplored (RU)**. You want to add the rest of mods to not have any support from **EveryComp (EC)** with the _branch_ from **RU**? 

"Version" is for which mod supported by **EC**, so I'll know which version to look at.   Curseforge is for link of the supported mod. 

just so you know.

**Comment by Fingernailsss** [comment]
didn't know how else to report this.

also, i gave out links to every mod i am referring to and specified what mod each item is from in the body text

**Comment by Xelbayria** [comment]
Ok. I'll assume the version is 1.20.1 (you haven't answered the question). 

This will be fixed. 

### TASK:
- [x] Reasons: 1) already have branches or 2) shouldn't be included.  EXCLUDE: 
	- [x] **Nether's Exoticism** (1)
	- [x] **Snifferent** (1)
	- [x] **Gardens Of The Dead** (2)

**Comment by Xelbayria** [comment]
Included in **v2.6.70**

Addition: it's also included in 1.19.2, too
