### ISSUE TITLE
[🐞]: Nether Update Expanded Textures

### ISSUE THREAD

**Issue by Ghastly13** [MehVahdJukaar/WoodGood#558]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

2.6.66

### Moonlight Lib Version

2.12.6

### Issue with mods

Nether Update Expanded 3.23

### Issue Detail

These bugs apply to each of the three wood types present in Nether Updated Expanded, including: Frosted Stem, Elder Stem, and Dragon Stem.
When meaning to use the sides of the block, Every Compat uses the top or bottom of the block instead. This means that instead of bark, it uses the inside wood texture. This really only causes a huge problem with mods that only use the side textures, like the Hollow Logs from Quark or Twilight Forest.

Additionally, the Hollow Logs from Quark aren't called Hollow Stems, as they should be.

### OPTIONAL: To Produce

Use Nether Update Expanded and Every Compat at the same time as a mod such as Quark. The problem should be immediately obvious.

**Comment by Xelbayria** [comment]
👌  this should be an easy fix.

**Comment by Xelbayria** [comment]
Fixed in **v2.6.67**.
