### ISSUE TITLE
[🐞]: Game crashes on startup (Every Compat)

### ISSUE THREAD

**Issue by Cuetsu** [MehVahdJukaar/WoodGood#560]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.66

### Moonlight Lib Version

moonlight-1.20-2.12.6-forge

### Issue with mods

The mod itself (Every Compat)

### Issue Detail

I'm playing the Minecolonies Dimensional Adventure modpack, I added Every Compat to the mods list and now my game crashes on startup. Tried every version of the mod between 2.6.60 to the latest version.

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/user-attachments/files/16168386/latest.log)

[crash-2024-07-10_23.02.39-client.txt](https://github.com/user-attachments/files/16168388/crash-2024-07-10_23.02.39-client.txt)

**Comment by Xelbayria** [comment]
Try disable all of mods except just a few essential mods including **EveryComp** & **Moonlight Lib**. Then enable the disabled mods one by one or 2 by 2 until you get the crash. 

I am not sure which mods is the culprit

**Comment by Devilswarchild** [comment]
it has been found that excessive building is the culprit, currently trying to see which version prior to its latest version will allow wood good to work normally. we will get back to you.

**Comment by Devilswarchild** [comment]
ok so had to downgrade excessive building back down to its 2.2.0 version from 3.0.1

**Comment by Xelbayria** [comment]
That's good. Now we know who is the culprit. And does the downgrade version solve the problem?

**Comment by Devilswarchild** [comment]
> That's good. Now we know who is the culprit. And does the downgrade version solve the problem?

it indeed does however I a noticed a massive spike in ram usage when I got it working but im pretty sure that's bc my modpack has a large volume of mods (400+) that wood good is trying to create variants from

**Comment by Xelbayria** [comment]
I see. If you are just playing in a singleplayer world, then you can use everycomp-entries.toml to disable a few modules that you really don't need. It should give you a list of supported mod as a module

However if you are playing Multiplayer, then don't because you can risk a de-sync between client and server which can leads to problem. It will be difficult to solve unless you backup the server's world.

**Comment by Xelbayria** [comment]
Any progress on your side?

**Comment by Devilswarchild** [comment]
it was for the official server of my modpack and have since decided against its use. the massive increase in ram usage isn't worth it. but if any one who doesnt play on the official server is more than welcome to add it to his or her Singleplayer experience.

**Comment by Xelbayria** [comment]
Good to see the progress on this. You can close this if it's resolved.
