### ISSUE TITLE
[🗃]: Shrubs from Regions Unexplored

### ISSUE THREAD

**Issue by Fingernailsss** [MehVahdJukaar/WoodGood#561]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/regions-unexplored

### FABRIC Version Availability

- [ ] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

regions_unexplored

### Types

**Block:**
- Branches (you already have these)
- Shrubs (you don't have these)

### Optional Details

Shrubs are 2 block tall plants crafted from using 2 saplings. You can just use the oak shrub as a base and have the wood part be colored by a log and the leaves be colored by modded leaves

**Comment by Xelbayria** [comment]
I've took a look at the shrubs from **Regions Unexplored (RU)**. There is no good way to generate a texture of shrubs for other mods (**Biomes O Plenty** or others...). 

Many trees from other mods that are "coniferous tree" type and some are "deciduous tree".  If I made **EveryComp** generate textures for Shrubs. All of the shrubs would look like a recolored "oak shrub (deciduous tree)", It will be not based on each tree's sapling.

**Comment by Fingernailsss** [comment]
That is exactly what i am suggesting.

**Comment by Xelbayria** [comment]
so you don't mind all of saplings from other mods to have the same look of "oak shrubs" being recolored with leaves and logs? 

you can choose one of shrubs as a base for me to use. it could be "acacia" or "birch" or "dark oak"

**Comment by Fingernailsss** [comment]
between those 3 it would be dark oak

**Comment by Xelbayria** [comment]
There are like 9 vanilla leaves IIRC is the counts. you can choose one of them to be used as a base. so it's "Dark Oak"?

**Comment by Fingernailsss** [comment]
Yes

**Comment by Xelbayria** [comment]
you're playing Minecraft 1.20.1, right?

**Comment by Fingernailsss** [comment]
yep

**Comment by Xelbayria** [comment]
Finished with 1.20.1, so it will be in **v2.6.67**

**Comment by Fingernailsss** [comment]
Cool

**Comment by Xelbayria** [comment]
Fingernailsss, you can ignore this: 

RegionsUnexplored Support have been Added to 1.19.2-FABRIC & 1.19.2-FORGE

**Comment by Fingernailsss** [comment]
![2024-07-21_18 06 27](https://github.com/user-attachments/assets/55bbf6f6-ac90-4d1a-8b3b-3fb5448b9d15)
We have a small problem.

(also, some of these are not craftable)

**Comment by Xelbayria** [comment]
yes I know about the recipe problem. it's already fixed. but I'm working on improving these textures

**Comment by Xelbayria** [comment]
The improvement of textures are all finished.
