### ISSUE TITLE
[🐞]: Both Halves of Fancy Bed Drop a Fancy Bed

### ISSUE THREAD

**Issue by freyebeans** [MehVahdJukaar/WoodGood#562]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2

### Loader

Forge

### EveryCompat Version

everycomp-1.18.2-2.5.24

### Moonlight Lib Version

moonlight-1.19.2-2.3.6-forge

### Issue with mods

just Handcrafted

### Issue Detail

The fancy bed drops two bed because both halves drop a bed when it should only drop from the head

**Comment by Xelbayria** [comment]
Thanks for reporting this issue. 

Fixed in **v2.5.25**
