### ISSUE TITLE
[🐞]: 1.20.1 Quark Every Compat

### ISSUE THREAD

**Issue by Krimatoria** [MehVahdJukaar/WoodGood#563]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.66.jar

### Moonlight Lib Version

moonlight-1.20-2.12.6-forge.jar

### Issue with mods

Quark-4.0-458.jar

### Issue Detail

Log

### OPTIONAL: Latest.log | Crash-report Attachment

> 
> [00:21:30] [Render thread/ERROR] [Every Compat/]: Failed to generate server dynamic assets for module EveryCompat Quark Module: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.Block.m_5456_()" because "log" is null
> 
> 3966 | [00:21:30] [Render thread/ERROR] [Every Compat/]: Failed to generate server dynamic assets for module EveryCompat Quark Module: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.Block.m_5456_()" because "log" is null

**Comment by Xelbayria** [comment]
which wood mod?

**Comment by Krimatoria** [comment]
> which wood mod?

everycomp-1.20-2.6.66.jar

**Comment by Xelbayria** [comment]
nvm. I can see the error on my side.   FYI, wood mod is a mod that add woods like "Biomes O' plenty" or "The Twilight Forest" so on.

**Comment by Montysmith** [comment]
What was the issue, I am having this issue as well.

**Comment by Xelbayria** [comment]
Not sure why. I'm investigating to find out why the error show up.

**Comment by Xelbayria** [comment]
Found it. The cause is the `.requireChildren("log")` being commented out in the **Quark Module**. what it does is check for logs that leaveTypes have. U know the recipe to craft Hedge, it required 2 things: leaves and logs. The error is gone.

**Comment by Krimatoria** [comment]
> Found it. The cause is the `.requireChildren("log")` being commented out in the **Quark Module**. what it does is check for logs that leaveTypes have. U know the recipe to craft Hedge, it required 2 things: leaves and logs. The error is gone.

I found something else interesting) But that's another problem)))
