### ISSUE TITLE
[🐞]: Quark hedges missing

### ISSUE THREAD

**Issue by CaptConrad** [MehVahdJukaar/WoodGood#565]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.67

### Moonlight Lib Version

moonlight-1.20-2.12.6

### Issue with mods

Quark's hedges missing

### Issue Detail

After the latest update, hedges for other modded wood types (i.e. not Vanilla and Quark wood types) don't exist.

**Comment by Xelbayria** [comment]
Do you mean the hedge (**Quark**) with other wood mods are missing?

**Comment by CaptConrad** [comment]
Yes I think.

For example, I have Twilight Forest and Regions Unexplored on my modpack. There are no hedges for those mods' wood types.

I also made a test modpack that had just Quark, Twilight Forest, and EC, and there were no hedges for TF wood types so I can confirm it wasn't another mod causing issues.

**Comment by Xelbayria** [comment]
I'll look in this. 

EDIT: 
ah yes, i know what's the problem. it will be fixed in v2.6.68
