### ISSUE TITLE
[🐞]: 1.19.2 Missing ID spam

### ISSUE THREAD

**Issue by ashezly** [MehVahdJukaar/WoodGood#566]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [x] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [x] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2

### Loader

Forge

### EveryCompat Version

everycompat-1.19.2-2.5.24

### Moonlight Lib Version

moonlight-1.19.2-2.3.6-forge

### Issue with mods

biomesoplenty, blue_skies, ecologics, iceandfire, endlessbiomes (removed), phantasm, quark, twilight forest, aether, atmospheric, cataclysm (removed), aether, abundant atmosphere, atmospheric, deeper and darker

### Issue Detail

When I load minecraft and join my server I am meeted with, "Internal Exception: java.lang.NullPointerException: Cannot invoke \"net.minecraft.nbt.CompoundTag.m_128461_(String)\" because \"nbt\" is null" I check my latest log and all I see is a missing id spam from most of my mods that add blocks. Vertical slabs and Supplementaries also had some missing ids. I repair my forge and it works but the next day the same problem occurs. I remove everycompat and it still happens. 

### OPTIONAL: Latest.log | Crash-report Attachment

[latest (1).log](https://github.com/user-attachments/files/16322721/latest.1.log)

**Comment by MehVahdJukaar** [comment]
I done see that nbt issue in that log you send. Send crash log too. Missing I'd warns are unrelated, just means you removed mods from your world which had some of those blocks or items present before

**Comment by ashezly** [comment]
It didn't send me a crash report. After receiving the connection lost screen, I would exit the game and attempt to repair the profile using the CurseForge app. This problem has been going on since Wednesday and I have no clue what is wrong.
![compound tag](https://github.com/user-attachments/assets/3ee832e4-58f2-4c14-8072-af439d9260e6)

**Comment by MehVahdJukaar** [comment]
You need to check server log

**Comment by ashezly** [comment]
my friends are experiencing the same issue, but I'm not
server log: https://mclo.gs/MPhnAZm (I think)

**Comment by MehVahdJukaar** [comment]
Then your friend is doing something wrong and it's clearly not a mod issue. Probably mismatched mods

**Comment by ashezly** [comment]
[latest (3).log](https://github.com/user-attachments/files/16323133/latest.3.log) 
[latest (4).log](https://github.com/user-attachments/files/16323135/latest.4.log)
my friends logs

**Comment by ashezly** [comment]
me and my friend tried to isolate the problem and they got in but now I can't?

**Comment by Xelbayria** [comment]
Check and make sure your Client have the exact same version of mods (every mod) as the one on Server's side. If you can't join the server, it should have give you the error message saying what's wrong. Usually, the clues will show itself to tell you what's the problem.

**Comment by ashezly** [comment]
Didn't work
[latest.log](https://github.com/user-attachments/files/16325806/latest.log)

**Comment by ashezly** [comment]
ok after some testing: dark paintings, decorative blocks, or deeper and darker does not work

**Comment by Xelbayria** [comment]
Can you provide details regarding **dark painting**, **Decorative Blocks** (is supported by EveryComp) **Deeper and darker**? 

do these 3 provide the same error in latest.log?

**Comment by ashezly** [comment]
The thing is i removed the mods but I still get the same error. i can provide a mod list for you?

**Comment by Xelbayria** [comment]
As long as the mod list doesn't have more than 10 mods. Go ahead, share the list. 

The best way to do this is to disable all of mods and enable them one by one. so we can isolate which mod is the culprit. This way I can find out what's the problem and fix it. 

EDIT: 
does the same error in latest.log show up on your Client side(not Server)? 

and try remove the mod "cataclysm".  Make sure you backup your world if you are the host of the server

**Comment by ashezly** [comment]
i managed to fix it and turns out xaero's world map was causing problems and we removed it from the server and it works!

**Comment by Xelbayria** [comment]
great! 👍🏻 There are other alternative mod to Xaero's World Map you can look at.
Have a fun with the server.
