### ISSUE TITLE
[🐞]: 1.20.1 Shrub? What

### ISSUE THREAD

**Issue by Krimatoria** [MehVahdJukaar/WoodGood#568]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

Everycomp-1.20-2.6.67.jar

### Moonlight Lib Version

Moonlight-1.20-2.12.8-forge.jar

### Issue with mods

Everycomp-1.20-2.6.67.jar
Quark-4.0-458.jar
Moonlight-1.20-2.12.8-forge.jar

### Issue Detail

[Render thread/ERROR]: Failed to generate recipe for ru/gardens_of_the_dead/soulblight_shrub 
(Well, so do other mods where there is this shrub)
I'm already confused whether it was or not, it doesn't seem to be. In short, the whole log is full of errors again.

https://gist.github.com/Krimatoria/c24cd11c24f113a341a07926632b738c

![image](https://github.com/user-attachments/assets/75645f72-4a83-496e-b5dc-1c931a3690ea)

**Comment by Xelbayria** [comment]
Dont worry about this. The recipe problem is fixed. I'm working on improving the textures for shrub. 

the code for shrub in v2.6.67 is outdated and incorrect. 

EDIT: 
FYI, "ru" is Regions Unexplored. that's where shrubs are from.  The support for **RU** are branches and shrubs

**Comment by Krimatoria** [comment]
> Не беспокойтесь об этом. Проблема с рецептом исправлена. Я работаю над улучшением текстур для кустарника.
> 
> код для кустарника в v2.6.67 устарел и неверен.
> 
> EDIT: FYI, "ru" - это Regions Unexplored. Вот откуда кустарники. Поддержка **RU** - это ветви и кустарники

NiceEEE)

**Comment by Xelbayria** [comment]
finally done! it was a pain in the bum.

**Comment by Krimatoria** [comment]
> наконец-то сделано! это была настоящая головная боль.



> finally done! it was a pain in the bum.

And why is it a difficult problem? Interesting)

**Comment by Xelbayria** [comment]
**The Twilight Forest**'s leaves are all tinted. The texture generated for shrub were all "grey" due to tinted texture. I had to talk with devs in discord to find a good way. it took me 4 days to figure out the solution and got everything working. 

all good now. Let me know if you find any problems.
