### ISSUE TITLE
[🐞]: Enlightend: Indigo Stem gets called Hollow Log, and Cerulean Stalk inconsistencies

### ISSUE THREAD

**Issue by VoidLeech** [MehVahdJukaar/WoodGood#569]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

1.20-2.6.68

### Moonlight Lib Version

1.20-2.12.9

### Issue with mods

Endlightend 5.0.14 in conjunction with:
Definitely:
Quark
Twilight Forest
Questionably:
Decorative Blocks

### Issue Detail

Similar to #548, Enlightend's Indigo Stem actually got mentioned there but misattributed. With Quark/Twilight Forest Hollow Logs, the everycomp blocks gets called Hollow Log instead of Hollow Stem.

Additionally, Enlightend has Cerulean as wood type, with the "log" being the Block of Cerulean Stalk, which is akin to a Block of Bamboo. This brings inconsistencies with some of the modules:
- Quark/Twilight Forest don't have a Hollow Log for bamboo, yet one is created for cerulean
- Decorative Blocks doesn't have a Beam for bamboo, yet one is created for cerulean
There might be other supported mods that have a similar stance w.r.t. bamboo for some of their blocks, but I'm not familiar enough with them to know.

If these inconsistencies are deemed not worth fixing, at the very least the name for the Hollow Logs should reflect that the base is a Block of Cerulean Stalk, and not a log.

**Comment by Xelbayria** [comment]
I'll need the ID of these blocks from EveryComp, so I can correct their display title.

**Comment by VoidLeech** [comment]
Right, sorry. By that message I'm assuming the only intention is renaming, the relevant ids of mentioned blocks are:
Should be Hollow Indigo Stem:
everycomp:q/enlightened_end/hollow_indigo_log
everycomp:tf/enlightened_end/hollow_indigo_log
Should be Hollow Block of Cerulean Stalk:
everycomp:q/enlightened_end/hollow_cerulean_log
everycomp:tf/enlightened_end/hollow_cerulean_log

**Comment by Xelbayria** [comment]
thank you! That will allow me to get it done faster

**Comment by Xelbayria** [comment]
The display title is fixed for these woods from **Enlgihtened_End**. 

so this: 
- Quark/Twilight Forest don't have a Hollow Log for bamboo, yet one is created for cerulean
- Decorative Blocks doesn't have a Beam for bamboo, yet one is created for cerulean

DO you want to include Bamboo for **Decorative Blocks**?

the reason why **Quark**, **Twilight Forest** are skipped because the textures for hollow_log required _log_ and _stripped_log_. Unless Bamboo already have _stripped_log_ texture, then I can fix that. I just need the ID

**Comment by VoidLeech** [comment]
I’m not fully clear on the question, but I think *no*. Let me clarify:
- Bamboo is a vanilla wood, so the variant block mod dev should provide that variant I think
- Thus it seems a conscious decision for the Quark/Twilight Forest/Decorative Blocks devs to not include a Bamboo variant for a block (hollow log/hollow log/beam respectively)
- Since Cerulean from enlightened_end is like bamboo, it’s odd/could be unintended EveryCompat provides a compat block for those block types with that wood type (because it currently does; the block’s registry id and texture ids are named as if the block is a log, even though it isn’t)

So personally I think these 3 blocks ***shouldn’t*** exist, but that might conflict with EveryComp’s goals:
- everycomp:q/enlightened_end/hollow_cerulean_log
- everycomp:tf/enlightened_end/hollow_cerulean_log
- everycomp:db/enlightened_end/cerulean_beam

**Comment by Xelbayria** [comment]
so you preferred all of the 3 ids to not exist? I can make it not exist. but some people will prefer that they exists. There is one way to fix that. You just need to go in `./config/everycomp-entries.toml` IIRC. That's assuming you're using 1.20.1 

and find the woodType, "cerulean" and set it to `false`. There are 1 pro and 1 con: 
PRO: cerulean with 3 ids will be hided via JEI/REI 
CON: all of furniture mods combined with "cerulean" will be also hided, too. 

I fixed the display title, so you'll see Cerulean as `Hollow Cerulean Stem`... but the id with "log" is just an ID for registering.

**Comment by VoidLeech** [comment]
That’s exactly it yes, and yeah some people might prefer the opposite so it’s very understandable to not disable them (I saw the config yeah but the con’s too big, I’ll resort to crafttweaker/datapack to hide/disable them)
Think this issue can be closed then (:

With the id thing I referred to enlightened_end’s own id for the base cerulean stalk block containing log (and thus allowing everycomp to generate certain compat blocks), just so we’re clear there, and I get the internal id can’t/shouldn’t be changed.

**Comment by Xelbayria** [comment]
right, i forgot to mention KubeJS or CraftTweaker to hide them. yea. internal ID can't be changed because it's based on the ID of the mods like "hollow_log" from quark or Twilight Forest, can't change that. EveryComp is just following the behave of mod. that's it. 

Have fun! 


EDIT: 

display title are fixed in **v2.6.69**
