### ISSUE TITLE
[🐞]: Another Furniture and Decorative Blocks error

### ISSUE THREAD

**Issue by Flame4ik97** [MehVahdJukaar/WoodGood#570]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.68

### Moonlight Lib Version

moonlight-1.20-2.12.9-forge

### Issue with mods

Another Furniture 3.0.1
Decorative Blocks [ Forge 1.20.1 ] v4.1.3

### Issue Detail

When using Every Compat with Another Furniture, Decorative Blocks, or both, when creating a new world or entering an old world, an error occurs, making it impossible to enter the world. If you run Every Compat without these mods, the world goes perfectly. If you run both of these mods without every compat, the error also does not occur. Besides these furniture mods, I also use Hearth and Home, Storage Drawers, Quark, Architect Palette, Woodworks, Boatload, Backpacked and they work without problems.

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/user-attachments/files/16399023/latest.log)
[Server thread/ERROR] [net.minecraftforge.fml.javafmlmod.FMLModContainer/LOADING]: Caught exception during event net.minecraftforge.event.BuildCreativeModeTabContentsEvent@2439fd6d dispatch for modid everycomp
java.util.NoSuchElementException: No value present

**Comment by Flame4ik97** [comment]
If you only run MoonlightLib, Every Compat, Another Furniture and Decorative Blocks, then you can enter the world, but when you open the inventory you are simply thrown out of the game with a crash.

**Comment by Xelbayria** [comment]
Did you figure out what's the problem?
