### ISSUE TITLE
[❔]: Decoration Delight compat

### ISSUE THREAD

**Issue by Flame4ik97** [MehVahdJukaar/WoodGood#571]
### Question

https://www.curseforge.com/minecraft/mc-mods/decoration-delight

### Optional: Details

I know that there is support for this mod on 1.19.2, but when playing on this version I did not see any support, apparently there is a problem. In addition, the author of the mod recently updated the mod to version 1.20.1. Are there plans to add and fix the mod to support Every Compat?

**Comment by Xelbayria** [comment]
The mod is currently WIP. 

EDIT: 
I took a look and turned out I thought i added it but ended up forget about it. Will be added in **v2.5.26**

EDIT 2: 
Added to version 1.20.1
