### ISSUE TITLE
[🐞]: Born in Chaos missing/incorrect textures

### ISSUE THREAD

**Issue by NickW1102** [MehVahdJukaar/WoodGood#572]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.68

### Moonlight Lib Version

moonlight-1.20-2.12.9-forge

### Issue with mods

Born in Chaos <born_in_chaos_[Forge]1.20.1_1.3.1>
GeckoLib <geckolib-forge-1.20.1-4.4.7>
Valhelsia Structures <valhelsia_structures-forge-1.20.1-1.1.2>
Valhelsia Core <valhelsia_core-forge-1.20.1-1.1.2>
Quark <Quark-4.0-458>
Zeta <Zeta-1.0-19>

### Issue Detail

When using Valhelsia Structures with Born in Chaos, the automatically generated scorched wood posts are missing their textures. It would appear this is due to the textures never being generated, as they're missing from the debug resource pack.
Similarly, the generated hollow scorched logs from Quark are both missing textures on some sides and using incorrect textures on others, though this time it seems to be due to the model pointing to the wrong texture files.

**Comment by Xelbayria** [comment]
i'll check

**Comment by Xelbayria** [comment]
Fixed in v2.6.69

the real cause is the texture filename of log, stripped_log, and planks are not all in English.
