### ISSUE TITLE
[📦]: Oh the Biomes We've Gone 

### ISSUE THREAD

**Issue by OminousDiscovery** [MehVahdJukaar/WoodGood#573]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-weve-gone

### Curseforge-Fabric (Optional)

https://www.curseforge.com/minecraft/mc-mods/oh-the-biomes-weve-gone/files/5574105

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20.1

### MODID

im not sure :(

### Types

a lot of planks and stuff. I'm not fully sure if its 1 to 1 but this is just the 1.20.1 version of BYG im pretty sure

**Comment by Xelbayria** [comment]
planks and logs, stripped_log don't need to be added to EveryComp blc it can detect them. Let's call that mod "BWG" just like BYG. so if BWG have furniture blocks or items. I could add them. 

can you investigate? If there is no furniture, then it's better to close this issue.

**Comment by MehVahdJukaar** [comment]
Do you mean it doesn't work already?

**Comment by OminousDiscovery** [comment]
yes

**Comment by Xelbayria** [comment]
Do you meant "yes" as in EveryComp not detecting these woodTypes from BWG? You should check the sound of these woodType, it need to be "bass" sound. 

usually, updating 1.19.2 to 1.20.1, some time, the dev forgot to update woodTypes' property which is soundType

**Comment by Xelbayria** [comment]
I haven't heard from you. Can you answer my question above?

**Comment by championhestu** [comment]
I'm not the OP, but since the BYG mod was renamed, none of the BYG blocks in EveryCompat work anymore. They have to be updated/renamed.

**Comment by MehVahdJukaar** [comment]
They are different blocks. One can have both mods on

**Comment by Xelbayria** [comment]
> I'm not the OP, but since the BYG mod was renamed, none of the BYG blocks in EveryCompat work anymore. They have to be updated/renamed.

EveryComp doesn't support BYG or BWG. IT can detect the woodTypes as long as it has the "bass" sound. BYG was updated from 1.19.2 to 1.20.1 as BWG (Some times, Dev forgot to add the "bass" sound to the woodTypes). **Use _Note Block_ to check the sounds of wood variants from BWG. if they don't have "bass" sound.** You need to let the dev know. 

If they have the "bass" sound, then I can add these undetected woodTypes to EveryComp

EDIT: 

I've took a quick look at **B W G** and EveryComp have no problem detecting the woodTypes from **B W G**. This `none of the BYG blocks in EveryCompat work anymore` is not helping devs understand what's the problem you are facing. you gotta be more specific

**Comment by championhestu** [comment]
> > I'm not the OP, but since the BYG mod was renamed, none of the BYG blocks in EveryCompat work anymore. They have to be updated/renamed.
> 
> EveryComp doesn't support BYG or BWG. IT can detect the woodTypes as long as it has the "bass" sound. BYG was updated from 1.19.2 to 1.20.1 as BWG (Some times, Dev forgot to add the "bass" sound to the woodTypes). **Use _Note Block_ to check the sounds of wood variants from BWG. if they don't have "bass" sound.** You need to let the dev know.
> 
> If they have the "bass" sound, then I can add these undetected woodTypes to EveryComp
> 
> EDIT:
> 
> I've took a quick look at **B W G** and EveryComp have no problem detecting the woodTypes from **B W G**. This `none of the BYG blocks in EveryCompat work anymore` is not helping devs understand what's the problem you are facing. you gotta be more specific

What I mean to say is that Every Compat had custom textures for things like cabinets, ladders and chests for BYG/BWG woodtypes. Those custom textures are not available anymore because of BWG's name change.
Furthermore, the directory I used for a resource pack that revamps all BYG/BWG textures, including the Every Compat ones, no longer works because of this.

**Comment by Xelbayria** [comment]
Okay. EveryCompat automatically detect the woodType from BWG. Even if the name in BWG's woodTypes changed. EveryCompat will use the changed name, too (if BWG happened to have a new update). you get the idea. 

Something is causing the problem you are facing. You need to find out what is it. First, have you changed the names in Resource Pack to match the BWG's name changes.

EDIT: 
I forgot to mention the namespace of BWG is now `biomeswevegone`. You may also want to check the namespace in Resource Pack is correct (change it from `byg` to new namespace

**Comment by Cricket742** [comment]
Hi, I just ran into this problem. I changed the name space in the assets/quark/textures/quark variant chests/everycomp folder to biomeswevegone fixed the issue. So that does need to be changed but it fixes the issue.

**Comment by Xelbayria** [comment]
☝🏻  There you go, that's why i suggested what i said in my previous message. There is nothing I can do on my side.
