### ISSUE TITLE
[🐞]: Chests from Variant Vanilla Blocks are not generated on fabric

### ISSUE THREAD

**Issue by Helinos** [MehVahdJukaar/WoodGood#576]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Fabric

### EveryCompat Version

everycomp-1.20-2.6.69

### Moonlight Lib Version

moonlight-1.20-2.12.9-fabric

### Issue with mods

Variant Vanilla Blocks 1.3.8
Natures Spirit 1.6.0-1.20.1
Cinderscapes 4.0.10
(Presumably any other fabric mod that adds wood)

### Issue Detail

When using Variant Vanilla Blocks every block is generated correctly aside from chest variants.
![image](https://github.com/user-attachments/assets/84d4c9f6-9063-4f30-bab2-910fea0f8357)
![image](https://github.com/user-attachments/assets/f4e6f8b3-e6db-474e-8fb9-c0a19651a293)
![image](https://github.com/user-attachments/assets/24900f5d-f169-4a12-b2ff-c1e8759ac38b)

**Comment by Xelbayria** [comment]
I'm aware of this. the problem is FABRIC is not the same loader as FORGE. i cannot figure out the correct way to add CHEST and TRAPPED_CHEST

**Comment by Xelbayria** [comment]
Included in **v2.6.70**
