### ISSUE TITLE
[🐞]: Missing textures error in logs when using EveryCompat and Feywild

### ISSUE THREAD

**Issue by wExtraBenji** [MehVahdJukaar/WoodGood#577]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.70

### Moonlight Lib Version

moonlight-1.20-2.12.9

### Issue with mods

Feywild 1.20 4.0.3

### Issue Detail

In the log during boot, many instances of "Missing textures" warnings happen that are identified as everycompat:feywild 

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/user-attachments/files/16489389/latest.log)

**Comment by Xelbayria** [comment]
Hmm. I see you haven't added a list of furniture mod. it must be included. don't worry about it. 

### Furniture Mod: 
- Quark
- The Twilight Forest
- Macaw's Fences & Walls
- Backpack

### Wood Mod: 
- Feywild:
  - autumn_tree
  - hexen_tree
  - spring_tree
  - blossom_tree
  - winter_tree

- Dreamy Cottage
  - white_oak (mcf)

**Comment by wExtraBenji** [comment]
To add to the ones you've listed
Furniture Mods: Assorted Decor, Cluttered, Decorative Blocks, Fairy Lights, Fantasy's Furniture, Handcrafted, Hearth and Home, MCW except furniture, MOA Decor: Holidays, Supplementaries, Supplementaries Squared, Tanuki Decor, Magic Vibe Decorations
Wood mods: The Aether, Hexerai, Forbidden and Arcanus, Biomes O' Plenty, Autumnity, Ars Nouveau
(I think this is all of them, apologies, I didn't see anything saying to include the list)

**Comment by Xelbayria** [comment]
Alright, i only need the mods that have the missing textures. it's easier to focus this way.

**Comment by Xelbayria** [comment]
Fixed in v2.6.71


There are some issues with texturing from **Dreamy Cottage**. they are all fixed. And **Feywild**'s side are all fixed, too.
