### ISSUE TITLE
[🐞]: Handcrafted x Let's do Blooming Nature Swamp Oak Fancy bed duplicates when broken

### ISSUE THREAD

**Issue by ParsnipThePossum** [MehVahdJukaar/WoodGood#579]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.70

### Moonlight Lib Version

moonlight-1.20-2.12.9-forge

### Issue with mods

handcrafted-forge-1.20.1-3.0.6
letsdo-bloomingnature-forge-1.0.7

### Issue Detail

i crafted a fancy bed from handcrafted using bloomingnature's swamp oak and when i place down one and break it it drops 2 beds at a time

**Comment by Xelbayria** [comment]
Fixed in v2.6.71
