### ISSUE TITLE
[📦]: Re:Deco

### ISSUE THREAD

**Issue by kingkuys2123** [MehVahdJukaar/WoodGood#580]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/redeco

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

redeco

### Types

**Block:**
- Cabinets
- Chairs
- Benches
- Coffee Tables
- Counters
- Crates
- Display Cases
- Drawers
- Lattices
- Pedestal
- Fences
- Gates
- Shelves
- Side Tables
- Stools
- Sword Mounts
- Tables

**Comment by Xelbayria** [comment]
Duplicated. Related to #456
