### ISSUE TITLE
[🐞]: 1.20.1  Failed to generate server dynamic assets - Quark

### ISSUE THREAD

**Issue by Krimatoria** [MehVahdJukaar/WoodGood#583]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.70.jar

### Moonlight Lib Version

moonlight-1.20-2.12.9-forge.jar

### Issue with mods

Quark-4.0-460.jar 

### Issue Detail

> 
> [16:42:21] [Render thread/ERROR] [Every Compat/]: Failed to generate server dynamic assets for module EveryCompat Quark Module: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.Block.m_5456_()" because "log" is null
> 
> 14337 | [16:42:21] [Render thread/ERROR] [Every Compat/]: Failed to generate server dynamic assets for module EveryCompat Quark Module: java.lang.NullPointerException: Cannot invoke "net.minecraft.world.level.block.Block.m_5456_()" because "log" is null
> 
>

**Comment by Xelbayria** [comment]
Which block? and I need the latest.log. You can just drag the file here.

### EDIT: 
I need to know which wood mod. The one that cause the error.

**Comment by Krimatoria** [comment]
> Какой блок? и мне нужен latest.log. Вы можете просто перетащить файл сюда.
> 
> ### РЕДАКТИРОВАТЬ:
> Мне нужно знать, какой мод дерева. Тот, который вызывает ошибку.

I can only watch it this week. If I see which blog I'll write)

**Comment by Krimatoria** [comment]
> Which block? and I need the latest.log. You can just drag the file here.
> 
> ### EDIT:
> I need to know which wood mod. The one that cause the error.

If I see which block I will write)

**Comment by Xelbayria** [comment]
Have you find out what's the block & Wood Mod?

**Comment by Krimatoria** [comment]
> Вы уже выяснили, что такое Block & Wood Mod?

I'm with my friends on the server right now, I'll try to see.

**Comment by Krimatoria** [comment]
And what does that mistake mean? What to look for? Visually, at least in the subjects, Quark has no problems, at least through the EMI interface, I do not see this. Is some kind of interaction or recipe possible?

<details>
<summary>Images</summary>

![image](https://github.com/user-attachments/assets/dfc674d8-8809-4f56-beba-dc4a87daee55)
![image](https://github.com/user-attachments/assets/c415dd23-9de2-4bea-b5b2-de341ff71702)
![image](https://github.com/user-attachments/assets/06c3e15d-ef45-40a0-bd2f-edca5e7b4575)
![image](https://github.com/user-attachments/assets/471c1223-4e62-4281-9392-b079fe4664c3)
![image](https://github.com/user-attachments/assets/a638064e-1d13-47ec-a3a8-095b85ae3882)

</details>

**Comment by Xelbayria** [comment]
what's the real problem? If the problem is the items not showing up in EMI, then try REI or JEI

**Comment by Krimatoria** [comment]
> what's the real problem? If the problem is the items not showing up in EMI, then try REI or JEI

I'm trying to figure out what the problem is. I can't figure it out yet. I looked at all the things in EMI at Qark. There are no visual problems, the error says about some textures. If I see something, I will write here.

**Comment by Xelbayria** [comment]
Any news on this issue?

**Comment by Krimatoria** [comment]
> Any news on this issue?

1. I'll add the Quark mod and your mod right now and see if there are any errors. But in the game itself, in a large assembly, I did not see any visual errors anywhere. 
2. And then I will run a large build

if there are no errors in the first case, then it is not directly related. If there is an error in a large assembly again, then I will write.

**Comment by Krimatoria** [comment]
I only launched your mod and Quark and this error appeared. I added EMI just to view the recipes. If you look at recipes in EMI, it's like JEI. Then Quark has a lot of pages, your mod shows one item, it shows all possible options, but only 1 item (it's hard to explain, they just change there, you can see for yourself) and only EveryCompat is signed. That is, there is no EveryCompat + Quark recipe. Maybe this is what the error says? If this is how it should be, then everything is ok) It's just that Quark adds its own tree, maybe recipes from your mod were created there before?

1. Created a new world
2. Open your inventory and enter @ quark or @ everycompat (without spaces) in the field below
3. Opened the log file

- Zeta-1.0-24.jar
- Quark-4.0-460.jar
- moonlight-1.20-2.12.17-forge.jar
- everycomp-1.20-2.6.73.jar
- emi-1.1.12+1.20.1+forge.jar

> [11:06:42] [Render thread/ERROR] [Every Compat/]: EVERY COMPAT REGISTERED 0 BLOCKS! This means that you dont need the mod and should remove it!

<details>
<summary>Image</summary>

![image](https://github.com/user-attachments/assets/156c5f22-a8e0-47b0-a55e-feb20b299dc3)
![image](https://github.com/user-attachments/assets/d65cc459-6903-43b8-af5e-7f3e615d4565)

</details>

**Comment by Xelbayria** [comment]
> EVERY COMPAT REGISTERED 0 BLOCKS! This means that you dont need the mod and should remove it!

I see. That's because you have no wood mod added. **EveryComp** doesn't have any wood mod (Biomes O' Plenty) or whatever. I am familiar with that error. It's not really an error, it's just a warning and tell you that you don't need **EveryComp**

> I'm trying to figure out what the problem is. I can't figure it out yet. I looked at all the things in EMI at Qark. There are no visual problems, the error says about some textures. If I see something, I will write here.

There are no problem with **Quark** & **EveryComp**

**Comment by Krimatoria** [comment]
> > EVERY COMPAT REGISTERED 0 BLOCKS! This means that you dont need the mod and should remove it!
> 
> I see. That's because you have no wood mod added. **EveryComp** doesn't have any wood mod (Biomes O' Plenty) or whatever. I am familiar with that error. It's not really an error, it's just a warning and tell you that you don't need **EveryComp**
> 
> > I'm trying to figure out what the problem is. I can't figure it out yet. I looked at all the things in EMI at Qark. There are no visual problems, the error says about some textures. If I see something, I will write here.
> 
> There are no problem with **Quark** & **EveryComp**

Well, then can the problem be closed?)

well, yes, I have RegionsUnexploredForge-0.5.6+1.20.1.jar . Biomes O' Plenty did not set. Although I don't know what's more interesting with Terralith.

**Comment by Xelbayria** [comment]
you can re-open this issue if the issue come back. I'll tests with BOP, RegionsUnexplored, & Terrlith on my side.
