### ISSUE TITLE
[🐞]: Quark Variants and Biomes we've gone

### ISSUE THREAD

**Issue by Cricket742** [MehVahdJukaar/WoodGood#586]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

1.20-2.6.71

### Moonlight Lib Version

1.20.1-2.12.13

### Issue with mods

Quark and Biome's we've gone

### Issue Detail

The namespace in the folder "assets/quark/textures/quark variant chests/everycomp" is still "BYG" instead of "biomeswevegone", so the quark compat textures are not being loaded. Before I was able to change it myself and fix the issue, but I figured it should be fixed officially

**Comment by Xelbayria** [comment]
I'll need the resource pack. I'll do some testing on my side. You can just drag the resource pack file here. I'll able to download it and use it. 

I'll need more details to understand what's the problem.

**Comment by Cricket742** [comment]
There’s no resource pack? It’s a folder in the everycompat mod’s asset directory.

**Comment by Xelbayria** [comment]
Ah. Sorry, I misunderstood you. I understand what's the problem.

**Comment by Cricket742** [comment]
On another note, I've just noticed that some of the wood namespaces have changed as well.  "rainbow" has changed to "rainbow_eucalyptus", "blue" has changed to "blue enchanted", "cherry" has changed to "sakura", "green" has changed to "green_enchanted", "white" has changed to "white_mangrove", and "witch" has changed to "witch_hazel". There are also three new wood types called ironwood, florus, and embur but no pressure to make special quark textures for them tbh.

**Comment by Cricket742** [comment]
Update: Ok even with the changed namespace AND changed file names, the quark variant chest textures aren't loading.

Edit: I'm going to try changing the texture names to "chest left" and so on to see if that works

Edit: It did not work, I noticed in each name space folder in  Oh the biomes we've gone  just has a the item name like "crafting_table.png" in each namespace so that might have something to do with it?

**Comment by Xelbayria** [comment]
> On another note, I've just noticed that some of the wood namespaces have changed as well. "rainbow" has changed to "rainbow_eucalyptus", "blue" has changed to "blue enchanted", "cherry" has changed to "sakura", "green" has changed to "green_enchanted", "white" has changed to "white_mangrove", and "witch" has changed to "witch_hazel". There are also three new wood types called ironwood, florus, and embur but no pressure to make special quark textures for them tbh.

I know about these changed name. I'm currently working on fixing the issue. 

EDIT:
you don't need to worry about this issue. I know how to fix the problem.

**Comment by Xelbayria** [comment]
Fixed in v2.6.72

**Comment by Enterprise12nx01** [comment]
1.19.2 latest version, using BDCraft with its mod addons, only textures for every compat are broken(not for everything) but they are fine once bdcraft is disabled, any idea why?
here is the list of mod related items broken:

BOP
Ad Astra
Botania 
Domum ornamentum
tinkers construct
ice and fire
thermal
fruitful fun
assembly line machines

some of these mods dont even have a texture pack addon, like assembly line machines. some are unfinished texture addons.
how can i fix this?

**Comment by Xelbayria** [comment]
isn't BDCraft a resource pack? 

did you have it loaded during running Minecraft, then reboot it so EveryCompat can access to the texture from BDCraft

**Comment by Enterprise12nx01** [comment]
> isn't BDCraft a resource pack?
> 
> did you have it loaded during running Minecraft, then reboot it so EveryCompat can access to the texture from BDCraft

Yes it is, and it has community made additions for mods. I have many users using it and I have personally reloaded Minecraft several times with it on with the mod.
It is only chests missing textures from those mods specifically that this mod is adding variants of

**Comment by Xelbayria** [comment]
The only solution I can think of is to add the missing textures to the resource pack. If the resource pack you have doesn't account for everything. You've mentioned that it has some unfinished and missing textures for the item/block. 

You can use 7zip to add the missing textures to the existing resource pack (BDCraft) OR create your own new resource pack to add these missing textures.

**Comment by Enterprise12nx01** [comment]
> The only solution I can think of is to add the missing textures to the resource pack. If the resource pack you have doesn't account for everything. You've mentioned that it has some unfinished and missing textures for the item/block.
> 
> You can use 7zip to add the missing textures to the existing resource pack (BDCraft) OR create your own new resource pack to add these missing textures.

I'll take a look, there's no broken textures with it off(from yours or any mod) but maybe some don't have bdcraft textures and your mods trying to pull something that doesn't exist from the pack

**Comment by Xelbayria** [comment]
> maybe some don't have bdcraft textures and your mods trying to pull something that doesn't exist from the pack

exactly! that's what I am thinking

**Comment by Enterprise12nx01** [comment]
> > maybe some don't have bdcraft textures and your mods trying to pull something that doesn't exist from the pack
> 
> exactly! that's what I am thinking

coming back to report, mahogany chest from every compat tag "everycomp:q/biomesoplenty/mahogany_chest" has no texture, but BDcraft does have a texture for its planks in biomes o plenty addon texture.
fruitful fun mod, i do not even have a bdcraft addon texture for that mod, and its still giving no texture for that chest. maybe the way its coded your mod is expecting a texture from that pack, having a fallback for the mods texture maybe is a fix? i have no idea how this works
so every compat is somehow pulling something wrong, if you would like to check the ones with issues, here is a link to my pack, the bdcraft texturepack is already included in download and just has to be enabled.
https://www.curseforge.com/minecraft/modpacks/industrial-age-the-turning/files/5771787

using @everycompat in jei will show u all the blocks, if you dont mind browsing through them, some hedges have no textures, and other items/blocks

**Comment by Xelbayria** [comment]
Ok. This discussion is still going on. You'll need to create a new issue and we can continue our discussion from there. 

Before you go and create a new issue. Try place the default textures from Minecraft's side or Mod's side in BDCraft's resource pack. This way you can fill the missing textures that are required by **EveryCompat**. Test the method to see if that resolve the issue of missing textures. I think EveryCompat is looking in BDCraft's pack instead of Minecraft's pack. 

On another thought, I don't think there's a way to make EC look at the Minecraft's pack (making it the fallback).
