### ISSUE TITLE
[❔]: Ecologics Chest types added but uncraftable

### ISSUE THREAD

**Issue by SymbolKlar** [MehVahdJukaar/WoodGood#587]
### Question

How do I enable the crafting recipes for the chests from Ecologics?

### Optional: Details

Ecologics and Every Compat are installed, I see the new chests from trees like Walnut Tree etc. as Walnut Chest but I can't craft them. Any idea why? JEI won't give a recipe and normal chest crafting gives a vanilla chest. Thanks.

**Comment by MehVahdJukaar** [comment]
For this to be an issue you must confirm that their original mod chests are craftable. When EC and ecologics are on no chest is added. you have a third mod that adds chest variants. That one.

**Comment by SymbolKlar** [comment]
Sorry, I'm having a hard time understanding what you meant. When I disable Every Compat The chests do not exist. Enabling Every Compat adds "Walnut Chest" and " Walnut Trapped Chest" and neither are craftable, as in they do not have a crafting recipe. Any way to fix? Sorry for taking your time.

**Comment by SymbolKlar** [comment]
Found the problem, it was Woodworks and Every Compat Clashing.

**Comment by SymbolKlar** [comment]
There seems to be some type of conflict between Quark and Woodworks trying to figure it out

**Comment by SymbolKlar** [comment]
The mod "Woodworks" is adding the chests variants for vanilla blocks but they do not exist for modded planks without Every Compat so I cannot test if they're craftable.

**Comment by SymbolKlar** [comment]
![image](https://github.com/user-attachments/assets/6a924e89-4781-42d3-bb4c-634f47ed6951)
![image](https://github.com/user-attachments/assets/9b1175e5-3a91-46be-8eac-88b942f01e54)
Neither have a crafting recipe

**Comment by Xelbayria** [comment]
ok I'll check with Ecologics and Woodworks.

**Comment by Xelbayria** [comment]
i had no problem on my side. The only one mod that can cause such issue is Quark. Do you have Quark installed?

**Comment by SymbolKlar** [comment]
Yes but upon the removal of quark the chests on the left (woodworks) still can't be crafted

**Comment by Xelbayria** [comment]
First, try launch Minecraft with:
- Ecologics
- EveryComp
- Moonlight lib
- Woodworks & Blueprint

if you can craft the chests, then one of the mods in the modpack is the culprit. You'll have to find out which one.

**Comment by SymbolKlar** [comment]
I cannot craft the chest when only those mods are enabled. No other mod is active.

<details>
<summary>Image 1</summary>

![image](https://github.com/user-attachments/assets/52b1754f-f732-44c9-9626-6b0c5e9cc3ac)

</details>

<details>
<summary>Image 2</summary>

![image](https://github.com/user-attachments/assets/d8bc7f8f-a634-4345-ab9f-945dcdca93ce)

</details>

The chest IS added, I can obtain it via the creative menu but it isn't craftable.

<details>
<summary>Image 3</summary>

![image](https://github.com/user-attachments/assets/aa6774ab-0b7b-42d6-8a3e-b9c675a70ae6)

</details>

**Comment by Xelbayria** [comment]
Oh you should have mentioned 1.18.2 
I thought you were on 1.20.1
I'll check on 1.18.2 


### UPDATE:
🤦🏻 The code did not include the recipe for chest & trapped_chest. that's what make chests uncraftable.

**Comment by SymbolKlar** [comment]
How would I go about fixing this on my end?

**Comment by Xelbayria** [comment]
3 ways to fix this is use CraftTweaker or KubeJS or Datapack. Don't worry about this. I am currently working on it. 

### EDIT:

oh right, FYI. this is actually a bug.

**Comment by SymbolKlar** [comment]
AFAIK There are no recipes for "Oh The Biomes You'll Go" As well

**Comment by Xelbayria** [comment]
It's not about wood mod (BYG). Furniture mod (Woodworks) have the recipe. I forgot to include the recipe for _chest_ & _trapped_chest_

it doesn't matter which wood mod, the _chest_ & _trapped_chest_ are still uncraftable. that's what i am trying to point out.

**Comment by Xelbayria** [comment]
Fixed in v1.6.15 (1.18.2)
