### ISSUE TITLE
[❔]: Campfires

### ISSUE THREAD

**Issue by EdoEquin0x** [MehVahdJukaar/WoodGood#588]
### Question

Any mod compatible with this one that adds campfires ?

**Comment by Xelbayria** [comment]
Go to EveryComp's page via Curseforge, you'll see a picture showing which mods are supported in 3 different versions. 

As far as I know, i don't think there is a supported mod that have a wood variant campfire

**Comment by EdoEquin0x** [comment]
I found a mod that could fit, I will make a request, thanks for the info!
