### ISSUE TITLE
[🐞]: Biomes We've Gone Florus Stem - Hollow Log (Quark/Twilight Forest)

### ISSUE THREAD

**Issue by Ghastly13** [MehVahdJukaar/WoodGood#590]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

2.6.72

### Moonlight Lib Version

2.12.14

### Issue with mods

Biomes We've Gone 1.1.1 beta
Quark 4.0-460
Twilight Forest

### Issue Detail

The Florus Stem added by Biomes We've Gone has an incorrectly named hollow log variant. The variant should be named Hollow Florus Stem. I have only tested Quark however it should be the same issue with Twilight Forest.
The ID of the florus stem is: biomeswevegone:florus_stem

**Comment by Xelbayria** [comment]
Fixed in v2.6.73

Corrected the title for `florus_stem` from **Oh The Biomes We've Gone** with **Quark** and **The Twilight Forest**
