### ISSUE TITLE
[Modrinth Mistake] 1.21 in 1.20.1 typo

### ISSUE THREAD

**Issue by TheShadyyOneYT** [MehVahdJukaar/WoodGood#591]
### says 1.21 in game version 1.20.1

Imgur: https://imgur.com/a/xb1Yhrz

![Screenshot 2024-08-21 172954](https://github.com/user-attachments/assets/4daf4b1d-3f9d-4361-8e09-86f61b01cae0)
![Screenshot 2024-08-21 173051](https://github.com/user-attachments/assets/2e1c4ed9-9857-4d3e-a740-dac04ec8d757)

**Comment by TheShadyyOneYT** [comment]
the mod version states 1.21 is in 1.20.1 If its for 1.21, it should be made into a new category for 1.21

**Comment by Xelbayria** [comment]
Yes, I know. it's my mistake. I had to use displaying title to label it 1.20.1

## UPDATED: 
Don't worry about it. The next version will have the correct version with v2.6.73

**Comment by TheShadyyOneYT** [comment]
Ok glad you noticed 👍

**Comment by Xelbayria** [comment]
tbh, i am glad I noticed, too
