### ISSUE TITLE
[🗃]: Arts and Crafts Compatability Mod Support

### ISSUE THREAD

**Issue by BlueIsADude** [MehVahdJukaar/WoodGood#595]
[Arts and Crafts](https://www.curseforge.com/minecraft/mc-mods/artsandcrafts) has an [official compatibility mod](https://www.curseforge.com/minecraft/mc-mods/artsandcrafts-compatibility) that offers custom-made textures for its unique looking Cork wood set, but currently causes duplicate items when paired with Every Compat.

Perhaps you can add a check for this compatibility mod into Every Compat's code, and disable item generation for certain mods (Twigs, Farmer's Delight, Dramatic Doors, just to name a few) if the mod is installed?

**Comment by Xelbayria** [comment]
Hmm. I'll check 

and the version is 1.20.1, right? 

### EDIT:
I'll need the ID of the duplicated items and ID of the item from **Arts & Crafts Compat**. Please make a list. thanks!

**Comment by Xelbayria** [comment]
Fixed in v2.6.73
