### ISSUE TITLE
[🐞]: Crash on start with DotBe.

### ISSUE THREAD

**Issue by Gavin456b** [MehVahdJukaar/WoodGood#598]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.73

### Moonlight Lib Version

moonlight-1.20-2.12.17-forge

### Issue with mods

Dawn of time: Builder Edition

### Issue Detail

Crashes on launch with the newest update of Dawn of Time: Builders Edition, probably due to the rewrite of the entire mod. No other mods present in my game. The crash only occurs with these two both present at the same time and not separately. 

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/user-attachments/files/16790069/latest.log)

### OPTIONAL: To Produce

Launch game with nothing but Every Compat & Dawn of Time.

**Comment by Xelbayria** [comment]
Fixed in v2.6.74

**Comment by Gavin456b** [comment]
When does this patch come out?

**Comment by Xelbayria** [comment]
on Tuesday, There are a few bugs that need to be fixed.

**Comment by Gavin456b** [comment]
@Xelbayria  Looks like DotBe reverted back to 1.5.7 so the new patch is now causing a crash since the changes in DotBe were reverted....

**Comment by Xelbayria** [comment]
again? I'll check the DotBe

**Comment by Gavin456b** [comment]
Yeah..lol. I guess 1.5.8 was buggy so they pulled it

**Comment by Xelbayria** [comment]
Yea, I figured they pulled it because I don't see any newer version. Let me know when the new version is out. I'll check if I need to update the module to support that newer version
