### ISSUE TITLE
[📦]: Cactus Planks from [Let's Do] BloomingNature

### ISSUE THREAD

**Issue by etherealgears** [MehVahdJukaar/WoodGood#600]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/lets-do-bloomingnature

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20.1

### MODID

bloomingnature

### Types

The Cactus woodeset from [Let's Do] Blooming Nature currently includes:

1. Planks
2. Stairs
3. Slab
4. Pressure Plate
5. Button
6. Trapdoor
7. Door
8. Window (block category unique to [Let's Do] BloomingNature)
10. Fence
11. Fence Gate
12. Sign
13. Hanging Sign
14. Boat
15. Boat With Chest (called 'Chest Boat')

### Optional Details

Every Compat already supports all of the wood types for [Let's Do] BloomingNature, except for the Cactus woodset. The Cactus woodset is crafted from cactuses, analogous to how vanilla bamboo planks are crafted. My suggestion would be to add support for plank-based blocks from the Cactus woodset, even though it doesn't have logs. I don't know if this is possible or not, but I thought it would be worth suggesting.

**Comment by Xelbayria** [comment]
is Cactus woodset from **BloomingNature**? Sometimes EveryComp doesn't detect a woodset, so it get skipped. it happens. The good news is It can be fixed

**Comment by Xelbayria** [comment]
Haven't heard from you. Can you answer my question ☝🏻? Every Compat detect woodTypes by "bass" sound.

**Comment by Xelbayria** [comment]
I've checked Blooming Nature and it doesn't have the Cactus you speak of. I think it's the wrong mod but one of the mod series may have the Cactus

**Comment by monyarm** [comment]
Actually, Blooming Nature does have cactus planks. They're "bloomingnature:cactus_planks". They don't have a log, but you could use the vanilla cactus block for that.
Blooming Nature also has wood windows for it's own wood types, but not the vanilla wood types. My best guess is that the vanilla ones are in another Let's Do mod?

**Comment by Xelbayria** [comment]
I'll check the recipe for cactus_planks and if it does use vanilla_cactus as the LOG. i could add it later on
