### ISSUE TITLE
[🗃]: Blooming planks from deeper darker are ignored

### ISSUE THREAD

**Issue by mxnmnm** [MehVahdJukaar/WoodGood#601]
### Version

v1.3

### Curseforge

https://www.curseforge.com/minecraft/mc-mods/deeperdarker

### Details

Deeper Darker added a new plank that isn't detected likely due to it belonging to a stem instead of a log. Having some way to manually add entries for weird things like this might be helpful or just making an exception for this scenario considering how it's pretty rare.

**Comment by Xelbayria** [comment]
Alright, I'll need the ID of these stem <strike> and which Minecraft version? </strike>

## EDIT:
figured it out & it's 1.20.1. Now I need just the ID of the stems and which furniture mod?

**Comment by mxnmnm** [comment]
I don't think there is much that can be done with the stems, but the planks are where the compat is missing. I will put the stems and planks in case you can do something with the stems. This is for ALL mods so there is not a single mod that has any options showing for the planks.

Stem: deeperdarker:blooming_stem

Planks: deeperdarker:bloom_planks

**Comment by Xelbayria** [comment]
> This is for ALL mods so there is not a single mod that has any options showing for the planks.

like Macaw's mods? or furniture mods?  it doesn't matter which furniture mods, right?

**Comment by mxnmnm** [comment]
Just all mods including things like chipped, quark, and any other mod that every compat has stuff for.

**Comment by Xelbayria** [comment]
The texture of _blooming_stem_ have a cross (not a full 16x16). The block of _blooming_stem_ is actually not a full block, it's 1/4 of the block. With this, it won't be included.

**Comment by mxnmnm** [comment]
Yea, but the planks are like normal planks. I wasn't expecting the stems to be added, just the planks.

**Comment by Xelbayria** [comment]
How did EveryComp detect woodTypes is by "bass" sound that log have. then it will add Planks to the list of children (that included door, ladder, so on). EveryComp can detect other stems from mods. The reason why it did not include _blooming_ is due to the texture it is using is not a fully 16x16

There is nothing I can do about this.
