### ISSUE TITLE
[🐞]: The Abyss II Hollow Luna Log

### ISSUE THREAD

**Issue by Ghastly13** [MehVahdJukaar/WoodGood#602]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

2.6.73

### Moonlight Lib Version

2.12.17

### Issue with mods

The Abyss II 1.0.5-beta https://www.curseforge.com/minecraft/mc-mods/the-abyss-chapter-ii

### Issue Detail

Quark/Twilight Forest Hollow Logs have incorrect textures
Luna Log theabyss:luna_log
![2024-08-30_12 53 21](https://github.com/user-attachments/assets/da662a6e-fe2d-4043-a4d4-2588eda7fd43)

**Comment by Ghastly13** [comment]
The Hollow Rena Log has the same issue
theabyss:rena_log

**Comment by Xelbayria** [comment]
k, I'll need the ID of that block. I know what's the problem.

**Comment by Xelbayria** [comment]
Fixed in v2.6.74
