### ISSUE TITLE
[📦]: Tropicraft

### ISSUE THREAD

**Issue by Redkoopa170** [MehVahdJukaar/WoodGood#603]
## REASON: 

Can't add it to v1.18.2 blc somehow Moonlight Lib/Selene is saying it cannot find the BlockItem using `Supplier.get()` and is returned with **null**. 

Idk why. 

### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/tropicraft

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

tropicraft

### Types

**Block:**
- Boardwalk

**Tropicraft Woodtypes to make compadible?:**
-Mangrove
-Mahogany
-Palm

![boardwalks](https://github.com/user-attachments/assets/2cb658c5-1370-4bc0-ab21-361217182f54)

### Optional Details

There is also a bamboo like woodtype though I think it's not a full on woodtype. There is also a Chunk O' head that works similarly to a woodtype though IDK if it really counts. It works more like how netherbrick has more block varieties.

It be neat to see the tropicrafts actual woodtypes tho made compatible though.

**Comment by Xelbayria** [comment]
- Added to v2.6.77 (1.20.1)
- Added to v2.5.29 (1.19.2)
