### ISSUE TITLE
[🗃]: Missing Quark Vertical Slabs

### ISSUE THREAD

**Issue by DaRealSparky** [MehVahdJukaar/WoodGood#604]
### Version

Quark-4.0-460

### Curseforge

https://www.curseforge.com/minecraft/mc-mods/quark

### Details

Only thing I've noticed missing from Quark Mod support is the vertical slabs. Other than that, perfect.

**Comment by Xelbayria** [comment]
with which wood mods?

**Comment by DaRealSparky** [comment]
So far, only with Biomes We’ve Gone. I plan on using a few more mods, but I’m installing a few at a time so I can make sure that everything is stable and can be configured properly.

**Comment by Xelbayria** [comment]
Alright, I'll try to finish fixing the bug (here) and one more module. then I'll upload the new version tonight.

**Comment by Xelbayria** [comment]
I cannot add that _vertical_slab_ to EveryComp because of the source code in Quark's Vertical_slab. It has a limitation. There is nothing I can do. 

I recommend this: [Vertical Slab Compat](https://www.curseforge.com/minecraft/mc-mods/vertical-slabs-compat) Made by MehVahdJukaar
