### ISSUE TITLE
[🐞]: Chipped classic trapdoor missing Compat textures

### ISSUE THREAD

**Issue by DawnBun** [MehVahdJukaar/WoodGood#605]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2

### Loader

Forge

### EveryCompat Version

1.19.2-1.1.6+8

### Moonlight Lib Version

1.19.2-2.3.7

### Issue with mods

Chipped 2.1.5

Not the culprit but included for posterity, the following mods were included in the troubleshooting mod list;
Autumnity 4.0.1
Blueprint 6.2.0
ConnectedTexturesMod 1.19.2-1.1.6+8
Just Enough Items 11.6.0.1024
Resourceful Libs 1.1.24
Handcrafted 2.0.6

### Issue Detail

The Classic Trapdoor from chipped is missing compatibility textures.
Handcrafted is listed above as the troubleshooting was initially made to troubleshoot 2 problems, the other being literally all the placeable blocks from Handcrafted missing textures however I was unable to reproduce this in the limited time I had so when I have a moment to do so I will create another bug report if I can isolate the issue and confirm if it is indeed an issue with this mod or another one

### OPTIONAL: To Produce

1) Install Wood Good and Requirements
2) Install Chipped and Requirements
3) Install a mod that adds at least one new Wood Type (I used Autumnity for troubleshooting but this affected every wood mod I had installed)
4) enter a world in creative mode, or in survival with a mod such as JEI installed
5) Look at the compat Trapdoor

**Comment by Xelbayria** [comment]
Fixed in v2.5.27
