### ISSUE TITLE
[📦]: Mr. Crayfish's Refurbished Furniture Mod 1.19.2?

### ISSUE THREAD

**Issue by CheezBallzFTW** [MehVahdJukaar/WoodGood#606]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/refurbished-furniture

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20.1

### FORGE Version Availability

- [ ] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

refurbished_furniture

### Types

It's already supported in 1.20.1 so I assume this isn't necessary here right?

**Comment by Xelbayria** [comment]
it's fine to suggest it to be supported in 1.19.2. I just checked. I don't know it's already out for 1.19.2

**Comment by Xelbayria** [comment]
Added to v2.5.27
