### ISSUE TITLE
[🐞]: Cannot craft the boards via Handcrafted

### ISSUE THREAD

**Issue by Swyatosha** [MehVahdJukaar/WoodGood#608]
### Minecraft Version

ex 1.19.2

### Supported Mod Version

ex 2.5.26 (I'm not asking for EveryComp's version. it's Handcrafted 🤦🏻‍♀️

### Details

<strike> idk what i need write here </strike>

 Hello! this is an amazing mod but there is one problem, it is impossible to craft boards for the Handcrafted mod from mod woods, I mean when you throw boards on a stone cutter you do not get special boards from the Handcrafted mod for crafting furniture

**Comment by Xelbayria** [comment]
Next time, please use "Report a Bug" if you found a problem. 

Mod Enhancement is for when a furniture mod have added a new block in its newer version and EveryComp doesn't support that "new block" yet.

**Comment by Swyatosha** [comment]
my bad, but i dont use Enhancement mod.

**Comment by Swyatosha** [comment]
> Next time, please use "Report a Bug" if you found a problem.
> 
> Mod Enhancement is for when a furniture mod have added a new block in its newer version and EveryComp doesn't support that "new block" yet.

**Comment by Swyatosha** [comment]
wait, mod Enhancement is for fabric, im use forge

**Comment by Xelbayria** [comment]
Fabric, right? I'll correct my mistake

**Comment by Swyatosha** [comment]
nah i mean i use fabric not forge :>

**Comment by Swyatosha** [comment]
no i mean im use forge but u say smth abt enhancement and there no forge version for this mod

**Comment by Xelbayria** [comment]
It looks like you do not understand what I said. Don't worry about it. it's a bug. 

I'll check on FORGE's side with crafting the boards

**Comment by Swyatosha** [comment]
oh okay, ty so much!

**Comment by Xelbayria** [comment]
Ah yes, I remember now. It's not an issue on EveryComp, it's an issue on Handcrafted's side. 

if you have JEI | REI | EMI, then you can use it to check the recipe of _oak_board_. it don't have recipe, either. The Dev of Handcrafted must have forgot to add the recipe for the boards. Boards are removed in 1.20.1.

There is nothing I can do about this. Your opinion is to fix this is via KubeJS or CraftTweaker. OR you can let the dev know about the missing recipe for boards.

**Comment by Swyatosha** [comment]
oki thank you for helping!

**Comment by Swyatosha** [comment]
wait a sec, boards really don't have a craft, u can make it only by throwing a plank in a stone cutter

**Comment by Swyatosha** [comment]
and i still can craft boards with a vanilla wood, and i just can't do it with modded wood, is that a still problem with handcrafted?

**Comment by Xelbayria** [comment]
Eh? can you tell me the version of Handcrafted? 

EDIT: 
I checked. I am using v2.0.6. Are you using a modpack?

**Comment by Swyatosha** [comment]
yeah

**Comment by Xelbayria** [comment]
So The dev of Modpack must have used KubeJS or CraftTweaker to fix the missing recipes for Handcrafted. There is no way for EveryComp to get that recipe. You need to tell The Dev about the missing recipes for EveryComp's side with Handcrafted & wood mods. 

technically, it's still a Handcrafted problem.

**Comment by Swyatosha** [comment]
alr thank u so much! have a great day ^^

**Comment by Xelbayria** [comment]
you're welcome. I hope the problem got resolved in the future! Have fun with the modpack.
