### ISSUE TITLE
[🐞]: Building But Better Frame textures don't work for Forge 1.20.1

### ISSUE THREAD

**Issue by ElyssiaRos** [MehVahdJukaar/WoodGood#609]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.74

### Moonlight Lib Version

moonlight-1.20-2.12.17-forge

### Issue with mods

- Mods below here, none of their woodtypes work with the **Frame** item AND block textures of the Building But Better 1.0.1 1.20.1 Forge
- Aether 1.4.2
- Aether-Redux 2.0.17
- Ancient Aether 1.0.4
- Better Archeology 1.2.1
- Born in Chaos 1.3.1
- Cluttered 2.1
- Deep Aether 1.0.4
- Deeper and Darker 1.3.2
- Eidolon Repraised 0.3.8.13
- Gardens of the Dead 4.0.1
- Ice and Fire 2.1.13-Beta-5
- L_Ender's Cataclysm 1.99.6
- Let's Do Beacharty 1.1.5
- Let's Do Blooming Nature 1.0.9
- Let's Do Meadow 1.3.19
- Let's Do Vinery 1.4.28
- My Nether's Delight 0.1.7.5
- Picture proof below;
- 
![missingno](https://github.com/user-attachments/assets/4e5cc254-8a42-4805-ab3b-8d6fc44eb601)
![2024-09-07_00 43 13](https://github.com/user-attachments/assets/c96ca085-4fe8-4906-b968-5e764b7f30f2)

### Issue Detail

Simply none of the modded wood textures work with the _frame_ item and block from **Building But Better!** mod.

**Comment by Xelbayria** [comment]
I noticed your **Building But Better** version is **v1.0.1**, It should be **v1.1.1**. I had no problem on my side. Get the latest version from Modrinth (idk why the dev did not upload the latest version to Curseforge). 

let me know if the latest version of **Building But Better** fix the problem.

**Comment by ElyssiaRos** [comment]
_Oh_ i use CurseForge so i didn't know that it was updated! I got the latest version from Modrinth as you said, it give an error at first but turns out i just needed to add **MidnightLib**. After that it worked all perfectly fine!

I also added a comment on the CurseForge version so hopefully they'll update it soon as well.

Thank you so much for your help, have good day/night!
