### ISSUE TITLE
[🐞]: Long Load then Crash

### ISSUE THREAD

**Issue by lanwoodall423** [MehVahdJukaar/WoodGood#612]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

2.6.74

### Moonlight Lib Version

2.12.20

### Issue with mods

Unsure

### Issue Detail

Minecraft loads for maybe 20min before finally crashing. Removing Every Compat fixes the issue. It seems to hang on creating models.

### OPTIONAL: Latest.log | Crash-report Attachment

[crash-2024-09-09_08.53.26-client.txt](https://github.com/user-attachments/files/16934704/crash-2024-09-09_08.53.26-client.txt)

**Comment by Xelbayria** [comment]
according to the crash report, you do not have enough RAM. you need to add more RAM

EDIT:
I mean the reason why your minecraft crashed is because of "Out of Memory"

**Comment by Xelbayria** [comment]
Haven't heard from you. I'll be closing this since there is no replying.
