### ISSUE TITLE
[🐞]: Missing textures on Handcrafted's Counters with ETF

### ISSUE THREAD

**Issue by Lictor000** [MehVahdJukaar/WoodGood#614]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.19.2

### Loader

Forge

### EveryCompat Version

everycompat -1.19.2-2.5.27

### Moonlight Lib Version

moonlight-1.19.2-2.3.7-forge

### Issue with mods

Handcrafted 1.19.2-2.0.6
Entity Texture Features 1.19.2-6.0.1

### Issue Detail

When Entity Texture Features is installed, the "Counter" blocks by Handcrafted are missing the wood texture part.
This happens only for the Every Compat added blocks and not the ones made from vanilla wood, reason why I'm reporting here first.

Tested without any other mod other than bare minimum necessary to get the new compat blocks. It happens for any modded wood I tried so far.

**Comment by MehVahdJukaar** [comment]
There's been bugs in the past with etf randomly breaking other mod textures for no reason so repor this to them too

**Comment by Lictor000** [comment]
Report opened on [EFT's github](https://github.com/Traben-0/Entity_Texture_Features/issues/311) too

**Comment by Xelbayria** [comment]
> There's been bugs in the past with etf randomly breaking other mod textures for no reason so repor this to them too

I was going to say the samilar thing with different meaning as MehVahdJukaar said. But I suspected that ETF may be responsible for the missing texture.   Create a new world without ETF. if you have no missing texture, then it's an issue on ETF, not EveryComp

**Comment by Lictor000** [comment]
> > There's been bugs in the past with etf randomly breaking other mod textures for no reason so repor this to them too
> 
> I was going to say the samilar thing with different meaning as MehVahdJukaar said. But I suspected that ETF may be responsible for the missing texture. Create a new world without ETF. if you have no missing texture, then it's an issue on ETF, not EveryComp

Ok, already did that in the testing that lead me to point ETF as the possible culprit. I confirm that uninstalling ETF fixes the missing textures (either on a new or an old world), sorry if it wasn't clear in my first post.

**Comment by Xelbayria** [comment]
No worries. Now we know who is the real culprit. There is nothing I can do on Every Compat's side.
