### ISSUE TITLE
[📦]: Timber Frames

### ISSUE THREAD

**Issue by LenKagamine** [MehVahdJukaar/WoodGood#615]
## REASON for v1.18.2: 

Won't add to v1.18.2 blc it has too much of works and the code is very old and it required a lot of custom classes to make it work. 

### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/timber-frames

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [ ] 1.19.2
- [X] 1.20.1

### MODID

timber_frames

### Types

**Block:**
- {woodtype}_timber_frame_alpha

### Optional Details

Timber Frames adds in timber frames made from wood and clay. Textures can be changed with a broad knife, and the clay texture for nether wood timber frames is darker.

**Comment by Xelbayria** [comment]
Added to v2.6.77 (1.20.1)
