### ISSUE TITLE
[📦]: add burrowers mod

### ISSUE THREAD

**Issue by LandonsBS** [MehVahdJukaar/WoodGood#616]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/burrowers

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [ ] 1.20.1

### FORGE Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [x] 1.20.1

### MODID

Burrowers

### Types

I think none of the blocks are added yet

**Comment by Xelbayria** [comment]
Ok You'll have to keep an eye on this mod and if it adds a new block that have variant woods. Then you can update the information by just editing.

**Comment by LandonsBS** [comment]
im pretty sure it currently doesnt add any block that has variant woods it just adds a new woodset called rootwood

**Comment by Xelbayria** [comment]
I see. Then Every Compat should be able to detect that new woodset by "bass" sound. Otherwise, it's an issue on the mod's side. Some mod from 1.19.2 updated to 1.20.1 doesn't have the correct sound for a wood. 

will be closing this.
