### ISSUE TITLE
[🐞]: Every Compat breaks Cold Sweat and Lit it Up Mods

### ISSUE THREAD

**Issue by ThisOneMadow** [MehVahdJukaar/WoodGood#618]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.75

### Moonlight Lib Version

moonlight-1.20-2.13.2-forge

### Issue with mods

- Cold Sweat (ver. ColdSweat-2.3.4)
- Lit it Up (ver. lititup-1.20.1-4.16)

### Issue Detail

When attempting to light any campfire from the Every Compat mod while using the Lit It Up mod, the fire appears to levitate above the campfire instead of actually igniting it. 

Additionally, it seems that the Every Compat mod is removing any heat generated from the campfires when the Cold Sweat mod is active. Even the vanilla ones.

### OPTIONAL: To Produce

1) Place any campfire from the mods
2) Take Flint and Steel or Sparkling Flint (from Lit It Up)
3) Use it on any Campfire from Every Compat and the fire will be put on top of it instead of lightning it. **(Lit it Up)**
4) Also the campfires wont give any heat anymore **(Cold Sweat)**

**Comment by Xelbayria** [comment]
Fixed in v2.6.78

REASON: I forgot to add the tags `#minecraft:campfires` to the campfires from EveryComp
