### ISSUE TITLE
[Compat] The Graveyard coffins

### ISSUE THREAD

**Issue by saltyseadoggo** [MehVahdJukaar/WoodGood#62]
I would like to see this mod add compat with [The Graveyard](https://www.curseforge.com/minecraft/mc-mods/the-graveyard-forge)'s coffins, so they can be made from other mods' wood types.~

**Comment by Xelbayria** [comment]
## Reason: 
The Graveyard has its own model format, the OBJ format which Every Compat doesn't support in. It will take too much work to add support for the OBJ format.
