### ISSUE TITLE
[🐞]: New Update Crashes in Creative

### ISSUE THREAD

**Issue by AbelRunes** [MehVahdJukaar/WoodGood#621]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

evercomp-1.20-2.6.77

### Moonlight Lib Version

moonlight-1.20-2.13.2-forge

### Issue with mods

another_furniture

### Issue Detail

When changing game mod to creative it causes the game to crash. Or when in creative and trying to load the items it seems to also crash. Back porting it fixed the issue currently. The Crash report states its another furniture but I'm not sure if there's anything else.

### OPTIONAL: Latest.log | Crash-report Attachment

[crash-2024-10-02_17.20.35-client.txt](https://github.com/user-attachments/files/17237005/crash-2024-10-02_17.20.35-client.txt)

**Comment by Xelbayria** [comment]
REASON: The module for **Another Furniture** is missing the code to include the item in Inventory Tab. 

Fixed in v2.6.78

**Comment by Xelbayria** [comment]
More details: 

I ended up had to change the tab for the blocks from Every Compat to be put in `BUILDING_BLOCKS` instead of **Another Furniture (AF)**'s tab. 

there are issue between FORGE & FABRIC of **AF**'s tab. They are not "kind of" the same thing. 

## UPDATED: 

forget above. it's fixed.
