### ISSUE TITLE
[🐞]: Still Crashing, also Added/ Remvoed Items In JEI

### ISSUE THREAD

**Issue by AbelRunes** [MehVahdJukaar/WoodGood#622]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

evercomp-1.20-2.6.78

### Moonlight Lib Version

moonlight-1.20-2.13.2-forge

### Issue with mods

Another Furniture (Crash.)
Plenty of Golems, Born In Chaos, Enlightened, Sophisticated Storage, Biomes of Plenty, Fairlights plus a few others. (Maybe just JEI? I'm not sure if its the mods or JEI itself, there's no log of it just visual.)

### Issue Detail

So, I still get the crash whenever I change to creative and press E or start in creative and press E. I can see JEI whenever I'm in a backpack with Sophisticated Backpacks otherwise it just crashes. Survival is fine and loads correctly. I also noticed with this update and the previous one new items were added to JEI but its more images that the game needs to render then actual Items. Including command blocks, while also taking other mods like Sophisticated Storage or Fairylights and compressing them to a single Item. I'll include screenshots from the new update and the previous one for comparison.
I'm not sure if the compressing several items into one was intentional or not, but I rather place it in here just in case? And Im also sorry in advance for doing this a second time. 
Also as Im going over all of this it seems whatever the mod has added is now just in JEI. Including their icons for the mod tabs in creative. But with the Wood Good version 2.6.76 none of these are there? Including their icons for the mod tabs in creative. 
I also created a new world to test this just in case.

### OPTIONAL: Latest.log | Crash-report Attachment

[crash-2024-10-03_03.41.10-client.txt](https://github.com/user-attachments/files/17241587/crash-2024-10-03_03.41.10-client.txt)
(Adding or Compressing Items 2.6.77-.2.6.78)

<details>
<summary>Images</summary>

![Plenty of Golems](https://github.com/user-attachments/assets/1a024e2c-5819-4446-8a61-a74c4108faa1)
![BorninChaos](https://github.com/user-attachments/assets/f575096a-f7ba-4f36-98c5-092dbde8a2d3)
![Enlgithened](https://github.com/user-attachments/assets/1d642d83-db49-414a-a001-0fed49897eab)
![Storage](https://github.com/user-attachments/assets/0095ffb7-bf16-461d-ba12-e18e854cca56)
![Biomes](https://github.com/user-attachments/assets/574322b1-5645-46a9-816a-d9f8dd34d0f7)
![Fairyligths](https://github.com/user-attachments/assets/3795a06c-02a3-4707-99bd-a8bd875e8766)
(Previous Version 2.6.76)
![PlentyofGolemsPervious](https://github.com/user-attachments/assets/a6e3ea99-922a-4565-880d-a2aced94b934)
![BorninChaosPervious](https://github.com/user-attachments/assets/bef82f94-48fd-41cd-b691-672ade9a3a60)
![EnlgithenedPervious](https://github.com/user-attachments/assets/bc21c0c0-7b1c-4e87-b17c-e121d44bb496)
![StoragePervious](https://github.com/user-attachments/assets/233ab58c-0011-4090-8a4e-50d958dd7ab3)
![BiomesPervious](https://github.com/user-attachments/assets/6b9436a2-1cf1-42b8-8cc3-04846a8a878a)
![FairyligthsPervious](https://github.com/user-attachments/assets/57f2079c-5778-4f7b-aa89-bd01cb712cbd)

</details>

**Comment by Xelbayria** [comment]
Dont worry about this. it's fixed in v2.6.79

**Comment by AbelRunes** [comment]
The creative crashing or the items?

**Comment by Xelbayria** [comment]
it was the creative crashing. it was indeed **Another Furniture**, the situation is quite tricky. Anyway, it's all fixed.

**Comment by Xelbayria** [comment]
related to #621
