### ISSUE TITLE
[🐞]: Crash to desktop with latest version of Every Compat, Corail Pillar, and Decorative Blocks

### ISSUE THREAD

**Issue by Massanutten** [MehVahdJukaar/WoodGood#623]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.78

### Moonlight Lib Version

moonlight-1.20-2.13.2

### Issue with mods

Corail Pillar <corail_pillar-1.20.1-5.9.1>
Decorative Blocks <decorative_blocks-forge-1.20.1-4.1.3>

### Issue Detail

CTD immediately after entering a world and trying to open inventory. According to the crash log, it's a problem with Every Compat and Corail Pillar. Disabled Corail Pillar and tried again and encountered another CTD, this time caused by Decorative Blocks. Tried a third time with both Corail Pillar and Decorative Blocks disabled and encountered no further issues. 

### OPTIONAL: Latest.log | Crash-report Attachment

Corail Pillar crash:
[crash-2024-10-03_06.05.26-client.txt](https://github.com/user-attachments/files/17242677/crash-2024-10-03_06.05.26-client.txt)

Decorative Blocks crash:
[crash-2024-10-03_06.28.31-client.txt](https://github.com/user-attachments/files/17242899/crash-2024-10-03_06.28.31-client.txt)

### OPTIONAL: To Produce

Enter a Minecraft world and open inventory with Decorative Blocks and/or Corail PIllar and the latest version of Every Compat installed.

**Comment by gabepikamole** [comment]
will comment to say i'm having sort of the same issue. when creative mod is enabled and i open the inventory, game crashes. the first lines point to this mod. just tested disabling it and it worked just fine, it just didn't when i enabled turned lan on and opened the thing. will test going on a creative world from the getgo to see whether this mod really is the issue, but it seems like it is so far.

**Comment by Massanutten** [comment]
The newest version <everycomp-1.20-2.6.79> has fixed both issues for me

**Comment by gabepikamole** [comment]
ty!
