### ISSUE TITLE
[🐞]: Compatiablitiy with Chipped Gone. 

### ISSUE THREAD

**Issue by AbelRunes** [MehVahdJukaar/WoodGood#624]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

evercomp-1.20-2.6.79

### Moonlight Lib Version

moonlight-1.20-2.13.2-forge

### Issue with mods

Chipped

### Issue Detail

So I noticed that some of my build was gone with the new update. And realized that all Chipped compatibility is just gone with the other mods I have which is like biomes of plenty and undergarden.

**Comment by Xelbayria** [comment]
Let me check

**Comment by Xelbayria** [comment]
Found the problem. The Module for Chipped was disabled. I apologize for the trouble.

**Comment by Xelbayria** [comment]
Found the problem. The Chipped module has some blocks that doesn't have "tab" code included. and the module get skipped. 

I hope you have a backup world because this will be fixed in v2.6.80

**Comment by AbelRunes** [comment]
I do have a backup and back ported to 2.6.76

**Comment by Xelbayria** [comment]
👍🏻 good choice of version 2.6.76. v2.6.77 to 2.6.79 are a messy mod, bruh. 

Anyway, tell your friends to ensure that they have backed up their world (if they played in singleworld). It's a good thing you did. 

### a bit more story in what's going on
**Every Compat (EC)** added a code that require every Module to have `setTab` included for every block they supported. Chipped do not have `setTab` for the variant logs. The module get skipped as a result. (tbh, i did not expect this).

**Comment by Xelbayria** [comment]
Fixed in v2.6.80

**Comment by AbelRunes** [comment]
Sweet!

**Comment by Xelbayria** [comment]
I also fixed the missing texture for classic_\<type\>_trapdoor. Thanks for the report.
