### ISSUE TITLE
[🐞]: [Campfires] Missing Textures, No Recipes, and No Light

### ISSUE THREAD

**Issue by ThisOneMadow** [MehVahdJukaar/WoodGood#625]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.80

### Moonlight Lib Version

moonlight-1.20-2.13.2-forge

### Issue with mods

- **Under The Moon** (ver. UnderTheMoon_1.0.5)
- **Ad Astra** (ver. ad_astra-forge-1.20.1-1.15.5)
- **Upgrade Aquatic** (ver. upgrade_aquatic-1.20.1-6.0.1)
- **Regions Unexplored** (ver. RegionsUnexploredForge-0.5.6+1.20.1)

### Issue Detail

**Any added campfires don't emit light and have no crafting recipes.**
(Only from Beautiful Campfires are working correctly)

Also noticed some missing textures with:
- Sweptwood Campfire _(when Lit)_ **(Under The Moon)**
- Strophar Campfire **(Ad Astra)**
- Driftwood Campfire _(when Lit)_ **(Upgrade Aquatic)**
- Pink Bioshroom Campfire _(when Lit)_ **(Regions Unexplored)**
- Redwood Campfire _(when Lit)_ **(Regions Unexplored)**

This also applies to all Soul Campfires.

**Comment by Xelbayria** [comment]
Fixed in v2.6.81

- forgot to include the recipe 🤦🏻 
- fixed the missing texture (the culprit is _ad_astra:strophar_stem_)
- Fixed a few more things.
