### ISSUE TITLE
[🐞]: Building But Better Wooden Blocks Are No Longer Generated

### ISSUE THREAD

**Issue by autumnly24** [MehVahdJukaar/WoodGood#627]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.80

### Moonlight Lib Version

moonlight-1.20-2.13.2-forge

### Issue with mods

Building But Better (1.20.1 Forge, 1.0.1)

### Issue Detail

I have a modpack that includes both Every Compat and Building But Better. After updating Every Compat, None of the Generated BBB Blocks using different woodtypes exist, and have been deleted from builds.

### OPTIONAL: To Produce

- Launch Minecraft Forge 1.20.1 with Every Compat (the version provided), Building But Better, and a mod that adds compatible woodsets.
- See that none of the blocks are generated

**Comment by Xelbayria** [comment]
Hmm. I need to check the mod's source code

# UPDATE

Ok I see the Fabric side already have the module built-in for EveryCompat. But Forge side don't have it. 

NOTE: what i mean is the module is in the mod's source code, not EveryCompat's (the dev included that in the mod)

**Comment by Xelbayria** [comment]
Fixed/Restored on FORGE SIDE in v2.6.81
