### ISSUE TITLE
[🐞]: Malum woods in Workshop for handsome adventurer blocks behave strangely when broken

### ISSUE THREAD

**Issue by StellaRoomy** [MehVahdJukaar/WoodGood#635]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.82

### Moonlight Lib Version

moonlight-1.20-2.13.4

### Issue with mods

Malum <malum-1.20.1-1.6.2> - Workshop for handsome adventurer <workshop_for_handsome_adventurer--mc1.20.1--1.15.2>

### Issue Detail

Runewood and Soulwood "6 Slot" Tool Racks (triple, framed, partly framed) duplicate when broken, dropping both the top and bottom block

Runewood and Soulwood Workstations drop nothing when broken

### OPTIONAL: To Produce

1) Place the listed block(s)
2) Break the block
3) Item is duped, or Nothing Drops

**Comment by Xelbayria** [comment]
Fixed in v2.6.83
