### ISSUE TITLE
[🗃]: Valhesia Furniture Chairs

### ISSUE THREAD

**Issue by LenKagamine** [MehVahdJukaar/WoodGood#638]
### Minecraft Version

1.20.1

### Supported Mod Version

1.1.3

### Supported mod's Curseforge

https://www.curseforge.com/minecraft/mc-mods/valhelsia-furniture

### Details

Every Compat adds in variants for the chair and the chair with hay seat, but not for the chair with a colored seat.

**Comment by LenKagamine** [comment]
I also looked some more and there are no added wood variants for tables with tablecloth and no upholstered chairs are added, either.

**Comment by Xelbayria** [comment]
Ok can you make it clear? 
Are you saying that there are missing furniture/block that haven't been supported by EveryCompat (EC)? 
- Tables with tablecloth
- uphoistered chair

Just so you know, the reason why i won't add other furniture/blocks that have colors which is 16 separated block with 16 colors. it's too much. 

IIRC, it's the same for Tables With tablecloth, will check

**Comment by LenKagamine** [comment]
Yes, sorry, that's what I meant. I understand, it does sound like a lot of work.

**Comment by Xelbayria** [comment]
No worries. Now I know what's the problem. I'm going to check the mod to see what else i am missing.

**Comment by Xelbayria** [comment]
I haven't missed anything. EC supported 6 different furniture/block from the mod. but the rest of the other furniture have wool or tablecloth. I already mentioned the reason above. Unfortunately, they won't be added at all. 

<details>
<summary>If you want to know why</summary>
EveryComp = EC

let's do math, if I added 1 block: _upholstered_chair_ without the color. but included 16 blocks (colors). that's 17 blocks. 

if you use **Biomes O' Plenty** which adds ~ 12 woodTypes. How many blocks **EC** generated: 204 blocks for one type of block: _upholstered_chair_. The amount will be insane if table with tablecloth and others with 16 colors are included. 

</details>
