### ISSUE TITLE
[🐞]: Valhelsia Furniture desks do not connect

### ISSUE THREAD

**Issue by LenKagamine** [MehVahdJukaar/WoodGood#639]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

2.6.82

### Moonlight Lib Version

2.13.7

### Issue with mods

Valhelsia Furniture 1.1.3

### Issue Detail

Desks and Desk Drawers added by Every Compat do not connect to each other like base Valhelsia Furniture desks do.
![2024-10-11_18 19 43](https://github.com/user-attachments/assets/72e68620-34c5-4b9c-93d9-5e620940d96f)

**Comment by Xelbayria** [comment]
Can confirm the _DESK_ not connecting to _DESK_DRAWER_. Will investigate to find out how it works.

**Comment by Xelbayria** [comment]
Fixed in v2.6.84
