### ISSUE TITLE
[🐞]: Every Compat's Tiki Torch has no Lights + no other Ceiling Fan Lights(?)

### ISSUE THREAD

**Issue by Fyshishark** [MehVahdJukaar/WoodGood#642]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.83.jar

### Moonlight Lib Version

moonlight-1.20-2.13.7-forge.jar

### Issue with mods

Macaw's Lights and Lamps
<mcw-lights-1.1.0-mc1.20.1forge>

Enlightend 
<enlightend-5.0.14-1.20.1>

Luminous Nether 
<LuminousNether V1.2 - Forge 1.20.1>

Jaden's Nether Expansion 
<Jadens-Nether-Expansion-2.0.2-Forge>

Undergarden 
<The_Undergarden-1.20.1-0.8.14>

### Issue Detail

The Tiki Torches for other mods do not emit lights...
![lightbug](https://github.com/user-attachments/assets/73ce0e46-0ee0-4554-a30c-7e2b1a01216d)

I've also found out that there are no Ceiling Fan Lights for the mentioned mods,
either there's a bug or it is not implemented yet
![lightbug2](https://github.com/user-attachments/assets/c72cd305-fae0-4103-b55b-93712d463795)

### OPTIONAL: To Produce

Tiki Torches issue
 1) Install the mentioned issue mods
 2) Acquire the modded Tiki Torches
 3) Place the modded Tiki Torches in the dark

Ceiling Fan Lights issue
 1) Install the mentioned issue mods
 2) Open the Creative Tab and check the Every Compat Tab or Search "Ceiling Fan Light" in Creative Tab

**Comment by Xelbayria** [comment]
### Fixed in v2.6.84

---

Ok Tiki Torches' issue should be fixed in v2.6.84 (will need your confirmation). 

and are you sure that _Ceiling Fan Lights_ is from macaw's Lights & Lamps. I've checked. and Nothing. I supposed it's from other mods.

**Comment by Fyshishark** [comment]
Alrigh thanks, I can't confirm the Tiki Torches issue yet as I assume v2.6.84 is still in review by the Curseforge and Modrinth moderators (it's not in files yet during the time of this comment)

also yes, the Ceiling Fan Light is indeed from Macaw's Lights & Lamps, I did isolate the WoodGoods and the other mods... Strange you can't find it in your side...
![Yes](https://github.com/user-attachments/assets/253701a3-cdcd-4551-8726-c4163f11491a)

**Comment by Xelbayria** [comment]
I haven't upload the v2.6.84 because there are other bugs I need to fix. And 🤔 what's the version of Macaw's Lights and Lamps?

**Comment by Fyshishark** [comment]
Ah okok, the version of Macaw's Lights and Lamps is: _v1.1.0 / mc1.20.1 - Forge_

Looking at its changelog, they've just added the Ceiling Fan Lights in this version

**Comment by Xelbayria** [comment]
alright, That will be included.

**Comment by Xelbayria** [comment]
### _ceiling_fan_light_ added to v2.6.84
