### ISSUE TITLE
[📦]: Macaw's Stairs

### ISSUE THREAD

**Issue by brisingraerowing** [MehVahdJukaar/WoodGood#643]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/macaws-stairs

### FABRIC Version Availability

- [ ] 1.18.2
- [ ] 1.19.2
- [X] 1.20.1

### FORGE Version Availability

- [X] 1.18.2
- [X] 1.19.2
- [X] 1.20.1

### MODID

mcwstairs

### Types

**Block:** - **_Edited by Xelbayria (Next time, please list them like below)_**
- terrace_stairs
- skyline_stairs
- compact_stairs
- loft_stairs
- bulk_stairs
- balconies
- railings
- platform

### Optional Details

Stair Railings can be added to any vanilla or modded stairs. Balcony railings can have up to four in one block. Both come in several styles that can be changed using shears.

**Comment by Xelbayria** [comment]
ADDED to: 
- v2.6.84 (1.20.1)
- v2.5.29 (1.19.2)
- v1.6.17 (1.18.2)
