### ISSUE TITLE
[🐞]: The inventory textures for a specific mod are bugging out.

### ISSUE THREAD

**Issue by MannazGORI** [MehVahdJukaar/WoodGood#644]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.84

### Moonlight Lib Version

moonlight-1.20-2.13.10-forge

### Issue with mods

Macaw's Doors
mcw-doors-1.1.1forge-mc1.20.1

### Issue Detail

In addition to the above-mentioned mod, when I individually used mods that add the following types of logs, the inventory textures for Macaw's Doors' doors bugged out.

Log-adding mods used for verifying the issue
caupona-1.20.1-0.4.9
mapletree-1.4.0

![2024-10-15_02 11 32](https://github.com/user-attachments/assets/6724e699-dcfb-4265-8708-8cb0c13b9789)
![2024-10-15_02 15 59](https://github.com/user-attachments/assets/2e480f9f-02c3-44d0-8e0f-ac11b9f4e532)

Forge Version
1.20.1 - 47.3.11

**Comment by MannazGORI** [comment]
I'm sorry if the sentences are strange because I'm using a translation function.

**Comment by Xelbayria** [comment]
no worries. I have a good idea of what's the problem.

**Comment by Xelbayria** [comment]
### Fixed in v2.6.84H. 

---

My guess was correct. Thanks for the report

**Comment by Xelbayria** [comment]
Uploaded to Curseforge, will take a while to get approval.  FYI, "H" in the version is just "hotfix". You should be good to go with that version.

**Comment by MannazGORI** [comment]
I tried the updated version. It's back to normal! Thank you for your hard work on the fix.
