### ISSUE TITLE
[🐞]: Macaw's Light, Wrong Light Level for Soul Tiki Torch

### ISSUE THREAD

**Issue by Fyshishark** [MehVahdJukaar/WoodGood#645]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.84H

### Moonlight Lib Version

moonlight-1.20-2.13.10-forge

### Issue with mods

Arts & Crafts 
<arts_and_crafts-forge-1.20.1-1.2.0>

Enlightend
<enlightend-5.0.14-1.20.1>

[Lets Do] BeachParty
<letsdo-beachparty-forge-1.1.5>

Luminious Nether
<Luminous Nether V1.2.1 - Forge 1.20.1>

Macaw's Lights and Lamps
<mcw-lights-1.1.0-mc1.20.1forge>

The Undergarden
<The_Undergarden-1.20.1-0.8.14>

### Issue Detail

Modded Soul Tiki Torches' light level are at 15, while the Vanilla Soul Tiki Torches' are at 10
![wronglevel](https://github.com/user-attachments/assets/19c935a4-58f7-4ced-8a2f-eb583ca7e804)

### OPTIONAL: To Produce

1) Install any mods with custom wood + Macaw's Lights mod
2) Aquire Soul Tiki Torches, both Vanilla Wood-type and Modded Wood-type
3) Press F3 to check for the differences of Light Level (Use the vanilla wood-type as the original comparison)

**Comment by Xelbayria** [comment]
oh 🤦🏻, I thought i've corrected the light level for soul_tiki_torches.

**Comment by Xelbayria** [comment]
### Fixed in v2.6.85
