### ISSUE TITLE
[🗃]:  Missing Azalea Post for caverns and chasms & quark integration 

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/WoodGood#648]
### Minecraft Version

1.20.1

### Supported Mod Version

3.0.0

### Supported mod's Curseforge

https://www.curseforge.com/minecraft/mc-mods/caverns-and-chasms

### Details

Azalea and posts were both added in a 1.18 version, however they are not registered for some reason

**Comment by Xelbayria** [comment]
Will check.

**Comment by Xelbayria** [comment]
I need to know which Furniture mod is it? 

EDIT:
🤦🏻‍♂️  just saw the title and it answered my question

**UPDATE**:
Just checked the source code. it has `.requireChildren("fence")` which mean it need a fence from woodType from wood mods

if a woodType don't have it, then it will get skipped. You should check in **Caverns & Chasms** to see if a WoodType has one or not

**Comment by Xelbayria** [comment]
### UPDATE: 
From what I find out is that **Caverns And Chasms** aren't available for 1.20.1. There is only 1.19.2 for the mod. Are you sure you got the right Wood mod that have Azalea?

**Comment by MehVahdJukaar** [comment]
We won't provide support form payed mods or mods that are not available for the current version on curseforge or modrinth

**Comment by thelegitdolt** [comment]
Aw

**Comment by thelegitdolt** [comment]
But this should break with every mod with azalea wood, like ecologics, so it’s still an important fix in my opinions

**Comment by MehVahdJukaar** [comment]
ecologics is hardcoded to not do that. We'll take a look at this once that mod is available for 1.20

**Comment by Xelbayria** [comment]
You can re-open this issue when the mod is available for 1.20.1.

**Comment by thelegitdolt** [comment]
Caverns and chasms is released for 1.20
