### ISSUE TITLE
[🐞]: quark hedges lack crafting recipes

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/WoodGood#649]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.84H.jar

### Moonlight Lib Version

moonlight-1.20-2.13.13-forge

### Issue with mods

Quark

### Issue Detail

Quark leaf hedges are not craftable.

**Comment by Xelbayria** [comment]
I need to know which wood mod is it?

and "leaf hedge"  do you meant "oak_hedge" or is it "oak_leaf_carpet"?

**Comment by thelegitdolt** [comment]
i mean hedges not leaf carpets. The hedges are from quark

**Comment by Xelbayria** [comment]
ok. it's _oak_hedge_

I know hedges are from quark.   wood mods are where woodTypes from

it can be Biomes O' Plenty or other wood mods.

FYI, EveryCompat use Wood mods and Furniture Mods to create blocks. Quark is Furniture Mod and the wood mods is unknown.

**Comment by thelegitdolt** [comment]
okay this is my mistake uhhh yeah they all have crafting recipes as normal

**Comment by Xelbayria** [comment]
What happened? 

EDIT:
nvm. i saw your message in other issue. Datapack is what broke the recipes. No worries.
