### ISSUE TITLE
[🐞]: No block added by this mod is tagged `minecraft:mineable/axe`

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/WoodGood#650]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.84H.jar

### Moonlight Lib Version

moonlight-1.20-2.13.13-forge

### Issue with mods

Architect's Palette, Quark, Farmer's Delight, Woodworks

### Issue Detail

Blocks added by this mod is not tagged `minecraft:mineable/axe` and is therefore not fast-mined with axes

**Comment by Xelbayria** [comment]
I need to know which blocks from each mod.

**Comment by thelegitdolt** [comment]
none of the blocks are tagged correctly

**Comment by thelegitdolt** [comment]
OK after further testing i don't thin kthis is true at all, i think i accidentally broke something because i was working with datapacks

**Comment by Xelbayria** [comment]
Ah ok I see.
