### ISSUE TITLE
[🐞]:  Reloading resource packs that modify every compat textures cause the mod to ungenerate its textures 

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/WoodGood#651]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

everycomp-1.20-2.6.84H.jar

### Moonlight Lib Version

moonlight-1.20-2.13.13-forge

### Issue with mods

This appears to happen with every mod.  I have installed Quark and Architect's Palette, and Autumnity. 

### Issue Detail

I have attempted to change some of every compat's assets with a texture pack
<img width="462" alt="Screenshot 2024-10-23 at 10 09 58 PM" src="https://github.com/user-attachments/assets/f7456dfe-f960-4b14-9c12-37611cecbd40">
The above shows the image of all of the files that I changed. 

When launching the game, everything is fine. However, if you reload the texture pack (F3 + T), the following happens: 

<img width="1512" alt="Screenshot 2024-10-23 at 10 06 12 PM" src="https://github.com/user-attachments/assets/14342769-916c-44fa-8cce-356505bdeda0">

### OPTIONAL: Latest.log | Crash-report Attachment

https://gist.github.com/thelegitdolt/7e954f055e8a87c5c7f7755b0bf2df57
An excerpt. This shows all the models not being loaded yada yada. 

### OPTIONAL: To Produce

1. Install this texture pack  (unzip into texture pack folder)
[dolt_mod_resource.zip](https://github.com/user-attachments/files/17501537/dolt_mod_resource.zip)
2. Launch the game with every compat installed as well as some mods that makes it generate some blocks I suppose
3. Reload the texture ack
4. Wow all the textures are gone

**Comment by Xelbayria** [comment]
I need the latest.log to look at the errors. The gist.github you provide is only pointing at the missing the model for planks and other blocks from a few different mods

**Comment by thelegitdolt** [comment]
i will give logs asap. I've also noticed that removing recipes + reloading will break the entire everycomp datapack

**Comment by Xelbayria** [comment]
Ok i've tested your resource pack. I had no problem but what I did is unzipped the ZIP

`dolt_mod_resource.zip > dolt_mod_resource > ...` 

I selected all of them and added to `dolt_mod_resource.zip` via context menu (**7-zip > add to dolt_mod_resource.zip**). The structure should look like this: 

```
dolt_mod_resource.zip
    L> assets
    L> pack.mcmeta
    L> so on...
```


and use it as a resource pack. You need to change one thing in `pack.mcmeta` which is 
- **"pack_format": 9,**

TO 

- **"pack_format": 15,**

how do i know it's 15. take a look at [pack_format](https://minecraft.fandom.com/wiki/Pack_format)

**Comment by thelegitdolt** [comment]
I changed my pack resource to 15 and can still reproduce the issue. Did you reload the texture pack after you launched it

**Comment by thelegitdolt** [comment]
<img width="1512" alt="Screenshot 2024-10-23 at 11 10 17 PM" src="https://github.com/user-attachments/assets/42be3299-ee8b-472a-a45d-0107389f57c8">

**Comment by Xelbayria** [comment]
Yes I also "reload the texture". 

Some of blocks from Quark like _hedges_ or _fences_, they don't need generated textures because they are using the vanilla textures from Minecraft. that applied to other wood mods (Biomes O' Plenty or Autumnity). 


You only have these: 
- Quark 
- Architect's Palette
- Autumnity.

correct, if there are 1 or 2 more wood mods, i need to know which one.

**Comment by thelegitdolt** [comment]
can you send the texture pack you used

**Comment by thelegitdolt** [comment]
this is a copy of my everycomp config
https://gist.github.com/thelegitdolt/60ea72fa572f138bf7894773bf5fb677
is there something here that owuld cuase any problems

**Comment by thelegitdolt** [comment]
> Some of blocks from Quark like hedges or fences, they don't need generated textures because they are using the vanilla textures from Minecraft. that applied to other wood mods (Biomes O' Plenty or Autumnity).

Yes, but they still require generated blockstates files and models, which is what is broken

**Comment by Xelbayria** [comment]
![github_issues_651](https://github.com/user-attachments/assets/cfc1b30d-7bf7-4b9a-b53d-751043621cbf)

That's what it looks like.  What i said in my post about the structure is very clear. 

> Yes, but they still require generated blockstates files and models, which is what is broken

They will get generated but something is preventing EveryCompat from finishing the job. It's the same recipes. you'll have to isolate all of mods down to one mod that is giving you the issue.

**Comment by thelegitdolt** [comment]
i will do that

**Comment by MehVahdJukaar** [comment]
i need latest.log

**Comment by thelegitdolt** [comment]
Hey! 

I can reproduce with Every Compat, Quark, Autumnity, Quark, Blueprint, and Moonlight. 

Please try my texture pack again with just these mods. 

Logs: 
[hi.txt](https://github.com/user-attachments/files/17510340/hi.txt)

**Comment by thelegitdolt** [comment]
This ALSO APPLIES to using a datapack to change recipes. After doing `/reload`, all every compat datapacks will disappear, so recipes and others will be gone.

**Comment by Xelbayria** [comment]
I had no problem with these mods you've mentioned. Try do it without datapack and if you have no problem, then Datapack's the culprit. 

### EDIT:
I looked at the latest.log: `Reloading ResourceManager: vanilla, mod_resources, Moonlight Mods Dynamic Assets, file/Detail-Brush-1.6-1.20, file/Farcr's Re-Crafted V2.12, file/Peeves - 1.19x, file/Up To Scratch V9, file/nomorezfightingironbars-1.13+.zip, file/soft_weather.zip, resources/dolt_mod_resource`

- **Peeves - 1.19x**, isn't it for 1.19.2. You should be using 1.20.1
- **nomorezfightingironbars-1.13+** - make sure it's compatible with 1.20.1 (check out the description)
- The rest I assumed should be 1.20.1
- The mods resources are fine

**Comment by thelegitdolt** [comment]
Resource packs will work for 1.20.1 even if they are made for a different version. Are you saying that using the 1.19.2 version of peeves is causing the texture pack reload issue? 


Can you please describe in greater detail how you are attempting to reproduce the bug? I am using Autumnity, Blueprint, Quark, Every Compat, Openloader, and Moonlight. 
https://gist.github.com/thelegitdolt/d2675663527332ea369917c5685487e3 This is my every compat configuration.
if you insert the texture pack i am using into the Openloader texture pack (you can run `/openloader folder resources` in game to bring it up), reload the texture pack, all every compat resources should disappear.

**Comment by thelegitdolt** [comment]
I am not using a datapack, I am using crafttweaker to remove certain recipes. If you install [Crafttweaker](https://modrinth.com/mod/crafttweaker/version/14.0.43) and put the following  file into your scripts folder (run `/ct scripts` to bring it up) 

https://cdn.discordapp.com/attachments/949164314852487218/1299090430037594112/hedge_make_good.zs?ex=671befbe&is=671a9e3e&hm=cf0ccc65ba56d450860d96a104eaecaaedd6b9e657e24b2be815807954f9febb&

On `/reload`, you should see that crafttweaker cannot find these recipes, all items added by every compat are missing recipes. (You can use JEI to see this).

**Comment by thelegitdolt** [comment]
I'm not sure how crafttweaker removes recipes but it is probably something datapack-related since i believe it is the same issue that is causing every compat textures to break after a texture reload

**Comment by Xelbayria** [comment]
I see. I have **CraftTweaker (CrT)** installed. and I don't have **Openloader**, i'll install and run a quick test.  and I'll try that script to see if I can reproduce the issue

I have the **dolt_mod_resource.zip** enabled. I tried to use `F3 + T` and `/reload` 
can't replicate the issue. this is clearly not EveryCompat's issue. something else is causing the issue. you have to find it.

**Comment by Xelbayria** [comment]
I've ran test with **Openloader** and another test with **CrT** using the script you provided. 

I can't replicate the issue. 

---

> On /reload, you should see that crafttweaker cannot find these recipes, all items added by every compat are missing recipes. (You can use JEI to see this).

I use EMI with JEI. yea I can tell what's going on. I don't see any errors when I ran `/reload` 

---

> I'm not sure how crafttweaker removes recipes but it is probably something datapack-related since i believe it is the same issue that is causing every compat textures to break after a texture reload

Simply, What **CrT** is doing is remove the recipes from the "RAM". so when you are crafting _hedge_, Minecraft would use "RAM" to look up recipes and found one that match what you are doing to output "hedge". 

"RAM" may not an appropriate term to describe where the resources are restored in. It's the same place that datapack, recipes, and textures are restored in.

**Comment by thelegitdolt** [comment]
i'll like make a video of exactly what i'm doing JUST IN CASE you are missing something, if not I've literally no idea what to do

**Comment by thelegitdolt** [comment]
https://gist.github.com/thelegitdolt/ac01e9a5428c4ced0ee3c5c3c31b2951 < latest.log
Okay i deleted + regenerated teh every compat config and this issue seems to have fixed itself. Yay!
```
	creative_tab = true
	#Makes dynamic assets that are generated depend on loaded resource packs. Turn off to make them just use vanilla assets
	assets_depend_on_loaded_packs = true
	#Creates a debug folder inside your instance directory where all the dynamically generated resources will be saved
	save_debug_resources = false
```
In my broken instance I had `assets_depend_on_loaded_packs` set to false and `save_debug_resources` set to true but after everything became default it was all fixed. Can you please try see if you can recreate this issue with the exact configs that I've sent

**Comment by MehVahdJukaar** [comment]
Depends on loaded packs makes EC only look at vanilla pack. That's it's purpose

**Comment by Xelbayria** [comment]
Ran a quick test on my side. I still can't replicate the issue. it's good that you got it all working properly.
