### ISSUE TITLE
[🗃]: Incomplete cutting board recipe support for farmer's delight

### ISSUE THREAD

**Issue by thelegitdolt** [MehVahdJukaar/WoodGood#652]
### Minecraft Version

1.20.1

### Supported Mod Version

1.2.4 

### Supported mod's Curseforge

https://modrinth.com/mod/farmers-delight (curseforge BAD!!)

### Details

On a farmer's delight cutting board, it is possible to axe hanging signs, doors, trapdoors, and signs into their respective planks. 

It is also possible to strip wood into stripped wood. 

<img width="444" alt="Screenshot 2024-10-23 at 10 25 45 PM" src="https://github.com/user-attachments/assets/47660668-a2ef-4223-be22-5a0f6b4ae7a9">
<img width="464" alt="Screenshot 2024-10-23 at 10 22 58 PM" src="https://github.com/user-attachments/assets/5cc83baa-acb9-48f7-a044-ff6bbba2e877">
<img width="455" alt="Screenshot 2024-10-23 at 10 23 00 PM" src="https://github.com/user-attachments/assets/ece72bb8-5b00-4939-be0e-57716c08a9fb">

Every compat does not add these recipes (there is only stripping logs as far as i can tell)

**Comment by Xelbayria** [comment]
Interesting. I don't know Farmer's Delight have more recipes

**Comment by Xelbayria** [comment]
## Fixed in 2.6.91

**Comment by thelegitdolt** [comment]
thank you xalbrai
