### ISSUE TITLE
[🐞]: Mod has failed to load correctly

### ISSUE THREAD

**Issue by katherinerempel99** [MehVahdJukaar/WoodGood#653]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Forge

### EveryCompat Version

1.20-2.6.85

### Moonlight Lib Version

1.20-2.13.16

### Issue with mods

DawnOfTime 1.5.7
Eldritch End 1.20.1-0.3.2

### Issue Detail

Mod seems to have an issue with either DawnOfTime or EldritchEnd. Won't load up game. Gives message "java.lang.NoSuchFieldError: INSTANCE"

### OPTIONAL: Latest.log | Crash-report Attachment

[crash-2024-10-27_19.12.05-fml.txt](https://github.com/user-attachments/files/17535930/crash-2024-10-27_19.12.05-fml.txt)
[latest.log](https://github.com/user-attachments/files/17535946/latest.log)

**Comment by Xelbayria** [comment]
Try without **Eldritch End** mod. 

EDIT:
nvm. I think i found the cause. fixed

**Comment by Xelbayria** [comment]
# Fixed in v2.6.87
