### ISSUE TITLE
[🐞]: crash on final load screen. Handcrafted, WilderWild, Dramatic Doors, and every comp incompatibility [1.21.1]

### ISSUE THREAD

**Issue by Sinogard** [MehVahdJukaar/WoodGood#656]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21

### Loader

Fabric

### EveryCompat Version

1.21-2.70

### Moonlight Lib Version

1.21-2.15.0

### Issue with mods

Looks like handcrafted, Wilderwilds, and Dramatic Doors are conflicting with everycomp. With those disable the game runs with my massive mod list. I expect Handcrafteds crash is due to the changable nature of the bed sheets, drapes, and other blocks that can be altered. 
Wilder wilds and Dramatic Doors i am less sure of see logs attached.

### Issue Detail

crashing just before the loading screen.

### OPTIONAL: Latest.log | Crash-report Attachment

[New Paste 1.txt](https://github.com/user-attachments/files/17581766/New.Paste.1.txt)
[2024-10-30-7.log](https://github.com/user-attachments/files/17582095/2024-10-30-7.log)

**Comment by Xelbayria** [comment]
## Wilder Wild is FIXED IN v2.7.1

--- 

now for other modules which I'm waiting for. going to fix them now.

**Comment by Xelbayria** [comment]
## Dramatic Doors (FABRIC & FORGE) is FIXED in v2.7.1

===

## Handcrafted (COMMON) is FIXED in v2.7.1

**Comment by Sinogard** [comment]
went ahead and downloaded the source and compiled it.
it crashed again giving a different error.
[2024-10-31-7.log](https://github.com/user-attachments/files/17594282/2024-10-31-7.log)
i had to copy and paste the error in from multiMC since it didnt write it into the log for some reason.

**Comment by Sinogard** [comment]
nevermind that last log. I figured out what i did wrong when building it. I am supposed to combine the common jar and the fabric jar together into one jar, no? after doing that i got this crash log. 
[latest.log](https://github.com/user-attachments/files/17594491/latest.log)

**Comment by Xelbayria** [comment]
I know about problem. I'm trying to find out what the heck is going on. I had no problem on my side. 

EDIT: 

> nevermind that last log. I figured out what i did wrong when building it. I am supposed to combine the common jar and the fabric jar together into one jar, no? after doing that i got this crash log.

Don't worry about it. You just let the IDE build it for you using COMMON and FABRIC. it's the same for NEOFORGE. 

if you are talking about "manually combining common.jar and fabric.jar". no that's not how it works. 

common is just source code for IDE to use.

**Comment by Sinogard** [comment]
latest release runs. not sure why the source didnt build correctly but the issue seems resolved.

**Comment by Xelbayria** [comment]
👍🏻 It turned out I had to use `gradle clean` to clean up the existing stuff. so it can use the new source code (updated codes) including new version (2.7.X).
