### ISSUE TITLE
[🐞]: Crash on NeoForge 1.21.1, Error with loading config file early

### ISSUE THREAD

**Issue by ToxinZangoose** [MehVahdJukaar/WoodGood#658]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21.1

### Loader

Neoforge

### EveryCompat Version

EveryCompat 1.21-2.7.2

### Moonlight Lib Version

Moonlight - 1.21-2.15.2

### Issue with mods

Not an issue with other mods per se, but an issue with loading the config before it was generated.

### Issue Detail

I cannot boot up the latest version of 1.21.1 with Every Compat, I haven't tried without any other mods, but this mod is the issue since I can launch the game without it.

### OPTIONAL: Latest.log | Crash-report Attachment

https://mclo.gs/GXevCvv (With full mod list, including performance boosters.)

https://mclo.gs/3v2Ne45 (With performance boosters removed)

### OPTIONAL: To Produce

Place Every Compat into the mod folder.
Launch game.
Crash.

**Comment by Xelbayria** [comment]
Can you run with the following: 
- EveryComp
- Moonlight Lib
- Supported mods (choose one)
- Wood mods of your choice (Can be biomes O' plenty or others) 

Launch the minecraft. If you have no problem, then add 1 or 2 mods until you got the crash. then isolate 1 of 2 mods to see if you can reproduce the crash with just one mod

**Comment by ToxinZangoose** [comment]
I will try it out. Thank you for the response!

**Comment by ToxinZangoose** [comment]
Ok, after a painstaking couple of launches, I have found the culprit to be Colossal Chests. I will report this to the development team for that mod. Thank you again!

**Comment by Xelbayria** [comment]
I see. **Colossal Chests** isn't supported by EveryCompat. Good idea to report it to team. 

You're welcome.
