### ISSUE TITLE
[question] Renaming compat items

### ISSUE THREAD

**Issue by PixelatedBruh** [MehVahdJukaar/WoodGood#66]
Hi currently I am trying to rename a block that was created by the mod. example "dragon tree flower box" from another furnature mod.  using a resource packs lang file to change it to "red dragon tree flower box". The lang files in your mod only lets you rename the entire group. I cant rename one specific flower box. Is that even possible with how this mod works? if so I don't know how so I'm asking if you could tell me how I could. Thanks for the great mod regardless

**Comment by MehVahdJukaar** [comment]
You can rename single entries normally as any other item

**Comment by MehVahdJukaar** [comment]
You take the block Id, turn it into a translation line (block.everycomp....) and add a translation in your pack

**Comment by PixelatedBruh** [comment]
i tried to do that but it failed to work could you provide and example?

**Comment by MehVahdJukaar** [comment]
block.everycomp.af/quark/blossom_flower_box or if it doesn't work rescue / with .

**Comment by PixelatedBruh** [comment]
thanks
block.everycomp.af.dragon_tree_planter_box worked
I see my error was using slashes before. thank you for the help

**Comment by MehVahdJukaar** [comment]
Weird it worked tho, it should include the mod id the wood type is from (i.e. /quark/) as that is in th I'd itself. Is that the actual line you used?

**Comment by PixelatedBruh** [comment]
this is infact the line i used. it infact was able to change the blocks name as i wanted
