### ISSUE TITLE
[🐞]: Every Compat crashing with Regions Unexplored

### ISSUE THREAD

**Issue by Kw126** [MehVahdJukaar/WoodGood#663]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21

### Loader

Fabric

### EveryCompat Version

fabric_1.21-2.7.2 (issue occurs on all versions available for 1.21 as of Nov 4/2024)

### Moonlight Lib Version

fabric_1.21-2.15.7

### Issue with mods

(Fabric 1.21) Regions Unexplored v0.5.6.1

### Issue Detail

Game crashes every time i try to launch it

### OPTIONAL: Latest.log | Crash-report Attachment

[crash-2024-11-04_01.33.17-client.txt](https://github.com/user-attachments/files/17614522/crash-2024-11-04_01.33.17-client.txt)

**Comment by Xelbayria** [comment]
I already updated the module for Regions Unexplored. 


## FIXED in v2.7.3
