### ISSUE TITLE
[🐞]: Crashes with Wilder Wild on 1.20.1 Fabric

### ISSUE THREAD

**Issue by emihead** [MehVahdJukaar/WoodGood#664]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.20.1

### Loader

Fabric

### EveryCompat Version

1.20-2.6.87

### Moonlight Lib Version

1.20-2.13.21

### Issue with mods

Wilder Wild 3.0.6-mc1.20.1

### Issue Detail

Every Compat doesn't work at all with this mod.
On versions above 1.20-2.6.72, the game crashes at startup. The game works fine on version .72 and below. This is interesting considering .73 is the version where the compat with this mod was added. I suspect it may be outdated.
I'm using a minimal modpack with just EC, WW, libraries, and Handcrafted to generate variants.

This seems to be the main issue: `java.lang.ClassNotFoundException: net.frozenblock.wilderwild.tag.WilderBlockTags`

### OPTIONAL: Latest.log | Crash-report Attachment

Log: https://mclo.gs/N7KH3zh

### OPTIONAL: To Produce

1. Install the aforementioned mods
2. Launch the game

**Comment by Xelbayria** [comment]
> This seems to be the main issue: java.lang.ClassNotFoundException: net.frozenblock.wilderwild.tag.WilderBlockTags

You are correct. I don't have to investigate. I already know what's the problem. 

`WilderBlockTags` is now changed to `WWBlockTags`. This mean the changed code is back-ported from 1.21 (that's how i know) 

for now downgrade to **WilderWild**'s older version, and it will work fine on your side.

**Comment by emihead** [comment]
It seems to be that the latest working version of WW is from a large number of updates ago, which is really unfortunate.
There's no rush, but do let me know if/when you end up backporting the fixes. I tried editing and building the mod from source myself but I greatly underestimated how much goes into a seemingly small change like that.

**Comment by Xelbayria** [comment]
> I greatly underestimated how much goes into a seemingly small change like that.

make that two, i too underestimated that even a small change can cause a crash. *sigh* 

It's not much of works to fix the problem. no worries

**Comment by Xelbayria** [comment]
### Fixed in v2.6.88

**Comment by emihead** [comment]
Sorry if this is a silly question, but is this an unreleased update or am I looking in the wrong place? I don't see it on Modrinth or Curseforge

**Comment by Xelbayria** [comment]
"Uploaded" and "Fixed" are two different things. So the new version haven't been uploaded yet. there are other bugs I need to fix. 
You should downgrade **Wilder Wild**, so you can play for now.

**Comment by emihead** [comment]
Ok, I understand, just wanted to make sure! Thank you for fixing the issue so quickly.
