### ISSUE TITLE
[🗃]: Storage Drawers created by Every Compat miss some of the tags

### ISSUE THREAD

**Issue by Dominus-Sicarum** [MehVahdJukaar/WoodGood#665]
### Minecraft Version

1.20.1

### Supported Mod Version

12.9.10

### Supported mod's Curseforge

https://www.curseforge.com/minecraft/mc-mods/storage-drawers

### Details

Namely:
storagedrawers:full_drawers
storagedrawers:half_drawers
storagedrawers:trim

Not a critical issue, but those are used in compacting drawers and framing table recipes.

**Comment by Xelbayria** [comment]
I see. Thanks for the report

**Comment by Xelbayria** [comment]
## Enhanced in v2.6.89
