### ISSUE TITLE
[🐞]: [1.21.1] Mod Crashed with CC:Tweaked and The Twilight Forest

### ISSUE THREAD

**Issue by Periam** [MehVahdJukaar/WoodGood#667]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21.1

### Loader

Neoforge

### EveryCompat Version

everycomp-1.21-2.7.2-neoforge.jar

### Moonlight Lib Version

moonlight-1.21-2.15.10-neoforge.jar

### Issue with mods

twilightforest-1.21.1-4.6.2790-universal.jar
jei-1.21.1-neoforge-19.21.0.247.jar
cc-tweaked-1.21.1-forge-1.113.1.jar

### Issue Detail

When the mod was installed the old and new world do not load.

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/user-attachments/files/17625074/latest.log)
[crash-2024-11-04_20.44.27-server.txt](https://github.com/user-attachments/files/17625075/crash-2024-11-04_20.44.27-server.txt)

**Comment by CsillaAria** [comment]
Having the same issue. 

Crash report:  https://bytebin.lucko.me/K1JmbEM2qc

Latest log:  https://bytebin.lucko.me/BrUzK8RNxu

**Comment by Xelbayria** [comment]
### CAUSE: 
- Creative Tabs

**Comment by Xelbayria** [comment]
This will take a while. The bug is quite troublesome and not easy to solve.

**Comment by Xelbayria** [comment]
## FIXED in Moonlight lib v2.16.2

---
Update your Moonlight lib to ☝🏻

**Comment by Xelbayria** [comment]
Uploading **Moonlight Lib v2.16.3** - Fixed the Stonecutter Recipe not being generated via **EveryCompat**

This applied to **The Twilight Forest**. 

Have fun!
