### ISSUE TITLE
[🐞]: recipes not generated using chipped crafting stations

### ISSUE THREAD

**Issue by Sinogard** [MehVahdJukaar/WoodGood#668]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.21.1

### Loader

Fabric

### EveryCompat Version

1.21-2.7.2

### Moonlight Lib Version

1.21-2.15.12

### Issue with mods

Chipped 4.0.2

### Issue Detail

recipes not generated for new recipes using chipped crafting stations.

**Comment by Xelbayria** [comment]
## Fixed in v2.7.3
