### ISSUE TITLE
[🐞]: Failed to load correctly (1.18.2)

### ISSUE THREAD

**Issue by TheQuacken02** [MehVahdJukaar/WoodGood#671]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version

1.18.2

### Loader

Forge

### EveryCompat Version

1.6.14

### Moonlight Lib Version

1.17.14

### Issue with mods

unknown conflict?

### Issue Detail

everytime on every version of Everycomp it comes up with the same "failed to load correctly" i tried using diffrent versions of everycomp as well as diffrent Moonligh lib versions, deleting mods and still nothing has changed ;-;

### OPTIONAL: Latest.log | Crash-report Attachment

https://paste.ee/p/Gb65o

**Comment by Xelbayria** [comment]
I've encountered this before. Try do a right-click on the desktop, to open up a context menu. Select the "refresh". 

Let me know if you don't understand. Desktop is where you just right-click on the background of your personal Image. 

Then try run the Minecraft again with the mods you had that failed to successfully launch the minecraft.

**Comment by TheQuacken02** [comment]
> I've encountered this before. Try do a right-click on the desktop, to open up a context menu. Select the "refresh".
> 
> Let me know if you don't understand. Desktop is where you just right-click on the background of your personal Image.
> 
> Then try run the Minecraft again with the mods you had that failed to successfully launch the minecraft.

i tried and unfortunatly still comesd up with fail to load correctly

**Comment by Xelbayria** [comment]
tbh i don't know what caused it. I have encountered it on my side a few times. 

let me know if you don't understand what i said in my previous message. I'll send you a picture

**Comment by TheQuacken02** [comment]
@Xelbayria  think i did it right, just right clicking the desk top to refresh everything but it hasnt helped im afraid

**Comment by Xelbayria** [comment]
Alright, Disable all of the mods except:
- EveryCompat
- Moonlight lib
- Furniture mods (like macaw's mods) 
- Wood mods (Biomes O' Plenty) 

try launch the minecraft. If you have no problem with the launching, then you can enable 1-2 mods until the launch failed. With that we'll find out who is the culprit.

**Comment by WonderSnail** [comment]
Just had this same issue, and apparently the storage shelves mod was the culprit. It's a pretty common mod so I wouldn't be surprised if this applies here

**Comment by Xelbayria** [comment]
Storage shelves from which mods?  I'm currently working on 1.18.2 to finish a few bugs and new modules 

@WonderSnail I'll need the report-crash from your side. You can use mclo.gs website and share the link here. 

and @TheQuacken02 I found the problem: 

`com/fizzware/dramaticdoors/blocks/ShortDoorBlock`, Dramatic Doors is the culprit. I'll get this fixed.

**Comment by WonderSnail** [comment]
here's the crash report, disabling [this mod](https://www.curseforge.com/minecraft/mc-mods/storage-drawers) fixed the issue.
[crash-2024-11-13_13.27.19-fml.txt](https://github.com/user-attachments/files/17738833/crash-2024-11-13_13.27.19-fml.txt)

**Comment by Xelbayria** [comment]
what a coincidence, i was working on the Storage Drawers Module.

**Comment by Xelbayria** [comment]
I took another look at the crash report. I saw that you used EveryCompat **v1.6.16** which is good. 

BUT I noticed that you are using older version of Storage Drawers: v10.2.1. the latest version is v10.3.0

the older version is what caused your Minecraft to crash.

**Comment by Xelbayria** [comment]
@TheQuacken02 

There was nothing to fix. Just like @WonderSnail was using the older version. You too were using an older version of Dramatic Doors (the latest version is v2.3.1_4)

*sigh*

There is a reason why you always must do this: 

`- [ ] Always check you are using the latest version of the mods and its dependencies`

**Comment by TheQuacken02** [comment]
@Xelbayria hey so sorry for not responding my pc needed repairing, ive removed said storage mod as well as get the most recent versions. it all worked but i did find a conflict with a mod called Nekoration, ive known the mod to be the colprrite of conflicts so hopefuly this helps too

**Comment by Xelbayria** [comment]
No worries. what's the problem with Nekoration?

**Comment by TheQuacken02** [comment]
@Xelbayria  it comes up with "error during the error event phase" it used to do this with macaws doors but now just dosnt like every comp, i think its more on that mods end. i apoligies in advance as i really struggle to read logs due to dyslexia XD but heres the crash report for it. 

([Nekoration](https://www.curseforge.com/minecraft/mc-mods/nekoration) is the most recent version too as well as its dependance [Patchouli](https://www.curseforge.com/minecraft/mc-mods/patchouli))

https://paste.ee/p/BJFlN

**Comment by Xelbayria** [comment]
I've ran test on my side. The issue is on **Nekoration** mod according to the crash report. 

If you launched Minecraft with only **Nekoration** and **Patchouli**, then you still get the crash. yea. Some people reported the same thing in the comments via Nekoration's Curseforge. 

The Dev's last active was 2 years ago.

**Comment by TheQuacken02** [comment]
@Xelbayria Thats so weird ? it works alonside my other mods?

**Comment by Xelbayria** [comment]
I've ran a quick test because of comment i saw in Nekoration. it looks like **Nekoration** is doing fine but has a conflict with **Dramatic Doors**. The Dev of **Dramatic Doors** is aware of this since October 2024.

I ran another test with just **EveryCompat** & **Nekoration**, i had no problem. I recommend that you remove **Dramatic Doors** if you want to use **Nekoration**. otherwise, remove **Nekoration**, if you want to use **Dramatic Doors**

**Comment by TheQuacken02** [comment]
@Xelbayria well thats a good thing that its been made aware, thank you so much for all the help ^^
