### ISSUE TITLE
[🗃]: Painted planks from Regions Unexplored 

### ISSUE THREAD

**Issue by Jay420blaze** [MehVahdJukaar/WoodGood#677]
### Minecraft Version

1.20.1

### Supported Mod Version

v0.5.6

### Supported mod's Curseforge

https://www.curseforge.com/minecraft/mc-mods/regions-unexplored

### Details

Regions unexplored adds 16 variants of "painted" planks. I would like to see these supported. Thanks!

**Comment by Xelbayria** [comment]
Wait a min. 16 variants of "painted" planks?   you meant 16 color for a woodType? It's not worth the trouble. 

if you do math: with Biomes O' Plenty's 19 WoodTypes (IIRC) 

that's 16 * 19 = 304 blocks added by EveryCompat.

**Comment by MehVahdJukaar** [comment]
do those block provide AT LEAST vanilla wood variant blocks (stairs, fences, boats,signs..)?

**Comment by Xelbayria** [comment]
I've investigated. The system is very simple. 

the tags: `#minecraft:planks` and `#forge:planks` can be added to planks from any wood mods. These planks with the tags can be used as ingredients to craft painted planks.

Best way to do this is 
1) create a resource pack and create JSON file with name "planks" via `~/data/tags/minecraft/blocks/...` and `~/data/tags/minecraft/items/...` IIRC

2) Use KubeJS or CraftTweaker to add the tags to these planks from wood mods.

**Comment by Xelbayria** [comment]
The planks from other wood mods are now added with the tags so you can use them to get painted planks. 

## ENHANCED IN v2.6.90

--- 

What i said in my previous is a temporary solution until i got the time to add this. All done.
