### ISSUE TITLE
[🐞]: Farmer's Delight and Let's do vinery

### ISSUE THREAD

**Issue by Goldocelot** [MehVahdJukaar/WoodGood#680]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader

1.21.X - NEOFORGE

### EveryCompat Version

everycomp-1.21-2.7.2-neoforge

### Moonlight Lib Version

moonlight-1.21-2.15.11-neoforge

### Issue with mods

Farmer's Delight
FarmersDelight-1.21.1-1.2.5

Let's do vinery (and it's libs)
letsdo-vinery-neoforge-1.5.0-beta-release
letsdo-API-forge-1.3.0-beta-release-forge
architectury-13.0.8-neoforge

### Issue Detail

With Every Compat (Wood Good), Farmer's Delight and Let's do vinery opening the inventory in creative mod make the game crash.

I've tested the others mods without Every Compat (Wood Good) and everything works well.

### OPTIONAL: Latest.log | Crash-report Attachment

[crash-2024-11-11_16.07.50-client.txt](https://github.com/user-attachments/files/17704183/crash-2024-11-11_16.07.50-client.txt)

### OPTIONAL: To Produce

1) Set your gamemode in creative
2) Open your inventory
3) The bug happen here

**Comment by Xelbayria** [comment]
## FIXED in Moonlight Lib v2.16.2

---

This took a while to find the real cause. **The Twilight Forest** have the same problem.
