### ISSUE TITLE
[🐞]: IDK if this is a bug, but I have ~20% performance (fps) decrease (from ~55 to ~45 fps) when having this installed

### ISSUE THREAD

**Issue by MikiP98** [MehVahdJukaar/WoodGood#681]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [ ] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [ ] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader

1.20.1 - FABRIC

### EveryCompat Version

EveryCompat-1.20-2.6.88

### Moonlight Lib Version

Moonlight-Lib-fabric_1.20-2.13.25

### Issue with mods

I have >400 mods, if I find the time I will do a binary search through them to maybe find which mod combo gives the performance decrease.
Notable mods for this mod might be:
- BoP
- Another Furniture
- Valhelsia Furniture
- MrCrayfish's Furniture Mod: Refurbished
- Macaw's Holidays

As you can probably imagine I have Embeddium and other performance mods still enabled, I though that posting the issue was more important then the rules here, sorry about that, I don't have the time right now to play with it now.

### Issue Detail

When running the game with this mod installed I noticed significantly less fps, I went from ~55 without this mod to ~45 with this mod.
I disabled the mod, checked the fps, enabled the mod back and checked the fps, 2 times and the fps drop was consistent.

I don't think that this mod should give such a performance difference...
I just wanted you to know such issue exists and with limited information I gave I don't expect it to be fixed anytime soon...

### OPTIONAL: Latest.log | Crash-report Attachment

Log without this mod:
[latest.log](https://github.com/user-attachments/files/17707067/latest.log)

Log with this mod:
[latest.log](https://github.com/user-attachments/files/17707196/latest.log)

### OPTIONAL: To Produce

I can export the modpack in Modrinth, and edit in a lint to it here if you want easy reproduction steps.
With the modpack installed it will be:
- Open the game with this mod enabled and see the lower fps...

**Comment by MehVahdJukaar** [comment]
Sounds like you are running out of ram. I can see that you got EC to register 1700 blocks, 17% of the ones you have there. Ram increase you would need would be proportionate to that

**Comment by MikiP98** [comment]
I will check in a moment, right now I had 16 GB allocated and after GC clear it was dropping to <7 GB.  
I will allocate 24 GB and report back.

**Comment by MikiP98** [comment]
Seems it helped, there still seems to be a small 2-3 fps decrease, but it is much more manageable.  
It it a huge amount or RAM usage though, I think I will need to remove this mod from the modpack, as of my friends have only 16 GB in their systems.

You can add to the faq: `If performance decreases, allocate more RAM to MC and close all background apps`
Or just mention that is is very memory hungry.
Decision is yours though.

You can close the issue if you want, THX for help :)

**Comment by Xelbayria** [comment]
Another option is to remove a wood mod (one that have like 19 woodTypes) 

last option is to remove one of furniture mods (Like Chipped, it has lot of blocks)

**Comment by MehVahdJukaar** [comment]
The memory increase is, on the average mospack, pretty much proportionate to the amount of mods, with just some mods on you won't have anything to worry about, alone it consumes 0, but start adding wood mods and lyi can see how the amount of blocks registry could easily explode. Up to the user to not install a billion furniture mods or decide wether they want quantity over quality
