### ISSUE TITLE
[🗃]: MrCrayfish's Furniture Mod: Refurbished

### ISSUE THREAD

**Issue by DarthCaesium** [MehVahdJukaar/WoodGood#684]
### Before Continuing:

- [X] See [EC Backlog](https://github.com/users/MehVahdJukaar/projects/1/views/1) if someone already suggested a mod that you are going to suggest.

### Curseforge (Normal)

https://www.curseforge.com/minecraft/mc-mods/refurbished-furniture

### Version

1.21.X - FABRIC
1.21.X - FORGE

### MODID

refurbished-furniture

### Details

The models for MrCrayfish's Furniture Mod: Refurbished have been updated compared to his original mod. Currently, there's an incompatibility between Every Compat and this mod because of it.

**Comment by Xelbayria** [comment]
Next time, use "Module Enhancement" when you are creating a new issue. FYI, EveryCompat already support the mod. 

What's the Minecraft Version?

**Comment by DarthCaesium** [comment]
1.21.1. I get the purple and black checkerboard textures for all of these blocks' variants.

**Comment by Xelbayria** [comment]
ok gotcha. I am going to investigate to see what changed.

**Comment by Xelbayria** [comment]
### FIXED in v2.7.4
