### ISSUE TITLE
[🐞]: NeoForge 1.21.1 Crash with Furnish

### ISSUE THREAD

**Issue by NovaViper** [MehVahdJukaar/WoodGood#686]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader

1.21.1-NEOFORGE

### EveryCompat Version

1.21-2.7.3

### Moonlight Lib Version

1.21-2.15.14

### Issue with mods

Furnish v27

### Issue Detail

Immediately crashes when loading up the game with Furnish and EveryCompact (also the error persists even with just only, with the error in the logs: ` class net.mehvahdjukaar.every_compat.neoforge.EveryCompatForge java.lang.NoSuchFieldError: Class io.github.wouink.furnish.Furnish does not have member field 'dev.architectury.registry.registries.RegistrySupplier CREATIVE_TAB'`

### OPTIONAL: Latest.log | Crash-report Attachment

https://mclo.gs/RdTee9N

**Comment by Xelbayria** [comment]
### FIXED in v2.7.4
