### ISSUE TITLE
[🐞]: Missing Texture of Functional Storage

### ISSUE THREAD

**Issue by SSWTLZZ** [MehVahdJukaar/WoodGood#688]
### Before Continuing:

- [x] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader

1.20.1-FORGE

### EveryCompat Version

everycomp-1.20-2.6.90

### Moonlight Lib Version

moonlight-1.20-2.13.26-forge

### Issue with mods

Functional Storage 1.2.1-1.2.12

### Issue Detail

Missing Texture of Functional Storage
![image](https://github.com/user-attachments/assets/01b21f81-3479-4f91-b4e6-13f1684341d0)

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/user-attachments/files/17790556/latest.log)

**Comment by Xelbayria** [comment]
## FIXED in v2.6.92
