### ISSUE TITLE
[🐞]: Bewitchment Barks are not generating for Better End/Better Nether (Fabric 1.20.1)

### ISSUE THREAD

**Issue by Zhaith-Izaliel** [MehVahdJukaar/WoodGood#689]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader

1.20.1-FABRIC

### EveryCompat Version

everycompat-1.20-2.6.90

### Moonlight Lib Version

moonlight-1.20-2.13.25-fabric

### Issue with mods

- Bewitchment <1.20-10>
- Better End <4.0.11>
- Better Nether <9.0.10>

### Issue Detail

When using Every Compat does not generate the bark item and `AthameStrippingRecipes` associated with them for **every wood type** from Better End or Better Nether. 

I suspect this behavior occurs because Better End / Better Nether does not use the ID conventions for wood objects (i.e. stripped logs are called `betterend:end_lotus_stripped_log` instead of `betterend:stripped_end_lotus_log`, and `betternether:stalagnate_bark` instead of `.*_wood`, and its stripped version uses also `betternether:stalagnate_stripped_bark`, instead of `stripped_stalagnate_wood`).

It's important to note that the "Poppet Shelves" are generated correctly and use the correct textures. 

The entries for the woods from Better End and Better Nether are present in `config/everycomp-entries.json`.

**Comment by Xelbayria** [comment]
Your suspicion are correct, the IDs for stripped_log wasn't detected. I am quite surprised to see `_bark` for "_wood".  interesting IDs.

**Comment by Zhaith-Izaliel** [comment]
Yeah it's a bit annoying too: I'm making a modpack and I had to put conditions in my CT scripts for specific betterend / betternether wood types because of their naming conventions.

**Comment by Xelbayria** [comment]
Alright, The fix will be included in Moonlight Lib (it's responsible for detecting woodTypes and leaveTYpes)

**Comment by Zhaith-Izaliel** [comment]
Thank you for your reactivity ! Do you have an ETA on when you'll release a new version of the lib ?

**Comment by Xelbayria** [comment]
It's not much of works. I'm just adding the ID of WoodTypes.. I'll need the ID of planks and logs, too. 

then i can add stripped_log. all done

**Comment by Zhaith-Izaliel** [comment]
I can dump the ID for planks, logs and woods, gimme a minute or two

**Comment by Zhaith-Izaliel** [comment]
If I didn't miss one:
```
betterend:end_lotus_log,
betterend:end_lotus_planks,
betterend:end_lotus_bark,
betterend:jellyshroom_log,
betterend:jellyshroom_planks,
betterend:jellyshroom_bark,
betterend:lucernia_log,
betterend:lucernia_planks,
betterend:lucernia_bark,
betterend:mossy_glowshroom_log,
betterend:mossy_glowshroom_planks,
betterend:mossy_glowshroom_bark,
betterend:pythadendron_log,
betterend:pythadendron_planks,
betterend:pythadendron_bark,
betterend:dragon_tree_log,
betterend:dragon_tree_planks,
betterend:dragon_tree_bark,
betterend:helix_tree_log,
betterend:helix_tree_planks,
betterend:helix_tree_bark,
betterend:lacugrove_log,
betterend:lacugrove_planks,
betterend:lacugrove_bark,
betterend:tenanea_log,
betterend:tenanea_planks,
betterend:tenanea_bark,
betterend:umbrella_tree_log,
betterend:umbrella_tree_planks,
betterend:umbrella_tree_bark,
betternether:anchor_tree_log,
betternether:anchor_tree_planks,
betternether:anchor_tree_bark,
betternether:mushroom_fir_log,
betternether:mushroom_fir_planks,
betternether:mushroom_fir_bark,
betternether:nether_sakura_log,
betternether:nether_sakura_planks,
betternether:nether_sakura_bark,
betternether:nether_reed_planks,
betternether:nether_mushroom_planks,
betternether:rubeus_log,
betternether:rubeus_planks,
betternether:rubeus_bark,
betternether:stalagnate_log,
betternether:stalagnate_planks,
betternether:stalagnate_bark,
betternether:wart_log,
betternether:wart_planks,
betternether:wart_bark,
betternether:willow_log,
betternether:willow_planks,
betternether:willow_bark,
```

Note that for `betternether:nether_mushroom` and`betternether:nether_reed`, only the planks exists, there isn't a log nor wood version since it's more akin to a stem in the mod.

**Comment by Xelbayria** [comment]
oh wow. lot of them are using "bark"  that will take me a few minutes to add them.

**Comment by Zhaith-Izaliel** [comment]
I have another bug with Bewitchment (a rendering bug with the generated Poppet Shelves), I'll open another issue for this one.

**Comment by Zhaith-Izaliel** [comment]
> oh wow. lot of them are using "bark" that will take me a few minutes to add them.

Yeah they followed through their own convention but I would have preferred if they used the one in Minecraft lol

**Comment by Xelbayria** [comment]
Alright. 
about the nether_mushroom and nether_reed. 

does it have "block" along with "planks", i can use that "block" as a log. and if there is a stripped_log. i'll need the name, too

## EDIT:

> Yeah they followed through their own convention but I would have preferred if they used the one in Minecraft lol

make that 2. I've seen 1 mod that have their own convention. that's why i created a special code in Moonlight lib which will save me a lot of time 

i was right. that mods, Better Nether and Better End make 2nd and 3rd mods with their own convention

**Comment by Xelbayria** [comment]
Oh you forgot to add stripped_log in the list, too. i'll need it for the rest of woodTypes

**Comment by Zhaith-Izaliel** [comment]
There is no "log" nor "stripped log" for it. The nether reed is like tall grass and the nether mushroom has a stem specific item for it. They can't be stripped, so the AthameStrippingRecipe will not work with them. There is only planks + slabs / stairs etc. The rest of the craftable items are generated with everycomp so don't worry about it

**Comment by Zhaith-Izaliel** [comment]
> Oh you forgot to add stripped_log in the list, too. i'll need it for the rest of woodTypes

Sorry, I'll add everything

**Comment by Zhaith-Izaliel** [comment]
Here is the full list:
```
betterend:end_lotus_log,
betterend:end_lotus_stripped_log,
betterend:end_lotus_planks,
betterend:end_lotus_bark,
betterend:end_lotus_stripped_bark,
betterend:jellyshroom_log,
betterend:jellyshroom_stripped_log,
betterend:jellyshroom_planks,
betterend:jellyshroom_bark,
betterend:jellyshroom_stripped_bark,
betterend:lucernia_log,
betterend:lucernia_stripped_log,
betterend:lucernia_planks,
betterend:lucernia_bark,
betterend:lucernia_stripped_bark,
betterend:mossy_glowshroom_log,
betterend:mossy_glowshroom_stripped_log,
betterend:mossy_glowshroom_planks,
betterend:mossy_glowshroom_bark,
betterend:mossy_glowshroom_stripped_bark,
betterend:pythadendron_log,
betterend:pythadendron_stripped_log,
betterend:pythadendron_planks,
betterend:pythadendron_bark,
betterend:pythadendron_stripped_bark,
betterend:dragon_tree_log,
betterend:dragon_tree_stripped_log,
betterend:dragon_tree_planks,
betterend:dragon_tree_bark,
betterend:dragon_tree_stripped_bark,
betterend:helix_tree_log,
betterend:helix_tree_stripped_log,
betterend:helix_tree_planks,
betterend:helix_tree_bark,
betterend:helix_tree_stripped_bark,
betterend:lacugrove_log,
betterend:lacugrove_stripped_log,
betterend:lacugrove_planks,
betterend:lacugrove_bark,
betterend:lacugrove_stripped_bark,
betterend:tenanea_log,
betterend:tenanea_stripped_log,
betterend:tenanea_planks,
betterend:tenanea_bark,
betterend:tenanea_stripped_bark,
betterend:umbrella_tree_log,
betterend:umbrella_tree_stripped_log,
betterend:umbrella_tree_planks,
betterend:umbrella_tree_bark,
betterend:umbrella_tree_stripped_bark,
betternether:anchor_tree_log,
betternether:anchor_tree_stripped_log,
betternether:anchor_tree_planks,
betternether:anchor_tree_bark,
betternether:anchor_tree_stripped_bark,
betternether:mushroom_fir_log,
betternether:mushroom_fir_stripped_log,
betternether:mushroom_fir_planks,
betternether:mushroom_fir_bark,
betternether:mushroom_fir_stripped_bark,
betternether:nether_sakura_log,
betternether:nether_sakura_stripped_log,
betternether:nether_sakura_planks,
betternether:nether_sakura_bark,
betternether:nether_sakura_stripped_bark,
betternether:nether_reed_planks,
betternether:nether_mushroom_planks,
betternether:rubeus_log,
betternether:rubeus_stripped_log,
betternether:rubeus_planks,
betternether:rubeus_bark,
betternether:rubeus_stripped_bark,
betternether:stalagnate_log,
betternether:stalagnate_stripped_log,
betternether:stalagnate_planks,
betternether:stalagnate_bark,
betternether:stalagnate_stripped_bark,
betternether:wart_log,
betternether:wart_stripped_log,
betternether:wart_planks,
betternether:wart_bark,
betternether:wart_stripped_bark,
betternether:willow_log,
betternether:willow_stripped_log,
betternether:willow_planks,
betternether:willow_bark,
betternether:willow_stripped_bark,

```

**Comment by Xelbayria** [comment]
all done. now i need to run a quick test to ensure its' working

**Comment by Zhaith-Izaliel** [comment]
Alright, thank you for your work ! I let you close this issue when you're satisfied with the result :)

**Comment by Xelbayria** [comment]
One more thing to fix. 

lucernia_leaves texture need to be corrected. the name is different from convention naming. 🙄

**Comment by Xelbayria** [comment]
Uploaded to Curseforge & Modrinth. That should make your work for modpack easier! hopefully! ^_^

**Comment by Zhaith-Izaliel** [comment]
I tested the modification and it doesn't seem to propagate correctly with Every Compat (ie. it doesn't register the AthameStrippingRecipes automatically for BetterEnd and BetterNether, even with the latest moonight lib for 1.20.1. Is that to be expected ? If so, do you have a documentation on how I could access the moonlight lib API with crafttweaker ? (I would like to avoid writting my own mod for this modpack)

Thank you very much.

Moonlight Lib Version: <1.20-2.13.27> for Fabric 1.20.1

**Comment by Xelbayria** [comment]
AthameStrippingRecipes. which mod is it from?

**Comment by Zhaith-Izaliel** [comment]
Bewitchment, it's the recipe you do by right clicking with the Athame a log or wood block that has a bark. The barks item for bewitchment are not generated for betterend / betternether, but works with other modded wood type

**Comment by Xelbayria** [comment]
let me check

**Comment by Xelbayria** [comment]
I remember that AthamesStripping Recipe. I am the one who added that in the module to support that recipe. 

it required `stripped_log`.. so you get a log with the athame tool to get a stripped_log and a bark 


EDIT: 
hmm Moonlight lib should have fixed that. I'll need to check

**Comment by Xelbayria** [comment]
Aargghhh. I found a mistake in Moonlight Lib. waaaa.  this `betterend:end_lotus_stripped_log,`

in the code, it was looking for `betterend:stripped_end_lotus_log,` that's why it wasn't detected. 🤦🏻 

a quick fix will be in v2.13.28

The `stripped_wood` are correct. I'll let u know when new moonlight lib is uploaded to Curseforge.

**Comment by Zhaith-Izaliel** [comment]
> Aargghhh. I found a mistake in Moonlight Lib. waaaa. this `betterend:end_lotus_stripped_log,`
> 
> in the code, it was looking for `betterend:stripped_end_lotus_log,` that's why it wasn't detected. 🤦🏻
> 
> a quick fix will be in v2.13.28
> 
> The `stripped_wood` are correct. I'll let u know when new moonlight lib is uploaded to Curseforge.

Thank you, so I wasn't crazy after all lmao.

I use modrinth so as long as it is available on this one I can fetch the update using packwiz and ferium :blush:

**Comment by Xelbayria** [comment]
## Fixed. 

---

I really want to chock the dev of Better Nether & Better End for the dang "bark". It took me a while to figure out the real cause. 

Moonlight Lib's issue was corrected BUT it's not the only issue. EveryCompat has a system that check for "blockType". It's to prevent duplication of the same thing. 


in this case `betterend:end_lotus_stripped_bark` from BetterEnd is considered to be a BlockType named "bark". The "bark" from Bewitchment is also a BlockType/ItemType. EveryCompat will use the BlockType with "bark" from Bewitchment on wood mods (BetterEnd) to see if it already exist or not. 

if it already exist, then it will be skipped. Remember above: `It's to prevent duplication of the same thing.`

Anyway, it's all fixed.

**Comment by Zhaith-Izaliel** [comment]
I'll open an issue on their repos to try make some changes in their wood IDs naming convention, linking this issue for the trouble. We'll see if that changes anything.

As always, thank you for your work !

**Comment by Xelbayria** [comment]
if they won't fix it. then don't worry about it. 

beside that, i added this to EveryCompat (it's not much of work): 

```java
// Better Nether & Better End have stripped_bark as stripped_wood but bark from Bewitchment caused EC to skip        
if (woodFrom.matches("betternether|betterend") && name.contains("bark")) return false;
```

it's in a method called `isEntryAlreadyRegistered()` as you can see its' purpose


## EDIT: 

Uploaded Moonlight Lib v2.13.28 to Curseforge & Modrinth

# AND

Uploaded EveryCompat v2.6.91

ALL DONE. Have fun with the modpack! @Zhaith-Izaliel

**Comment by Xelbayria** [comment]
Let me know if they are planning to fix the naming convention blc i need to update Moonlight Lib to account for the changes in Better Nether and Better End

the naming convention just have to be same as Minecraft's `stripped_<woodType>_log` same for wood and stripped_wood. that's it.

**Comment by Zhaith-Izaliel** [comment]
> Let me know if they are planning to fix the naming convention blc i need to update Moonlight Lib to account for the changes in Better Nether and Better End
> 
> the naming convention just have to be same as Minecraft's `stripped_<woodType>_log` same for wood and stripped_wood. that's it.

yes no problem, I'll open an issue on upstream moonlight lib if the change is adopted to betterend / betternether (linking the relevant issues as well as this one)

**Comment by MehVahdJukaar** [comment]
I'm pretty sure I blacklisted those 2 mods entirely as those are dynamic generated and can't really work well with EC as it does the same. Much of their assets aren't available when EC queries for them so it just causes problems I just decided to exclude them

**Comment by Xelbayria** [comment]
Interesting. does the dynamic generation included the textures? Is that why EC failed to find them? 

When I ran these 2 mods with EC, there was no problem on my side. but their naming convention or ID wasn't the standard naming.

**Comment by Zhaith-Izaliel** [comment]
Honnestly, I think it would be sad to loose access to Better End and Better Nether in EC when most of the textures seem to load and work correctly, besides the nether mushroom and nether reed "logs" @Xelbayria took care about in another issue I raised. It would be better if they changed their ID naming convention, but other than that, it seems to work fine with EC. Let's see with subsequent versions though.
