### ISSUE TITLE
[1.19.2] Server crashes while trying to strip a log with immersive weathering installed

### ISSUE THREAD

**Issue by baooduy** [MehVahdJukaar/WoodGood#69]
Here's the crash log
[crash-2022-10-21_17.04.37-server.txt](https://github.com/MehVahdJukaar/WoodGood/files/9841093/crash-2022-10-21_17.04.37-server.txt)

**Comment by MehVahdJukaar** [comment]
Are you on latest IW version?

**Comment by baooduy** [comment]
Yes

**Comment by baooduy** [comment]
Oh my bad, only the client is on the latest version, the server isnt
