### ISSUE TITLE
[🐞]: Bewitchment Poppet Shelves' back de-render solid blocks

### ISSUE THREAD

**Issue by Zhaith-Izaliel** [MehVahdJukaar/WoodGood#690]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader

1.20.1-FABRIC

### EveryCompat Version

everycompat-1.20-2.6.90

### Moonlight Lib Version

moonlight-1.20-2.13.25-fabric

### Issue with mods

- Bewitchment <1.20-10>
- Any modded woods.

### Issue Detail

The generated Poppet Shelves de-render solid blocks when placed directly against a solid bock. You can see here in the screenshot, I used the baobab tree from Biomes We've Gone but this issue is consistent with every modded woods I tested (Paradise Lost, Biomes We've Gone, Biomes'O'Plenty, Better End, Better Nether)

Here is a screenshot: 
![image](https://github.com/user-attachments/assets/7d6b3ffe-77a7-42aa-82c2-89b946ef425f)

You can see the difference with the native Poppet Shelves on the right (dark oak in that case):
![image](https://github.com/user-attachments/assets/cc594950-af5e-4335-8b11-b16c32678025)

**Comment by Xelbayria** [comment]
I see! I know where is the problem. easy fix.

**Comment by Zhaith-Izaliel** [comment]
You're fast ! Thank you for your work ! :smile:

**Comment by Xelbayria** [comment]
## Fixed in v2.6.91
