### ISSUE TITLE
[🐞]: Regions Unexplored - Boatload - Large Blackwood Boat and Blackwood Furnace Boat

### ISSUE THREAD

**Issue by Ghastly13** [MehVahdJukaar/WoodGood#695]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader

1.20.1-FORGE

### EveryCompat Version

2.6.92

### Moonlight Lib Version

2.12.30

### Issue with mods

Regions Unexplored 0.5.6
Boatload 5.0.1

### Issue Detail

Boatload boat inventory models do not use the correct textures.
![2024-11-25_00 36 39](https://github.com/user-attachments/assets/1da0324b-1db0-4475-9135-4068063be3ab)

**Comment by Ghastly13** [comment]
This issue doesn't appear with any other wood type.

**Comment by Xelbayria** [comment]
that's strange. Will look into this

**Comment by Xelbayria** [comment]
I cannot replicate the problem on my side. Can you describe the problem? 

You mentioned "Boatload boat inventory models do not use the correct textures." I do not see it on my side.

**Comment by Xelbayria** [comment]
oh you meant the item (inventory). nvm.

**Comment by Xelbayria** [comment]
## Fixed in v2.6.93
