### ISSUE TITLE
[🐞]: Alex's Caves Thornwood - Twilight Forest/Quark Hollow Log Enhancement

### ISSUE THREAD

**Issue by Ghastly13** [MehVahdJukaar/WoodGood#696]
### Before Continuing:

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader

1.20.1 - FORGE  (YOU FORGOT THIS) 

### EveryCompat Version

2.6.92

### Moonlight Lib Version

2.13.30

### Issue with mods

Alex's Caves 2.02
Twilight Forest 4.3.2508
Quark 4.0-460

### Issue Detail

Hollow Logs from both Twilight Forest and Quark do not have Thornwood's unique shell textures. I'm not sure if those are called shell textures in Minecraft. Whatever those thorny bits are, they don't have them.
![2024-11-25_00 44 15](https://github.com/user-attachments/assets/374d2b31-5cff-46e8-903c-661de3769ab0)

**Comment by Xelbayria** [comment]
I've took a quick look at **Alex's Cave**, the bit part is called `thornwood_log_spines` 

one problem: EveryComp is just following how a mod is behaving. **Quark** & **Twilight Forest** doesn't have the model that use `log_spines` like **Alex's Cave** does. 

## EDIT: 

unfortunately, there is nothing I can do about this. Will closing this as "not planned".
