### ISSUE TITLE
[🗃]: Palm Vertical Slabs -- missing in action!

### ISSUE THREAD

**Issue by uuRETCH** [MehVahdJukaar/WoodGood#699]
### Version - Loader

1.20.1 - FORGE

### Supported Mod Version

Regions Unexplored v0.5.6 (and Quark 4.0-460?)

### Supported mod's Curseforge

https://www.curseforge.com/minecraft/mc-mods/regions-unexplored/files/5558225

### Details

There's already a good amount of support for Palm through this mod, and I'm grateful for it. Just no vertical slabs for it!

There are actually a few different wood types that they're missing for, now that I really look. Eucalyptus, Redwood, Socotra... every wood from Regions Unexplored, it looks like.

**Comment by Xelbayria** [comment]
vertical slab from which furniture mod?  I assumed the wood mod is Region unexplored? 🤔 

nvm. I did not noticed the rest of the sentence under Supported mod Version

Quark and Region Unexplored

**Comment by Xelbayria** [comment]
## ADDED in v2.6.93

---

it's not necessary to say which wood mods. You could say the vertical slab from Quark is not supported. It took me a while to understand what you are asking for.
