### ISSUE TITLE
[🐞]: Create windows

### ISSUE THREAD

**Issue by TWizrd** [MehVahdJukaar/WoodGood#700]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FABRIC

### EveryCompat Version

1.20-2.6.92

### Moonlight Lib Version

fabric_1.20-2.13.32

### Issue with mods

Create Fabric 0.5.1-f-build.1417+mc1.20.1
All mods adding new wood types (Biomes O' Plenty 19.0.0.91 as example)

### Issue Detail

Every compat does not work with create mod windows and window panes.

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/user-attachments/files/17937023/latest.log)

**Comment by Xelbayria** [comment]
I need more details. "Every Compat does not work with create mod windows and window panes" doesn't help me understand what's the problem. you gotta be specific.

**Comment by TWizrd** [comment]
So, the Create mod marked supported by Every Compat, but they actually don't work together. There are no Create wooden blocks made from wood added by other mods in creative menu, also I don't see them in JEI. Additionally, the logs contain the following messages: 
`[Render thread/ERROR]: Creative tab cant be null. Found null one for entry set window`

**Comment by Xelbayria** [comment]
> There are no Create wooden blocks made from wood added by other mods in creative menu, also I don't see them in JEI

Above is the details I want to know. 

EDIT: This is something you need to keep in mind "this mod doesn't work with with another mod" when you create a new issue to report a bug. It is not very specific and not very detailed. It's vague detail. Not easy for a DEV to find out what's the problem. 
if you provide detail like above, then I would knew what was the problem without looking at latest.log. 

> [Render thread/ERROR]: Creative tab cant be null. Found null one for entry set window

I already saw the latest.log. It's already fixed.

**Comment by Xelbayria** [comment]
## FIXED IN v2.6.93
