### ISSUE TITLE
[🐞]: Compat issue with Missing Wilds

### ISSUE THREAD

**Issue by 6xolotl** [MehVahdJukaar/WoodGood#701]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.21.1 - FABRIC

### EveryCompat Version

everycomp-1.21-2.7.5-fabric

### Moonlight Lib Version

moonlight-1.21-2.17.7-fabric

### Issue with mods

MissingWilds-fabric-1.3.3+1.21

### Issue Detail

Game will not open. Missing Wilds creator suggests the mod may be expecting MW's code to be wrapped in RegistryObject's like it was before 1.21. Issue persists with or without Sodium active (I'm using the Curseforge launcher, if that's important).

### OPTIONAL: Latest.log | Crash-report Attachment

[crash-2024-11-28_17.19.37-client.txt](https://github.com/user-attachments/files/17952832/crash-2024-11-28_17.19.37-client.txt)

### OPTIONAL: To Produce

Attempt to launch Minecraft with both Missing Wilds and Every Compat installed.

**Comment by Xelbayria** [comment]
## Fixed in v2.7.6

**Comment by Xelbayria** [comment]
> Game will not open. Missing Wilds creator suggests the mod may be expecting MW's code to be wrapped in RegistryObject's like it was before 1.21.

You can let Creator know. It's because EveryComp couldn't get the required block as a reference block using `MissingWildsBlocks.FALLEN_ACACIA_LOG`. I had to change the method to get the block.
