### ISSUE TITLE
[🐞]: Crash with Storage Drawers 

### ISSUE THREAD

**Issue by Merlin1809** [MehVahdJukaar/WoodGood#702]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.21.1 - FABRIC

### EveryCompat Version

everycomp-1.21-2.7.5

### Moonlight Lib Version

moonlight-1.21-2.17.7-fabric

### Issue with mods

Storage Drawers-fabric-1.21-13.8.4

### Issue Detail

Storage drawers and every compat cause the game to crash on startup.

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/user-attachments/files/17959566/latest.log)

**Comment by Xelbayria** [comment]
according to latest.log: 
`EVERY COMPAT REGISTERED 0 BLOCKS! This means that you dont need the mod and should remove it!`

You don't have any wood mods. I need the `crash-report` file as it's in `.minecraft/crash-report/...` 

i may find out why your minecraft crashed.

**Comment by Merlin1809** [comment]
doesn't matter if I have wood mods or not it still crashes on startup (tested with BOP):

[crash-2024-11-29_21.44.07-client.txt](https://github.com/user-attachments/files/17962914/crash-2024-11-29_21.44.07-client.txt)

Edit: works normally with every compat version 2.7.4

**Comment by Xelbayria** [comment]
## FIXED in v2.7.6

---

NOTE: v2.7.4 - if you put an item/block into the drawers, you'll see the Item's not being rendered.
