### ISSUE TITLE
[🐞]: Macaw's compat bypass with Biomes o Plenty compat mod

### ISSUE THREAD

**Issue by XlosVSM** [MehVahdJukaar/WoodGood#704]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### EveryCompat Version

everycomp-1.20-2.6.94

### Moonlight Lib Version

moonlight-1.20-2.13.33

### Issue with mods

- Biomes O' Plenty <18.0.0.592>
- Macaw's Bridges - Biomes O' Plenty
- Macaw's Fences - Biomes O' Plenty
- Macaw's Furnitures - Biomes O' Plenty
- Macaw's Roofs - Biomes O' Plenty

### Issue Detail

These mods create compats between Biomes O' Plenty and Macaw's mods. So if the game has Every Compat and one of these compat mods installed, the Every Compat ones will be disabled (not in creative menu, JEI, and not craftable). This way modpack creators or general users do not have to tidy up with Crafttweaker/KubeJS and using the Hide settings in JEI.

**Comment by MehVahdJukaar** [comment]
Biggest question is why even have those mods when EC does the same

**Comment by Xelbayria** [comment]
about Macaw's Compat, it's included in EC's code to skip generating blocks from Macaw's if there are compat/addon mods installed. 

I wondered what's the problem?

**Comment by Xelbayria** [comment]
Can you tell me what's the problem?

**Comment by XlosVSM** [comment]
Can't seem to recreate it anymore, she'll be fine
