### ISSUE TITLE
[🐞]: Crash on startup related to Farmer's Delight with any wood mods

### ISSUE THREAD

**Issue by Fingernailsss** [MehVahdJukaar/WoodGood#705]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### EveryCompat Version

1.20-2.7.0

### Moonlight Lib Version

1.20-2.13.33

### Issue with mods

N/A

### Issue Detail

Game crashes before loadup. Don't even get to the main menu. Problem ceases when Wood Good is removed.

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/user-attachments/files/18029405/latest.log)

"[15:35:46] [Render thread/ERROR]:Caught exception during event RegisterEvent dispatch for modid everycomp"

### OPTIONAL: To Produce

Just started up the game with the mod.

**Comment by Xelbayria** [comment]
> Just started up the game with the mod.

that won't help. I need to know which supported mod. I got another report. it was **Farmer's Delight** that caused the crash. Do you have it installed?

**Comment by brnbrd** [comment]
> > Just started up the game with the mod.
> 
> that won't help. I need to know which supported mod. I got another report. it was **Farmer's Delight** that caused the crash. Do you have it installed?

I can report the crash occurs alongside the new 1.2.6 version of Farmer's Delight on 1.20.1

**Comment by Fingernailsss** [comment]
> > Just started up the game with the mod.
> 
> that won't help. I need to know which supported mod. I got another report. it was **Farmer's Delight** that caused the crash. Do you have it installed?

yes

**Comment by Xelbayria** [comment]
Alright. it's **Farmer's Delight**, for now, Use **Every Compat v2.6.94**. it will works fine. 

v2.7.0 have a major changed code to support an addon, **Stone Zone**

**Comment by Xelbayria** [comment]
## FIXED in v2.7.1
