### ISSUE TITLE
[🐞]: 1.20.1 Forge Crash with Farmer's Delight + Biomes We've Gone

### ISSUE THREAD

**Issue by Astral-Haze** [MehVahdJukaar/WoodGood#706]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### EveryCompat Version

1.20-2.7.0

### Moonlight Lib Version

1.20-2.13.33

### Issue with mods

Farmer's Delight, Biomes We've Gone (Dependencies for those are necessary but do not cause a crash on their own)

### Issue Detail

Game crashes and terminates before title screen

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/user-attachments/files/18030190/latest.log)

### OPTIONAL: To Produce

Download or update to the latest versions of the mods, attempt to launch the game

**Comment by Astral-Haze** [comment]
just noticed a similar ticket has been made since I checked before filling this one out so this may be a duplicate of that one

**Comment by Xelbayria** [comment]
No worries, i can mark this as duplicated issue. Use **EveryComp v2.6.94**, it will work fine with **Farmer's Delight**

**Comment by Xelbayria** [comment]
[Original Issue](#705)
