### ISSUE TITLE
Every Compat crashes with Variant Vanilla Blocks

### ISSUE THREAD

**Issue by JacobTDC** [MehVahdJukaar/WoodGood#707]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FABRIC

### EveryCompat Version

everycompat-1.20-2.7.0

### Moonlight Lib Version

moonlight-fabric_1.20-2.13.33

### Issue with mods

Variant Vanilla Blocks (any version)

### Issue Detail

Minecraft crashes on start before showing the splash screen when using Every Compat with Variant Vanilla Blocks.

The issue is reproducible with Every Compat (1.20-2.6.81 and up, previous versions work fine), Moonlight Library (any compatible version), and Variant Vanilla Blocks (any version) on Fabric 1.20.1 Loader 0.16.9.

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/user-attachments/files/18032506/latest.log)
[crash-2024-12-05_21.44.08-client.txt](https://github.com/user-attachments/files/18032512/crash-2024-12-05_21.44.08-client.txt)

**Comment by Xelbayria** [comment]
i know what's the problem. Will fix

**Comment by Xelbayria** [comment]
## FIXED in v2.7.1
