### ISSUE TITLE
[🐞]: [1.21.1] Latest Everywood mod version conflict with Farmer and Totemic

### ISSUE THREAD

**Issue by Periam** [MehVahdJukaar/WoodGood#708]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.21.1 - NEOFORGE

### EveryCompat Version

Every Compat 1.21-2.7.6 (everycomp)

### Moonlight Lib Version

Moonlight Lib 1.21-2.17.10 (moonlight)

### Issue with mods

Farmer's Delight 1.2.6 (farmersdelight)
Just Enough Items 19.21.0.247 (jei)
Totemic 1.21.1-0.12.14 (totemic)

### Issue Detail

After installing the latest version of the mod, new worlds or old one do not load.
![image](https://github.com/user-attachments/assets/c355cf5c-fa57-4342-a984-3bdff4e2b499)

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/user-attachments/files/18041270/latest.log)

### OPTIONAL: To Produce

1-Install the latest version of the mod
2-Install JEI, Farmer and totemic
3-Launch the game and load a world.

**Comment by Xelbayria** [comment]
Did it crash?  I'll check on my side. 

EDIT: 
Ok I see what happened.

**Comment by Xelbayria** [comment]
## FIXED in v2.8.0
