### ISSUE TITLE
[Bug] Not Same Version If same version

### ISSUE THREAD

**Issue by SugarDaddii** [MehVahdJukaar/WoodGood#71]
![82B522F1-F5A3-48CB-8ECF-D5722370D745](https://user-images.githubusercontent.com/14795020/197334701-35b7c486-14f1-4458-9e31-36132db7bc11.png)

This is sometimes when i want join a server. What can i do?

**Comment by MehVahdJukaar** [comment]
Update moonlight. Should he fixed

**Comment by Gottaloveeggs** [comment]
had same issue, updating moonlight fixed it (would have been nice if the log mentioned it tho)

**Comment by mxnmnm** [comment]
i have been experiencing this with every compat versions 2.6.41 and beyond

**Comment by Xelbayria** [comment]
Did you update **Moonlight Lib** to v2.9.11? 

if that doesn't work, then delete **EveryComp** and download a clean mod.

**Comment by mxnmnm** [comment]
This did not fix it (I'm using moonlight-1.20-2.11.9-forge) and I redownloaded
here is the client log: https://gist.github.com/mxnmnm/008e4a2bf5d8e6afb9c50623f26f8444
server log: https://gist.github.com/mxnmnm/2d682654fbd559d11b2daec0f7be814b

**Comment by Xelbayria** [comment]
@MehVahdJukaar I could use your help with ☝️ 
I took a look at the log. I wasn't sure if this is related to mismatched ID for the blocks. The version @mxnmnm is on **1.20.1**

**Comment by MehVahdJukaar** [comment]
Mod list on server and client must differ

**Comment by mxnmnm** [comment]
Then why would it work on 2.6.40 (and all previous versions) and not later versions. The mod lists do not differ (I made sure of this before reporting by copying both mod folders and seeing if any files were not overridden). The only differences would be client-side mods on the client and not the server.

**Comment by MehVahdJukaar** [comment]
because new EC versions might add new modules supporting other mods you might have. This could be explained by yor client having different mod (versions) than the server like i said.
From your log i see all chipped blocks are reported missing so has to be something with that. Justcopy paste your clent mod folder to the server. If *that* doesnt work then we know it must be something else

**Comment by mxnmnm** [comment]
Ok I found the guilty mod and all is good.

**Comment by mxnmnm** [comment]
Ok something to note for future people who might see this: if you are using sinytra connector try and delete the connector folder on both the server and client
