### ISSUE TITLE
[🐞]: Server crash: Class failed to load

### ISSUE THREAD

**Issue by mosharky** [MehVahdJukaar/WoodGood#710]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### EveryCompat Version

everycomp-1.20-2.7.1

### Moonlight Lib Version

moonlight-1.20-2.13.34

### Issue with mods

None

### Issue Detail

A server with only Moonlight + EveryCompat will crash on startup due to a class failing to load

### OPTIONAL: Latest.log | Crash-report Attachment

- [latest.log](https://mclo.gs/rBCyYCI)
- [crash report](https://mclo.gs/evlql98)

### OPTIONAL: To Produce

Run EveryCompat + dependencies on a server

**Comment by Xelbayria** [comment]
Did you install any supported mods & wood mods?

**Comment by mosharky** [comment]
Yes, same exact crash

**Comment by Xelbayria** [comment]
Alright, it's because of class not being found: BlockEntityWithoutRenderer (this shouldn't be on server, only Client). I'll check 

## UPDATE: 
this will take a while to fix. 🤔

**Comment by Xelbayria** [comment]
Did you try v2.7.0? 

If it doesn't work, then use v2.6.94 for now. This problem is strange. it shouldn't have happened on server because the class is actually excluded. 

### UPDATED: 
I think Moonlight Lib is the problem, i'll speak with MehVahdJukaar about this 

### UPDATED#1: 
@mosharky 
Can you run the server with just Moonlight Lib? I need to confirm my suspicion

**Comment by mosharky** [comment]
Can do tomorrow (like 12 hours from now)

**Comment by mosharky** [comment]
The server starts up just fine with only Moonlight lib.

**Comment by Xelbayria** [comment]
Thanks for testing & provide the result. If you have installed Supplementaries on the server, let me know if it caused the same crash. I investigated Moonlight lib and found some code that use `BlockEntityWithoutLevelRenderer` and it is not excluded for server side. 

---

## UPDATE: 

Meh found one more class in EveryComp that aren't excluded for server side. and the good news is 

Server started up fine now.

**Comment by Xelbayria** [comment]
## FIXED in v2.7.2
