### ISSUE TITLE
[🐞]: Hedges from Macaw's Fences and Walls generated for Regions Unexplored do not connect to each other.

### ISSUE THREAD

**Issue by irish-brigid** [MehVahdJukaar/WoodGood#712]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.19.2 - FORGE

### EveryCompat Version

everycomp-1.19.2-2.5.30

### Moonlight Lib Version

moonlight-1.19.2-2.3.7-forge

### Issue with mods

Macaw's Fences and Walls (1.1.2 mc1.19.2)
Regions Unexplored (0.5.3 mc1.19.2)

### Issue Detail

Exactly as the title says. The hedge blocks made from Regions Unexplored leaves do not connect to each other or to other hedge, fence, or wall blocks.

### OPTIONAL: To Produce

1) Load Minecraft with Macaw's Fences and Walls, Regions Unexplored, and Every Compat
2) Make hedge blocks using Regions Unexplored leaves
3) Place hedge blocks

**Comment by Xelbayria** [comment]
I think i know why. Thanks for the report.

**Comment by Xelbayria** [comment]
## FIXED in v2.5.31
