### ISSUE TITLE
[🐞]: server crash with aoa3 + farmer's delight

### ISSUE THREAD

**Issue by mihile** [MehVahdJukaar/WoodGood#713]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.21.1 - NEOFORGE

### EveryCompat Version

everycomp-1.21-2.7.6-neoforge

### Moonlight Lib Version

moonlight-1.21-2.17.11-neoforge

### Issue with mods

Advent Of Ascension 3.7.15 + Farmer's Delight 1.2.6

### Issue Detail

![image](https://github.com/user-attachments/assets/a0c07ff7-b380-4a01-ba2b-616f5dbfc8a6)
When using aoa3 and farmer's delight together, connection error happen with everycomp 2.7.6
The issue does not occur in versions 2.7.5 and earlier

### OPTIONAL: Latest.log | Crash-report Attachment

https://mclo.gs/d9fqczh

**Comment by Xelbayria** [comment]
I need the Crash-report

**Comment by mihile** [comment]
https://mclo.gs/ORyBqeM
oh my bad. It's not a **server** crash.
When I try to connect to the server, get lost connection and client crashes a second later.
lost connection also happens in single-play without the crash.

**Comment by MehVahdJukaar** [comment]
Send latest.log

**Comment by mihile** [comment]
https://mclo.gs/MH2hdwG
here it is!

**Comment by MehVahdJukaar** [comment]
Are you sure both client and serve rhave same mod versions of all mods? Does it happen without EC

**Comment by mihile** [comment]
yes. I've only install Everycomp, Farmer's Delight, Moonlight, and AoE3.
server is working but can't join server. 
same issue in single play.

When I remove Everycomp from both the server and client, join server works well.

**Comment by Xelbayria** [comment]
ok i see it's related to strangewood from AOA3. the problem is model file. i'll need to look in this. 

` Failed to add Block{everycomp:fd/aoa3/stranglewood_cabinet} model json file:`

**Comment by TeraNovell** [comment]
I get the same error message only with these mods:
* Neoforge: 21.1.85
* Every Compat: 2.7.6
* Moonlight Lib: 2.17.12
* Farmer's Delight: 1.2.6
* Biomes O' Plenty: 1.21.1
  * GlitchCore: 2.1.0.0
  * TerraBlender: 4.1.0.5

As soon as I try to load a world, I get the same message. But when I remove Farmer's Delight or Biomes O' Plenty again, everything continues to run.

[latest.log](https://github.com/user-attachments/files/18110900/latest.log)

**Comment by Xelbayria** [comment]
<strike>I think i found the cause. 

The generated blocks, _cabinet_ are included with tags that _cabinet_ of **Farmer's Delight (FD)** is no longer tagged with. </strike>

what? The tags for **FD** is actually loaded and included with _cabinet_. I need to investigate a bit more. 

## UPDATED: 

The FarmersDelight Module is outdated for the **FD** v1.2.6. 

**EDIT:**
The problem is that **EC** generated Block for _cabinet_ but did not generate item for _cabinet_. I even added a code for that and it still doesn't generate the item. idk why.

**Comment by Xelbayria** [comment]
Turned out the problem is Moonlight lib, 

You'll need to use **Moonlight Lib v2.17.12**. It fixed the item not being generated.

**Comment by TeraNovell** [comment]
@Xelbayria Just to make sure it hasn't been overlooked. I have the same message with version 2.17.12 only without aoa3 ^^

**Comment by Xelbayria** [comment]
Will check again.

**Comment by Xelbayria** [comment]
@TeraNovaLP 
Using **EC v2.8.0**, I ran a test on my side to see if i can join the server. i had no problem. 
With AOA3, too. 

I need to fix the problem with _strangewood_

### UPDATED: 
ported the fix from 1.20.1 to 1.21.1

should be all finished. I am going to upload v2.8.0 and if you find a problem, you can create a new issue.

**Comment by Xelbayria** [comment]
## FIXED in v2.8.0
