### ISSUE TITLE
[🐞]: Crashed with MoreCraftingTable - 1.20.1 

### ISSUE THREAD

**Issue by Dronicode** [MehVahdJukaar/WoodGood#714]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FABRIC

### EveryCompat Version

1.20-2.7.3

### Moonlight Lib Version

1.20-2.13.37

### Issue with mods

More Crafting Tables 1.2.7

### Issue Detail

Every Compat causes a crash when attempting to load the game when this mod is present.
I'm an amateur and may be wrong but to try to be helpful for saving you guys some time I had a look through and believe this is caused by a typo. 

According to that mod's github, the path is this:
src/main/java/io/github/lieonlion/lolmct**/block**/MoreCraftingTableBlock.java
The crash (report in next section) says this:
Caused by: java.lang.ClassNotFoundException: io.github.lieonlion.lolmct.**bock**.MoreCraftingTableBlock

Notice the missing 'L' in 'block'.

Thanks!

### OPTIONAL: Latest.log | Crash-report Attachment
[crash-2024-12-11_21.40.35-client.txt](https://github.com/user-attachments/files/18102098/crash-2024-12-11_21.40.35-client.txt)

**Comment by Xelbayria** [comment]
Thanks for the report. next time, drag the crash-report/latest.log file in here, it will get uploaded so the dev can take a look at what's the problem

**Comment by Dronicode** [comment]
Sorry about that. Should I recreate the issue to get a fresh log and add it in? I have a bug to report for the stone compat mod so I'll make sure to do it properly on that one.

**Comment by Xelbayria** [comment]
Please do, thanks.

**Comment by Dronicode** [comment]
Proper crash log file added.

**Comment by Xelbayria** [comment]
i see what you mean "L" missing in **block**... This is the first time I've seen a problem like this. 

## UPDATED
Turned out the MCT version v1.2.7 for FABRIC was updated to fix the path `bock` to `block`. so the module via EveryCompat was outdated. 

I updated it. all good now.

**Comment by Xelbayria** [comment]
## FIXED|UPDATED in v2.7.4
