### ISSUE TITLE
[🐞]: EveryCompat crash with latest update.

### ISSUE THREAD

**Issue by Periam** [MehVahdJukaar/WoodGood#716]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.21.1 - NEOFORGE

### EveryCompat Version

Every Compat 1.21-2.8.0 (everycomp)

### Moonlight Lib Version

Moonlight Lib 1.21-2.17.12 (moonlight)

### Issue with mods

I have enchanted with mod but disable.
Bagus Lib 1.21.1-13.5.0 (bagus_lib)
Every Compat 1.21-2.8.0 (everycomp)
Just Enough Items 19.21.0.247 (jei)
Minecraft 1.21.1 (minecraft)
Moonlight Lib 1.21-2.17.12 (moonlight)
NeoForge 21.1.83 (neoforge)

### Issue Detail

After installing the latest version the game does not load.

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/user-attachments/files/18129246/latest.log)

**Comment by Xelbayria** [comment]
Has the v2.8.1 fixed the problem?

**Comment by Xelbayria** [comment]
@Periam 

It should be fixed by now. if the issue still persist with the same error, then you can re-open this issue.
