### ISSUE TITLE
[🐞]: Diagonal Fences x Macaw's Fences and Walls: not dropping the item

### ISSUE THREAD

**Issue by Gasteb** [MehVahdJukaar/WoodGood#718]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### EveryCompat Version

everycomp-1.20-2.7.3

### Moonlight Lib Version

moonlight-1.20-2.13.37

### Issue with mods

Combined/Main Issue
Diagonal Fences [Forge & Fabric]: [DiagonalFences-v8.1.5-1.20.1-Forge]
Macaw'sFences and Walls: [mcw-fences-1.1.2-mc1.20.1forge]

Tested with
Regions Unexplored (forge/fabric)  [RegionsUnexploredForge-0.5.6+1.20.1
Moonlight Lib                                  [moonlight-1.20-2.13.37]
Everycompat (Wood Good)             [everycomp-1.20-2.7.3]
PuzzlesLib [Forge & Fabric]             [PuzzleLib-v8.1.25-1.20.1-forge]
TerraBlender(Forge)                         [TerraBlender-forge-1.20.1-3.0.1.7]

### Issue Detail

With any modded plank/wood that adds the mod,
combined with **Diagonal Fence** (the problem) with **Macaw's Fences and Walls** can't drop these following variant of everycompat:

-<wood>_picket_fence
-<wood>_stockade_fence
-<wood>_horse_fence
-<wood>_wired_fence

Using even without "BetterF3-7.0.2-Forge-1.20.1" checks the Block ID as
"diagonalfences:everycomp/mcf/regions_unexplored/maple_horse_fence".

Tried with other wood implementation:
-Ars Nouveau
-Quark
-Deeper and Darker
-Better Archeology
Results the same issue of the drop don't dropping.

### OPTIONAL: To Produce

1) Place any modded wood of these variant:
    -<wood>_picket_fence
    -<wood>_stockade_fence
   -<wood>_horse_fence
   -<wood>_wired_fence
2) Break with any "Axe" Tool or by hand
3) No drop given

**Comment by Xelbayria** [comment]
Interesting

**Comment by Xelbayria** [comment]
I've looked into this. this problem will take some time to fix.

**Comment by Gasteb** [comment]
Thank you for reading this issue! I'll wait gladly

**Comment by Xelbayria** [comment]
## FIXED IN v2.7.7
