### ISSUE TITLE
Crashes on startup when attempting to load Create module in server environment.

### ISSUE THREAD

**Issue by JacobTDC** [MehVahdJukaar/WoodGood#719]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [x] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FABRIC

### EveryCompat Version

everycomp-1.20-2.7.3

### Moonlight Lib Version

moonlight-1.20-2.13.37

### Issue with mods

create-fabric-0.5.1-j-build.1631+mc1.20.1
create-fabric-0.5.1-j-build.1609+mc1.20.1

### Issue Detail

As the title describes, for some reason, the Create module crashes on server environments. I've tested it with both of the versions of Create listed above.

I'm using `fabric-server-mc.1.20.1-loader.0.16.9-launcher.1.0.1.jar` with no extra arguments (other than `-Xmx`), and openjdk-17-jre.

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/user-attachments/files/18138996/latest.log)

**Comment by Xelbayria** [comment]
<strike>There should be crash report, can you check... if there is, then you can include it</strike>

don't worry about it, I just took a look at the latest.log.  you should wait for v2.7.1 (it should fixed the bug)

**Comment by JacobTDC** [comment]
> There should be crash report, can you check... if there is, then you can include it
> 
> don't worry about it, I just took a look at the latest.log. you should wait for v2.7.1 (it should fixed the bug)

By v2.7.1, I assume you mean v2.7.4? Anyway, took me a minute of searching, but I found your commit fixing the issue (9bd98564b61a666ae4f6da88a2cd0630bd2b205e and cd4e4a2ea8d9e2c4a65e0b2aa2bbda486c3d318c). I will go ahead and close this for now.

Also, thank you guys for all your hard work maintaining this project.

**Comment by Xelbayria** [comment]
🤦🏻  yes i meant v2.7.4.  And yup that's the commit.

**Comment by Xelbayria** [comment]
## FIXED in v2.7.4
