### ISSUE TITLE
[🐞]: Handcrafted containers crash on placing

### ISSUE THREAD

**Issue by dhi-holo** [MehVahdJukaar/WoodGood#720]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.21.1 - FABRIC

### EveryCompat Version

everycomp-1.21-2.8.1-fabric

### Moonlight Lib Version

moonlight-1.21-2.17.12-fabric

### Issue with mods

handcrafted-fabric-1.21.1-4.0.2 - Furniture

Tested with [Cobblemon](https://gitlab.com/cable-mc/cobblemon) and [Arts & Crafts](https://modrinth.com/mod/artsandcrafts) for woodtypes, crashes seem identical.

### Issue Detail

When placing down any of the listed blocks in the To Produce section, when generated by Every Compat, the game instantly crashes. The first line of the crash report states 
`java.lang.IllegalStateException: Invalid block entity handcrafted:container // earth.terrarium.handcrafted.common.blockentities.ContainerBlockEntity state at class_2338{x=-5, y=66, z=-29}, got Block{everycomp:hc/cobblemon/apricorn_side_table}[color=none,facing=west,waterlogged=false]` 
(with the material reference changed to the relevant block type, block states, and wood type for the other possible examples)

If this crash ends up being on Handcrafted's end, rather than Every Compat, let me know, I can go bug them with this instead. 

### OPTIONAL: Latest.log | Crash-report Attachment

[crash-2024-12-16_16.08.17-client.txt](https://github.com/user-attachments/files/18145574/crash-2024-12-16_16.08.17-client.txt)
[latest.log](https://github.com/user-attachments/files/18145577/latest.log)

### OPTIONAL: To Produce

Place down any of the following blocks via Every Compat (Wood Good) created variants:
Nightstand, Desk, Side Table, Counter, Cupboard, Drawer, Shelf

**Comment by Xelbayria** [comment]
No need to bug them. I have a good idea of what's the problem. I need to check Handcrafted's source code to see what changed.

**Comment by Xelbayria** [comment]
The changelog of Handcrafted v4.0.2 via Curseforge. Handcrafted's source code have changed to fix the same crash you saw. EC's code was outdated. so I updated it.

**Comment by Xelbayria** [comment]
## FIXED in v2.8.2
