### ISSUE TITLE
[🐞]: Missing textures for Chipped with latest update

### ISSUE THREAD

**Issue by SplitCreatureX** [MehVahdJukaar/WoodGood#722]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FABRIC

### EveryCompat Version

everycompat-1.20-2.7.4-fabric

### Moonlight Lib Version

moonlight-1.20-2.13.29-fabric

### Issue with mods

Chipped-3.0.7-fabric
Chipped-3.0.6-fabric
Backpacked-2.2.7-fabric

### Issue Detail

Missing textures for certain types of chipped modded blocks. Specifically, all modded block variants from chipped planks, doors, trapdoors, and logs.

Every other category seems unaffected.

Also Missing some textures for modded wood shelves from the backpacked mod

### OPTIONAL: To Produce

1. Have latest version of both everycompat and moonlight
2. Install chipped along with some mods such as better nether or hybrid aquatic
3. Search for blocks such as driftwood logs and see missing textures

**Comment by Xelbayria** [comment]
Update **Moonlight Lib (ML)** to v2.13.39

EDIT: I forgot to Update EveryCompat's dependencies to use new version. it will be give a warning/error message that the version of ML is needed from v2.7.5 onward

**Comment by SplitCreatureX** [comment]
Just tested it with moonlight v2.13.39, still having the same issue.
![image](https://github.com/user-attachments/assets/5e376dd0-624b-43d0-a7e5-2eeac96ca7ec)

**Comment by squigglezworth** [comment]
Downgrading to EveryCompat `v2.7.3` works as a temporary fix

**Comment by Xelbayria** [comment]
☝🏻  do what squiggiezworth did. it is a good solution for now. i'm currently investigating the problem on Chipped's textures

**Comment by JacobTDC** [comment]
> Downgrading to EveryCompat `v2.7.3` works as a temporary fix

While this will solve the textures issue, it's not a viable fix in some cases (i.e. server), as v2.7.4 implements critical bug fixes.

~~It may, however, be possible to have a server use v2.7.4, and the clients use v2.7.3, but I will have to test later, as I'm currently at work. Will update this once I do.~~

So, the solution, if you are using Wood Good on a server, is to use the most recent versions of Wood Good and Moonlight on the server, and use Moonlight v2.13.37 and Wood Good v2.7.3 on the client.

**Comment by AbelRunes** [comment]
This issue is also on Forge, first it was only chipped but it seems if you roll it back, all the textures in all the mods break. This is v2.7.4 (Below) This is without rolling back moonlight lib
![2024-12-16_20 23 54](https://github.com/user-attachments/assets/da130bc0-97b5-43fe-ac08-de800edb89b5)
Then it seems v2.7.3, v2.7.2, and so far v.2.7.1 break the entire mod completely after rolling back. 
![2024-12-16_20 30 11](https://github.com/user-attachments/assets/4afe48c5-16ed-44da-91ca-ecfe48800a1c)

**Comment by JacobTDC** [comment]
> This issue is also on Forge, first it was only chipped but it seems if you roll it back, all the textures in all the mods break. This is v2.7.4 (Below) This is without rolling back moonlight lib
> ![2024-12-16_20 23 54](https://github.com/user-attachments/assets/da130bc0-97b5-43fe-ac08-de800edb89b5)
> Then it seems v2.7.3, v2.7.2, and so far v.2.7.1 break the entire mod completely after rolling back. 
> ![2024-12-16_20 30 11](https://github.com/user-attachments/assets/4afe48c5-16ed-44da-91ca-ecfe48800a1c)
> 

I experienced the same thing. It appears to be an issue with Moonlight Lib. Revert Moonlight Lib back to 2.13.37 as well, and it should work.

**Comment by squigglezworth** [comment]
Apologies - I didn't realize I had downgraded that earlier as well before posting, and was literally about to post the same followup you did, but got distracted trying to help fix the issue :P

**Comment by AbelRunes** [comment]
Re:Deco, and Wood Works also has textures that break, and with a bit of testing rolling back to 2.13.37 on Moonlight Lib as Jacob suggested and Wood Good to 2.7.3 fixes the issues, I didn't see the updated comment up there my bad

**Comment by Xelbayria** [comment]
What you guys said about **EveryCompat (EC) v2.7.3** or below will only work with **Moonlight Lib (ML) v2.13.37**

### You got the right answer. 

**ML** has some changed code in the code that are responsible for modifying the model files to point at the textures and also generate the texture in the correct location. 

the code did not account for the subfolder that textures are located in. which is why you are seeing the missing texture in these blocks

Unfortunately, **StoneZone (SZ) v2.7.1** required **EC v2.7.4+** and **ML v2.13.39+**

**SZ v2.7.0** has some bugs that is not really stable to play if you are playing with **Create**. 

it will take times to fix the bug and cleanup little problems that we, the DEVs did not think of.

**Comment by Xelbayria** [comment]
## UPDATED in v2.7.5 & FIXED in Moonlight Lib v2.13.40

---

ChippedModule is a bit outdated so it's updated.

**Comment by squigglezworth** [comment]
If the update to Moonlight was meant to fix this, I'm still getting missing textures.  
https://mclo.gs/u3S4NvR
```
[19:38:00] [Worker-ResourceReload-1/WARN] [minecraft/ModelManager]: Missing textures in model everycomp:ch/biomesoplenty/barred_magic_door#inventory:
    minecraft:textures/atlas/blocks.png:everycomp:item/ch/doors/ch/biomesoplenty/barred_magic_door
```

**Comment by Xelbayria** [comment]
> If the update to Moonlight was meant to fix this, I'm still getting missing textures. [mclo.gs/u3S4NvR](https://mclo.gs/u3S4NvR)
> 
> ```
> [19:38:00] [Worker-ResourceReload-1/WARN] [minecraft/ModelManager]: Missing textures in model everycomp:ch/biomesoplenty/barred_magic_door#inventory:
>     minecraft:textures/atlas/blocks.png:everycomp:item/ch/doors/ch/biomesoplenty/barred_magic_door
> ```

That's because I pointed out in my previous: 

> ChippedModule is a bit outdated so it's updated.

**Moonlight Lib** is major responsible for the problem. the missing texture for "door" item is due to old code in ChippedModule being outdated

**Comment by Xelbayria** [comment]
Uploaded
