### ISSUE TITLE
[🐞]: Latest version of wood good causes this crazy error screen

### ISSUE THREAD

**Issue by Cricket742** [MehVahdJukaar/WoodGood#723]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### EveryCompat Version

2.7.4

### Moonlight Lib Version

2.13.39

### Issue with mods

Chipped 3.0.7

### Issue Detail

![image](https://github.com/user-attachments/assets/0cd15782-db0b-493b-add3-c27068578c7e)
I get this screen when trying to load minecraft with the latest version of wood good, Downgrading to version 2.7.3 fixes the issue.

disabling chipped allows the game to load but the loading screen still goes a tad crazy for a bit

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/user-attachments/files/18169331/latest.log)
and here's the log when I disabled chipped
[latest.log](https://github.com/user-attachments/files/18172337/latest.log)

**Comment by Xelbayria** [comment]
the problem with Chipped is already reported and is fixed. 

EDIT: 
I took a quick look at the latest.log. you should wait for v2.7.5. Hopefully it should fix the issues that you are having with. I'll let u know when it's uploaded

**Comment by Xelbayria** [comment]
v2.7.5 Uploaded! 

let me know if there are any problems

**Comment by Xelbayria** [comment]
If the problem persists, then you can re-open this issue. I assumed it's resolved with the latest version.
