### ISSUE TITLE
[🐞]: Creative Mode Tab Incorrect Texture Filename

### ISSUE THREAD

**Issue by stlouisn** [MehVahdJukaar/WoodGood#725]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.21.1 - FABRIC

### EveryCompat Version

1.21-2.8.1

### Moonlight Lib Version

1.21-2.17.12

### Issue with mods

missing texture from creative tab for every compat. tested with only two other mods (otherwise there is no creative tab) azalea wood and another furniture.

### Issue Detail

looks like its looking for texture file called tab_items_search.**png.png**

the double extension being the problem.

### OPTIONAL: Latest.log | Crash-report Attachment

```java
[Render thread/WARN]: Failed to load texture: minecraft:textures/gui/container/creative_inventory/tab_item_search.png.png
java.io.FileNotFoundException: minecraft:textures/gui/container/creative_inventory/tab_item_search.png.png
```

**Comment by Xelbayria** [comment]
Thanks for the report. I need the latest.log so i can get more details

**Comment by Xelbayria** [comment]
Thanks for the PR. I can't find that method to fix the filename with extra ".png"
