### ISSUE TITLE
[🐞]: Boatload's boat types do not have textures

### ISSUE THREAD

**Issue by theshank908** [MehVahdJukaar/WoodGood#730]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### EveryCompat Version

everycomp-1.20-2.7.6

### Moonlight Lib Version

moonlight-1.20-2.13.41-forge

### Issue with mods

boatload-1.20.1-5.0.1

### Issue Detail

Boatload boats generated by everycomp do not have a texture when placed.

**Comment by Xelbayria** [comment]
## FIXED in v2.7.7
