### ISSUE TITLE
[🐞]: Tall Macaw Door Variant Issues

### ISSUE THREAD

**Issue by tillasiren** [MehVahdJukaar/WoodGood#733]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### EveryCompat Version

everycompat 1.20-2.7.6

### Moonlight Lib Version

moonlight 1.20-2.13.41

### Issue with mods

Dramatic Doors
Macaw's Doors
Ars Nouveau (Wood Types)
Biomes O Plenty (Wood Types)
Quark (Wood Types)

### Issue Detail

I was finally getting around to making recipes for some items I noticed generated but did not make recipes and noticed a good few updates had occurred so I decided to test the updated version before doing all the work. And noticed that the items still did not have recipes and they additionally had texture errors in the updated version that I did not have in the previous version I was using.

Item/block: Tall Doors Variants from the Dramatic Doors 
Issue: Errored out Textures when in item form. 
Wood Variants I see this with: All from the above listed mods barn glass doors appear to be an exception

![image](https://github.com/user-attachments/assets/db851b90-30db-4d15-8f0a-568c2e1ecfdf)

Additionally none of the tall macaws door variants have recipes generated along with the item (currently working on a datapack to add those and noticed the issue.)

(I can be reached faster in the discord if you require more information.)

**Comment by Xelbayria** [comment]
## FIXED in v2.7.7

**Comment by tillasiren** [comment]
Additionally since testing this in single player I've been unable to login to my server... I don't suppose you wuld have any idea how to fix that?
(Didn't update server version and reverted my client back to the matching ones)

**Comment by Xelbayria** [comment]
## FIXED in v2.7.7

**Comment by Xelbayria** [comment]
> (Didn't update server version and reverted my client back to the matching ones)

well, good idea to do some testing in the single player to ensure everything is fine. it's a good thing you did that. because of that, i got the problem fixed. 

with that you can revert your CLIENT's side to match the current version mod of SERVER's. that should resolve your problem joining the server. It's important to keep both CLIENT and SERVER to use the same version for every single mod (except the mod that can be only used in CLIENT side)

**Comment by tillasiren** [comment]
I have just got into contact with MehVahdJukaar in the discord in a thread describing the problem currently. But my issue was that even AFTER reverting I was unable to connect. (Thread title "Can't rejoin server after mod update (changed versions back to server version)" int he supplementaries discord as that is the official one yall use to my knowledge)

**Comment by Xelbayria** [comment]
hmm. Can i get the latest.log for both SERVER & CLIENT 

you can use https://mclo.gs/ to share the logs

**Comment by MehVahdJukaar** [comment]
Install packet fix mod. Maybe you have so many blocks it's reaching packet limit

**Comment by Xelbayria** [comment]
oh right. i remembered now.
