### ISSUE TITLE
[🐞]: Boatload's Entity Texture is missing when placed. 

### ISSUE THREAD

**Issue by xhatz** [MehVahdJukaar/WoodGood#735]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### EveryCompat Version

everycomp-1.20-2.7.6

### Moonlight Lib Version

moonlight-1.20-2.13.41-forge

### Issue with mods

Boatload, Biomes O' Plenty

### Issue Detail

The boat textures from boatload seems broken when using every compat (missing texture) in conjonction with other mods such as Biomes O' Plenty.

**Comment by Xelbayria** [comment]
This is a duplicated issue. and there is another issue just like this. already closed. 

ORIGINAL: #730

**Comment by xhatz** [comment]
My bad, I had searched but looked poorly 😅 thank you for the fix ♥️
