### ISSUE TITLE
[🐞]: small ships

### ISSUE THREAD

**Issue by GreenForzeGaming** [MehVahdJukaar/WoodGood#738]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.21.1 - FABRIC

### EveryCompat Version

1.21-2.8.2

### Moonlight Lib Version

1.21-2.17.12

### Issue with mods

![image](https://github.com/user-attachments/assets/adc299c3-6738-4378-a6e7-84f581cfffd6)

### Issue Detail

![image](https://github.com/user-attachments/assets/0790722d-6ee1-45b3-bb26-2cf2caeff9d9)

**Comment by Xelbayria** [comment]
Can you get the ID of these with the missing texture? 

EDIT: 
You should report the issue to the mod that provide support for the Small Ships. Every Compat don't have support for the small ships. 

The ID is to check which mod is the one that provide support. 

There is nothing I can do about this on my side.
