### ISSUE TITLE
[🐞]: Mod "Lucky's Cozy Home" breaks many recipes to ask for Oak instead of different wood types

### ISSUE THREAD

**Issue by Eourist** [MehVahdJukaar/WoodGood#739]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### EveryCompat Version

everycomp-1.20-2.7.8

### Moonlight Lib Version

moonlight-1.20-2.13.42

### Issue with mods

cozy_home-3.0.4-forge-1.20.1

### Issue Detail

When the mod "Lucky's Cozy Home" is installed, many recipes break, asking for Oak materials instead of the corresponding wood type.
Examples: 
Beam (from mod "Building But Better") using Baobab wood (from "Regions Unexplored" mod)
![2024-12-26_12 46 09](https://github.com/user-attachments/assets/69cacc58-3ff1-4752-9066-647300e90c53)

Trim (from mod "Hearth & Home") using Trumped wood (from "Quark" mod)
![2024-12-26_12 45 57](https://github.com/user-attachments/assets/5d2cd7d5-0f83-48c3-800a-9b732e597856)

Among many other recipes.

By simply removing "Lucky's Cozy Home" and re-launching the game, these recipes are fixed:
![2024-12-26_12 48 14](https://github.com/user-attachments/assets/c71f49b4-ff53-4313-b1c1-d62e5e23b0b8)
![2024-12-26_12 50 50](https://github.com/user-attachments/assets/77c45a64-929a-4f76-967b-e7c7e1e901b4)

**Comment by Xelbayria** [comment]
has **Lucky's Cozy Home** been recently updated? 

EDIT: nvm. The last update was in summer 2024

**Comment by Xelbayria** [comment]
You should report that issue to DEV of **Lucky's Cozy Home**. I can't debug this in IDEA because the mod is made with MCreator (it's garbage, or so i heard). 

Something in the mod is somehow screwing up the generation of recipe in EveryCompat. so idk. 

NOTE: debug mode is to find out what's the cause of why these oak are not being swapped out to the correct ingredient.

**Comment by Xelbayria** [comment]
Related to #882
