### ISSUE TITLE
[🐞]: Valhelsia Furniture recipes ignoring sticks

### ISSUE THREAD

**Issue by Eourist** [MehVahdJukaar/WoodGood#740]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### EveryCompat Version

everycomp-1.20-2.7.8

### Moonlight Lib Version

moonlight-1.20-2.13.42

### Issue with mods

valhelsia_furniture-forge-1.20.1-1.1.3

### Issue Detail

<details>
<summary>Images</summary>

The recipe for a Valhelsia Chair looks like this:
![2024-12-26_12 52 06](https://github.com/user-attachments/assets/1f5e444d-ad78-4173-bd72-c52ed0a7eb6e)
But for some reason it's crafted even when I don't include the sticks:
![2024-12-26_12 52 29](https://github.com/user-attachments/assets/dbadf7ee-4eec-44e7-adde-a6152395dcad)
It also happens with the other recipes, the Table, Desk, and Desk Drawer:
![2024-12-26_12 56 45](https://github.com/user-attachments/assets/d86bb43f-ffde-4256-b547-6e2f96bcf790)
![2024-12-26_12 52 44](https://github.com/user-attachments/assets/486fe1c9-e464-4ded-904d-7836ee5616dc)
![2024-12-26_12 52 34](https://github.com/user-attachments/assets/d2158b3c-2cd1-4483-b748-9dfa037c4cff)

Polymorph sometimes works and allows me to craft slabs, but sometimes it doesn't, I don't understand why:
![2024-12-26_12 54 38](https://github.com/user-attachments/assets/b90664dd-8309-4da6-9346-3d1fb6e0f8b1)

</details>

**Comment by Xelbayria** [comment]
Hmm I remember this issue.  the problem is the JEI/REI/EMI. I'll find the old issue. 

EDIT: 
Seeing the recipe viewer you are using is a JEI. Try use REI or EMI.

**Comment by Xelbayria** [comment]
Found the [old issue](https://github.com/emilyploszaj/emi/issues/705)

I was discussing this issue with the DEV of EMI to find out why it happened. There are more information in the issue.

**Comment by Eourist** [comment]
Tried EMI, the recipe viewer doesn't show the sticks, so now it actually matches what the crafting table does. 
So if I'm understanding this correctly, there's some custom formatting in Valhelsia Furniture's recipes, which apparently JEI knows how to interpret, but not EMI or EveryComp?

**Comment by Xelbayria** [comment]
> there's some custom formatting in Valhelsia Furniture's recipes

Correct. BUT EveryComp is not a recipe viewer. it support furniture mods that don't have support for Wood mods (Biomes O' Plenty and more). you are also correct, EMI or REI cannot interpret the condition in the recipe. Only JEI is capable of this, IIRC. 

If you look at the recipe of Valhelsia Furniture (VF).   it has a condition where it would be loaded depending on loader: FABRIC or FORGE. 

VF is the only one I know that have a custom recipe which use condition to decide which ingredient based on the loader

**Comment by Xelbayria** [comment]
Alright, there is nothing I can do on my side. The issue is on **Valhelsia Furniture** where they use a conditional in a recipe (making it a unique recipe). **EMI** or **REI** failed to interpret that conditional and ended up ignoring it.

**EMI** can work with **JEI**. If you try to craft using the recipes, you'll find it's working fine. 

BEST SOLUTION: The DEVs of **EMI** or **REI** should have update their mod to be able to interpret the conditional. You already saw the decision of EMI's DEV on the old issue I created above. 

The other solution is to report the issue to DEV of **Valhelsia Furniture** to update the recipe so EMI & REI can work with the recipe.
