### ISSUE TITLE
[❔]: Optimizing my usage of this mod.

### ISSUE THREAD

**Issue by RealMichaelDino** [MehVahdJukaar/WoodGood#741]
### Question

What known mods tend to use a lot of ram with every compat

### Optional: Details

Hello hello,
This and stone zone together have got to be some of my favourite mods! However, I'm trying to best optimize my usage of it as to not totally consume all my computer's ram into a black hole.
If I'm correct mods that tend to add either lots of wood types (like biomes o plenty) or lots of block variants (like chipped) when combined tend to use a lot of memory.
Are there other known mods that tend to add a lot of wood types or block variants that I should be aware of?
All advice is appreciated!
(Ps can provide my modpack list or specs if that helps)

**Comment by MehVahdJukaar** [comment]
So the mod will log which mod is taking up most resources and how many blocks it added so check your logs

**Comment by Xelbayria** [comment]
you are right about Chipped, it added a lot of supported blocks. I wouldn't recommend it unless you are making a small modpack. 

Biomes O' Plenty has 13 WoodTypes. The easiest way to find out how many StoneTypes/WoodTypes in a mod is to check out. 

MehVahdJukaar added the logging system to the latest.log. here's what it looks like: 
```
[Render thread/INFO] [Moonlight/]: Initialized block sets in 32ms
[Render thread/INFO] [Every Compat/]: Registering Compat WoodType Blocks
[Render thread/INFO] [Every Compat/]: EveryCompat Create Module: registered 10 WoodType blocks
[Render thread/INFO] [Every Compat/]: EveryCompat Quark Module: registered 18 WoodType blocks
[Render thread/INFO] [Every Compat/]: Registering Compat LeavesType Blocks
[Render thread/INFO] [Every Compat/]: EveryCompat Quark Module: registered 2 LeavesType blocks
[Render thread/INFO] [Every Compat/]: Registering Compat StoneType Blocks
[Render thread/INFO] [Every Compat/]: StoneZone Create Module: registered 153 StoneType blocks
[Render thread/INFO] [Every Compat/]: StoneZone Quark Module: registered 4 StoneType blocks
```

with Alex's Cave as the Stone Mod & also Wood Mod.
Quark has some wood and stones, too.

**Comment by RealMichaelDino** [comment]
Before hand I was looking at the debug logs and seeing that chipped was responsible for like... 22000+ blocks? Yeesh that's alot!
There were a few other mods adding notable amounts with Builders Delight at ~7000, nowhere near the amount chipped adds though due to it being in a big modpack.
I'll make another test in the morning and see how well it performs without chipped (probably better I'd imagine).
I may also have a look at testing with macaw's mods now without chipped and see how that goes.

**Comment by RealMichaelDino** [comment]
Did my testing today and indeed without chipped the modpack's memory usage is significantly reduced, unfortunately macaw's also consumes a lot of ram when separately tested, but other mods seem to work fine without sending the ram usage to the stratosphere.
I think with that my question is now answered, thanks for the assistance and the mod!

**Comment by Xelbayria** [comment]
No problem!
