### ISSUE TITLE
[🐞]: textureless brimwood furnitures | Another Furniture + Regions Unexplored FORGE 1.20.1

### ISSUE THREAD

**Issue by Wordierlight296** [MehVahdJukaar/WoodGood#742]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### VERSION - LOADER

1.20.1 - FORGE

### EveryCompat Version

everycomp-1.20-2.7.8

### Moonlight Lib Version

moonlight-1.20-2.13.42-forge

### Issue with mods

modpack mod list:

another_furniture-forge-1.20.1-3.0.1

RegionsUnexploredForge-0.5.6+1.20.1

TerraBlender-forge-1.20.1-3.0.1.7

Those mods seems to work fine together with the exception of brimwood...
Brimwood furnitures are textureless.

### Issue Detail

![Screenshot 2024-12-27 220350](https://github.com/user-attachments/assets/301ce0d0-d940-421e-9b4b-3ea52bf492c7)
![Screenshot 2024-12-27 220545](https://github.com/user-attachments/assets/454f7131-9873-4d56-91e5-cdc361671522)

### OPTIONAL: Latest.log | Crash-report Attachment

[latest.log](https://github.com/user-attachments/files/18263787/latest.log)

### OPTIONAL: To Produce

Just run the modpack with those mods enabled.

**Comment by RealMichaelDino** [comment]
I can independently confirm this is also occurring within my modpack where a bunch of the brimwood textures and the another furniture mod are yielding the null textures whilst other wood types are seemingly unaffected.
![image](https://github.com/user-attachments/assets/922e8e47-d358-47ff-8936-117028fdf98a)

**Comment by Xelbayria** [comment]
Seeing the JEI in the picture. that's worse than I thought.

**Comment by Wordierlight296** [comment]
It also happen to brimwood glass panels of create mod as well.

**Comment by Xelbayria** [comment]
yea I am investigating this to find out why.

**Comment by RealMichaelDino** [comment]
Indeed a bunch of other mods seemed to have broken textures with brimwood for some reason, I only mentioned another furniture since it was the subject of this bug but a bunch of other mods were seemingly breaking with brimwoods textures for whatever reason.

**Comment by Xelbayria** [comment]
Try Moonlight Lib **v2.13.44**

**Comment by Wordierlight296** [comment]
thank you so much! textures are looking fine now.

![Screenshot 2024-12-29 164201](https://github.com/user-attachments/assets/cb24d017-7cac-4413-bcb6-973b3681a52c)

**Comment by Xelbayria** [comment]
## FIXED in Moonlight Lib v2.13.44
