### ISSUE TITLE
[🐞]: missing texture of the functional storage 1x2 drawer 

### ISSUE THREAD

**Issue by SSWTLZZ69** [MehVahdJukaar/WoodGood#743]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.20.1 - FORGE

### EveryCompat Version

everycomp-1.20-2.7.8

### Moonlight Lib Version

moonlight-1.20-2.13.42-forge

### Issue with mods

functionalstorage-1.20.1-1.2.12

### Issue Detail

![image](https://github.com/user-attachments/assets/299f5c51-9978-435e-8fb8-1576b47fdae1)
the face of the 1x2 drawer is missing

**Comment by Xelbayria** [comment]
## FIXED in v2.7.9

---

CAUSE: the two textures that are supposed to be added to 2 different resources (but ended up added to the one same resource twice). There is a bug in the code that `newId` wasn't updated after `keepNamespace=true`.
