### ISSUE TITLE
[🐞]: Glitched sakura textures with Missing Wilds and Macaw's Trapdoors

### ISSUE THREAD

**Issue by Tysos24** [MehVahdJukaar/WoodGood#744]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.21.1 - FABRIC

### EveryCompat Version

everycomp-1.21-2.8.2

### Moonlight Lib Version

moonlight-1.21-2.17.12

### Issue with mods

Terrestria v7.0.1
Macaw's Trapdoors v1.1.4
Missing Wilds v1.3.3+1.21

### Issue Detail

The sakura wood from Terrestria has glitched textures as two of Macaw's Trapdoors and the Missing Wilds fallen log
![2024-12-28_14 40 30](https://github.com/user-attachments/assets/2f5e2645-3497-4b9b-857e-4681e9c669c2)
![2024-12-28_14 40 51](https://github.com/user-attachments/assets/2dc941cb-f8ee-48cd-97da-48824b1afbbc)
![2024-12-28_14 41 00](https://github.com/user-attachments/assets/e74f2ca9-a949-415d-849e-850d3311ea67)

### OPTIONAL: Latest.log | Crash-report Attachment

N/A

### OPTIONAL: To Produce

1) Install Every Compat, Terrestria, and Macaw's Trapdoors or Missing Wilds.
2) Check the Every Compat creative tab

**Comment by Xelbayria** [comment]
Going to blacklist that woodType, Sakura from these 2 supported mods.

**Comment by Xelbayria** [comment]
## BLACKLISTED in v2.8.3

---

why? It's simple. Take a look at the texture of _sakura_ and also _yucca_palm_ via Terrestria.

They are not 16x16. but actually 8x8. The logs you saw in the picture is just half size of the full log.

**EDIT:** 
Just so you know, only _ranch_trapdoor_ is blacklisted with 2 WoodTypes
