### ISSUE TITLE
[🗃]: Macaw’s Doors and Dramatic Doors together don’t have tall Macaw’s doors made from modded woods

### ISSUE THREAD

**Issue by Tysos24** [MehVahdJukaar/WoodGood#745]
### Version - Loader

1.21.1 - FABRIC

### Supported Mod Version

MDv1.1.1, DDv3.2.7

### Supported mod's Curseforge

https://www.curseforge.com/minecraft/mc-mods/macaws-doors, https://www.curseforge.com/minecraft/mc-mods/dramatic-doors

### Details

This isn’t an update issue; rather it’s an oversight. Dramatic Doors has native compatibility for Macaw’s Doors, so Every Compat ignores them. However, this means that 3-block-tall Macaw’s Doors don’t have support for modded woods.

**Comment by Xelbayria** [comment]
It should be supported. I'll check

**Comment by Xelbayria** [comment]
oh so that's why. it is only supported on FORGE.

**Comment by Xelbayria** [comment]
## Dramatic Doors & Supported Macaw's Doors have been moved to COMMON in v2.8.3

---

This mean Supported Macaw's Door will be now supported on FABRIC from the version onward
