### ISSUE TITLE
[🐞]: server crash

### ISSUE THREAD

**Issue by GreenForzeGaming** [MehVahdJukaar/WoodGood#747]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.21.1 - FABRIC

### EveryCompat Version

1.21-2.8.2

### Moonlight Lib Version

1.21-2.17.12

### Issue with mods

<details>
<summary>partially of latest.log</summary>

29.12 22:35:00 [Server] main/ERROR Failed to start the minecraft server
29.12 22:35:00 [Server] INFO java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'everycomp' at 'net.mehvahdjukaar.every_compat.fabric.EveryCompatFabric'!
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.FabricLoaderImpl.lambda$invokeEntrypoints$2(FabricLoaderImpl.java:403) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:401) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO Suppressed: net.fabricmc.loader.api.EntrypointException: Exception while loading entries for entrypoint 'main' provided by 'moreoverlays'
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:56) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:63) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at knot/net.minecraft.server.Main.main(Main.java:111) [server-intermediary.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480) [fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) [fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) [fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) [fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO Caused by: java.lang.RuntimeException: Cannot load class at.ridgo8.moreoverlays.MoreOverlays in environment type SERVER
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.transformer.FabricTransformer.transform(FabricTransformer.java:59) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPreMixinClassByteArray(KnotClassDelegate.java:462) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:415) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:323) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
29.12 22:35:00 [Server] INFO at java.base/java.lang.Class.forName0(Native Method) ~[?:?]
29.12 22:35:00 [Server] INFO at java.base/java.lang.Class.forName(Class.java:534) ~[?:?]
29.12 22:35:00 [Server] INFO at java.base/java.lang.Class.forName(Class.java:513) ~[?:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:124) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO ... 7 more
29.12 22:35:00 [Server] INFO Caused by: java.lang.NoClassDefFoundError: net/minecraft/class_756
29.12 22:35:00 [Server] INFO at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
29.12 22:35:00 [Server] INFO at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
29.12 22:35:00 [Server] INFO at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
29.12 22:35:00 [Server] INFO at knot/net.mehvahdjukaar.every_compat.ECRegistry.<clinit>(ECRegistry.java:19) ~[everycomp-1.21-2.8.2-fabric.jar:?]
29.12 22:35:00 [Server] INFO at knot/net.mehvahdjukaar.every_compat.EveryCompat.init(EveryCompat.java:105) ~[everycomp-1.21-2.8.2-fabric.jar:?]
29.12 22:35:00 [Server] INFO at knot/net.mehvahdjukaar.every_compat.EveryCompatCommon.initialize(EveryCompatCommon.java:35) ~[everycomp-1.21-2.8.2-fabric.jar:?]
29.12 22:35:00 [Server] INFO at knot/net.mehvahdjukaar.every_compat.fabric.EveryCompatFabric.onInitialize(EveryCompatFabric.java:28) ~[everycomp-1.21-2.8.2-fabric.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO ... 6 more
29.12 22:35:00 [Server] INFO Caused by: java.lang.ClassNotFoundException: net.minecraft.class_756
29.12 22:35:00 [Server] INFO at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
29.12 22:35:00 [Server] INFO at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
29.12 22:35:00 [Server] INFO at java.base/java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
29.12 22:35:00 [Server] INFO at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1027) ~[?:?]
29.12 22:35:00 [Server] INFO at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.defineClassFwd(KnotClassLoader.java:160) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:355) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:218) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:119) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:526) ~[?:?]
29.12 22:35:00 [Server] INFO at knot/net.mehvahdjukaar.every_compat.ECRegistry.<clinit>(ECRegistry.java:19) ~[everycomp-1.21-2.8.2-fabric.jar:?]
29.12 22:35:00 [Server] INFO at knot/net.mehvahdjukaar.every_compat.EveryCompat.init(EveryCompat.java:105) ~[everycomp-1.21-2.8.2-fabric.jar:?]
29.12 22:35:00 [Server] INFO at knot/net.mehvahdjukaar.every_compat.EveryCompatCommon.initialize(EveryCompatCommon.java:35) ~[everycomp-1.21-2.8.2-fabric.jar:?]
29.12 22:35:00 [Server] INFO at knot/net.mehvahdjukaar.every_compat.fabric.EveryCompatFabric.onInitialize(EveryCompatFabric.java:28) ~[everycomp-1.21-2.8.2-fabric.jar:?]
29.12 22:35:00 [Server] INFO at net.fabricmc.loader.impl.FabricLoaderImpl.invokeEntrypoints(FabricLoaderImpl.java:399) ~[fabric-loader-0.16.9.jar:?]
29.12 22:35:00 [Server] INFO ... 6 more
29.12 22:35:01 [Multicraft] Server shut down (starting)
29.12 22:35:01 [Multicraft] Restarting crashed server in 300 seconds
29.12 22:35:01 [Multicraft] Server stopped

</details>

### Issue Detail

server dont start

**Comment by Xelbayria** [comment]
Please don't use copy/paste. use https://mclo.gs/ to share the FULL log/crash-report. I am going to upload the new version now. 

EDIT: can you send the crash-report

**Comment by Xelbayria** [comment]
I took a look at the `partially of latest.log` and noticed this: 
`Cannot load class at.ridgo8.moreoverlays.MoreOverlays in environment type SERVER`

You need to remove **More Overlays Updated** from the SERVER, but you can keep it on your CLIENT, i am sure it's CLIENT only.

**Comment by Xelbayria** [comment]
I got an confirmation from [another issue](https://github.com/MehVahdJukaar/WoodGood/issues/736). so v2.8.3 has the fix to avoid a possibility crash on SERVER. If your SERVER still crashed, then you haven't removed the `only CLIENT side` mod from the SERVER.

Closing this.
