### ISSUE TITLE
[🐞]:  1.21.1 Every Compat Server Crash

### ISSUE THREAD

**Issue by FriedrichNietzsche8** [MehVahdJukaar/WoodGood#748]
### Code of Conduct

- [X] Always check you are using the latest version of the mods and its dependencies
- [X] Remove mod that enhances Minecraft: Optifine, Sodium, others. The issue still persists.
- [X] If you are unsure which mod is the culprit.
Disable all of your mods and enable them 1-2 mods each time to isolate the culprit
- [X] Confirm that there is no existing issue with a similar description submitted in the list of issues.

### Version - Loader (DO NOT FORGET TO SELECT THE CORRECT VERSION)

1.21.1 - FABRIC

### EveryCompat Version

everycomp-1.21-2.8.3-fabric

### Moonlight Lib Version

moonlight-1.21-2.17.12-fabric

### Issue with mods

Every Compat has issue with personal modpack in server starting department

### Issue Detail

Server does not start whenever everycomp-1.21-2.8.3-fabric is in the mod folder,
and does whenever everycomp-1.21-2.8.3-fabric is not in the mod folder

### OPTIONAL: Latest.log | Crash-report Attachment

https://mclo.gs/vHC30HW

**Comment by Xelbayria** [comment]
tsk. there is a typo in the code. Need to fix it now.

**Comment by Xelbayria** [comment]
I thought I corrected all of them. Going to upload now.

**Comment by Xelbayria** [comment]
It's uploaded now. Let me know if that resolved the crash

**Comment by FriedrichNietzsche8** [comment]
Testing now

**Comment by FriedrichNietzsche8** [comment]
Okay the server seems to run normally, so that issue is fixed
another issue seems to have popped up though, I'll open a new issue
