### ISSUE TITLE
[Feature] BYG vanilla signs

### ISSUE THREAD

**Issue by CallieEZ** [MehVahdJukaar/WoodGood#75]
Oh the biomes you'll go (atleast on 1.18+) doesn't include any signs for wood types, an intentional decision by the developer, is there a chance this mod can implement those sign types?

**Comment by MehVahdJukaar** [comment]
I don't plan to add any block from vanilla as that is the job of mods themselves. Intact the mod also kind of doesn't work perfectly when some mods do not have them as some texture generation is based off vanilla signs
