### ISSUE TITLE
[Bug] Mod doesn't support Twilight Forest's Mangrove wood

### ISSUE THREAD

**Issue by GizmoTheMoonPig** [MehVahdJukaar/WoodGood#76]
Pretty self-explanatory, load up Every Compat, Twilight Forest, and some mod that adds wood blocks (I used CFM and noticed it, but it happens with every other mod this mod supports), and notice how Mangrove doesn't show up. 

Weird thing is this worked just fine in 1.18, but I'm assuming you have some special casing with Minecraft's wood types so the addition of Mangrove in 1.19 vanilla broke it. I'd fix it myself, but I genuinely don't understand how this mod works in the slightest. 

Every Compat and Moonlight are on the latest version at the time of writing this (2.0.10 and 2.1.4 respectively)

**Comment by MehVahdJukaar** [comment]
Yeah indeed, it assumes no mod would ever add a wood type the same name as vanilla. It's kind of problematic as the way the mod detects what blocks to add is entirely named based. I'll add some other special cases to the special case spaghetti code

**Comment by MehVahdJukaar** [comment]
Fixed
