### ISSUE TITLE
Latest Version everycomp-1.19.2-2.1.1 incompatible with Moonlight Lib (Fabric)

### ISSUE THREAD

**Issue by onycius** [MehVahdJukaar/WoodGood#82]
Startup Error:
https://pastebin.com/Ar25QcA8

Does not occur with 2.1.0.

Edit: Curseforge Forge and Fabric files are swapped?

**Comment by papillo12** [comment]
I confirm that I have the same error

**Comment by MehVahdJukaar** [comment]
Can I get a lot from forge verison? I can't replicate thjs

**Comment by MehVahdJukaar** [comment]
Also I archived the fabric version just to be sure since it just had a single tiny fix

**Comment by onycius** [comment]
The posted Forge version works on Fabric, so I assume that you tagged the wrong version.

**Comment by MehVahdJukaar** [comment]
Are you sure? I downloaded it with cueseforge app and it worked for me. I might have messed stuff like stripping a dependency so it might be that if you don't have a mod installed it crashes but I can't figure out what that is
