### ISSUE TITLE
Some BiomesOPlenty leaf hedges are missing

### ISSUE THREAD

**Issue by 0Navis0** [MehVahdJukaar/WoodGood#83]
The leaf hedges for flowering oak, rainbow birch, origin, yellow autumn, orange autumn, maple leaves are missing.

**Comment by MehVahdJukaar** [comment]
they are all the ones that dont have a unique wood type associated. Quark hedges require one as they are made with a log. I'll have to manually add all those to the hardcoded section alongside all the other couple of weird types.

**Comment by MehVahdJukaar** [comment]
fixed
