### ISSUE TITLE
[1.19.2-2.1.1] [Forge] Startup crash

### ISSUE THREAD

**Issue by cech12** [MehVahdJukaar/WoodGood#85]
Minecraft: 1.19.2
Forge: 43.1.52
Every Compat: 1.19.2-2.1.1
Moonlight: 1.19.2-2.1.4

Crash at game startup. (with Every Compat 1.19.2-2.1.0 it does not happen)

Crash report: https://paste.ee/p/1vv9H

Seems to be related to #82

**Comment by MehVahdJukaar** [comment]
Same issue as that one aparently but I can't figure out whats going on as I can't replicate

**Comment by MehVahdJukaar** [comment]
I see what's going on. I'll fix soon. Basically happens when the mod doesn't register any leaf type variant block

**Comment by cech12** [comment]
In Every Compat 1.19.2-2.1.2 the issue is fixed! Thanks for your work! :)
