### ISSUE TITLE
Quilt/Fabric Crash on launch between versions [1.19.2-2.0.8] - [1.19.2-2.1.0]

### ISSUE THREAD

**Issue by ZanderF0** [MehVahdJukaar/WoodGood#86]
Getting the same crash between versions 1.19.2-2.0.8 up to the latest fabric release. Issue wasn't present in 1.19.2-2.0.7 when I was testing older versions but the game crashes in inventory menus with 2.0.7 because it's out of date.
[crash-2022-11-10_13.52.59-client.txt](https://github.com/MehVahdJukaar/WoodGood/files/9983848/crash-2022-11-10_13.52.59-client.txt)

**Comment by MehVahdJukaar** [comment]
I did archive that version yesterday tho

**Comment by MehVahdJukaar** [comment]
Update another furniture

**Comment by ZanderF0** [comment]
My bad, I didn't think to check Curseforge as I assumed the version on Modrinth would be up to date.
