### ISSUE TITLE
[1.19.2fabric]mod 2.1.4 game crash

### ISSUE THREAD

**Issue by DarkCrystalll** [MehVahdJukaar/WoodGood#91]
[minecraft-exported-crash-info-2022-11-20T00-31-36.zip](https://github.com/MehVahdJukaar/WoodGood/files/10047492/minecraft-exported-crash-info-2022-11-20T00-31-36.zip)

**Comment by DarkCrystalll** [comment]
The crash that occurred when I opened the second page of my backpack

**Comment by MehVahdJukaar** [comment]
Uninstall every compat

**Comment by MehVahdJukaar** [comment]
You don't need it. The mod registered 0 blocks meaning you don't have any of the supported mods or wood types installed

**Comment by DarkCrystalll** [comment]
Thank you for your answer. Now it can run normally on my computer(by add twilightforest)
but now,my friends computer have a new problem.It will Pause in loading the page, but the sound of the game's main menu has sounded,and I'm sure It is this mod responsible.
[minecraft-exported-logs-2022-11-23T04-05-15.log](https://github.com/MehVahdJukaar/WoodGood/files/10070759/minecraft-exported-logs-2022-11-23T04-05-15.log)

**Comment by MehVahdJukaar** [comment]
He run out of ram. Need to allocate more

**Comment by DarkCrystalll** [comment]
Oh, is that so.

**Comment by DarkCrystalll** [comment]
I saw someone feedback that this module needs too much ram, so whether it can be optimized?

**Comment by MehVahdJukaar** [comment]
It needs the exact ram you need to register blocks as any other mods does. It's jus that the mod in certain conditions can register many blocks but that's up to the user that installed too many wood types or furniture mods to decide if they want to have incomplete wood sets or not

**Comment by DarkCrystalll** [comment]
I understand. Thank you for your reply.
