### ISSUE TITLE
startup load problem

### ISSUE THREAD

**Issue by WeyehnR** [MehVahdJukaar/WoodGood#92]
Failure message: Every Compat (everycomp) encountered an error during the common_setup event phase
		java.lang.NoSuchMethodError: com.mcwwindows.kikoz.objects.Parapet: method 'void <init>()' not found
	Mod Version: 1.18.2-1.5.13
	Mod Issue URL: https://github.com/MehVahdJukaar/every_compat/issues
	Exception message: java.lang.NoSuchMethodError: com.mcwwindows.kikoz.objects.Parapet: method 'void <init>()' not found
i downloaded everycompat and i am getting this error message when i started up modded Minecraft
[crash-2022-11-24_23.09.17-fml.txt](https://github.com/MehVahdJukaar/WoodGood/files/10088564/crash-2022-11-24_23.09.17-fml.txt)

**Comment by brisingraerowing** [comment]
The latest Macaw's Windows version breaks the API. Downgrade to the last version until an update to this mod.

**Comment by LolJohn11** [comment]
Same with Macaw's Windows on 1.19.2 - waiting for the mod to be updated to fix this crash.

**Comment by LuckyLuc96** [comment]
Hi team - I have this same error while playing on Ubuntu. I don't have windows so this start up issue is probably going to be a big issue for me.

I did try reverting to an earlier version - went back as far as 1.4.0 with the same error.

I run a mod pack called vault hunters and can testify that there were no issues until I tried to update and/or reinstall the mod.

**Comment by MehVahdJukaar** [comment]
downgrade macaw windows

**Comment by MehVahdJukaar** [comment]
Also vault hunters modpack is setup so this does not occur as it uses a macaw wiwndows that is compatible with everycompat
