### ISSUE TITLE
Can't craft modded wooden slab

### ISSUE THREAD

**Issue by gousisme** [MehVahdJukaar/WoodGood#97]
As the title said, the default wood is fine tho

**Comment by katsutosh** [comment]
using:
- Forge - 43.1.57
- Every Compat - 2.1.6

Slabs from Twilight Forest works but the following mod slabs doesn't work for me (recipe is removed on world creation, without Every Compact the recipes are working)
- Oh The Biomes You'll Go
- Blue Skies
- Nature's Aura

**Comment by MuteTiefling** [comment]
Seems like EveryCompat is overriding the original recipe ID when creating the vertical slab recipe: 

![image](https://user-images.githubusercontent.com/9543430/208170475-b1b15cb3-7f94-4b69-add7-b46bff324ee3.png)

**Comment by MehVahdJukaar** [comment]
Hm everycompat doesn't even add any slabs. Only way to recipe override would be to add another one with the same name but recipes get added under its namespace so can't be possible.is anything in the log regarding failed recipes? Are you sure it's every company?  Also every compat doesn't add any vertical slab anymore

**Comment by MehVahdJukaar** [comment]
Vertical slabs compat does

**Comment by MuteTiefling** [comment]
Ah, well that explains it. We're still using everycomp-1.19.2-2.2.0

**Comment by Xelbayria** [comment]
@MuteTiefling 
is this issue resolved, if yes, then please close this

**Comment by MuteTiefling** [comment]
Can't close. Not my issue :D 

But it is resolved, yes.
